{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.284+fd02f73-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4437137"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa",
          "module": "malilib",
          "version": {
            "requires": "0.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4440850"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.284+fd02f73-beta.jar",
          "url": "magiclib-1_19_4-0.7.284+fd02f73-beta.jar",
          "size": 360736,
          "sha512": "185b6e2816f4894615765d0098f3f7eb6be6cfdd42b5db6fbe3cd8cf304157348ee98f06578735a30258a382471deda74ccfb743ee5c15fe64e6c1f0a479a00b",
          "sha256": "804c6349cdb3996a6f5b5bfe55dfa1e71d3bea25e17bcdc630062433c57519af",
          "sha1": "8a124f0b1b9d32f28acfbe06a0639e36a63d9197",
          "md5": "ccad55bf1fae4ce27a8c2f4ba52c54f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.284+fd02f73-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4437137"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa",
          "module": "malilib",
          "version": {
            "requires": "0.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4440850"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.284+fd02f73-beta.jar",
          "url": "magiclib-1_19_4-0.7.284+fd02f73-beta.jar",
          "size": 360736,
          "sha512": "185b6e2816f4894615765d0098f3f7eb6be6cfdd42b5db6fbe3cd8cf304157348ee98f06578735a30258a382471deda74ccfb743ee5c15fe64e6c1f0a479a00b",
          "sha256": "804c6349cdb3996a6f5b5bfe55dfa1e71d3bea25e17bcdc630062433c57519af",
          "sha1": "8a124f0b1b9d32f28acfbe06a0639e36a63d9197",
          "md5": "ccad55bf1fae4ce27a8c2f4ba52c54f9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.284+fd02f73-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.284+fd02f73-beta-sources.jar",
          "size": 159603,
          "sha512": "7fbfbf1d88871fefe11637ed0959cf48260d8be92d2b2932139dd4c99188ad59e78548cc1bab0b21b4c5950137b23c4bbe7fbce34ded4387b7393ba9d555a774",
          "sha256": "b304b2d18fb21edc28e7a8801cb853f768062613fb7efadd28b729ce56bace11",
          "sha1": "e46e29ebb297cd651e499b6f6ec23b7680cebfb9",
          "md5": "112f06f9daee6ddfb8bef950e759de1e"
        }
      ]
    }
  ]
}
