{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.319+530ec3a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.319+530ec3a-beta.jar",
          "url": "magiclib-1_17_1-0.7.319+530ec3a-beta.jar",
          "size": 371992,
          "sha512": "fae5693ee21198e56718b929ed860aaa54aace69f0025c0a45de7936436f88094af4dd61b609bfd286d81369a799dbd1dc666c3ded485f791ebe34045b078304",
          "sha256": "95894aabbc348331f1a45ac34b749737fed0bd1b6514903824cd1d6c6b8638af",
          "sha1": "bf1a8a5c28601931ef356e1e84a962bfe5eff37f",
          "md5": "122d287fca7c5d3a50728e3033455e13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.319+530ec3a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.319+530ec3a-beta.jar",
          "url": "magiclib-1_17_1-0.7.319+530ec3a-beta.jar",
          "size": 371992,
          "sha512": "fae5693ee21198e56718b929ed860aaa54aace69f0025c0a45de7936436f88094af4dd61b609bfd286d81369a799dbd1dc666c3ded485f791ebe34045b078304",
          "sha256": "95894aabbc348331f1a45ac34b749737fed0bd1b6514903824cd1d6c6b8638af",
          "sha1": "bf1a8a5c28601931ef356e1e84a962bfe5eff37f",
          "md5": "122d287fca7c5d3a50728e3033455e13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.319+530ec3a-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.319+530ec3a-beta-sources.jar",
          "size": 168379,
          "sha512": "680f7ae0fc6c2b61b97cb459bbece9652e87c0cdb0deabbc181eda30a966133c647c7755506cc15742b784941d6e6f8462da57b549702bcdef09c5aeaddd084f",
          "sha256": "6fb5203bbdf25fd8e00c30e945fb7e9972752a649a6d833f9175fa19be6c2bab",
          "sha1": "55f824ff97c7dbdfdfe12903a339539c0df15968",
          "md5": "78755756046c4510cbee2a24972c7732"
        }
      ]
    }
  ]
}
