{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.321+3d981a5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_19_2-0.7.321+3d981a5-beta.jar",
          "size": 374757,
          "sha512": "837cdb500c1ee692103dbe5a803dee67b0808407d0831f7036fd12d83c9144a30f059e6e4d7e008b75fbb364405d0b86574201dffe90faf628a26db526cd4b94",
          "sha256": "aa3e49d9d18052a9b0daf0d34b11d8c44c01c01236d315512f035e388f56ca84",
          "sha1": "65ca1f64ad8d30c38f8e7036aea59c7949588460",
          "md5": "c37ce4a4cba3fcfc5cacdf6e5aaebaf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.321+3d981a5-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_19_2-0.7.321+3d981a5-beta.jar",
          "size": 374757,
          "sha512": "837cdb500c1ee692103dbe5a803dee67b0808407d0831f7036fd12d83c9144a30f059e6e4d7e008b75fbb364405d0b86574201dffe90faf628a26db526cd4b94",
          "sha256": "aa3e49d9d18052a9b0daf0d34b11d8c44c01c01236d315512f035e388f56ca84",
          "sha1": "65ca1f64ad8d30c38f8e7036aea59c7949588460",
          "md5": "c37ce4a4cba3fcfc5cacdf6e5aaebaf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.321+3d981a5-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.321+3d981a5-beta-sources.jar",
          "size": 168382,
          "sha512": "d3b3628d12aeaf59d6d00bd4f577a42fc5796bbb54d77867e918af086fac7b4eb5dace6e2dcc541c0ad5acd21e21f5e18c6a1578937e789839c53ae7dcfb0776",
          "sha256": "addc99ecd037391b339f576d2c4d510ccb2fa924d6fcfc225f9b1b22e680989a",
          "sha1": "38747f700baa7f5fdf202760b611bed92f36ece4",
          "md5": "d4f5e30c553f446d4ffb290443ad83e2"
        }
      ]
    }
  ]
}
