{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.316+d66e799-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.69"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.316+d66e799-beta.jar",
          "url": "magiclib-1_18_2-0.7.316+d66e799-beta.jar",
          "size": 373595,
          "sha512": "36795ff3ba0c06c58479742d6bf67ef5562f21643e88379308a18fce6e4a52eee9aae8d89c1da14885875f5df468629f7519e110b07a3b4eff1ce58fdd7ef269",
          "sha256": "443cbd370cd8223d36442160fb8c47ecda7d7f44f194584cbd4f7a04eb8a3f1a",
          "sha1": "cda2589f5fad75fe90a2cafd7b4ab62b0d194914",
          "md5": "6d83a8cf9e3e6719471ba8561f0bdd9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.316+d66e799-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.69"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.316+d66e799-beta.jar",
          "url": "magiclib-1_18_2-0.7.316+d66e799-beta.jar",
          "size": 373595,
          "sha512": "36795ff3ba0c06c58479742d6bf67ef5562f21643e88379308a18fce6e4a52eee9aae8d89c1da14885875f5df468629f7519e110b07a3b4eff1ce58fdd7ef269",
          "sha256": "443cbd370cd8223d36442160fb8c47ecda7d7f44f194584cbd4f7a04eb8a3f1a",
          "sha1": "cda2589f5fad75fe90a2cafd7b4ab62b0d194914",
          "md5": "6d83a8cf9e3e6719471ba8561f0bdd9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.316+d66e799-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.316+d66e799-beta-sources.jar",
          "size": 168213,
          "sha512": "304eb8e487af58480d0fa227a1138b9e791250b3ae25e0e2c46c813a4f89c430babd9a3aa296abfa252654e7f08098e35727a21554fc6277729c96b0528f9626",
          "sha256": "6f0db96385685d3913403926a89faf6b962cae1058aac6903d4d9a41b5971d33",
          "sha1": "385aebe8924dd4baa84ad48157fa466f6c52acf5",
          "md5": "b9cba59d3b70aedebf8fc54dc2d8fb4c"
        }
      ]
    }
  ]
}
