{
  "formatVersion": "1.1",
  "component": {
    "group": "curse.maven",
    "module": "malilib-303119",
    "version": "22w19a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "malilib-303119-22w19a.jar",
          "url": "malilib-303119-22w19a.jar",
          "size": 516854,
          "sha512": "c8990f9f482444ed63b2e281fadc2e146ff0084f885d7220e28884a51f18abe9736e1753c4000ba211c219dc6d0d54b8ce21894e63a2b539e1d1cf3f107d8bef",
          "sha256": "313d47e56cb03d4e19228c43aeebe0086024812ce7b1a27bf5a75c2b870d850e",
          "sha1": "af74fc513a2dfce09390d2f8376a24ab826fc206",
          "md5": "ddbe96eccaff70d3cc2336cd2d2fae07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.4.25+ec94c6f6bf"
          }
        }
      ],
      "files": [
        {
          "name": "malilib-303119-22w19a.jar",
          "url": "malilib-303119-22w19a.jar",
          "size": 516854,
          "sha512": "c8990f9f482444ed63b2e281fadc2e146ff0084f885d7220e28884a51f18abe9736e1753c4000ba211c219dc6d0d54b8ce21894e63a2b539e1d1cf3f107d8bef",
          "sha256": "313d47e56cb03d4e19228c43aeebe0086024812ce7b1a27bf5a75c2b870d850e",
          "sha1": "af74fc513a2dfce09390d2f8376a24ab826fc206",
          "md5": "ddbe96eccaff70d3cc2336cd2d2fae07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "malilib-303119-22w19a-sources.jar",
          "url": "malilib-303119-22w19a-sources.jar",
          "size": 261669,
          "sha512": "6682d20684e4b76b3b1b0fa5f82cb925616040b03b83d2e657be57c57bae33b3dc0f2b6b64a9e68aca4cb78a38f7186f9bf11e6eae70a8087bc45cb02520902c",
          "sha256": "0ce3d7cf184ef70ff094fefc94bfe0b05af5cbd3b30e97ac2db521cbe9ad2028",
          "sha1": "892746a667b3fa84b4854a99ba86be10a652a476",
          "md5": "6f892855efc927a62d5970fb5cb05ab2"
        }
      ]
    }
  ]
}
