{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-carpet-compat-1_15_2",
    "version": "0.2.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_15_2",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3030941"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_15_2-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_15_2-0.2.2+32bcf58-beta.jar",
          "size": 144132,
          "sha512": "427e0e26eba0929f1ef62e10a45e202b4f7908daa490dcc0f61d6acf369495d26c9b08211df422ba8199680c495fbbcc2dd59155fe2db36b775caf5480d97316",
          "sha256": "29a7c6a5cd77118cb4827af5a3d11a5d715a5cdaded3213834c6896ee5d3a519",
          "sha1": "52528d3319bab553161581bc4f9a4276a8b24aa9",
          "md5": "9208c1688c54209807a57d96c394479a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_15_2",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3030941"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_15_2-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_15_2-0.2.2+32bcf58-beta.jar",
          "size": 144132,
          "sha512": "427e0e26eba0929f1ef62e10a45e202b4f7908daa490dcc0f61d6acf369495d26c9b08211df422ba8199680c495fbbcc2dd59155fe2db36b775caf5480d97316",
          "sha256": "29a7c6a5cd77118cb4827af5a3d11a5d715a5cdaded3213834c6896ee5d3a519",
          "sha1": "52528d3319bab553161581bc4f9a4276a8b24aa9",
          "md5": "9208c1688c54209807a57d96c394479a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_15_2",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_15_2-0.2.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-carpet-compat-1_15_2-0.2.2+32bcf58-beta-standalone-dev.jar",
          "size": 537110,
          "sha512": "103b839f443a960cc3f40ae7a2a00e8386815a9cd385f9dce2ed7d613aeb7d2181d41d089db5400acec940b1c4ca34f7cd0cbf4f77f9123f72fa02e512e09065",
          "sha256": "9812a5439c4e69fcceb01302c0256a6c4d64160645f1f404ca2687bb5dc42fdd",
          "sha1": "6567bc062b618bd4e351ba9ce95a45849f9c74a9",
          "md5": "4b9b9cca6929b4c3e0cc8eb0fa6023ce"
        }
      ]
    }
  ]
}
