{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479750"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.11.jar",
          "url": "magiclib-1_17_1-0.5.11.jar",
          "size": 242359,
          "sha512": "2bedf32ec58c8921fd63bc26896df89dd35cd6fe0c887adb8321b097e09fc18ba6ff6079a40e39946ac976000e10b8667d40e8e066fc90fe29d0134a06d69dcf",
          "sha256": "f2c5c9365bd5602d7cb2e50102592be4bc8c14a6ce2dd4b4252352bbb0ca5e3b",
          "sha1": "dba59abc5adb00014b74e7410fd9b32ae6c36140",
          "md5": "b003e0d10736884efc7902a5307dc9c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.11"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479750"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493811"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.11.jar",
          "url": "magiclib-1_17_1-0.5.11.jar",
          "size": 242359,
          "sha512": "2bedf32ec58c8921fd63bc26896df89dd35cd6fe0c887adb8321b097e09fc18ba6ff6079a40e39946ac976000e10b8667d40e8e066fc90fe29d0134a06d69dcf",
          "sha256": "f2c5c9365bd5602d7cb2e50102592be4bc8c14a6ce2dd4b4252352bbb0ca5e3b",
          "sha1": "dba59abc5adb00014b74e7410fd9b32ae6c36140",
          "md5": "b003e0d10736884efc7902a5307dc9c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.11-sources.jar",
          "url": "magiclib-1_17_1-0.5.11-sources.jar",
          "size": 185650,
          "sha512": "62a3c8410133ddf5c77f25b40fe126279f21e21ddb6bf2c8a923c29b584c6ffcd520fba04a1d1d5ae31514b559ba62c532c05829affec299ee708cd5ecbe2c8e",
          "sha256": "e06b1daa9ec282fec4a9ee1c5f76225b4fb42ef255cb59e496efa8cba2e036a1",
          "sha1": "b57833ac757de89e57acbccc44738412675805f8",
          "md5": "2b000982bb4aa13b5f2e7a337e1dcb3e"
        }
      ]
    }
  ]
}
