{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.322+57464f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.322+57464f9-beta.jar",
          "url": "magiclib-1_18_2-0.7.322+57464f9-beta.jar",
          "size": 373643,
          "sha512": "e0939f9f3c6998ffc34f33fcb3fa445d8cc29a0a6c14fa72f5a7acd75e0303f86f6aceff8a9dfaed9a55457ebeaa259100c3545e4908dba31a733638e29ad446",
          "sha256": "de8219a353966133ad9887780921b7cbfda57dccd20363374e377bca5b75f259",
          "sha1": "fc5ba60a49581db47fd3764aaf6f398990055c68",
          "md5": "70816f602d8140bed0901e2cc26e0971"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.322+57464f9-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.322+57464f9-beta.jar",
          "url": "magiclib-1_18_2-0.7.322+57464f9-beta.jar",
          "size": 373643,
          "sha512": "e0939f9f3c6998ffc34f33fcb3fa445d8cc29a0a6c14fa72f5a7acd75e0303f86f6aceff8a9dfaed9a55457ebeaa259100c3545e4908dba31a733638e29ad446",
          "sha256": "de8219a353966133ad9887780921b7cbfda57dccd20363374e377bca5b75f259",
          "sha1": "fc5ba60a49581db47fd3764aaf6f398990055c68",
          "md5": "70816f602d8140bed0901e2cc26e0971"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.322+57464f9-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.322+57464f9-beta-sources.jar",
          "size": 168430,
          "sha512": "d03863f44ef1b5313f382ea4864a580f7af521fe79cd5ee8280ce068906c2cb8cbd5a7fc74f5939533a6d8b3d3d32950be6099c058aef7c4d8402a4e3bfdb7f2",
          "sha256": "c1ce6d5b0c8299039b11e0e879238e437b92b784761ab9420f6ee95beea45a84",
          "sha1": "22280066026154761704d8764f1b5d8277a4d677",
          "md5": "07f879df9c1968bad8fc734526dfd56a"
        }
      ]
    }
  ]
}
