{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra-1_16_5",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_16_5",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_16_5-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_16_5-0.7.2+32bcf58-beta.jar",
          "size": 157470,
          "sha512": "d8503a4c565832a0d9b06ef1b788efb2eeb48420f3737504d89229ea6d2f7ceb82dab5ac28d22bde636a351e3be2d3f9ba9057d32f775d49b003102722b5d220",
          "sha256": "35e840fecec2d9859694fa7339cd4c18128239d4a14ce02d3baef5a97440bc91",
          "sha1": "25109a9be782197c8fce75bb67e2df78004277c1",
          "md5": "38ecc15f46519f4cf8a8431c5dc7bbcf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_16_5",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_16_5-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_16_5-0.7.2+32bcf58-beta.jar",
          "size": 157470,
          "sha512": "d8503a4c565832a0d9b06ef1b788efb2eeb48420f3737504d89229ea6d2f7ceb82dab5ac28d22bde636a351e3be2d3f9ba9057d32f775d49b003102722b5d220",
          "sha256": "35e840fecec2d9859694fa7339cd4c18128239d4a14ce02d3baef5a97440bc91",
          "sha1": "25109a9be782197c8fce75bb67e2df78004277c1",
          "md5": "38ecc15f46519f4cf8a8431c5dc7bbcf"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_16_5",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_16_5-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-malilib-extra-1_16_5-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 412985,
          "sha512": "8329aacd8b85af9cac06d1689e2ea879c050506de848fc58a8f63ea88ed048100ab6d104ce01d55cdfce6820394afd0b1136ca77e62656148df02c67b5a2c8f7",
          "sha256": "05436dfbc5d793daa2f01cd8474ccb3d001ac023685f671fd7c33ac619b758fe",
          "sha1": "1dc9c17222cef197612e4769ef2b23228d4697d7",
          "md5": "ebf7bd581c29a31fe731e7ed7adeeb8b"
        }
      ]
    }
  ]
}
