{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base-1_14_4",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_14_4-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_14_4-0.7.2+32bcf58-beta.jar",
          "size": 119273,
          "sha512": "fbc5e6d3f46a170a06c40b4c7895de4fbe9dafdf04f206d13cc06800a2732d2b6e21c140ddd27d1774b0d7dc160ab77bf4a0c767d8093d7f4a53c9075eb13b07",
          "sha256": "8e4e53e2aa3a9d862bf78098e06432ff0868106f921495d64ae46a054fd3faa3",
          "sha1": "9bf7c293126ff52d483d6f3450fa756b85e9109f",
          "md5": "9715782794557be6242c10b0c0482af7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2921052"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761403"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993195"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159393"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_14_4-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_14_4-0.7.2+32bcf58-beta.jar",
          "size": 119273,
          "sha512": "fbc5e6d3f46a170a06c40b4c7895de4fbe9dafdf04f206d13cc06800a2732d2b6e21c140ddd27d1774b0d7dc160ab77bf4a0c767d8093d7f4a53c9075eb13b07",
          "sha256": "8e4e53e2aa3a9d862bf78098e06432ff0868106f921495d64ae46a054fd3faa3",
          "sha1": "9bf7c293126ff52d483d6f3450fa756b85e9109f",
          "md5": "9715782794557be6242c10b0c0482af7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_14_4-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-base-1_14_4-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 259705,
          "sha512": "25ece1f0292f9cc7e16b25bf113a35e058c8952fd1aee2e9a09819fbc545079293a0e29b76ec05907b9564376ed32664eaf01ca65fb8ff1676aaaa9ee4234f7a",
          "sha256": "81bbc89e5d35e3aff0b2164cba835a65d4ab3089c345015e7f7cbb6dcc7a3f9b",
          "sha1": "3d9d57c4a5ebd2ce05f432fad8dc74da618e8b9f",
          "md5": "40e3507fdbf007fa411355bf07068d6d"
        }
      ]
    }
  ]
}
