{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.7.326+2b20e19-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.15.2-1.4.8+v200811"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.10.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.326+2b20e19-beta.jar",
          "url": "magiclib-1_15_2-0.7.326+2b20e19-beta.jar",
          "size": 373137,
          "sha512": "fec4c3aa7759cd7576f01999d943c11bab6170595d8cce9a0b35ff4fec43380d87d77feeeaa81cd1c1d0aca8a6e48c77405cf44c313ac961b60cd15ed0cd6218",
          "sha256": "fb076b29b197e6b26d1a1c12e0f49a3f2fe506ab15ca00798a31984e1c614c55",
          "sha1": "9a19bfaa156a17b44765ccffa24582a06fbd131a",
          "md5": "2e4564f6e647b10ce51a7da4da38a921"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.326+2b20e19-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.15.2-1.4.8+v200811"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.10.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "cloth-config",
          "version": {
            "requires": "2.14.2+fabric"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.326+2b20e19-beta.jar",
          "url": "magiclib-1_15_2-0.7.326+2b20e19-beta.jar",
          "size": 373137,
          "sha512": "fec4c3aa7759cd7576f01999d943c11bab6170595d8cce9a0b35ff4fec43380d87d77feeeaa81cd1c1d0aca8a6e48c77405cf44c313ac961b60cd15ed0cd6218",
          "sha256": "fb076b29b197e6b26d1a1c12e0f49a3f2fe506ab15ca00798a31984e1c614c55",
          "sha1": "9a19bfaa156a17b44765ccffa24582a06fbd131a",
          "md5": "2e4564f6e647b10ce51a7da4da38a921"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.326+2b20e19-beta-sources.jar",
          "url": "magiclib-1_15_2-0.7.326+2b20e19-beta-sources.jar",
          "size": 168580,
          "sha512": "d171e3019cae43b7f109168c82afea502b4a8f6ef009e746bd5c73bae9f061129f617a2ad400fad5647148ea70c8c3fc0f71cb60b84344abeeb3e7863d89394a",
          "sha256": "5afbd2171918f55a6b30cbb026596b98d1aae303b85877bdc1a4ea74314949ae",
          "sha1": "a79a1c546b96daaa127999884c77fd34077f6b2f",
          "md5": "4fe0c9e4ed89b7597a06489898d8551e"
        }
      ]
    }
  ]
}
