{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-core",
    "version": "0.7.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.12"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-core-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-core-0.7.3+c7ba8f9-beta.jar",
          "size": 146234,
          "sha512": "56d5318c7846f87f7bfe22940249b801af28438530054898c49050d06bd494f13d460e77e87f700115b78fde8decb16387950c8bd769d22e083dc0c65dfd8845",
          "sha256": "89a8692d3489a0d97274d1fca1a308105a25e623f17012c32095b1d6beb62a1a",
          "sha1": "8f01c431dfb426873620aaf09ce3d794ac0fb33c",
          "md5": "7798bad14dee37f75051b1a0b19b09c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.12"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-core-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-core-0.7.3+c7ba8f9-beta.jar",
          "size": 146234,
          "sha512": "56d5318c7846f87f7bfe22940249b801af28438530054898c49050d06bd494f13d460e77e87f700115b78fde8decb16387950c8bd769d22e083dc0c65dfd8845",
          "sha256": "89a8692d3489a0d97274d1fca1a308105a25e623f17012c32095b1d6beb62a1a",
          "sha1": "8f01c431dfb426873620aaf09ce3d794ac0fb33c",
          "md5": "7798bad14dee37f75051b1a0b19b09c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-core-0.7.3+c7ba8f9-beta-sources.jar",
          "url": "magiclib-core-0.7.3+c7ba8f9-beta-sources.jar",
          "size": 28466,
          "sha512": "406f8b4b6b06cdf389cf5eaf6a7a844d91eda6bc5c83ab16b70e3fe725da9065fb488627e1e8a8250e09066bb7b13e89ded2add9e0d2d448ddf9a8812c29ed58",
          "sha256": "15bcab45bcdc13204273056e89d6ce2cad95b8b9be123a76e94349b4c19bdb1c",
          "sha1": "2aa11d133ba00629c899e69f6a89e49c519db727",
          "md5": "5fed7d1f6c1fcb076c8762b57d2f1436"
        }
      ]
    }
  ]
}
