{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.319+530ec3a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.319+530ec3a-beta.jar",
          "url": "magiclib-1_18_2-0.7.319+530ec3a-beta.jar",
          "size": 373597,
          "sha512": "b33446a86a0696b9db95692afa611faf55cfddcd66fec59a1ce4a252008a258835932196114c086d52e4dc750ae7a0f33a37233908000a75d3c4a832edfdbfca",
          "sha256": "256125fb55966558dce829385dc29a04aa2e4fd8d0c0d38aa5cac1d9456a4b63",
          "sha1": "f04957d2b62b433cb903a8cb15f670b667ffe50c",
          "md5": "0402495ef97ace4a0f997f9a0b0c1ed3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.319+530ec3a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.319+530ec3a-beta.jar",
          "url": "magiclib-1_18_2-0.7.319+530ec3a-beta.jar",
          "size": 373597,
          "sha512": "b33446a86a0696b9db95692afa611faf55cfddcd66fec59a1ce4a252008a258835932196114c086d52e4dc750ae7a0f33a37233908000a75d3c4a832edfdbfca",
          "sha256": "256125fb55966558dce829385dc29a04aa2e4fd8d0c0d38aa5cac1d9456a4b63",
          "sha1": "f04957d2b62b433cb903a8cb15f670b667ffe50c",
          "md5": "0402495ef97ace4a0f997f9a0b0c1ed3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.319+530ec3a-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.319+530ec3a-beta-sources.jar",
          "size": 168389,
          "sha512": "b8ba223dfd7f5e11d1d81a7c31b87b09fd881c1b3f26bc32fb8a0a7658e0ca7ab0ba73ebba6b85c2131a05aff0ae9fad160f7475101a3d7db495493c368178a0",
          "sha256": "c4c31bb4e2518e141dedb848928b1909cee48308842ede1d11d81cfdeb8489cb",
          "sha1": "20c5868bc49f3e361957bd94a97add6d13caeebc",
          "md5": "ec863e887580224bfc632ac196b8c0d3"
        }
      ]
    }
  ]
}
