{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-carpet-compat-1_16_5",
    "version": "0.2.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_16_5",
          "version": {
            "requires": "0.5.3+c7ba8f9-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_16_5-0.2.3+c7ba8f9-beta.jar",
          "url": "magiclib-carpet-compat-1_16_5-0.2.3+c7ba8f9-beta.jar",
          "size": 149008,
          "sha512": "5f97ed0d29b485159486ad86f7135d94a7f8d3804600f30a0b780a20bd0996c6d7beee15cf7c814e6af1f993052c491ec33f6536d5f6ac9e2b661de2b8aa6609",
          "sha256": "70fce65793ef442b312bb290b50601d396025a2b60c012526a5e9c75ce70185c",
          "sha1": "4d6c937676a481cb9b427158a800899ff24713c1",
          "md5": "8ec5da33b110bb1d9e6f448b9021be12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_16_5",
          "version": {
            "requires": "0.5.3+c7ba8f9-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_16_5-0.2.3+c7ba8f9-beta.jar",
          "url": "magiclib-carpet-compat-1_16_5-0.2.3+c7ba8f9-beta.jar",
          "size": 149008,
          "sha512": "5f97ed0d29b485159486ad86f7135d94a7f8d3804600f30a0b780a20bd0996c6d7beee15cf7c814e6af1f993052c491ec33f6536d5f6ac9e2b661de2b8aa6609",
          "sha256": "70fce65793ef442b312bb290b50601d396025a2b60c012526a5e9c75ce70185c",
          "sha1": "4d6c937676a481cb9b427158a800899ff24713c1",
          "md5": "8ec5da33b110bb1d9e6f448b9021be12"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_16_5",
          "version": {
            "requires": "0.5.3+c7ba8f9-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_16_5-0.2.3+c7ba8f9-beta-standalone-dev.jar",
          "url": "magiclib-carpet-compat-1_16_5-0.2.3+c7ba8f9-beta-standalone-dev.jar",
          "size": 542880,
          "sha512": "96a35c51bb8052392ab23964b66ae794520666d6edd8f6e4fa75614f8b4bafbcab6be05c90305883f9eaba3cb1dee6cf258ed4b90603d700a52afcb2ef574403",
          "sha256": "360e43e752b92be90673211f1385fb349ac540ae2f31029e552fe6590cd28ef6",
          "sha1": "60a7d42f664c91125113b53a7700754fe81063c9",
          "md5": "2cbb3dc84f7c7119d6fb355066a86819"
        }
      ]
    }
  ]
}
