{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.311+83c833c-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.311+83c833c-beta.jar",
          "url": "magiclib-1_19_4-0.7.311+83c833c-beta.jar",
          "size": 373753,
          "sha512": "60cbd55905e7868304d993ddb3729a989be0b546a43606bba2d0bc68fdecde2c2ba8e778c1696c76dcff3c1234713a4f9026d84ee54b2014d3ff1526bb464ae6",
          "sha256": "aa7f71b7a0324e4d72a06d4deeef423223629642d756605905493931ce387d0b",
          "sha1": "d9672465e995825883c8e8a048ae1877f80878e6",
          "md5": "f81db386adef96b9cd6f194c0906a343"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.311+83c833c-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.311+83c833c-beta.jar",
          "url": "magiclib-1_19_4-0.7.311+83c833c-beta.jar",
          "size": 373753,
          "sha512": "60cbd55905e7868304d993ddb3729a989be0b546a43606bba2d0bc68fdecde2c2ba8e778c1696c76dcff3c1234713a4f9026d84ee54b2014d3ff1526bb464ae6",
          "sha256": "aa7f71b7a0324e4d72a06d4deeef423223629642d756605905493931ce387d0b",
          "sha1": "d9672465e995825883c8e8a048ae1877f80878e6",
          "md5": "f81db386adef96b9cd6f194c0906a343"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.311+83c833c-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.311+83c833c-beta-sources.jar",
          "size": 168193,
          "sha512": "6c2d1e1a34714694a4f545762971e89960b01fd246351fa2fa70a4a193bd6392ae430382e7fbee42e829f3fbeacd6d8a6b43bea47b380a63817aeac0b868eb13",
          "sha256": "ee7838408dee010ef904e2d2ef0d22ffdb968496eaf50a6c54e4e0e2fd339477",
          "sha1": "88519d0174756325648742c97f4d0c3a5f84691b",
          "md5": "b0742e3cbc76ceffb4a43536ebbbb341"
        }
      ]
    }
  ]
}
