{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.283+320fdb8-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-1_18_2-0.7.283+320fdb8-beta.jar",
          "size": 360585,
          "sha512": "c53d29a5b8be9de67e3a173ab2bd59f2a3fdb07c26d34547ef1a354a8cb6235b30c43a58f25c8341789ac80805619e397c14039f5cbb61229ceb32e8e8ac8f53",
          "sha256": "a1eb5fa7da5fbd5bee23e80b5639a73dfa989383904d0141ad773134718c4f35",
          "sha1": "96a4d67b42d97877d0d7e6728d7530c9f42fa0c2",
          "md5": "e06eee749dbae6bd6d3c6e5122f1363b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-1_18_2-0.7.283+320fdb8-beta.jar",
          "size": 360585,
          "sha512": "c53d29a5b8be9de67e3a173ab2bd59f2a3fdb07c26d34547ef1a354a8cb6235b30c43a58f25c8341789ac80805619e397c14039f5cbb61229ceb32e8e8ac8f53",
          "sha256": "a1eb5fa7da5fbd5bee23e80b5639a73dfa989383904d0141ad773134718c4f35",
          "sha1": "96a4d67b42d97877d0d7e6728d7530c9f42fa0c2",
          "md5": "e06eee749dbae6bd6d3c6e5122f1363b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.283+320fdb8-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.283+320fdb8-beta-sources.jar",
          "size": 159539,
          "sha512": "d1eb1a6bd65b8395306f54911d6d1d0a4135dc3fef95eee9df5e6db42f04c6bc05bb85fe926db347a2b2d4e84db2c24f07156ec2445c076b2bc2042df12e3b35",
          "sha256": "7561f06a112c00b608b96ec63a79d1711b87e5c8ce8e5ed6b83c8f90dc5bbfa4",
          "sha1": "536ead269bce6aec72abc187c57f0e74fbaf7143",
          "md5": "8aac614101f9523c922f72d8fcaa264f"
        }
      ]
    }
  ]
}
