{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_16_5",
    "version": "0.5.292+eec667c-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_16_5-0.5.292+eec667c-dev.jar",
          "url": "ommc-1_16_5-0.5.292+eec667c-dev.jar",
          "size": 1153644,
          "sha512": "f52425b41d95adeed12a538d65d64ab27b6057be398184a37d03eff70cb12c34cf5a1e023fe2b1a2ab04d438c59706dc2bb7073d4ea5513c3286436f02f53840",
          "sha256": "5c3d21ad363777a8833af1055dd64e47ee6d498c4eb66b4b3d10397640a85f24",
          "sha1": "f8b303205f0da8727b84d0df2c19df036b94f4e1",
          "md5": "cfd318084d361229d405437ea0a9abeb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.292+eec667c-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_16_5",
          "version": {
            "requires": "0.7.336"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_16_5-0.5.292+eec667c-dev.jar",
          "url": "ommc-1_16_5-0.5.292+eec667c-dev.jar",
          "size": 1153644,
          "sha512": "f52425b41d95adeed12a538d65d64ab27b6057be398184a37d03eff70cb12c34cf5a1e023fe2b1a2ab04d438c59706dc2bb7073d4ea5513c3286436f02f53840",
          "sha256": "5c3d21ad363777a8833af1055dd64e47ee6d498c4eb66b4b3d10397640a85f24",
          "sha1": "f8b303205f0da8727b84d0df2c19df036b94f4e1",
          "md5": "cfd318084d361229d405437ea0a9abeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
