{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.330+0499b91-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.330+0499b91-beta.jar",
          "url": "magiclib-1_19_2-0.7.330+0499b91-beta.jar",
          "size": 375963,
          "sha512": "d27f75589f50aa5ef6c2075a80193f7ba6367bd379f6c4dc3bb16b79e2373d92e3ffc5ed189320a03be2813e61e71e18bda52e59f0bb3fa8a993b7b4f81066a3",
          "sha256": "999bb7635b106930ff85c0e0ac00ed722704d33290bccefc5b757a4ec1bb5f85",
          "sha1": "d079f6cd700c53d965def0997989a173b6d1346e",
          "md5": "c4682d3d6b597131fb6ec1418a034a6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.330+0499b91-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.330+0499b91-beta.jar",
          "url": "magiclib-1_19_2-0.7.330+0499b91-beta.jar",
          "size": 375963,
          "sha512": "d27f75589f50aa5ef6c2075a80193f7ba6367bd379f6c4dc3bb16b79e2373d92e3ffc5ed189320a03be2813e61e71e18bda52e59f0bb3fa8a993b7b4f81066a3",
          "sha256": "999bb7635b106930ff85c0e0ac00ed722704d33290bccefc5b757a4ec1bb5f85",
          "sha1": "d079f6cd700c53d965def0997989a173b6d1346e",
          "md5": "c4682d3d6b597131fb6ec1418a034a6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.330+0499b91-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.330+0499b91-beta-sources.jar",
          "size": 168858,
          "sha512": "2849d185867eba0bcfd7f0253ed40a662c6f522e5e362a3aaae6c576a30cebc7bd75685f5f2689edb10e4964d2fea1ce99c7c29de33b1248b359dbe09cfaab47",
          "sha256": "be407eec1559345ea9c2f50a3aaaf5b2928dc1da3dfcf7bd779cfcb51cd1628a",
          "sha1": "68fca5caa16ef664012d9acf3985158b6f1f1b33",
          "md5": "a46d9a06340c01ddcb720922b67f9ac8"
        }
      ]
    }
  ]
}
