{
  "formatVersion": "1.1",
  "component": {
    "group": "curse.maven",
    "module": "ommc-454900-1_17_1",
    "version": "0.5-alpha+4d91bac",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-454900-1_17_1-0.5-alpha+4d91bac.jar",
          "url": "ommc-454900-1_17_1-0.5-alpha+4d91bac.jar",
          "size": 146246,
          "sha512": "950182f767d2555e979fa3a504e900fbc1c60c40bc7e99f42147d4adf98aa69d34320088eb6147f76d1a5300129caef370e568ae021c1abce4b5532850a8b4b3",
          "sha256": "8acd742627765bf60e3733994f546179d2b91bbf15988340ac2518aae33ba371",
          "sha1": "ead09a400cab6fd671620665f4f6871359b80313",
          "md5": "e6fbbdd8b7fec7eefb8c83a596b62a28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "ommc-454900",
          "version": {
            "requires": "0.5-alpha+4d91bac"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_17_1",
          "version": {
            "requires": "0.5.37"
          }
        }
      ],
      "files": [
        {
          "name": "ommc-454900-1_17_1-0.5-alpha+4d91bac.jar",
          "url": "ommc-454900-1_17_1-0.5-alpha+4d91bac.jar",
          "size": 146246,
          "sha512": "950182f767d2555e979fa3a504e900fbc1c60c40bc7e99f42147d4adf98aa69d34320088eb6147f76d1a5300129caef370e568ae021c1abce4b5532850a8b4b3",
          "sha256": "8acd742627765bf60e3733994f546179d2b91bbf15988340ac2518aae33ba371",
          "sha1": "ead09a400cab6fd671620665f4f6871359b80313",
          "md5": "e6fbbdd8b7fec7eefb8c83a596b62a28"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ommc-454900-1_17_1-0.5-alpha+4d91bac-sources.jar",
          "url": "ommc-454900-1_17_1-0.5-alpha+4d91bac-sources.jar",
          "size": 93500,
          "sha512": "15401ee429bec653d704a6223d45ec1a1447e5cc9b7cb8ec9cad6343ad2ea6b4c12f79e5e6ee2b7829e376672560f4fbe8a438c88c410acdff9921f00e73a76b",
          "sha256": "7e362181bc4f0358812c97dd584ac977c8864854d7c31c4a537b696f72b17236",
          "sha1": "d78ce798ee3c3c6a57e35f4094bedf8c18c4ba09",
          "md5": "ca746012161a5b5ee54cd0005c9a75ca"
        }
      ]
    }
  ]
}
