{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-minecraft-compat-1_15_2",
    "version": "0.5.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_15_2",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_15_2-0.5.2+32bcf58-beta.jar",
          "url": "magiclib-minecraft-compat-1_15_2-0.5.2+32bcf58-beta.jar",
          "size": 143206,
          "sha512": "66250c7d59cca38cb80692f8e745202fe18023af43ee0225806f547644e0cfe2484fd14b3f426ef944d4cfacf0b5130cbf5d189cfe7ce1af5c2c653378dc5cfd",
          "sha256": "2098d480e0f47b10e60c84babce55805e6fa9bd1d6ae074e7899d235edec5bf5",
          "sha1": "d2bcbfdc3f416f4d54b734d94abbc3a2b2225038",
          "md5": "999e02151e11b55be757acd35a0644c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_15_2",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_15_2-0.5.2+32bcf58-beta.jar",
          "url": "magiclib-minecraft-compat-1_15_2-0.5.2+32bcf58-beta.jar",
          "size": 143206,
          "sha512": "66250c7d59cca38cb80692f8e745202fe18023af43ee0225806f547644e0cfe2484fd14b3f426ef944d4cfacf0b5130cbf5d189cfe7ce1af5c2c653378dc5cfd",
          "sha256": "2098d480e0f47b10e60c84babce55805e6fa9bd1d6ae074e7899d235edec5bf5",
          "sha1": "d2bcbfdc3f416f4d54b734d94abbc3a2b2225038",
          "md5": "999e02151e11b55be757acd35a0644c2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_15_2",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_15_2-0.5.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-minecraft-compat-1_15_2-0.5.2+32bcf58-beta-standalone-dev.jar",
          "size": 396101,
          "sha512": "3c393a38d98e898ede084f91f569292efecf9f56d1166ba14831ee1e871776b3c69ced45ea2afb3c909bad0bfc4cd93473e75b3b39996c3e2a966045286fb6cc",
          "sha256": "8b5288f33aa42dd7bad816894421effb8f8cb7a5129139cf860e948e19e9a0c4",
          "sha1": "654cbec279d3390c7a44467334649b48970d5e82",
          "md5": "31c16a69a4d8edfa31023fc70f6a9ef4"
        }
      ]
    }
  ]
}
