{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_14_4",
    "version": "0.5.292+eec667c-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_14_4-0.5.292+eec667c-dev.jar",
          "url": "ommc-1_14_4-0.5.292+eec667c-dev.jar",
          "size": 1150084,
          "sha512": "18621a3bd31b9fb0af4d82d6188b63e73c33d55912596d2db93944e1334ede112995ea2a1efe03c2435f93554287b3cfc3be56b966b96987cff027a9625e13d4",
          "sha256": "72ca22b8796faad0f383a151eb6ed59b3c65883e86673ee6219a6cae3d04fbc0",
          "sha1": "bed246469075b71aec22363738dc6adebb0b13d1",
          "md5": "6e68e45fc2721591a1516c6cde612531"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.292+eec667c-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_14_4",
          "version": {
            "requires": "0.7.336"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_14_4-0.5.292+eec667c-dev.jar",
          "url": "ommc-1_14_4-0.5.292+eec667c-dev.jar",
          "size": 1150084,
          "sha512": "18621a3bd31b9fb0af4d82d6188b63e73c33d55912596d2db93944e1334ede112995ea2a1efe03c2435f93554287b3cfc3be56b966b96987cff027a9625e13d4",
          "sha256": "72ca22b8796faad0f383a151eb6ed59b3c65883e86673ee6219a6cae3d04fbc0",
          "sha1": "bed246469075b71aec22363738dc6adebb0b13d1",
          "md5": "6e68e45fc2721591a1516c6cde612531"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
