{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.308+d9af2fc-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_19_4-0.7.308+d9af2fc-beta.jar",
          "size": 371674,
          "sha512": "c7e51186d18fa3b06c83df3e439553333c40aa3e8235fc9099dad743f5e0bf61712652e4e8eda870d91532531042b0886420498afa06303619192267722fa8e0",
          "sha256": "2082b86db613c91fd6aeeaae22fff1168e65f2a216c88d3b652ac524cf39b8b2",
          "sha1": "f142e540f0bc97e7d34652856aa6db031d1d7478",
          "md5": "68dc4ccdcb8bbe1750df467580d98944"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.308+d9af2fc-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_19_4-0.7.308+d9af2fc-beta.jar",
          "size": 371674,
          "sha512": "c7e51186d18fa3b06c83df3e439553333c40aa3e8235fc9099dad743f5e0bf61712652e4e8eda870d91532531042b0886420498afa06303619192267722fa8e0",
          "sha256": "2082b86db613c91fd6aeeaae22fff1168e65f2a216c88d3b652ac524cf39b8b2",
          "sha1": "f142e540f0bc97e7d34652856aa6db031d1d7478",
          "md5": "68dc4ccdcb8bbe1750df467580d98944"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.308+d9af2fc-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.308+d9af2fc-beta-sources.jar",
          "size": 166852,
          "sha512": "db20229d6d5e611ead296a5cc5e2542fa4583d13f5ec5510d2b1d73f6668e44c239acaaa3261172116e60bd8cf5c51da270030e3eb3e311c0a161f319295e285",
          "sha256": "240f38b934c2a297d0596353a4b355d755ccccdb1fe234f7f0fac5043928be08",
          "sha1": "750e30476989377fecc58cfc22670b89b5127cf6",
          "md5": "2bfc7c79330af6d6350a3feb03f9578a"
        }
      ]
    }
  ]
}
