{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.284+fd02f73-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.284+fd02f73-beta.jar",
          "url": "magiclib-1_19_3-0.7.284+fd02f73-beta.jar",
          "size": 360693,
          "sha512": "a96ac24b66efd9ce8f6338e2a2284ed8d410f766709dccc7eec4f7b21f27094d23a5040847a202dd9e4ec39899ef3a4b3ad12c7567b4f88e07eece0def8d1f75",
          "sha256": "ddd8c9e8b1533bbc4f284b54c88494221d502639235b43365a55f032253aca21",
          "sha1": "224fb8da651d5626e4942c001e178753f3e306e3",
          "md5": "d850bc5c54e5732190ea67a5ec5a1e66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.284+fd02f73-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4215578"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.284+fd02f73-beta.jar",
          "url": "magiclib-1_19_3-0.7.284+fd02f73-beta.jar",
          "size": 360693,
          "sha512": "a96ac24b66efd9ce8f6338e2a2284ed8d410f766709dccc7eec4f7b21f27094d23a5040847a202dd9e4ec39899ef3a4b3ad12c7567b4f88e07eece0def8d1f75",
          "sha256": "ddd8c9e8b1533bbc4f284b54c88494221d502639235b43365a55f032253aca21",
          "sha1": "224fb8da651d5626e4942c001e178753f3e306e3",
          "md5": "d850bc5c54e5732190ea67a5ec5a1e66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.284+fd02f73-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.284+fd02f73-beta-sources.jar",
          "size": 159596,
          "sha512": "ca77438eff1d4cf5b90b4d99db4063b12aec45c3c04f780bcc3a30f10c158ef26e75ca868b36b17d70730ea69b71e17747c66608e1af3e50515f18678a0dc161",
          "sha256": "2cbfcf8d53bb79a0e06b49d0fbeecae416b438c0cf9ebf133a4c639f2b8daa0b",
          "sha1": "fabda307fbe7155bf6ee5f774ab0e22692c32f80",
          "md5": "5f50370b4797c2770b9743b06adfa3ff"
        }
      ]
    }
  ]
}
