{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.329+ed83ba7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.329+ed83ba7-beta.jar",
          "url": "magiclib-1_17_1-0.7.329+ed83ba7-beta.jar",
          "size": 373276,
          "sha512": "44e594ccb6725a0abc9849aeca627e2ecce7208faace93d2ea8a0b589f2ced92076a8605dd11173385c0cf4f977303df24ecaf544f3ceda21b8c07fb7688a22c",
          "sha256": "cf2af981c545ce6931d9efe9c9eddee57409e3f2bbc80b9829c81f1b09217bf3",
          "sha1": "a235f6f5d4035aecd77e8bfcab57b8f1084e5cc6",
          "md5": "6249d1875f4090bf51d54d31b5b71e51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.329+ed83ba7-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.329+ed83ba7-beta.jar",
          "url": "magiclib-1_17_1-0.7.329+ed83ba7-beta.jar",
          "size": 373276,
          "sha512": "44e594ccb6725a0abc9849aeca627e2ecce7208faace93d2ea8a0b589f2ced92076a8605dd11173385c0cf4f977303df24ecaf544f3ceda21b8c07fb7688a22c",
          "sha256": "cf2af981c545ce6931d9efe9c9eddee57409e3f2bbc80b9829c81f1b09217bf3",
          "sha1": "a235f6f5d4035aecd77e8bfcab57b8f1084e5cc6",
          "md5": "6249d1875f4090bf51d54d31b5b71e51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.329+ed83ba7-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.329+ed83ba7-beta-sources.jar",
          "size": 168931,
          "sha512": "c4b63a66458c83be9c44062e09149543c1a5589c28d60924d85a54f44593514fa77aed71cee6f707800a94014816afcee2012f8f8a94c4be2a7aa410a7c186b4",
          "sha256": "6de3e21d334b48673078d707b31c1352d7c45de118cbd9153901eed9c7d574c1",
          "sha1": "123c2dda0db378ecffbac65d7994fb4d71099496",
          "md5": "a40fbc9ef8dd3825a3801ee42f53fee7"
        }
      ]
    }
  ]
}
