{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_17_1",
    "version": "0.5.294+e12a73f-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_17_1-0.5.294+e12a73f-dev.jar",
          "url": "ommc-1_17_1-0.5.294+e12a73f-dev.jar",
          "size": 1141013,
          "sha512": "220573d89589dffe039b96b3a477d4bc72651a5c3e6bf506cde1850ee82acd725ec72040ffdc36086874f5c96eed7d4fdaadfec9e6d3e2b4bc1a8fc67aa9ff7f",
          "sha256": "7624a2930bdecf5010ff37be847fe2ea57c4a7d70933b5a72a2886cab6f674c7",
          "sha1": "9a721626a29e4df179c3379228c1c927e3df078e",
          "md5": "3faca58d7b16525dd44884e5374d0d9b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.294+e12a73f-dev"
          }
        },
        {
          "group": "top.hendrixshen.magiclib",
          "module": "magiclib-1_17_1",
          "version": {
            "requires": "0.7.345"
          },
          "excludes": [
            {
              "group": "carpet",
              "module": "fabric-carpet"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_17_1-0.5.294+e12a73f-dev.jar",
          "url": "ommc-1_17_1-0.5.294+e12a73f-dev.jar",
          "size": 1141013,
          "sha512": "220573d89589dffe039b96b3a477d4bc72651a5c3e6bf506cde1850ee82acd725ec72040ffdc36086874f5c96eed7d4fdaadfec9e6d3e2b4bc1a8fc67aa9ff7f",
          "sha256": "7624a2930bdecf5010ff37be847fe2ea57c4a7d70933b5a72a2886cab6f674c7",
          "sha1": "9a721626a29e4df179c3379228c1c927e3df078e",
          "md5": "3faca58d7b16525dd44884e5374d0d9b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
