{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.331+c783ba0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_19_3-0.7.331+c783ba0-beta.jar",
          "size": 375153,
          "sha512": "5f3b116cbd0ccd0ce19df3993baf1e2be47579ff44cf5ccfa999e1fddff8ef9ba6b45885affa456a36ba8d4476590994343262edd21bee9d703ddcf58d668999",
          "sha256": "2e98a797b1c21564e5fb3945e6d4f7da02ec8686de88f16b05c7a692c5b8abea",
          "sha1": "fb9f523a9be4ba79f6b3758e1a7bdceb85b235f9",
          "md5": "26e5855080d7e2d4061c3ebf3f05c52c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.331+c783ba0-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_19_3-0.7.331+c783ba0-beta.jar",
          "size": 375153,
          "sha512": "5f3b116cbd0ccd0ce19df3993baf1e2be47579ff44cf5ccfa999e1fddff8ef9ba6b45885affa456a36ba8d4476590994343262edd21bee9d703ddcf58d668999",
          "sha256": "2e98a797b1c21564e5fb3945e6d4f7da02ec8686de88f16b05c7a692c5b8abea",
          "sha1": "fb9f523a9be4ba79f6b3758e1a7bdceb85b235f9",
          "md5": "26e5855080d7e2d4061c3ebf3f05c52c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.331+c783ba0-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.331+c783ba0-beta-sources.jar",
          "size": 169006,
          "sha512": "e53b515364f109a10d8af42a114c051c9eb7d54b33f4af3bc744ed117929a91aa07c208afb9d5710f0f81ec080f15163b7cf881df8a0f3a879bc09f8a652dfff",
          "sha256": "cdbe9da1091b50a659fa8cd4d93a7fc26c72968aff04f781abda432ab4533ec0",
          "sha1": "9b65d2c5419ef824dec64ac78640ed53a236121f",
          "md5": "c27ecb54621094fd0c2923bd1c552832"
        }
      ]
    }
  ]
}
