{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra-1_16_5",
    "version": "0.7.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_16_5",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_16_5-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-malilib-extra-1_16_5-0.7.3+c7ba8f9-beta.jar",
          "size": 157457,
          "sha512": "e49384cd203973e878909b7362371aff5880a6b4376c90e39ec559271eff07095a74f49a462876a5613e7cfc85e7d5adae680e623910476a0d7fbc7348101cd4",
          "sha256": "33dd84969c6fc5241524805538be9113ab8ce12bfc0f2663a240197246a771fb",
          "sha1": "4544e99a8d037cfecf9265e6d4af04ada26801d6",
          "md5": "8ae235e2fa8cb29a422ba65a84b5c114"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_16_5",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_16_5-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-malilib-extra-1_16_5-0.7.3+c7ba8f9-beta.jar",
          "size": 157457,
          "sha512": "e49384cd203973e878909b7362371aff5880a6b4376c90e39ec559271eff07095a74f49a462876a5613e7cfc85e7d5adae680e623910476a0d7fbc7348101cd4",
          "sha256": "33dd84969c6fc5241524805538be9113ab8ce12bfc0f2663a240197246a771fb",
          "sha1": "4544e99a8d037cfecf9265e6d4af04ada26801d6",
          "md5": "8ae235e2fa8cb29a422ba65a84b5c114"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_16_5",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_16_5-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "url": "magiclib-malilib-extra-1_16_5-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "size": 412981,
          "sha512": "7e746cc117d4741fb97ee1f91b437e13dd56f06dcbd399a50bee2b4573cd216f3ac8bece21e6c777982f87131450bd5de3edba3bd0ba9fcba2bd735e498685df",
          "sha256": "e5bb9087c1b19c708a984f85695cd4b8722594557e8ceae43d687e795fa732e7",
          "sha1": "ec15273e8f5cd70a3929f41bd6357e32a997c920",
          "md5": "786756aa24cb4b381cb025553b8733f0"
        }
      ]
    }
  ]
}
