{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.309+3356ade-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.309+3356ade-beta.jar",
          "url": "magiclib-1_17_1-0.7.309+3356ade-beta.jar",
          "size": 369889,
          "sha512": "365cf5ff453e9bfba1b8503e294fc87e40c6cedd0a6097e3e95db8272f597e8da9b23a8aa748df27b7f2861b8c2657473cba1503e7e6804c5e64146d13d1ba83",
          "sha256": "cb433390a41f84680d33fa2f10bd623fa9e955e9c22a853524613ef8e476fb80",
          "sha1": "d0c7a318d893ec0f1e8b90e63df86cc71f18d445",
          "md5": "1b876b1dd0b4b975f64d1dc34b845236"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.309+3356ade-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.309+3356ade-beta.jar",
          "url": "magiclib-1_17_1-0.7.309+3356ade-beta.jar",
          "size": 369889,
          "sha512": "365cf5ff453e9bfba1b8503e294fc87e40c6cedd0a6097e3e95db8272f597e8da9b23a8aa748df27b7f2861b8c2657473cba1503e7e6804c5e64146d13d1ba83",
          "sha256": "cb433390a41f84680d33fa2f10bd623fa9e955e9c22a853524613ef8e476fb80",
          "sha1": "d0c7a318d893ec0f1e8b90e63df86cc71f18d445",
          "md5": "1b876b1dd0b4b975f64d1dc34b845236"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.309+3356ade-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.309+3356ade-beta-sources.jar",
          "size": 166848,
          "sha512": "be3d64503a4a726aaf0eb1f8297995ed60c4a62c9332e24b9f96b131ac5ac59e36db300c2880b02f51739d73586bab916bdf1867540aa7fa3d4eed3d613a423b",
          "sha256": "daa3c78b340f7f6fa4cb4e0db3372c25fa002cfd11379c4107135a22a213db6b",
          "sha1": "14cca900cef3295131f9dafcc301798f521018fc",
          "md5": "06853a89c533d3fb070af1e3b2f2e2e1"
        }
      ]
    }
  ]
}
