{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.300+7c8ee92-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_18_2-0.7.300+7c8ee92-beta.jar",
          "size": 360408,
          "sha512": "3de3664d1a3b958670347eaa007ec5f57f07b6b464e9fa2097a9b9074c091772f542b2e2cc3557a92cceed1212cc2b0c1e9ee0de20b1a2d4613f8907ff0f3acb",
          "sha256": "533790dba44f997a2d76621061a7b7fc045f18da8788d3a11179a7fc9d117fdd",
          "sha1": "e7730497cacc5c5053d4b7442adfd2219928efee",
          "md5": "384c8f47578d655b81d1e7665a5822a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.300+7c8ee92-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_18_2-0.7.300+7c8ee92-beta.jar",
          "size": 360408,
          "sha512": "3de3664d1a3b958670347eaa007ec5f57f07b6b464e9fa2097a9b9074c091772f542b2e2cc3557a92cceed1212cc2b0c1e9ee0de20b1a2d4613f8907ff0f3acb",
          "sha256": "533790dba44f997a2d76621061a7b7fc045f18da8788d3a11179a7fc9d117fdd",
          "sha1": "e7730497cacc5c5053d4b7442adfd2219928efee",
          "md5": "384c8f47578d655b81d1e7665a5822a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.300+7c8ee92-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.300+7c8ee92-beta-sources.jar",
          "size": 159567,
          "sha512": "b3bea2072e19d46536946621f4ca064240056477a6e01cb80cdbd4e15f9470c1e0936502a462ec4d9af1ad7ccd5a4bf13d5bbd9e4839efb9943fb73a6a14c1e9",
          "sha256": "ebd7f0d90cb87b2134863fea89d9e2067976ddf54936de6ee79fa86c11647309",
          "sha1": "ca84adaece214f72ccefb8042d447506291ac7d2",
          "md5": "74e0f09800201fa66bd8eb534ad629c5"
        }
      ]
    }
  ]
}
