{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-carpet-compat-1_14_4",
    "version": "0.2.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_14_4",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "2870184"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_14_4-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_14_4-0.2.2+32bcf58-beta.jar",
          "size": 144104,
          "sha512": "811fcbcfc1a62369777d992bf7a99233c47c2002887c512b9390e9af7ee5cb9b61c8853f7c1b5cb51fec8037e6dad57e4f7a7f1c429319c759e1a2fa5d725465",
          "sha256": "d3ecfcf8e20d6cd6d3eb46470dbdb34829b86a0a43626802af9b10262ce59104",
          "sha1": "3282300a9f9e93c4739e1c0cff15bdc10f3fafc8",
          "md5": "6f390d9329bec23097a827d53d8ef088"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_14_4",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "2870184"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_14_4-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_14_4-0.2.2+32bcf58-beta.jar",
          "size": 144104,
          "sha512": "811fcbcfc1a62369777d992bf7a99233c47c2002887c512b9390e9af7ee5cb9b61c8853f7c1b5cb51fec8037e6dad57e4f7a7f1c429319c759e1a2fa5d725465",
          "sha256": "d3ecfcf8e20d6cd6d3eb46470dbdb34829b86a0a43626802af9b10262ce59104",
          "sha1": "3282300a9f9e93c4739e1c0cff15bdc10f3fafc8",
          "md5": "6f390d9329bec23097a827d53d8ef088"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_14_4",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_14_4-0.2.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-carpet-compat-1_14_4-0.2.2+32bcf58-beta-standalone-dev.jar",
          "size": 552274,
          "sha512": "51b4d3bcde4ffcb488af85e5ddef9cd4e2251177c1c12e8c4acbd9342248ef96b985de0a8bdd80fd2d4dc76cc4b735d7e87959e851c0910cec2effa8f65ed179",
          "sha256": "5f89041de6cc43fe3a1d97c946789e8c9ff16c0b45a6f0d7f6578bcf5840e518",
          "sha1": "cf25a4c2e3a2814b8a2f9e1d63bfbf05bbac70b7",
          "md5": "1ac3f85eb9bc254e60c25d7db877fdda"
        }
      ]
    }
  ]
}
