{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-22w19a",
    "version": "0.5.27",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "22w19a"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3761830"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.52.2+1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-22w19a-0.5.27.jar",
          "url": "magiclib-22w19a-0.5.27.jar",
          "size": 254036,
          "sha512": "42f08591ef27bed4d23996374369c61057e850a8e40ba667e17f8e6f54ed57a0d9566707141c11914c0f7b73db91319d11611a29758bda4de640cf53790d3d31",
          "sha256": "d2f9820053c5abf72d3545d39ff73f25f185251170838b429366de97524b6b6b",
          "sha1": "a174d459f04675121b2ab8bb0d7cfa246a540250",
          "md5": "8ec27bd0df0e31eedc4c36256422bd26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.27"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "22w19a"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3761830"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.52.2+1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.5"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3545107"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-22w19a-0.5.27.jar",
          "url": "magiclib-22w19a-0.5.27.jar",
          "size": 254036,
          "sha512": "42f08591ef27bed4d23996374369c61057e850a8e40ba667e17f8e6f54ed57a0d9566707141c11914c0f7b73db91319d11611a29758bda4de640cf53790d3d31",
          "sha256": "d2f9820053c5abf72d3545d39ff73f25f185251170838b429366de97524b6b6b",
          "sha1": "a174d459f04675121b2ab8bb0d7cfa246a540250",
          "md5": "8ec27bd0df0e31eedc4c36256422bd26"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-22w19a-0.5.27-sources.jar",
          "url": "magiclib-22w19a-0.5.27-sources.jar",
          "size": 192543,
          "sha512": "e3289050e606bfe6a30e9213731a76e80bc9e2e816c9a0a2d9c7c3c975613d33379faccab635c5e66a4abf4ba0b4fee4e7e213dd8d397856e5ad958275e5ddbc",
          "sha256": "ee5c8932f0507ce802ef00ccaa917cd9f98dc33a70240910d94d96142a46eb7f",
          "sha1": "c34cb2c428bf4aa658a112e0ba1bd40bfcb9b0bf",
          "md5": "c9a5d7d9912060d618a6d97177ceea09"
        }
      ]
    }
  ]
}
