{
  "formatVersion": "1.1",
  "component": {
    "group": "curse.maven",
    "module": "malilib-303119",
    "version": "22w17a",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "malilib-303119-22w17a.jar",
          "url": "malilib-303119-22w17a.jar",
          "size": 516453,
          "sha512": "372f3e901bf67d9160306ff52fa94182b2d75ffa2c6795909b95678ebcfd99d18acd03ae4f967808b0588b73b9d2fd5e5665f24d2f2df540eb9724ae651d4e99",
          "sha256": "787c516fc316638715af9fc776e91373935c342fc57197b77a38426b305b4070",
          "sha1": "b3dd0613e5748188a4e4524774dee4b9e1c2330b",
          "md5": "6fb8f081f56b9618ba82f6a7b91c62e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.4.24+ec94c6f6a7"
          }
        }
      ],
      "files": [
        {
          "name": "malilib-303119-22w17a.jar",
          "url": "malilib-303119-22w17a.jar",
          "size": 516453,
          "sha512": "372f3e901bf67d9160306ff52fa94182b2d75ffa2c6795909b95678ebcfd99d18acd03ae4f967808b0588b73b9d2fd5e5665f24d2f2df540eb9724ae651d4e99",
          "sha256": "787c516fc316638715af9fc776e91373935c342fc57197b77a38426b305b4070",
          "sha1": "b3dd0613e5748188a4e4524774dee4b9e1c2330b",
          "md5": "6fb8f081f56b9618ba82f6a7b91c62e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "malilib-303119-22w17a-sources.jar",
          "url": "malilib-303119-22w17a-sources.jar",
          "size": 261593,
          "sha512": "a4c9c04cff6c4fb29ae1cba11264b94a4ca42073643c8693d0edbd5219643627812dcad6ad2c6e476a585ab10f7c8bcb20286c2298546c387aef74dc12020ea9",
          "sha256": "0da1718ca5047d0af69cb7c4f9cd2733b1b1634b140aaf17b7d4e7f750637ba2",
          "sha1": "354286f616d4d00d0d943624c3489772ffaa3e7e",
          "md5": "e518d43ec8914cfb6efd23614a41e303"
        }
      ]
    }
  ]
}
