{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.5.38",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.38.jar",
          "url": "magiclib-1_16_5-0.5.38.jar",
          "size": 255405,
          "sha512": "10dccd6ffd7fef7b7ab0726a6acec1c6af3758aefefdae1ca11e1ddfa26bfdfbdf25aaf2a778af323ad059e71465d6a116c58ff977a26885a3301f42ad52ba97",
          "sha256": "c0071b1f0c73d9ed029ca1950d4b97ecbbd27c3c08daa29cf0f6b68f2aa4d1f0",
          "sha1": "c1490c7538b2b07ebe56a1e449cab45dcc8fb7ae",
          "md5": "9aa3417c733b894fb7b6e7ff8041f553"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.38"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827450"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.38.jar",
          "url": "magiclib-1_16_5-0.5.38.jar",
          "size": 255405,
          "sha512": "10dccd6ffd7fef7b7ab0726a6acec1c6af3758aefefdae1ca11e1ddfa26bfdfbdf25aaf2a778af323ad059e71465d6a116c58ff977a26885a3301f42ad52ba97",
          "sha256": "c0071b1f0c73d9ed029ca1950d4b97ecbbd27c3c08daa29cf0f6b68f2aa4d1f0",
          "sha1": "c1490c7538b2b07ebe56a1e449cab45dcc8fb7ae",
          "md5": "9aa3417c733b894fb7b6e7ff8041f553"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.38-sources.jar",
          "url": "magiclib-1_16_5-0.5.38-sources.jar",
          "size": 192633,
          "sha512": "346e538354a5ce33692ade3bfc1ee78cc266db307b801e7066907c68bcb5b0bdd7d169a4375d60164fdf192416aa76336cd81a4e6ea2294eba53b28a11ca797c",
          "sha256": "2b18183112ef84745002bda9c7ec8c583358200bfaba71fc2c83f43fb5db57ac",
          "sha1": "1afd827cbeb256f2e40400ed44b223e4fe398bc8",
          "md5": "00083e7852bd717922c7bb98e6041843"
        }
      ]
    }
  ]
}
