{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.302+8d1be4b-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.302+8d1be4b-beta.jar",
          "url": "magiclib-1_17_1-0.7.302+8d1be4b-beta.jar",
          "size": 358970,
          "sha512": "9a1287970f06281d6bc5384cea166b5bb5322510edc3369ef47947f8d8bb7df0752a448e4c865935f0083a1460a1a0585fbdd2551eff67ad1e14033fa08293bd",
          "sha256": "7239e8d13442077df47cc2451027dff0a338f75db6380157d721e9e8a4541d6a",
          "sha1": "99c9817389457655d3f1b16643343df81b7301e5",
          "md5": "41f26001185c4fe0c7d66d8f0223077f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.302+8d1be4b-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.302+8d1be4b-beta.jar",
          "url": "magiclib-1_17_1-0.7.302+8d1be4b-beta.jar",
          "size": 358970,
          "sha512": "9a1287970f06281d6bc5384cea166b5bb5322510edc3369ef47947f8d8bb7df0752a448e4c865935f0083a1460a1a0585fbdd2551eff67ad1e14033fa08293bd",
          "sha256": "7239e8d13442077df47cc2451027dff0a338f75db6380157d721e9e8a4541d6a",
          "sha1": "99c9817389457655d3f1b16643343df81b7301e5",
          "md5": "41f26001185c4fe0c7d66d8f0223077f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.302+8d1be4b-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.302+8d1be4b-beta-sources.jar",
          "size": 159689,
          "sha512": "a2378785484609c95d93aabf3a5a3ac3dc684184199140a97c4c1d86db8eff7f8572a978ba491ad27aa799a72a5f78ae2d7e3e8a248fd700d9f885dc36dd28d9",
          "sha256": "3f2415fecc265177bbd295244108c52003b584226f1d54083ef8bca54817fca0",
          "sha1": "da51a6e4c9056cf774096bcb3648bc3ee5edb981",
          "md5": "7f46845f37f83c81005602f4ea8ab821"
        }
      ]
    }
  ]
}
