{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base-1_18_2",
    "version": "0.7.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.67.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_18_2-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-base-1_18_2-0.7.3+c7ba8f9-beta.jar",
          "size": 119670,
          "sha512": "48621293ca083cb90b3db52db6c57dc127566629d84657912ce2ac27d73a9606e20cebb2ac25c1c611f79e5a499aeca4a1827a47761b5b37f4e65c9b448ee7d6",
          "sha256": "1d85e21e0dce1b0073e77c329633e2200572b7dcbb0963d87a8c8d92ccdc81f0",
          "sha1": "8fddb628aa3f06d928af8b64361ce33aa2d1070e",
          "md5": "15b4da2744b710cc02a882e84f49cc45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.67.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_18_2-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-base-1_18_2-0.7.3+c7ba8f9-beta.jar",
          "size": 119670,
          "sha512": "48621293ca083cb90b3db52db6c57dc127566629d84657912ce2ac27d73a9606e20cebb2ac25c1c611f79e5a499aeca4a1827a47761b5b37f4e65c9b448ee7d6",
          "sha256": "1d85e21e0dce1b0073e77c329633e2200572b7dcbb0963d87a8c8d92ccdc81f0",
          "sha1": "8fddb628aa3f06d928af8b64361ce33aa2d1070e",
          "md5": "15b4da2744b710cc02a882e84f49cc45"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_18_2-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "url": "magiclib-base-1_18_2-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "size": 260132,
          "sha512": "2488f248d34a1da3f71805cdce3c5358598bf3e461cbcd2e2b93369ea4e517e9b0984eecf4e39a0731367dffc4ddfd63bd0ee56f1a0881e1735aaddd5b57ce8b",
          "sha256": "92d5b3041adb87b2a6bf4fce37638bb913c869c4fdbfeec5d0178828365ed23a",
          "sha1": "352af210e16abac63dc4d59851e7d70baedb0cb7",
          "md5": "aa7a7d374ce23c7f6da90cfe5d2ba527"
        }
      ]
    }
  ]
}
