{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.309+3356ade-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.309+3356ade-beta.jar",
          "url": "magiclib-1_19_4-0.7.309+3356ade-beta.jar",
          "size": 371819,
          "sha512": "dcbdc2e20daefcd12d882e8eb51531f3313d013f09037f90516fb50712542d41da69b812cae83dfee2f16d356158a29152c4d2e305053deea1573691d84c63a7",
          "sha256": "e033b9c3bf6e4112209a796977c0b049e974e7fe3561d2e6a80d6c3d4c875387",
          "sha1": "c3a16906bb99a257c85caa55b351b2200a20c911",
          "md5": "04df89ecb56334e0b6746e1a9c2b3e21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.309+3356ade-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.309+3356ade-beta.jar",
          "url": "magiclib-1_19_4-0.7.309+3356ade-beta.jar",
          "size": 371819,
          "sha512": "dcbdc2e20daefcd12d882e8eb51531f3313d013f09037f90516fb50712542d41da69b812cae83dfee2f16d356158a29152c4d2e305053deea1573691d84c63a7",
          "sha256": "e033b9c3bf6e4112209a796977c0b049e974e7fe3561d2e6a80d6c3d4c875387",
          "sha1": "c3a16906bb99a257c85caa55b351b2200a20c911",
          "md5": "04df89ecb56334e0b6746e1a9c2b3e21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.309+3356ade-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.309+3356ade-beta-sources.jar",
          "size": 166905,
          "sha512": "5611d4ccf4d6a25106f515677eb9c60f022a5dca57702f0267b8f410d9a55e6ffdcd460f9396cc9b2ed9835a5de4c260f674db7260f09c08aa75bbc297008ac1",
          "sha256": "c4ee5189b601f907348d8d6bdd2d8439fa585693c9ae874f80b4bbea853530f6",
          "sha1": "24de2325934dfe9401b82d2a1bf61e499c868922",
          "md5": "18c37f3cf31c1e8c0e5e79c72042e2eb"
        }
      ]
    }
  ]
}
