{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-carpet-compat-1_18_2",
    "version": "0.2.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_18_2",
          "version": {
            "requires": "0.5.3+c7ba8f9-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_18_2-0.2.3+c7ba8f9-beta.jar",
          "url": "magiclib-carpet-compat-1_18_2-0.2.3+c7ba8f9-beta.jar",
          "size": 148257,
          "sha512": "d69bcf735a116bbcf76f4ece8b217c47ceddf4dadd77ecabdcd359506dd29f9023e051e1726bc7fe665091ec88c4ff737706ddd0d2d3dd728a26c11a19998ec3",
          "sha256": "d8672a57cb35c3983e3469b6acf032e9a124d48494f267dcd260a18be80765c7",
          "sha1": "dd8ca0a9ea7ed2ced9d11ffc8a4626645935834c",
          "md5": "36699163f6ad43f0960bb234e0e259fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_18_2",
          "version": {
            "requires": "0.5.3+c7ba8f9-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_18_2-0.2.3+c7ba8f9-beta.jar",
          "url": "magiclib-carpet-compat-1_18_2-0.2.3+c7ba8f9-beta.jar",
          "size": 148257,
          "sha512": "d69bcf735a116bbcf76f4ece8b217c47ceddf4dadd77ecabdcd359506dd29f9023e051e1726bc7fe665091ec88c4ff737706ddd0d2d3dd728a26c11a19998ec3",
          "sha256": "d8672a57cb35c3983e3469b6acf032e9a124d48494f267dcd260a18be80765c7",
          "sha1": "dd8ca0a9ea7ed2ced9d11ffc8a4626645935834c",
          "md5": "36699163f6ad43f0960bb234e0e259fc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_18_2",
          "version": {
            "requires": "0.5.3+c7ba8f9-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_18_2-0.2.3+c7ba8f9-beta-standalone-dev.jar",
          "url": "magiclib-carpet-compat-1_18_2-0.2.3+c7ba8f9-beta-standalone-dev.jar",
          "size": 540354,
          "sha512": "21390337e013fc742165a8a27addcf2b485ea14c3e8bc8509696f705d1cc53f3f2cd9e261a9ab8d7ad9d17b49b41578d4521b12c94a78aed1ec9b60f7669290d",
          "sha256": "87e4da325199e1ca3f2a673f9021978e0ade8fcad97af1952e49edbf89fdf6a6",
          "sha1": "f9256599da4721b3406fc350c1e445d1c133ae96",
          "md5": "9725b3294be973f9fa91abc4de310105"
        }
      ]
    }
  ]
}
