{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.327+dfd83d3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.327+dfd83d3-beta.jar",
          "url": "magiclib-1_19_2-0.7.327+dfd83d3-beta.jar",
          "size": 375962,
          "sha512": "9cfdbf30fe6eab9c71dc48c7031f0994e2c1b05f27058f6d0be051b84d75fd40b63c0173940b63310ed7cab008b5a1afde26f0f72a554a2074c487f3a886cbd0",
          "sha256": "215c74fbcf715d3180c0297b4552aad0af81e295d66390808ecac5afba987ea6",
          "sha1": "7e1119efd01dc8294722b785fa78aaf6ca1f4cb3",
          "md5": "f1844f71d88aeb99d9121ef6355b655b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.327+dfd83d3-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.327+dfd83d3-beta.jar",
          "url": "magiclib-1_19_2-0.7.327+dfd83d3-beta.jar",
          "size": 375962,
          "sha512": "9cfdbf30fe6eab9c71dc48c7031f0994e2c1b05f27058f6d0be051b84d75fd40b63c0173940b63310ed7cab008b5a1afde26f0f72a554a2074c487f3a886cbd0",
          "sha256": "215c74fbcf715d3180c0297b4552aad0af81e295d66390808ecac5afba987ea6",
          "sha1": "7e1119efd01dc8294722b785fa78aaf6ca1f4cb3",
          "md5": "f1844f71d88aeb99d9121ef6355b655b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.327+dfd83d3-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.327+dfd83d3-beta-sources.jar",
          "size": 168858,
          "sha512": "c203e251a9ab7185f2fcd4a4c8c0757bfed849e7c44f6e9c156441ec3872552ba5e0152dbcf30072666725b0dc48b2309e99c56cfb7e3b6baddf9cc6c4bac699",
          "sha256": "01aa76efbbfda4890f14d8ffb148c01da7081932707fe5e2f19ebf9ac202adbf",
          "sha1": "82a06c4632ffe4abfcf7d09b7573cc543d739478",
          "md5": "4549392a7925a3a04ae6ae57c8d6aba4"
        }
      ]
    }
  ]
}
