{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.330+0499b91-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.330+0499b91-beta.jar",
          "url": "magiclib-1_17_1-0.7.330+0499b91-beta.jar",
          "size": 373278,
          "sha512": "8eb6eee23f882c74710d4a12052cb61077761cfbd6eb6b4a6b60cc511a1c474a78b70ec74c3fe3bb2769295e7e3828bed4a4aba7cdae25d441d29a9108ba688a",
          "sha256": "13900d2b6a0874b0e2da3c174a3bbac5e3ae6bc28838fb501b1a45f0880db008",
          "sha1": "f5f852bac3d3cb76d94a17adf4328f1b7faba49e",
          "md5": "cfc58c1268e83c2892f06f6fda5451cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.330+0499b91-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.330+0499b91-beta.jar",
          "url": "magiclib-1_17_1-0.7.330+0499b91-beta.jar",
          "size": 373278,
          "sha512": "8eb6eee23f882c74710d4a12052cb61077761cfbd6eb6b4a6b60cc511a1c474a78b70ec74c3fe3bb2769295e7e3828bed4a4aba7cdae25d441d29a9108ba688a",
          "sha256": "13900d2b6a0874b0e2da3c174a3bbac5e3ae6bc28838fb501b1a45f0880db008",
          "sha1": "f5f852bac3d3cb76d94a17adf4328f1b7faba49e",
          "md5": "cfc58c1268e83c2892f06f6fda5451cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.330+0499b91-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.330+0499b91-beta-sources.jar",
          "size": 168931,
          "sha512": "2b4993ef1f4df35bc5be52ff12dddba03ad0bdbfa8444151f9358b1cb88c543b45ff51a570534cecd3490bef2f6fad764364d926c962ec4643cf960258bc4eb8",
          "sha256": "bc6366a08ce7c3450e09885d594edea6504b5b230a8bf914b0ab360f50c091cd",
          "sha1": "3c5816fb8b79d20e54bb9272d11594b8de414a5a",
          "md5": "4708b75e6768c9d4c37fbada92e761cb"
        }
      ]
    }
  ]
}
