{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib",
    "version": "1.16.5-0.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479748"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1.16.5-0.5.3.jar",
          "url": "magiclib-1.16.5-0.5.3.jar",
          "size": 248401,
          "sha512": "fff45502a92082daaebd8128f033a55d465cc03bb4b3aaaffe4f04fd51af6935ea8cc5c19fcf6b773c0f415c0341cf913439bf13536ab338e240e444ea39ef71",
          "sha256": "1c31eeee417a78d3aa8af70af26201d98104f1c5ce88c6870dce116926088e96",
          "sha1": "1f6c3173d21c6811cbd7b3cdd8b9d6db5814792d",
          "md5": "b90dcbe870acb2008a195aa6765e3ac1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479748"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493810"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1.16.5-0.5.3.jar",
          "url": "magiclib-1.16.5-0.5.3.jar",
          "size": 248401,
          "sha512": "fff45502a92082daaebd8128f033a55d465cc03bb4b3aaaffe4f04fd51af6935ea8cc5c19fcf6b773c0f415c0341cf913439bf13536ab338e240e444ea39ef71",
          "sha256": "1c31eeee417a78d3aa8af70af26201d98104f1c5ce88c6870dce116926088e96",
          "sha1": "1f6c3173d21c6811cbd7b3cdd8b9d6db5814792d",
          "md5": "b90dcbe870acb2008a195aa6765e3ac1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1.16.5-0.5.3-sources.jar",
          "url": "magiclib-1.16.5-0.5.3-sources.jar",
          "size": 183843,
          "sha512": "a7114e6487e76846600711e9ab5441f730639a753867c0e7bc181c23a45afcbddaeced2c7a742e8bf09c875ad66d9187886cf97ce95109850ae81a180c2817bf",
          "sha256": "5de4c0531f9725be78ac2b418e721d8d7607170be1d606eeda6db986fdf9a243",
          "sha1": "e573c6712e75ff4aef7519f8dc9bc1f9aabbcd7f",
          "md5": "23b4a4c1ae3f8fda4a1ceb7ac6791a12"
        }
      ]
    }
  ]
}
