{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.5.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.31.jar",
          "url": "magiclib-1_14_4-0.5.31.jar",
          "size": 270244,
          "sha512": "d3db1f6d3de7012f572bb0181a0ebda5c0c55da694d2ddb8855b67aaeab1c3c813440318553045abd8e2dcdd5b2ba9adfc1e3c10fff57a55fe6b9092e564ff9d",
          "sha256": "670dfffe85bab899cec99cf89c2f0946cf7cec8a1641175afc18473aa62a181a",
          "sha1": "6e38afbd2b7b849b22ede424b845c0d2afea94dc",
          "md5": "dbb57da469b0b8948da7b8205791190b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.31"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493805"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.31.jar",
          "url": "magiclib-1_14_4-0.5.31.jar",
          "size": 270244,
          "sha512": "d3db1f6d3de7012f572bb0181a0ebda5c0c55da694d2ddb8855b67aaeab1c3c813440318553045abd8e2dcdd5b2ba9adfc1e3c10fff57a55fe6b9092e564ff9d",
          "sha256": "670dfffe85bab899cec99cf89c2f0946cf7cec8a1641175afc18473aa62a181a",
          "sha1": "6e38afbd2b7b849b22ede424b845c0d2afea94dc",
          "md5": "dbb57da469b0b8948da7b8205791190b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.31-sources.jar",
          "url": "magiclib-1_14_4-0.5.31-sources.jar",
          "size": 198081,
          "sha512": "7e6e3f6ec0d4c3cb929ad546e110986c150c836741901a2717c26b7f65eb696563a661250decfb1e7c7fe918e97a2512f17fe6d57e5b1c3a3197168f6b00be34",
          "sha256": "46b7d17c86db835153cbd72bb2ef537eff0fd10f73bd014b82eec4a3a11801ca",
          "sha1": "553d6a32dd99f2671d55dad4d99223f231c074d6",
          "md5": "544d67ed064961e6b238e4ab62381f58"
        }
      ]
    }
  ]
}
