{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.replaymod",
    "module": "preprocessor",
    "version": "SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "preprocessor-SNAPSHOT.jar",
          "url": "preprocessor-SNAPSHOT.jar",
          "size": 139561,
          "sha512": "726ca0ff1183a702b2700b4054ca36035a92b2a3c778bce76a863364f2a54ec1f63e7af5371f0ba87bc42da80784f2e40f92382019df780e7c9e0840a2f6d21b",
          "sha256": "b5841ac889d743a43aa69d5f63b3f2b4127ca6a7aca6acc53ea33ba8060424c5",
          "sha1": "275bbce8f28cfd737909f30e65b64982d2de9690",
          "md5": "b98e1d27014bdadd6d794564f45dde90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.ReplayMod",
          "module": "remap",
          "version": {
            "requires": "97d6082"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "0.2.1.13"
          }
        }
      ],
      "files": [
        {
          "name": "preprocessor-SNAPSHOT.jar",
          "url": "preprocessor-SNAPSHOT.jar",
          "size": 139561,
          "sha512": "726ca0ff1183a702b2700b4054ca36035a92b2a3c778bce76a863364f2a54ec1f63e7af5371f0ba87bc42da80784f2e40f92382019df780e7c9e0840a2f6d21b",
          "sha256": "b5841ac889d743a43aa69d5f63b3f2b4127ca6a7aca6acc53ea33ba8060424c5",
          "sha1": "275bbce8f28cfd737909f30e65b64982d2de9690",
          "md5": "b98e1d27014bdadd6d794564f45dde90"
        }
      ]
    }
  ]
}
