{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.replaymod",
    "module": "preprocessor",
    "version": "SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "preprocessor-SNAPSHOT.jar",
          "url": "preprocessor-SNAPSHOT.jar",
          "size": 144313,
          "sha512": "a0f7456a10c1087d2fbfaeaf38200fd6686371cd3a75fca1b807d1cb8124fbfc2331d174f364f0924426f7358d38337d9cf60c87e47e2560d0e80f0d6f12f587",
          "sha256": "ea51c1df154b46d1210118c5de9eb7bdc1633730331bfe42693e53c1050fafcc",
          "sha1": "f24e7d3b3b362fa528df2b54ea3c519755d9ced9",
          "md5": "4112e1661bd364cf68969f468a723b84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.github.Fallen-Breath",
          "module": "remap",
          "version": {
            "requires": "6d1565046f"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-mappings-parser",
          "version": {
            "requires": "0.2.1.13"
          }
        }
      ],
      "files": [
        {
          "name": "preprocessor-SNAPSHOT.jar",
          "url": "preprocessor-SNAPSHOT.jar",
          "size": 144313,
          "sha512": "a0f7456a10c1087d2fbfaeaf38200fd6686371cd3a75fca1b807d1cb8124fbfc2331d174f364f0924426f7358d38337d9cf60c87e47e2560d0e80f0d6f12f587",
          "sha256": "ea51c1df154b46d1210118c5de9eb7bdc1633730331bfe42693e53c1050fafcc",
          "sha1": "f24e7d3b3b362fa528df2b54ea3c519755d9ced9",
          "md5": "4112e1661bd364cf68969f468a723b84"
        }
      ]
    }
  ]
}
