{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.7.304+4912de4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "2870184"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_14_4-0.7.304+4912de4-beta.jar",
          "size": 374116,
          "sha512": "e74516d3c7550092b609423f9e79270c54c827de5e38e0db710d7a6aea8b3d666202795ae2c336e3f2cbd9a7c31fc6f0d505a2ba56ecf1dc5cc9be863cd15f58",
          "sha256": "3d402a4ddbe0385248191158a1086ec1cf28c787e6565b7a28c7c142d18b560d",
          "sha1": "c6be00bfcdb373122f3f3800f1752609968aa5d2",
          "md5": "21bfe33c390ba9c850c41f3f5dff4ade"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.304+4912de4-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "2870184"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2921052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761403"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993195"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159393"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_14_4-0.7.304+4912de4-beta.jar",
          "size": 374116,
          "sha512": "e74516d3c7550092b609423f9e79270c54c827de5e38e0db710d7a6aea8b3d666202795ae2c336e3f2cbd9a7c31fc6f0d505a2ba56ecf1dc5cc9be863cd15f58",
          "sha256": "3d402a4ddbe0385248191158a1086ec1cf28c787e6565b7a28c7c142d18b560d",
          "sha1": "c6be00bfcdb373122f3f3800f1752609968aa5d2",
          "md5": "21bfe33c390ba9c850c41f3f5dff4ade"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.7.304+4912de4-beta-sources.jar",
          "url": "magiclib-1_14_4-0.7.304+4912de4-beta-sources.jar",
          "size": 165288,
          "sha512": "b2823c13a524c21180c6d1435f1022ea12eb2bc81fa22a08bf11a3a3d363b8dce7e5375e7553e2eab0dec5335fd195aecd2ec369c9dd951fc990995d3b62aa12",
          "sha256": "f09dbd0553dfb025dd58acdcad569024e717f63807e68a8487ee232cee7eb8f4",
          "sha1": "8f8f30396a5a0db03f8e981fb7edca7587281e5e",
          "md5": "42774f9262f201d2f5970b04e62e6054"
        }
      ]
    }
  ]
}
