{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850113"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.33.jar",
          "url": "magiclib-1_18_2-0.5.33.jar",
          "size": 254452,
          "sha512": "d2696418d243d446b5a96ec85d4b9c477ff0122947194895d9a986b94760822708309bc591f66daaa9b73284aec9e31edc6ea487883cf7d8ca8ee975def72c88",
          "sha256": "30d1e2e27ced8bd1be7cee4133c77c4272a901c44fd3da4d254f6ac94af0f210",
          "sha1": "54ac0d374b11595a3cd2155e4fe93c341bfa3544",
          "md5": "17fca158677b3dcd38be5db3d3fadf62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850113"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827453"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.33.jar",
          "url": "magiclib-1_18_2-0.5.33.jar",
          "size": 254452,
          "sha512": "d2696418d243d446b5a96ec85d4b9c477ff0122947194895d9a986b94760822708309bc591f66daaa9b73284aec9e31edc6ea487883cf7d8ca8ee975def72c88",
          "sha256": "30d1e2e27ced8bd1be7cee4133c77c4272a901c44fd3da4d254f6ac94af0f210",
          "sha1": "54ac0d374b11595a3cd2155e4fe93c341bfa3544",
          "md5": "17fca158677b3dcd38be5db3d3fadf62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.33-sources.jar",
          "url": "magiclib-1_18_2-0.5.33-sources.jar",
          "size": 192713,
          "sha512": "93f89bbc8de0f9f586215eeeabc4f5de16cf15660fa793e8c09005503f762aa07b15fda616599c8ab5cbfaf1489f181827073f52f56351b89232aaa4a3ad35ad",
          "sha256": "ece8b719cbfce0f4831cdb5593bfd99ecc5595c46be1ae4d050c519efa0b7e1b",
          "sha1": "2afbd43a69a08fc21612bff5ea42a7d1b9aa9b86",
          "md5": "b6a3837271d6c0ccf00ceb04ccf1cec0"
        }
      ]
    }
  ]
}
