{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.336",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.336.jar",
          "url": "magiclib-1_19_3-0.7.336.jar",
          "size": 379528,
          "sha512": "e5078ff966adb37f5d4c91952c4d7b7a1a43495d62a5adef94689a388b079e36ac285e188f071d7b79742df57e5e0809c5a5b88e2864322904d72fd018dfb4ef",
          "sha256": "d6e80526c98f19fc7e873b1ec649e607f072e57a47b46162ffcfd3b0e3d42c63",
          "sha1": "323167e79c20e5be27076f40d32a3c3b45102334",
          "md5": "ace35e82bd83cfee4a3c14c4ff55b5eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.336"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.336.jar",
          "url": "magiclib-1_19_3-0.7.336.jar",
          "size": 379528,
          "sha512": "e5078ff966adb37f5d4c91952c4d7b7a1a43495d62a5adef94689a388b079e36ac285e188f071d7b79742df57e5e0809c5a5b88e2864322904d72fd018dfb4ef",
          "sha256": "d6e80526c98f19fc7e873b1ec649e607f072e57a47b46162ffcfd3b0e3d42c63",
          "sha1": "323167e79c20e5be27076f40d32a3c3b45102334",
          "md5": "ace35e82bd83cfee4a3c14c4ff55b5eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.336-sources.jar",
          "url": "magiclib-1_19_3-0.7.336-sources.jar",
          "size": 169912,
          "sha512": "2fd3cb91db876b18d667d3b9f0dd9e55aa990061434cc8db7139fd0bd265c02d85c2555fe1a1c761f41c9c7dbc9dd89b09fbbabd2b3e6c75daf48c674e2c6038",
          "sha256": "390b42711b65de1cee543508a883271274ed5ab57f412056301442b91ed8487b",
          "sha1": "5bf00f298ecc740ccad55c3ef5c0f5a29a98de38",
          "md5": "956351b53bb32b8a5b2a7fc0f932119b"
        }
      ]
    }
  ]
}
