{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_18_2",
    "version": "0.5.260+86e6882-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_18_2-0.5.260+86e6882-dev.jar",
          "url": "ommc-1_18_2-0.5.260+86e6882-dev.jar",
          "size": 1146695,
          "sha512": "417a26a7b880b549753b3cea7ae2db225fb5d139683885fa23ed3cd28464c0e81c9f4fc995d128c13347668cbbe3c9fb71a5da61922ea50a20b4ba1e90e310ed",
          "sha256": "7083a74f150b939a92654ca515cf82b5649d1d44070b08682f6201cd625d5881",
          "sha1": "a03366ed3c60fc7a85ba75c6fd2c81c6fd4a7f32",
          "md5": "ceb18d524f39b2224d7c74ecb05721b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.260+86e6882-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_18_2",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_18_2-0.5.260+86e6882-dev.jar",
          "url": "ommc-1_18_2-0.5.260+86e6882-dev.jar",
          "size": 1146695,
          "sha512": "417a26a7b880b549753b3cea7ae2db225fb5d139683885fa23ed3cd28464c0e81c9f4fc995d128c13347668cbbe3c9fb71a5da61922ea50a20b4ba1e90e310ed",
          "sha256": "7083a74f150b939a92654ca515cf82b5649d1d44070b08682f6201cd625d5881",
          "sha1": "a03366ed3c60fc7a85ba75c6fd2c81c6fd4a7f32",
          "md5": "ceb18d524f39b2224d7c74ecb05721b7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
