{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_20",
    "version": "0.7.336",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.20-1.4.112+v230608"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa.malilib",
          "module": "malilib-fabric-1.20.0",
          "version": {
            "requires": "0.15.4-nyan.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_20-0.7.336.jar",
          "url": "magiclib-1_20-0.7.336.jar",
          "size": 379744,
          "sha512": "c95ee4f8d0bc305d5436c6fa710b77d9477c31a65c7277a7dfe597abc9bd7ad7d90d18b5968a4dd64cb1bd840354ab8ebc5906bc4cb45fdc22649f0f264bb8eb",
          "sha256": "220f52247cf3b70ced26408f33d8fa07d21e187add61f258efefafe90b0cc9e9",
          "sha1": "b9e282aac4f4007d9e2af66dfc93b80e8edc35e4",
          "md5": "2ff671d69bd843aeeaec41d14cf94368"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.336"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.20-1.4.112+v230608"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa.malilib",
          "module": "malilib-fabric-1.20.0",
          "version": {
            "requires": "0.15.4-nyan.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.83.0+1.20"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_20-0.7.336.jar",
          "url": "magiclib-1_20-0.7.336.jar",
          "size": 379744,
          "sha512": "c95ee4f8d0bc305d5436c6fa710b77d9477c31a65c7277a7dfe597abc9bd7ad7d90d18b5968a4dd64cb1bd840354ab8ebc5906bc4cb45fdc22649f0f264bb8eb",
          "sha256": "220f52247cf3b70ced26408f33d8fa07d21e187add61f258efefafe90b0cc9e9",
          "sha1": "b9e282aac4f4007d9e2af66dfc93b80e8edc35e4",
          "md5": "2ff671d69bd843aeeaec41d14cf94368"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_20-0.7.336-sources.jar",
          "url": "magiclib-1_20-0.7.336-sources.jar",
          "size": 169911,
          "sha512": "81158980edb7bb4494206c8d1d187051c9d40fa6701f9d4765a79a576ba41c930acf38b4e38bcb53735698f19cc4680a1196797842b9d095cbd8cc1d40d2f337",
          "sha256": "94a7e519a8e1deb191968a70b24d0b1506d5697995f00812d3a4b0beb442e76a",
          "sha1": "f83a785627af8bd4e269775001c992e5f47a754d",
          "md5": "75dc63478dab91305aced0f47a0e7182"
        }
      ]
    }
  ]
}
