{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.309+3356ade-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.309+3356ade-beta.jar",
          "url": "magiclib-1_19_2-0.7.309+3356ade-beta.jar",
          "size": 372572,
          "sha512": "5ade76de13a2db476485b6652975bd0d0b83328d9fbffd85afbc906aa26bb6f4345ab3e3285062e3616f1d21289f6bca5453a41d58dc2fc7143f44388f561937",
          "sha256": "1941272ad9bd3b54060732d3bd63ced2571be73f1d40158c7ea0c79a71a0155f",
          "sha1": "9f10f6a63018c486c4deca754a679e1e914488a3",
          "md5": "4cd224c7508a18eabb9cac347ad75cdf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.309+3356ade-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.309+3356ade-beta.jar",
          "url": "magiclib-1_19_2-0.7.309+3356ade-beta.jar",
          "size": 372572,
          "sha512": "5ade76de13a2db476485b6652975bd0d0b83328d9fbffd85afbc906aa26bb6f4345ab3e3285062e3616f1d21289f6bca5453a41d58dc2fc7143f44388f561937",
          "sha256": "1941272ad9bd3b54060732d3bd63ced2571be73f1d40158c7ea0c79a71a0155f",
          "sha1": "9f10f6a63018c486c4deca754a679e1e914488a3",
          "md5": "4cd224c7508a18eabb9cac347ad75cdf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.309+3356ade-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.309+3356ade-beta-sources.jar",
          "size": 166775,
          "sha512": "2b668efac5f3b2b3613c846628c7f0f7e2dbbcf11ef3185e21eb62522bcb739e7812cc2ef6811bedef1a31a464de50af80700d59851602365245b501df2e9e55",
          "sha256": "b858dbb73b57931c585f7002a22d6a94dfb9c3af159585ec5166bc3e727b9937",
          "sha1": "5c78e5a22f4d7daad0bc94031e6e24bf52417133",
          "md5": "b089f117574f63d8011c52751b087ffe"
        }
      ]
    }
  ]
}
