{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_17_1",
    "version": "0.5.260+86e6882-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_17_1-0.5.260+86e6882-dev.jar",
          "url": "ommc-1_17_1-0.5.260+86e6882-dev.jar",
          "size": 1146723,
          "sha512": "78edd5928ec98158a77948ede3eaf92d1ce1b2bc4bcf1afdfc84833431ac6e011d314ac07c156d4f48813f3fba4058fed7f609b716dbd138160c1661d155312c",
          "sha256": "e06f25b00df058ff43172f592293dcb4b51b633b110663fc9845ee49026b03b8",
          "sha1": "f82f2e439b0c35612b66a9880070c3fdbdb38acb",
          "md5": "6388208dd9a8109e4aaf649e0ea9f371"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.260+86e6882-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_17_1",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_17_1-0.5.260+86e6882-dev.jar",
          "url": "ommc-1_17_1-0.5.260+86e6882-dev.jar",
          "size": 1146723,
          "sha512": "78edd5928ec98158a77948ede3eaf92d1ce1b2bc4bcf1afdfc84833431ac6e011d314ac07c156d4f48813f3fba4058fed7f609b716dbd138160c1661d155312c",
          "sha256": "e06f25b00df058ff43172f592293dcb4b51b633b110663fc9845ee49026b03b8",
          "sha1": "f82f2e439b0c35612b66a9880070c3fdbdb38acb",
          "md5": "6388208dd9a8109e4aaf649e0ea9f371"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
