{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_20-pre5",
    "version": "0.7.329+ed83ba7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.20-pre5-1.4.110+v230523"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa",
          "module": "malilib",
          "version": {
            "requires": "1.20-pre5-0.16.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.3+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_20-pre5-0.7.329+ed83ba7-beta.jar",
          "url": "magiclib-1_20-pre5-0.7.329+ed83ba7-beta.jar",
          "size": 375388,
          "sha512": "1c8874fa872ff570d1d2ffbcccadf96343e70b4a0e4dc0ce37cd8b4a936469ac78f587c465c1b41c40cfeec7687dffb5c5f47bba7101fd91e451e89c450106dc",
          "sha256": "21fa68252db370a381b8c634b7822452277da75e292d886d6dcfd5ab323df5fa",
          "sha1": "5c0ee5ce8fcf6c89fa2ce6e30b7661b743adc425",
          "md5": "f3d158ba3c5d7b0b0d9808a4d2709076"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.329+ed83ba7-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.20-pre5-1.4.110+v230523"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa",
          "module": "malilib",
          "version": {
            "requires": "1.20-pre5-0.16.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.3+1.20"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_20-pre5-0.7.329+ed83ba7-beta.jar",
          "url": "magiclib-1_20-pre5-0.7.329+ed83ba7-beta.jar",
          "size": 375388,
          "sha512": "1c8874fa872ff570d1d2ffbcccadf96343e70b4a0e4dc0ce37cd8b4a936469ac78f587c465c1b41c40cfeec7687dffb5c5f47bba7101fd91e451e89c450106dc",
          "sha256": "21fa68252db370a381b8c634b7822452277da75e292d886d6dcfd5ab323df5fa",
          "sha1": "5c0ee5ce8fcf6c89fa2ce6e30b7661b743adc425",
          "md5": "f3d158ba3c5d7b0b0d9808a4d2709076"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_20-pre5-0.7.329+ed83ba7-beta-sources.jar",
          "url": "magiclib-1_20-pre5-0.7.329+ed83ba7-beta-sources.jar",
          "size": 168985,
          "sha512": "18b36ac8256d92c2cc71f32800d01493ec90366d0ae584519d1d49a16713704671e8ad059012c5484dad33b6a29f77994c8ea808cafc9969d051a4fda52a88e0",
          "sha256": "8aafe371a7235994204a7c3c5a111a99c9768aa1dfa819eb4cce096507c4f74f",
          "sha1": "27f7bd66a6e0fb09e0df6ee940704fbaeb9f24b6",
          "md5": "c93070d8820e23b21734be1ee95b4515"
        }
      ]
    }
  ]
}
