{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.313+71378a6-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.313+71378a6-beta.jar",
          "url": "magiclib-1_19_4-0.7.313+71378a6-beta.jar",
          "size": 373754,
          "sha512": "1c3b36007c4ede82ed858a9e5ab362bc3d11b9f8bf19d1d088d19fd3fc3c7564a02c049ec0b4a74d1f1fa8397b9bcbd048628b4053b873a4207c73ac2aeefc23",
          "sha256": "75d6dc8f5f4a5ebb8e66093f8cde4d6a538f814b9ad6e86a97b0f2e965bd74e3",
          "sha1": "be9e55a92c1bddbcd4c08f1b9b17e356e8d10316",
          "md5": "9decda60795302f2c343640ebdaaf415"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.313+71378a6-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.313+71378a6-beta.jar",
          "url": "magiclib-1_19_4-0.7.313+71378a6-beta.jar",
          "size": 373754,
          "sha512": "1c3b36007c4ede82ed858a9e5ab362bc3d11b9f8bf19d1d088d19fd3fc3c7564a02c049ec0b4a74d1f1fa8397b9bcbd048628b4053b873a4207c73ac2aeefc23",
          "sha256": "75d6dc8f5f4a5ebb8e66093f8cde4d6a538f814b9ad6e86a97b0f2e965bd74e3",
          "sha1": "be9e55a92c1bddbcd4c08f1b9b17e356e8d10316",
          "md5": "9decda60795302f2c343640ebdaaf415"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.313+71378a6-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.313+71378a6-beta-sources.jar",
          "size": 168194,
          "sha512": "47a6f4384392dece3baad2a6ab0dcd7bd523871306f81d63ea138b92d8f886d8d05a4203530ca9bd4963c1e55e6748d1a18db7c6ef3d2228c669812b2b9b9079",
          "sha256": "437a8d03b63a22a60f4d531176e32c8e12881a41461a0b5dbf28645a417ce5f8",
          "sha1": "061e2490fff509e1fe86d5259886a957aed0b9ca",
          "md5": "258c9b8e037a254bee3d2c19eb915286"
        }
      ]
    }
  ]
}
