{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base-1_18_2",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.67.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_18_2-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_18_2-0.7.2+32bcf58-beta.jar",
          "size": 119684,
          "sha512": "e4bef2fd7b950a1692eb58a46e7a1e3d6de873ed6f09b52f59cd9887e98c2a4415890060628038bb1d2e6737e06a79522a31496ea8eb61b0d7ba1934dbe1e7b9",
          "sha256": "5364bee137d9de31b3d07681b87fe5fb24dcf24bf05f91d610ab770ae02ff551",
          "sha1": "6a607d92e1b1c507ae850e977388c4fde1397793",
          "md5": "05e60468f2b1af94fb731190b3d2d69e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.67.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_18_2-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_18_2-0.7.2+32bcf58-beta.jar",
          "size": 119684,
          "sha512": "e4bef2fd7b950a1692eb58a46e7a1e3d6de873ed6f09b52f59cd9887e98c2a4415890060628038bb1d2e6737e06a79522a31496ea8eb61b0d7ba1934dbe1e7b9",
          "sha256": "5364bee137d9de31b3d07681b87fe5fb24dcf24bf05f91d610ab770ae02ff551",
          "sha1": "6a607d92e1b1c507ae850e977388c4fde1397793",
          "md5": "05e60468f2b1af94fb731190b3d2d69e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_18_2-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-base-1_18_2-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 260134,
          "sha512": "a26c5c50d951b1d85cc5228acd699e9f8c41c563cd96fcb08b7cd217924b85c9eff63fe6b011cd375661fa48c407021a1c01ba4b372eea2471bd39a08cf82fac",
          "sha256": "c66b67e51c7a9830acbf96779289d61fb9201d31d95c3d19bc99e21338fe595f",
          "sha1": "2e27f2cd32a9eb0c759f7dcc55b48d5df06693de",
          "md5": "fabda6827ac8bafe4c9b9c1ba4e34aa1"
        }
      ]
    }
  ]
}
