{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.304+4912de4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_16_5-0.7.304+4912de4-beta.jar",
          "size": 360872,
          "sha512": "5ee9c3f00c57bfd1157bf1f6553915dda545c780e4cdfb55e81c842aeecf03d4c47cb28a82023ef74b4bd482569efb65bde68fa487f8e771ba975f18d90484ee",
          "sha256": "c9596884487457ba89af68ca60f3ae5a5ee8fc2a20407032fc70f910e2433776",
          "sha1": "4e0efc6faed4822c6f1c4c152d29c6a5ff5303e7",
          "md5": "f8d6d9c38e77e52b16ac034a7d3a6615"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.304+4912de4-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_16_5-0.7.304+4912de4-beta.jar",
          "size": 360872,
          "sha512": "5ee9c3f00c57bfd1157bf1f6553915dda545c780e4cdfb55e81c842aeecf03d4c47cb28a82023ef74b4bd482569efb65bde68fa487f8e771ba975f18d90484ee",
          "sha256": "c9596884487457ba89af68ca60f3ae5a5ee8fc2a20407032fc70f910e2433776",
          "sha1": "4e0efc6faed4822c6f1c4c152d29c6a5ff5303e7",
          "md5": "f8d6d9c38e77e52b16ac034a7d3a6615"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.304+4912de4-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.304+4912de4-beta-sources.jar",
          "size": 159566,
          "sha512": "5c16bb1decced3b05fc83ca75f798b10a1369550abe3862901420a1cf111934377c3431907a818c481dc21fbb27378791b827e03d72f9f5d6e75d75b4f9f5f14",
          "sha256": "19599b521417ca9be3771cd2929dbaeea7940fd4affc22969e85337644f2592e",
          "sha1": "1a6bf93b2c6b0a00743f11780d75c8adc347c653",
          "md5": "6414fd3b4195119ecc83a5c1374b3a53"
        }
      ]
    }
  ]
}
