{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.331+c783ba0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_19_2-0.7.331+c783ba0-beta.jar",
          "size": 375962,
          "sha512": "127948ad7cef8b4dc253da6ad885c6ee1f2c689cb71664686d909a4b263334d9ce4227df29fa335c62a25f21fd11119350bcfd435be0b4078ef6330b42bf87da",
          "sha256": "bcb84ba9cd09326f21f14edbfb759339543ca6ec753a7a4a553c55a36d48bb39",
          "sha1": "7015a77e2222ccc5f66a8847b2d62d3e15f58a04",
          "md5": "4190c802287f742f7dd14f85303b2aaf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.331+c783ba0-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_19_2-0.7.331+c783ba0-beta.jar",
          "size": 375962,
          "sha512": "127948ad7cef8b4dc253da6ad885c6ee1f2c689cb71664686d909a4b263334d9ce4227df29fa335c62a25f21fd11119350bcfd435be0b4078ef6330b42bf87da",
          "sha256": "bcb84ba9cd09326f21f14edbfb759339543ca6ec753a7a4a553c55a36d48bb39",
          "sha1": "7015a77e2222ccc5f66a8847b2d62d3e15f58a04",
          "md5": "4190c802287f742f7dd14f85303b2aaf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.331+c783ba0-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.331+c783ba0-beta-sources.jar",
          "size": 168858,
          "sha512": "f8920b648ba5f9eda34186ae0fae7172e980efd590ef68752c854f2339edadb74f2ee54484dbbfe45788ecd6b289e810e476c9d67e149cdd39ace4e905ad7fe6",
          "sha256": "2f6ea374a8a4340e95842a7a5703dc3281d7ecdba0e7d9065dabf4b69f18bb69",
          "sha1": "6de36d5b25573eb7e6f81d6346949fbe5c65082a",
          "md5": "ff8ce476b7f72fb4635446c358f2ef56"
        }
      ]
    }
  ]
}
