{
  "formatVersion": "1.1",
  "component": {
    "group": "curse.maven",
    "module": "ommc-454900-1_16_5",
    "version": "0.5-alpha+4d91bac",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-454900-1_16_5-0.5-alpha+4d91bac.jar",
          "url": "ommc-454900-1_16_5-0.5-alpha+4d91bac.jar",
          "size": 146067,
          "sha512": "b6e187e9e383241420d25dc1a9e91411df25ad15be17155dc8217a73511adb673f87a045ab763dbf89eb03b7596a0685465125d2234a5219d6e3fa261265669e",
          "sha256": "29b3d9999b034c4d69021c442b1bcbd3609000b252e19f796d5ffc62d1a86c2e",
          "sha1": "5fe0b6ecd60de29bac0b832995be1cd9d4a05ac8",
          "md5": "fc9437a88803b39848a07d05e9daee7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "ommc-454900",
          "version": {
            "requires": "0.5-alpha+4d91bac"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_16_5",
          "version": {
            "requires": "0.5.37"
          }
        }
      ],
      "files": [
        {
          "name": "ommc-454900-1_16_5-0.5-alpha+4d91bac.jar",
          "url": "ommc-454900-1_16_5-0.5-alpha+4d91bac.jar",
          "size": 146067,
          "sha512": "b6e187e9e383241420d25dc1a9e91411df25ad15be17155dc8217a73511adb673f87a045ab763dbf89eb03b7596a0685465125d2234a5219d6e3fa261265669e",
          "sha256": "29b3d9999b034c4d69021c442b1bcbd3609000b252e19f796d5ffc62d1a86c2e",
          "sha1": "5fe0b6ecd60de29bac0b832995be1cd9d4a05ac8",
          "md5": "fc9437a88803b39848a07d05e9daee7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ommc-454900-1_16_5-0.5-alpha+4d91bac-sources.jar",
          "url": "ommc-454900-1_16_5-0.5-alpha+4d91bac-sources.jar",
          "size": 93479,
          "sha512": "a35e020d62bca39257cfaabd1c858de015070bfc518371d13cb5d9f6a04f4b3c2631f8a605757f69baf6b60d15e66b4abf67a0d1efed3dfa5053e82c10fdb864",
          "sha256": "79e9e4f1edf213915d7e4c6f6a2efbbc65c5452644e1f335ca4e0fd986940850",
          "sha1": "d081325c2a75d1db4f9c85dfdee5cc2be9ca360d",
          "md5": "c97604205d64185efd8d1c17e601345a"
        }
      ]
    }
  ]
}
