{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.287+d8686f5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.287+d8686f5-beta.jar",
          "url": "magiclib-1_16_5-0.7.287+d8686f5-beta.jar",
          "size": 360837,
          "sha512": "43634d571a4b743275645efb2e0c04d9e12c44b86bac2fa150da317c6e07f02dddff15e4c2d5e4183fc20e868d6bf49bda608e8151144964aa0d5b7d06b61c91",
          "sha256": "27826c33d55661487be5be97680caf78b15575da627ef7aef2a7f1ff43d19683",
          "sha1": "47301282d0329ef6cf66ba57e9d25d81476b13f3",
          "md5": "72858fb686be12b644c4b22b54543764"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.287+d8686f5-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.287+d8686f5-beta.jar",
          "url": "magiclib-1_16_5-0.7.287+d8686f5-beta.jar",
          "size": 360837,
          "sha512": "43634d571a4b743275645efb2e0c04d9e12c44b86bac2fa150da317c6e07f02dddff15e4c2d5e4183fc20e868d6bf49bda608e8151144964aa0d5b7d06b61c91",
          "sha256": "27826c33d55661487be5be97680caf78b15575da627ef7aef2a7f1ff43d19683",
          "sha1": "47301282d0329ef6cf66ba57e9d25d81476b13f3",
          "md5": "72858fb686be12b644c4b22b54543764"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
