{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_20-pre4",
    "version": "0.7.326+2b20e19-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.20-pre2-1.4.109+v230516"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa",
          "module": "malilib",
          "version": {
            "requires": "1.20-pre4-0.16.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.2+1.20"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_20-pre4-0.7.326+2b20e19-beta.jar",
          "url": "magiclib-1_20-pre4-0.7.326+2b20e19-beta.jar",
          "size": 375390,
          "sha512": "11be3c14d6b9a9173bcd1a36193bc99c56955c97cbd171b4a1ed20ece2ff3406ca1970179aa516e7a83c9c8ad73660cba76b9531a5915d8a1dc8e4a7cef4d3fb",
          "sha256": "0299a825eafe979851a7277bed755390c5ca82657f1d369f446060a452734a32",
          "sha1": "ccd3e56d563c3eaddc28179e6ec450f60746ebe3",
          "md5": "4384a3f37ecb02f3def6bdfbae32db5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.326+2b20e19-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.20-pre2-1.4.109+v230516"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa",
          "module": "malilib",
          "version": {
            "requires": "1.20-pre4-0.16.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "7.0.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.2+1.20"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_20-pre4-0.7.326+2b20e19-beta.jar",
          "url": "magiclib-1_20-pre4-0.7.326+2b20e19-beta.jar",
          "size": 375390,
          "sha512": "11be3c14d6b9a9173bcd1a36193bc99c56955c97cbd171b4a1ed20ece2ff3406ca1970179aa516e7a83c9c8ad73660cba76b9531a5915d8a1dc8e4a7cef4d3fb",
          "sha256": "0299a825eafe979851a7277bed755390c5ca82657f1d369f446060a452734a32",
          "sha1": "ccd3e56d563c3eaddc28179e6ec450f60746ebe3",
          "md5": "4384a3f37ecb02f3def6bdfbae32db5b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_20-pre4-0.7.326+2b20e19-beta-sources.jar",
          "url": "magiclib-1_20-pre4-0.7.326+2b20e19-beta-sources.jar",
          "size": 168986,
          "sha512": "b5315a89e8a56a105b0aa32c66b14898e1af38350cffc906b6507ff7aa44f7f9a701e38f5fea7b98128eadb1039e25ce40a718c3d4f8949bf4025871f79be712",
          "sha256": "58b51ac5732c5d3e7c158239cd767c080d99aeb571296a465d64df26fb2a5d02",
          "sha1": "2a17c0e6d934cc64134fa67444ac79fe499cff52",
          "md5": "c188fd70f96fe610c90d3d666ec873c0"
        }
      ]
    }
  ]
}
