{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.308+d9af2fc-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_16_5-0.7.308+d9af2fc-beta.jar",
          "size": 371696,
          "sha512": "c79a4f79f58fb834b1754fe7a6d585a2fee27c8b3bc728a782473e9d83593b2419f8b7fe02bdecf39ba87bf01e458f874e5d61151de4d127de38d186c7d93ac0",
          "sha256": "e092cf60aa31374b45f19d285c9ca7ab4a6b80c5bedde34e1c340fb1c8725513",
          "sha1": "e4cd263e7a2d9c04c88b14c7fb06ed2cc0e55a5f",
          "md5": "e6355f1536586ee016ad45454c308501"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.308+d9af2fc-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_16_5-0.7.308+d9af2fc-beta.jar",
          "size": 371696,
          "sha512": "c79a4f79f58fb834b1754fe7a6d585a2fee27c8b3bc728a782473e9d83593b2419f8b7fe02bdecf39ba87bf01e458f874e5d61151de4d127de38d186c7d93ac0",
          "sha256": "e092cf60aa31374b45f19d285c9ca7ab4a6b80c5bedde34e1c340fb1c8725513",
          "sha1": "e4cd263e7a2d9c04c88b14c7fb06ed2cc0e55a5f",
          "md5": "e6355f1536586ee016ad45454c308501"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.308+d9af2fc-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.308+d9af2fc-beta-sources.jar",
          "size": 166626,
          "sha512": "42cf1b466afa844b1afaf9a1fdae51da17b5073bdec3150603d8c1a8e17e39bb975ccb258a0694ecc14e5a710871b09e24c508f99b40aa393410d602fcc38574",
          "sha256": "6b1763d971f574050411dc382fd61651f419d788bc81cb8f5d052f5008dc73aa",
          "sha1": "e40ce422f9d3888d8c471c51f5fd1a3669f54cae",
          "md5": "1ed4a570df56865c18c69d2ad1888968"
        }
      ]
    }
  ]
}
