{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.5.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850113"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.35.jar",
          "url": "magiclib-1_18_2-0.5.35.jar",
          "size": 254452,
          "sha512": "fc75f34322b52cd0e691f5f0e9673ff66ec0db7669f4eeaffd8f3f54c0f3f8aece522f232023a53455e10397c71a67f9bbebe7fab55fdfdefde06118ab69a640",
          "sha256": "0b3ef387d1e7056b06739338e2e0f4b23122d1d8a102ad1883bb5608cabeea0d",
          "sha1": "b85422d03f531d6a0c58b5a764fe48f13d25c095",
          "md5": "f40699f9596b572b15edcef3374eff0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.35"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.0+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850113"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827453"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.35.jar",
          "url": "magiclib-1_18_2-0.5.35.jar",
          "size": 254452,
          "sha512": "fc75f34322b52cd0e691f5f0e9673ff66ec0db7669f4eeaffd8f3f54c0f3f8aece522f232023a53455e10397c71a67f9bbebe7fab55fdfdefde06118ab69a640",
          "sha256": "0b3ef387d1e7056b06739338e2e0f4b23122d1d8a102ad1883bb5608cabeea0d",
          "sha1": "b85422d03f531d6a0c58b5a764fe48f13d25c095",
          "md5": "f40699f9596b572b15edcef3374eff0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.35-sources.jar",
          "url": "magiclib-1_18_2-0.5.35-sources.jar",
          "size": 192713,
          "sha512": "08a0831688b3555bb6f6c35dd7c2d79b41e828053a8371e70884ccf2d00cc56ea3980ab5b600f780f9a459faaee34348e7cc786f0047452573d0479b1d983d02",
          "sha256": "49291d104ee27e336946c9f517be52687943b743d5f404adc17d1c731c7e5b58",
          "sha1": "077f04b959588937142302861b7975d161c4f37f",
          "md5": "4bd4f6023b6537a8115e3ac1f9c45be4"
        }
      ]
    }
  ]
}
