{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.5.19",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479748"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.19.jar",
          "url": "magiclib-1_16_5-0.5.19.jar",
          "size": 247757,
          "sha512": "1eec2cb39d81c1eb601b1b7049d1db27d869881bedc31aaa63622cea7302e48891ea2157f23a541a9a606b02bdcd234792b1948213721623a51fd4938ad30b90",
          "sha256": "733a70d0dc3892888ad8e4a6c334f0b38048bd5b37f422d652da562227634cf5",
          "sha1": "af4e913bef911f77ddef02c1e9a2a5d94a8a9535",
          "md5": "ad0d0d34ebbf5406c2407916d9c8a934"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.19"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479748"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493810"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.19.jar",
          "url": "magiclib-1_16_5-0.5.19.jar",
          "size": 247757,
          "sha512": "1eec2cb39d81c1eb601b1b7049d1db27d869881bedc31aaa63622cea7302e48891ea2157f23a541a9a606b02bdcd234792b1948213721623a51fd4938ad30b90",
          "sha256": "733a70d0dc3892888ad8e4a6c334f0b38048bd5b37f422d652da562227634cf5",
          "sha1": "af4e913bef911f77ddef02c1e9a2a5d94a8a9535",
          "md5": "ad0d0d34ebbf5406c2407916d9c8a934"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.19-sources.jar",
          "url": "magiclib-1_16_5-0.5.19-sources.jar",
          "size": 186635,
          "sha512": "81231aebf793f186f9d288cc40bcd78bea7ab7d60e2177ddfe55e2bfaf75c6ec114eb3a8f756208d875956f18806cfbe861382b5be20163f6b566d275a0d9fa0",
          "sha256": "1a859c86b7eb56e021e0d027c78d398384b91e1974706370402dece1904ab578",
          "sha1": "4e983f0e7cbaeafd4d5cf3702dd29f4a416d7e82",
          "md5": "37ea25c038aaadaf24afc9ed881e7e56"
        }
      ]
    }
  ]
}
