{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.304+4912de4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_19_4-0.7.304+4912de4-beta.jar",
          "size": 360783,
          "sha512": "0329a8faeec7cf432f0f651770410049c7bc711bbd50181f27a5c20537449eafa0da4cd7a87e3a15d89d85a1d70746b4a402b3348ce3cba1f41dbbc6cdaa109d",
          "sha256": "d2ecc88e1f6aa65cfb957b670dd09eed3248c3d0cd2e56c14a06921618b7587f",
          "sha1": "af9eaddd5f9a966257ad32e7caee2f4ed0e5fda8",
          "md5": "163617baaab7d94749b90f8fc3eb93d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.304+4912de4-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_19_4-0.7.304+4912de4-beta.jar",
          "size": 360783,
          "sha512": "0329a8faeec7cf432f0f651770410049c7bc711bbd50181f27a5c20537449eafa0da4cd7a87e3a15d89d85a1d70746b4a402b3348ce3cba1f41dbbc6cdaa109d",
          "sha256": "d2ecc88e1f6aa65cfb957b670dd09eed3248c3d0cd2e56c14a06921618b7587f",
          "sha1": "af9eaddd5f9a966257ad32e7caee2f4ed0e5fda8",
          "md5": "163617baaab7d94749b90f8fc3eb93d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.304+4912de4-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.304+4912de4-beta-sources.jar",
          "size": 159775,
          "sha512": "8f709d4242fb670b403ef7af9d976e98d6cd70f2ec4c23d03c610122894b0c88b13b8fcd7664e692a855d730314a3a9a1bb9f577dabbae2744dbc9ac35b5837a",
          "sha256": "6ba3df2928f30fb1a7929db00051ce4f750ccdb9e1a0106c763f53a013274006",
          "sha1": "bad9fb5567b5bb894a3f8dcc56add89e34d1ac89",
          "md5": "42261f04bf9e160cc0e82175abafdf36"
        }
      ]
    }
  ]
}
