{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.280+c3d8807-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.280+c3d8807-beta.jar",
          "url": "magiclib-1_19_2-0.7.280+c3d8807-beta.jar",
          "size": 361477,
          "sha512": "49e56df03a3500a980ef99aeb751ac15b746d608453e1488f57f6034c8c519a291ff422e52b62e7304176b3087fc72644178ab3f96e01dc6fac6e77a92a95f08",
          "sha256": "bf9d23ab261aaad1601ca152ed6687c326cddb78c2d71b70711e6193541a00d6",
          "sha1": "bbb9e4d5ee3d61a77549a4caff3ac29ec8c92d47",
          "md5": "da6f86956cb658ac88007a24e80fcae9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.280+c3d8807-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.280+c3d8807-beta.jar",
          "url": "magiclib-1_19_2-0.7.280+c3d8807-beta.jar",
          "size": 361477,
          "sha512": "49e56df03a3500a980ef99aeb751ac15b746d608453e1488f57f6034c8c519a291ff422e52b62e7304176b3087fc72644178ab3f96e01dc6fac6e77a92a95f08",
          "sha256": "bf9d23ab261aaad1601ca152ed6687c326cddb78c2d71b70711e6193541a00d6",
          "sha1": "bbb9e4d5ee3d61a77549a4caff3ac29ec8c92d47",
          "md5": "da6f86956cb658ac88007a24e80fcae9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.280+c3d8807-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.280+c3d8807-beta-sources.jar",
          "size": 159332,
          "sha512": "3ef74806dc6728be75d508fcc9413f071dd2022c2fc5b5012003f18a23057a81728e110dfcbce7c4ae4962d853cf9b6dc203bc1ca8b0f41b31e7b084e364b89d",
          "sha256": "fc1f80e0f74c2dabad5cd203cd7896666203c0a2333d2fb0127563811d08639c",
          "sha1": "bdd070afd3f916d478ff4843de87a5891d8e4fcf",
          "md5": "d3ba4c563e6a2f7c31418237fd137a8a"
        }
      ]
    }
  ]
}
