{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base-1_15_2",
    "version": "0.7.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4031627"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_15_2-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-base-1_15_2-0.7.3+c7ba8f9-beta.jar",
          "size": 119147,
          "sha512": "aaa486a1e1d81b2fc82dde7a2e03709abda5f9f78fa62d430fbfa3b5e02b9ba3c816211a11815719c9486fabf7f43d5178cfe64cee5c5b947c1a1aa44d899d96",
          "sha256": "ddf3d6c634dff8808dce1937ccac7a648c23a5d110b1e20bd376f98c7453d253",
          "sha1": "c10a6ac93c26d0fddbb5b1724bcd59d8ce5414f1",
          "md5": "04d1ccd680289b3abaf55ddc3fd63322"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4031627"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761404"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993196"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_15_2-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-base-1_15_2-0.7.3+c7ba8f9-beta.jar",
          "size": 119147,
          "sha512": "aaa486a1e1d81b2fc82dde7a2e03709abda5f9f78fa62d430fbfa3b5e02b9ba3c816211a11815719c9486fabf7f43d5178cfe64cee5c5b947c1a1aa44d899d96",
          "sha256": "ddf3d6c634dff8808dce1937ccac7a648c23a5d110b1e20bd376f98c7453d253",
          "sha1": "c10a6ac93c26d0fddbb5b1724bcd59d8ce5414f1",
          "md5": "04d1ccd680289b3abaf55ddc3fd63322"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_15_2-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "url": "magiclib-base-1_15_2-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "size": 259589,
          "sha512": "e0ae3f13681035931458d8e06624336e9c69eea765fcc422d236311f33fba520a18f4bb54d32cb0498016769eaaebadbf1d6550cf299f4d7d4f6a02908123fdd",
          "sha256": "e91a41449fc8db175cbcacc3bb8dc8adbff32502570d9989bb4a04b49c5dd650",
          "sha1": "e20df4c275c8a83110178cbc1187d8f07f464050",
          "md5": "393ddfd2554de6ab9be75c5fe4de7cb7"
        }
      ]
    }
  ]
}
