{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.5.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.18.jar",
          "url": "magiclib-1_18_2-0.5.18.jar",
          "size": 246895,
          "sha512": "290b041b19f29cda63ea4969bc6738cb6cdeb92188f874d276a2031a2260687f3da5a039a0762da6bf5540b84d21f1641b486df7d8a56e098a3a7d5978104acf",
          "sha256": "5cb194c9cc5a711599282f30b33360e697c5581a59e5b893146947fd132193c2",
          "sha1": "548b7e146a997bb749d08e7e4d8792d2ac6de60a",
          "md5": "c41608089890cc883aa2624abb633e69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.18"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3545107"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.18.jar",
          "url": "magiclib-1_18_2-0.5.18.jar",
          "size": 246895,
          "sha512": "290b041b19f29cda63ea4969bc6738cb6cdeb92188f874d276a2031a2260687f3da5a039a0762da6bf5540b84d21f1641b486df7d8a56e098a3a7d5978104acf",
          "sha256": "5cb194c9cc5a711599282f30b33360e697c5581a59e5b893146947fd132193c2",
          "sha1": "548b7e146a997bb749d08e7e4d8792d2ac6de60a",
          "md5": "c41608089890cc883aa2624abb633e69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.18-sources.jar",
          "url": "magiclib-1_18_2-0.5.18-sources.jar",
          "size": 186726,
          "sha512": "cb5c875eed99d36b75ad5aa3af19cb68069369f1fec7d7c7d70e9bc958c32e4a9a45d406ee286b8510351bc0c2942dd229af32f61a7d3461e7dad47dda4a58fe",
          "sha256": "e3f88e65a43310025c24ac320bf61699d3c45c22bd78bb3b210bdfceb246e121",
          "sha1": "97c2b00284c203384354a5d0b8477f8ce9703cbb",
          "md5": "176bab0e0a7847c1b52f9d14c4ef2746"
        }
      ]
    }
  ]
}
