{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.7.316+d66e799-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.10.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.316+d66e799-beta.jar",
          "url": "magiclib-1_15_2-0.7.316+d66e799-beta.jar",
          "size": 371955,
          "sha512": "ca5381edd65ead4e34757b94b5e69ac16f3da3440ed7ebe0eeed4c5568a26f64eb9c1dedc43449b912dfe219e24fc8ce97c9d817e9a4e7a4986d18db1643f2bd",
          "sha256": "49ec36580ca4c0bc6e5b5d252cea2244cf1690a811b9cbc871b69854774a1708",
          "sha1": "5179162bfafbf1ad79d9e12728c68097fa27f8fa",
          "md5": "79914de775d4990356bcedca92da3474"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.316+d66e799-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.10.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "cloth-config",
          "version": {
            "requires": "2.14.2+fabric"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.316+d66e799-beta.jar",
          "url": "magiclib-1_15_2-0.7.316+d66e799-beta.jar",
          "size": 371955,
          "sha512": "ca5381edd65ead4e34757b94b5e69ac16f3da3440ed7ebe0eeed4c5568a26f64eb9c1dedc43449b912dfe219e24fc8ce97c9d817e9a4e7a4986d18db1643f2bd",
          "sha256": "49ec36580ca4c0bc6e5b5d252cea2244cf1690a811b9cbc871b69854774a1708",
          "sha1": "5179162bfafbf1ad79d9e12728c68097fa27f8fa",
          "md5": "79914de775d4990356bcedca92da3474"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.316+d66e799-beta-sources.jar",
          "url": "magiclib-1_15_2-0.7.316+d66e799-beta-sources.jar",
          "size": 167857,
          "sha512": "6f492b7110d7dbce2da0d0f39675992543f81b17470ef160327ea0e4a9a0e44004612149a7d7b584a28fc1050e47166fa2dcc96da404f2688c3a345f6f1e044d",
          "sha256": "d1aeae4e6c516c18c5cfd3c8bdee5ffb65d3665567028bd04cf4d420f31cce9e",
          "sha1": "a02f1b32459bc1768e0a110d3d4c882946b56e8d",
          "md5": "19e26b0aace534ad33492c7b25cfb70a"
        }
      ]
    }
  ]
}
