{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.5.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.26.jar",
          "url": "magiclib-1_18_2-0.5.26.jar",
          "size": 254108,
          "sha512": "95cbb998fd0b89ebec9ec527e43c20f923f109b6c6148d9ade527d283d23623369af1e663d2efe9102c3fea8b1fa04a30a0dcbf5a8a75a4ae4db8633815f85e3",
          "sha256": "3a38ab4ba9d94c21133dd9cffe2df864316ad7308d8f197cad849d8c0fd92e25",
          "sha1": "df0135964b41f9e1d9bcdde7377c5d15b8c80739",
          "md5": "3e46a2394a376e01981af79b55fb0177"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.5"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3545107"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.26.jar",
          "url": "magiclib-1_18_2-0.5.26.jar",
          "size": 254108,
          "sha512": "95cbb998fd0b89ebec9ec527e43c20f923f109b6c6148d9ade527d283d23623369af1e663d2efe9102c3fea8b1fa04a30a0dcbf5a8a75a4ae4db8633815f85e3",
          "sha256": "3a38ab4ba9d94c21133dd9cffe2df864316ad7308d8f197cad849d8c0fd92e25",
          "sha1": "df0135964b41f9e1d9bcdde7377c5d15b8c80739",
          "md5": "3e46a2394a376e01981af79b55fb0177"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.26-sources.jar",
          "url": "magiclib-1_18_2-0.5.26-sources.jar",
          "size": 192493,
          "sha512": "2c25a068327244b411a890017a21f1c3857ec60dd57f9c187b567f65c30f595e2220112e776e3d68ae165f73c25b64b2ca5935dee7717852226b13bb21cbb95d",
          "sha256": "de710f572562ecbf57ed18d26d052a13f48cef398e0850d5055842852f06aac9",
          "sha1": "f2f7fcfa388f3f87fc29c8bb3efa4c8e832e27bc",
          "md5": "630edc8c218f1b244d0b352e6142e177"
        }
      ]
    }
  ]
}
