{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.5.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.20.jar",
          "url": "magiclib-1_18_2-0.5.20.jar",
          "size": 250731,
          "sha512": "4f76da2a0d9173d28d5ee1d93dbcd25a9e5cdce7a79a314cd6611c8d2a11b4965de6310d2a97e32dcd69cd858274a8a1f253e4bdbe567c5f3daadd677842d501",
          "sha256": "054b71621eab91f58d15dee597268e462d9d2186c522416ef39de6ffeb388d7c",
          "sha1": "96fc51e0ea747a4fa1666aab11de6c22e251170b",
          "md5": "84fdde64f1c0fbf13c641b920c2e6089"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.20"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3545107"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.20.jar",
          "url": "magiclib-1_18_2-0.5.20.jar",
          "size": 250731,
          "sha512": "4f76da2a0d9173d28d5ee1d93dbcd25a9e5cdce7a79a314cd6611c8d2a11b4965de6310d2a97e32dcd69cd858274a8a1f253e4bdbe567c5f3daadd677842d501",
          "sha256": "054b71621eab91f58d15dee597268e462d9d2186c522416ef39de6ffeb388d7c",
          "sha1": "96fc51e0ea747a4fa1666aab11de6c22e251170b",
          "md5": "84fdde64f1c0fbf13c641b920c2e6089"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.20-sources.jar",
          "url": "magiclib-1_18_2-0.5.20-sources.jar",
          "size": 189987,
          "sha512": "0e20ea7be4b8ba3dd708b2b40f47e8456e3425e09d99aae31ec05378e414983a18e96de1e2a0f2ee098e7af6b46b19f3b2a35649961faaec0b59ad555f9d97ba",
          "sha256": "cf2721e03791a57681839d9fd43adb9c022456adf68eb8a65e4ed8e21158f897",
          "sha1": "9dabd323f61fcc298c5fbdac19448eb61a41ffb1",
          "md5": "9fb4aa6d077fc3ad68fa70cb85850ea5"
        }
      ]
    }
  ]
}
