{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.284+fd02f73-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.284+fd02f73-beta.jar",
          "url": "magiclib-1_19_2-0.7.284+fd02f73-beta.jar",
          "size": 361615,
          "sha512": "26af653537c6964c26151e5b7f65b62eb82eccf455f83e760ed4f7b01b6612c8f624a6be01c9dac58dc6528aa6f19675aa327179ad1aaa528e3e34df60729579",
          "sha256": "5f2c862e8ef8ae1677d4faddc22fa4f2cae57dc85cfc23979c0f0557c4941ffb",
          "sha1": "9b30ac1f112932baf36ee3de2960f26c86075376",
          "md5": "a721e8e44160b7b977dd5afc78b42cbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.284+fd02f73-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.284+fd02f73-beta.jar",
          "url": "magiclib-1_19_2-0.7.284+fd02f73-beta.jar",
          "size": 361615,
          "sha512": "26af653537c6964c26151e5b7f65b62eb82eccf455f83e760ed4f7b01b6612c8f624a6be01c9dac58dc6528aa6f19675aa327179ad1aaa528e3e34df60729579",
          "sha256": "5f2c862e8ef8ae1677d4faddc22fa4f2cae57dc85cfc23979c0f0557c4941ffb",
          "sha1": "9b30ac1f112932baf36ee3de2960f26c86075376",
          "md5": "a721e8e44160b7b977dd5afc78b42cbb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.284+fd02f73-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.284+fd02f73-beta-sources.jar",
          "size": 159445,
          "sha512": "3293d2c0ff1f2f10fd817cc91f8e7320916f9b2da97c4d47686c19ba50bc5e20194bbdd79cc316106eddffee5f820d86c70f21d403f72b11f5589a075d93e882",
          "sha256": "28582d4abba1cd6f739e0ce4e1ca90de4f30e5c3d7344ac5dbe265eae3f6bf66",
          "sha1": "53b9204c3762da895090496163e9316b82b09c60",
          "md5": "6a8246f9536d5897ba9c0c8228ab38d8"
        }
      ]
    }
  ]
}
