{
  "formatVersion": "1.1",
  "component": {
    "group": "fi.dy.masa",
    "module": "itemscroller",
    "version": "1.20-pre1-0.20.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "itemscroller-1.20-pre1-0.20.0.jar",
          "url": "itemscroller-1.20-pre1-0.20.0.jar",
          "size": 121230,
          "sha512": "6eee2a52e876bc10609f0c9eecce93f77304d2de17f03b029f92ce2d06bed6a54465eea56bd622d407b7354069ce5acc922ecd51579a5dc423d6c5c7bfd7af6b",
          "sha256": "4cffda3abec0425c2ae2c5e5f66e6738e94b4e4a85e35cd13aeaf02cad0864d9",
          "sha1": "27bc9a8e1a06e7d3b356291acf9abd7254e21689",
          "md5": "e3d36c18327212cf90df69bc68e582e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "fi.dy.masa.malilib",
          "module": "malilib-fabric-1.20-pre1",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "itemscroller-1.20-pre1-0.20.0.jar",
          "url": "itemscroller-1.20-pre1-0.20.0.jar",
          "size": 121230,
          "sha512": "6eee2a52e876bc10609f0c9eecce93f77304d2de17f03b029f92ce2d06bed6a54465eea56bd622d407b7354069ce5acc922ecd51579a5dc423d6c5c7bfd7af6b",
          "sha256": "4cffda3abec0425c2ae2c5e5f66e6738e94b4e4a85e35cd13aeaf02cad0864d9",
          "sha1": "27bc9a8e1a06e7d3b356291acf9abd7254e21689",
          "md5": "e3d36c18327212cf90df69bc68e582e1"
        }
      ]
    }
  ]
}
