{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.336+05361cf-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.336+05361cf-beta.jar",
          "url": "magiclib-1_17_1-0.7.336+05361cf-beta.jar",
          "size": 377695,
          "sha512": "e51e3ef7058956381137472ab426bf163ea363d8db7705bcfc63488e3e58d3835531d6bbef13a7f0a19e14550396d5e123b50a5b1ddd0c735036800259406476",
          "sha256": "7226aaf3cd174724eaba10a14465b8a41c34a980b6bb2b61dc925f0f1eff4ed6",
          "sha1": "126d651f57723559a0329f37218c80e794c25da5",
          "md5": "27132fa7847765c06be5538f513de176"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.336+05361cf-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.336+05361cf-beta.jar",
          "url": "magiclib-1_17_1-0.7.336+05361cf-beta.jar",
          "size": 377695,
          "sha512": "e51e3ef7058956381137472ab426bf163ea363d8db7705bcfc63488e3e58d3835531d6bbef13a7f0a19e14550396d5e123b50a5b1ddd0c735036800259406476",
          "sha256": "7226aaf3cd174724eaba10a14465b8a41c34a980b6bb2b61dc925f0f1eff4ed6",
          "sha1": "126d651f57723559a0329f37218c80e794c25da5",
          "md5": "27132fa7847765c06be5538f513de176"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.336+05361cf-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.336+05361cf-beta-sources.jar",
          "size": 169834,
          "sha512": "2818ec7eb57fef29705e01aa0ba7ee3b2eba108ee2591f7396bce85690bac79e8aff228e1b6f9f5a93b556810dda67e8544023c58712b8382b8ef3325830019a",
          "sha256": "8256e0a4174e2644330d7d7d6770927a9825d25839cd1630ac9e63fcc4c3158b",
          "sha1": "cee81a94014ba6c707eda41744e0af9ac1d1e9d6",
          "md5": "4e0527bcee81f27f1fddfc73f4f9bd46"
        }
      ]
    }
  ]
}
