{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.305+183e2ea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_17_1-0.7.305+183e2ea-beta.jar",
          "size": 358968,
          "sha512": "d3eed0f2cc2dcf98500ad0edf6d1f6a49958bd0600d35ee327a9b5e042b4bf7c19d56fde0382c42d9617f4e2060858aee93788955cbadaf077b08ff629635e4a",
          "sha256": "94a67c26027c467a6a8eab2042aa3233a71915f485692f69266a94e08f2784fd",
          "sha1": "e8f555df68c50f38a46a74f85e9db0f425e3f06a",
          "md5": "8030dee61856f6f1691a66338fb56a70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.305+183e2ea-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_17_1-0.7.305+183e2ea-beta.jar",
          "size": 358968,
          "sha512": "d3eed0f2cc2dcf98500ad0edf6d1f6a49958bd0600d35ee327a9b5e042b4bf7c19d56fde0382c42d9617f4e2060858aee93788955cbadaf077b08ff629635e4a",
          "sha256": "94a67c26027c467a6a8eab2042aa3233a71915f485692f69266a94e08f2784fd",
          "sha1": "e8f555df68c50f38a46a74f85e9db0f425e3f06a",
          "md5": "8030dee61856f6f1691a66338fb56a70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.305+183e2ea-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.305+183e2ea-beta-sources.jar",
          "size": 159687,
          "sha512": "4b722c7f924abaa7ef3c5df73c2b08ff38d67392d5abea58187814a8b52decd13a00dc6dee9e2b9b9271ce4c6c7a88cc5119d2e1f7cca7892a90b3142207a39a",
          "sha256": "3c3d9905883ce891e4b9dca513b5f7cb9b91f288edbd560d40c2d40f492a0bc9",
          "sha1": "f905a4a73dfa76cc1ee3930641c7ee9e235c3b46",
          "md5": "066915c19519a6a29d2004b69ee7782f"
        }
      ]
    }
  ]
}
