{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.305+183e2ea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_19_3-0.7.305+183e2ea-beta.jar",
          "size": 360736,
          "sha512": "61959ba67513e63f69d764ee9a8b0d825396970b73253e07f3c0dd9d323dd320bdf5c9ef6ad6526a3a94234a8ca5e1f4aeed87ed39c4a5cf9b6ee1b0f290a613",
          "sha256": "c545a9ddce0b59367c45a32c3849caad88cc25a40d23a63f6474d0a6ac8a0eb8",
          "sha1": "7a6c02995d0952f8b24611c6329a2b81bd04fdba",
          "md5": "dfe6b729abcf07155540ac8f92b78535"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.305+183e2ea-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_19_3-0.7.305+183e2ea-beta.jar",
          "size": 360736,
          "sha512": "61959ba67513e63f69d764ee9a8b0d825396970b73253e07f3c0dd9d323dd320bdf5c9ef6ad6526a3a94234a8ca5e1f4aeed87ed39c4a5cf9b6ee1b0f290a613",
          "sha256": "c545a9ddce0b59367c45a32c3849caad88cc25a40d23a63f6474d0a6ac8a0eb8",
          "sha1": "7a6c02995d0952f8b24611c6329a2b81bd04fdba",
          "md5": "dfe6b729abcf07155540ac8f92b78535"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.305+183e2ea-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.305+183e2ea-beta-sources.jar",
          "size": 159765,
          "sha512": "217e33a7cb4a87a82235f484b7ca3f73928ead743835f4ad99f7651fc31867d831912867e948eb9664b869c31e559b048c570d8a2a80d2911edf9b64388d91ab",
          "sha256": "7e95c41fb8aadf0593793a1a8212f6d9096ef7b7b06cc27f8a58e571f4de2641",
          "sha1": "3ed246e9a2ccbc53b496467886bfa180e7221978",
          "md5": "54469656b253392566f75ef39cb9d01e"
        }
      ]
    }
  ]
}
