{
  "formatVersion": "1.1",
  "component": {
    "group": "fi.dy.masa",
    "module": "malilib",
    "version": "23w17a-0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "malilib-23w17a-0.16.0.jar",
          "url": "malilib-23w17a-0.16.0.jar",
          "size": 540725,
          "sha512": "60d294d61989143d06be2fcb1c998ec430425f42dc766d67de61c812439242a980c0fa1876a2e649d6c62c39a5ecfc0b3ece6c6f4467f7a6cb890d250ccc3e57",
          "sha256": "42298b15b23c3c8f7f1e16b5137a3cf308f71273a04861c2059460f67b6969a6",
          "sha1": "14823ef29236a8389c1b2836d41056a78816f20b",
          "md5": "3b83ef7be5504eea455e5c49ed1ee5c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.11.4+bd913b0d4e"
          }
        }
      ],
      "files": [
        {
          "name": "malilib-23w17a-0.16.0.jar",
          "url": "malilib-23w17a-0.16.0.jar",
          "size": 540725,
          "sha512": "60d294d61989143d06be2fcb1c998ec430425f42dc766d67de61c812439242a980c0fa1876a2e649d6c62c39a5ecfc0b3ece6c6f4467f7a6cb890d250ccc3e57",
          "sha256": "42298b15b23c3c8f7f1e16b5137a3cf308f71273a04861c2059460f67b6969a6",
          "sha1": "14823ef29236a8389c1b2836d41056a78816f20b",
          "md5": "3b83ef7be5504eea455e5c49ed1ee5c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "malilib-23w17a-0.16.0-sources.jar",
          "url": "malilib-23w17a-0.16.0-sources.jar",
          "size": 266719,
          "sha512": "74be3b282564858604ebf45b3935ed4ece7ec8cf0b497fbdf370947331cd79739e04f7590aad058feb71e44398e93aa176bf94cf1821f4f62ecf97583c911067",
          "sha256": "7199ba36a08c49b3c467d981af801a1d89d03fa8cb26db3fdd17fb1ed2d71cc2",
          "sha1": "58415ca89295771d1659de87b82734362e4fe28a",
          "md5": "807e29b66f5ab453c47599feca072c79"
        }
      ]
    }
  ]
}
