{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_19_3",
    "version": "0.5.263+0749a47-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_19_3-0.5.263+0749a47-dev.jar",
          "url": "ommc-1_19_3-0.5.263+0749a47-dev.jar",
          "size": 1145876,
          "sha512": "f51558a185f017a0bb0567fd2f754c9f8eb4f68a59440309511c634b4b6d3986c61b92b52706b17cee18415f1a7a1e7b14d9ed338b90864b075d42493f1813c7",
          "sha256": "d77b4d7f557b42f92f6c04ea718a0bc3557bc8bed60e160196ca00c030f2e0ff",
          "sha1": "48362fa744f6142f8abd7274a020b013272b936b",
          "md5": "e3c349acfd35e48f81b976cb2ce4e1d4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.263+0749a47-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_19_3",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_19_3-0.5.263+0749a47-dev.jar",
          "url": "ommc-1_19_3-0.5.263+0749a47-dev.jar",
          "size": 1145876,
          "sha512": "f51558a185f017a0bb0567fd2f754c9f8eb4f68a59440309511c634b4b6d3986c61b92b52706b17cee18415f1a7a1e7b14d9ed338b90864b075d42493f1813c7",
          "sha256": "d77b4d7f557b42f92f6c04ea718a0bc3557bc8bed60e160196ca00c030f2e0ff",
          "sha1": "48362fa744f6142f8abd7274a020b013272b936b",
          "md5": "e3c349acfd35e48f81b976cb2ce4e1d4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
