{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.321+3d981a5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.80.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_19_4-0.7.321+3d981a5-beta.jar",
          "size": 374149,
          "sha512": "cdc8b1b741aa0901b2caee7daa2a36e8b00b8a456522281099dc73f01ab6cbbc4cbcac01178eb165cc93238e5ffda6e57b92121d5444d5816ba55d583bf27c22",
          "sha256": "abd03a1dd8d141d50ede8a2ba86c28099880308ee31d74e85d3d0318292641f1",
          "sha1": "dd19e3ae8a9d154e97c63b4d4b4543167be42b57",
          "md5": "a959223a647b27aeb11b74730e2564af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.321+3d981a5-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.80.0+1.19.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.2-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_19_4-0.7.321+3d981a5-beta.jar",
          "size": 374149,
          "sha512": "cdc8b1b741aa0901b2caee7daa2a36e8b00b8a456522281099dc73f01ab6cbbc4cbcac01178eb165cc93238e5ffda6e57b92121d5444d5816ba55d583bf27c22",
          "sha256": "abd03a1dd8d141d50ede8a2ba86c28099880308ee31d74e85d3d0318292641f1",
          "sha1": "dd19e3ae8a9d154e97c63b4d4b4543167be42b57",
          "md5": "a959223a647b27aeb11b74730e2564af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.321+3d981a5-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.321+3d981a5-beta-sources.jar",
          "size": 168508,
          "sha512": "7fb255268d4a9729b438aa4d806f9ff897d439d5325e49bf316c7019808532f6f663ca2929494e20fd410def61074d3c0622cef4e8b45c69a8a03cfe17dbc5c6",
          "sha256": "96a3e2710c54f31d384f400f3b79fc5799ca9d2769b625a0fb7c28649b254856",
          "sha1": "6e9fa0063aadddd422c23fa7f599f856b65fa0b9",
          "md5": "ebf6c83c159593ca0dc7391e91e4f051"
        }
      ]
    }
  ]
}
