{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.6.223+552a9a4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3030941"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4031627"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.6.223+552a9a4-beta.jar",
          "url": "magiclib-1_15_2-0.6.223+552a9a4-beta.jar",
          "size": 330211,
          "sha512": "52acd53d19d9829ef958e2fa68ffe0781c6be1b1ad21fb99284d03b8cc3b11ce5977311f0c3ba8dfaf0d3e194d8265860e1ad6b1e80917347dd69cd3ef76e493",
          "sha256": "9e428ecbca528864de502ee7936e5e3257fd83b5001abb8cbce1c9f9e48fda4d",
          "sha1": "e7d41b9c6573cf37dde6e09960e59ae7cce78019",
          "md5": "51dccc282fa09d496fca45add676daea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.223+552a9a4-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3030941"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4031627"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761404"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993196"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.6.223+552a9a4-beta.jar",
          "url": "magiclib-1_15_2-0.6.223+552a9a4-beta.jar",
          "size": 330211,
          "sha512": "52acd53d19d9829ef958e2fa68ffe0781c6be1b1ad21fb99284d03b8cc3b11ce5977311f0c3ba8dfaf0d3e194d8265860e1ad6b1e80917347dd69cd3ef76e493",
          "sha256": "9e428ecbca528864de502ee7936e5e3257fd83b5001abb8cbce1c9f9e48fda4d",
          "sha1": "e7d41b9c6573cf37dde6e09960e59ae7cce78019",
          "md5": "51dccc282fa09d496fca45add676daea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.6.223+552a9a4-beta-sources.jar",
          "url": "magiclib-1_15_2-0.6.223+552a9a4-beta-sources.jar",
          "size": 231078,
          "sha512": "1ce8f78b15cba532935d782c158ad9ac70bbcfd6fb1de6f023ccbcd10081db7d2e5cd6e015891f3c5830af53ed3abd943ef62d4221acffa8123d9a3f66806696",
          "sha256": "1d13da06f492916b433f52ab0de7f56574b8e7192ffe71e89e2a4eff5d8da595",
          "sha1": "d685fbb7c13d5fce7fb1f9db484189ae08b754ad",
          "md5": "088822a5fdae7f144595d9021c3d17a1"
        }
      ]
    }
  ]
}
