{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.313+71378a6-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.313+71378a6-beta.jar",
          "url": "magiclib-1_19_2-0.7.313+71378a6-beta.jar",
          "size": 374515,
          "sha512": "4da14b8a239bdac61000a16bcb9fa4e03f1ee956bbcfe5df5491f63ca7f293cf3a173548311008e023e45cc410b6eb749586c7a37e0b175d0cd8f22217233101",
          "sha256": "c94caf88551828f76f83f09d1823d2d48cb00439f7a7ebab481a8d62c86f2f78",
          "sha1": "3f25a80b2fe7f1fb9b4cc2c6c564d951682dcfb8",
          "md5": "494ab666d34c3c65cbc4b0f47680ce1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.313+71378a6-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.313+71378a6-beta.jar",
          "url": "magiclib-1_19_2-0.7.313+71378a6-beta.jar",
          "size": 374515,
          "sha512": "4da14b8a239bdac61000a16bcb9fa4e03f1ee956bbcfe5df5491f63ca7f293cf3a173548311008e023e45cc410b6eb749586c7a37e0b175d0cd8f22217233101",
          "sha256": "c94caf88551828f76f83f09d1823d2d48cb00439f7a7ebab481a8d62c86f2f78",
          "sha1": "3f25a80b2fe7f1fb9b4cc2c6c564d951682dcfb8",
          "md5": "494ab666d34c3c65cbc4b0f47680ce1f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.313+71378a6-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.313+71378a6-beta-sources.jar",
          "size": 168067,
          "sha512": "3447a3e0518c9961012309db13128d2deb706778937bdb0b67a7e542d27a29a6af8f37f290cfc9df36299917d7ca23a7aad5685997726ce236efa7e4318904e9",
          "sha256": "e86b81cb503319656593daba8cae633961383b994f5065da8fdcb008a134d5d1",
          "sha1": "36e790f8f02146b2def9fe6093a39387e5fafe5c",
          "md5": "f9c219f00d25622e5d2411e03fd0524e"
        }
      ]
    }
  ]
}
