{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-minecraft-compat-1_19_3",
    "version": "0.5.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_19_3",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_19_3-0.5.2+32bcf58-beta.jar",
          "url": "magiclib-minecraft-compat-1_19_3-0.5.2+32bcf58-beta.jar",
          "size": 142209,
          "sha512": "e3cbe6068d568198745decf680f2daf0060f336f2591d5420d39d135669b3ef40db69bdd337e6f2083b2d773657a06b3d874b3b5cdc8674faa6766a674bcf0f7",
          "sha256": "0e149f9f52fa59739b9974c774a4ce7f4662593099765e08393efb5104b0d95e",
          "sha1": "67e4688e284b84c48d92476b34fb501317cdd7fa",
          "md5": "21f947f4a9e04d02fdcf32f41b5d117c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_19_3",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_19_3-0.5.2+32bcf58-beta.jar",
          "url": "magiclib-minecraft-compat-1_19_3-0.5.2+32bcf58-beta.jar",
          "size": 142209,
          "sha512": "e3cbe6068d568198745decf680f2daf0060f336f2591d5420d39d135669b3ef40db69bdd337e6f2083b2d773657a06b3d874b3b5cdc8674faa6766a674bcf0f7",
          "sha256": "0e149f9f52fa59739b9974c774a4ce7f4662593099765e08393efb5104b0d95e",
          "sha1": "67e4688e284b84c48d92476b34fb501317cdd7fa",
          "md5": "21f947f4a9e04d02fdcf32f41b5d117c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_19_3",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_19_3-0.5.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-minecraft-compat-1_19_3-0.5.2+32bcf58-beta-standalone-dev.jar",
          "size": 395725,
          "sha512": "67be139a17c49a70d1846e1732a006edd3ec6cb0f70bf76f80697a8c83f3c454e6866eee8e84e2cdbb7dc30a94840ad74373e3fb9ce7db236a681fd94cb1abfa",
          "sha256": "4a3746b9625e901688f9dd9243c84c6749e40e026052acb1898a78d5964b6794",
          "sha1": "b1cbf4f134969969e6ebb13bc79e6bb99d82e12e",
          "md5": "a49068a509d3e97f91d6bc4b3d83d806"
        }
      ]
    }
  ]
}
