{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.337+67c250a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_17_1-0.7.337+67c250a-beta.jar",
          "size": 377693,
          "sha512": "bbc514d282057605870cd978fc20b23e5984c49a18332605e6970a170a3bc7c11654631ae0c5727c919dfbd8a527ecd1b2abe9c5b3a106c4046f3cb46b8e94d6",
          "sha256": "3e33c6cc856d22691e394d297b500f8b7b52924ad0c2e6d8cacbfa14a2ab05c6",
          "sha1": "d982f608e6767f4018044168677d0ff0a4631319",
          "md5": "f6cf9e4c51faa2449e3d786aa555982a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.337+67c250a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_17_1-0.7.337+67c250a-beta.jar",
          "size": 377693,
          "sha512": "bbc514d282057605870cd978fc20b23e5984c49a18332605e6970a170a3bc7c11654631ae0c5727c919dfbd8a527ecd1b2abe9c5b3a106c4046f3cb46b8e94d6",
          "sha256": "3e33c6cc856d22691e394d297b500f8b7b52924ad0c2e6d8cacbfa14a2ab05c6",
          "sha1": "d982f608e6767f4018044168677d0ff0a4631319",
          "md5": "f6cf9e4c51faa2449e3d786aa555982a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.337+67c250a-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.337+67c250a-beta-sources.jar",
          "size": 169834,
          "sha512": "9676f76d13591e938b95166c82969030c6f5a6306ae7533c1b3e0370f3d03e2a5823e3017b3f3f753a8040ce0cab9e9fd1122c78c73ec4f49071546efa1bdbf8",
          "sha256": "7e8cb17df00bd32d52cc70a633673d453ba92441b869062f9927778f4c03c7b9",
          "sha1": "1951a793c589eb71e7a29484e52a7b6c2049aab0",
          "md5": "6df59057d1bf522a8f2ceb2cbe71118f"
        }
      ]
    }
  ]
}
