{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.322+57464f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.322+57464f9-beta.jar",
          "url": "magiclib-1_19_2-0.7.322+57464f9-beta.jar",
          "size": 374724,
          "sha512": "f230545c3e6ad8aa3554613a08d7420f40ee0c77f410b1782ff20978e021f528d69d487d663092867ca8bdb5377f92a1ab788b80d4889b53e3c2a089f8f1f2a9",
          "sha256": "69d9974ecae4c9143356c0d29554c22f3e3fb0480b029a1af9768214eca8dfe7",
          "sha1": "23a7c3d474e16b1eaa9bf0c5a1ac3a7c0321c7e2",
          "md5": "e6ab4d17f0c4eb10e7f81cb4dfdaf136"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.322+57464f9-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.322+57464f9-beta.jar",
          "url": "magiclib-1_19_2-0.7.322+57464f9-beta.jar",
          "size": 374724,
          "sha512": "f230545c3e6ad8aa3554613a08d7420f40ee0c77f410b1782ff20978e021f528d69d487d663092867ca8bdb5377f92a1ab788b80d4889b53e3c2a089f8f1f2a9",
          "sha256": "69d9974ecae4c9143356c0d29554c22f3e3fb0480b029a1af9768214eca8dfe7",
          "sha1": "23a7c3d474e16b1eaa9bf0c5a1ac3a7c0321c7e2",
          "md5": "e6ab4d17f0c4eb10e7f81cb4dfdaf136"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.322+57464f9-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.322+57464f9-beta-sources.jar",
          "size": 168346,
          "sha512": "e2d10a3dad28e6318a5081939532f646aae4707ca56413a575cf0fa41541c03ef12bb73cec3f5e849f8de0ac0f80cc451ace5b0a9dfee0a3480c1999a7ab7a4f",
          "sha256": "b51f6a42c3f80cfda33b8bf534e46443dc9be219e47e9af03b88fbfee8139f7d",
          "sha1": "8b3aeaef54ac6531936dc4f445cb8c1dfda6ffb7",
          "md5": "5020365ffc7576d72457aeefcea92c29"
        }
      ]
    }
  ]
}
