{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.317+92abd79-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.317+92abd79-beta.jar",
          "url": "magiclib-1_16_5-0.7.317+92abd79-beta.jar",
          "size": 373947,
          "sha512": "afa28d80749eed39f795908e00deb54756ae6bd16744e5224d1544bcfad7cb581be9984dc40865277a11e4a58cb237bc9a173a436b489a405b8953e9f16e6b83",
          "sha256": "78c8298ce4a73ed1cdf6784647dd28203cee43a8b61241a5db31ffe669bcaba5",
          "sha1": "aa963cc65363e5667fb217c4377306394893c55d",
          "md5": "65d2909cd8dee8e78fc8087eae7d31ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.317+92abd79-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.16"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.317+92abd79-beta.jar",
          "url": "magiclib-1_16_5-0.7.317+92abd79-beta.jar",
          "size": 373947,
          "sha512": "afa28d80749eed39f795908e00deb54756ae6bd16744e5224d1544bcfad7cb581be9984dc40865277a11e4a58cb237bc9a173a436b489a405b8953e9f16e6b83",
          "sha256": "78c8298ce4a73ed1cdf6784647dd28203cee43a8b61241a5db31ffe669bcaba5",
          "sha1": "aa963cc65363e5667fb217c4377306394893c55d",
          "md5": "65d2909cd8dee8e78fc8087eae7d31ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.317+92abd79-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.317+92abd79-beta-sources.jar",
          "size": 168032,
          "sha512": "cff89b9045887b861d4eee78e4929fe42beb7d6bf16d79029ca5d0915cd59bcbb0cff5fe47cc9a3d4da2590d2d8025594c98e8fd96935a85eb616b020ea2da09",
          "sha256": "ffd59483241faad7bcb2f6200942539d1bbec034460b4ba4638541bf370235e0",
          "sha1": "77e5a06fdc0fcdd3323645d556fefc467896158f",
          "md5": "50454d5c8605aa28cad08d686910398b"
        }
      ]
    }
  ]
}
