{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.280+c3d8807-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4437137"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa",
          "module": "malilib",
          "version": {
            "requires": "0.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4440850"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.280+c3d8807-beta.jar",
          "url": "magiclib-1_19_4-0.7.280+c3d8807-beta.jar",
          "size": 360654,
          "sha512": "7e00306b6c8b5a2a0b3079b20c7f76b393e93c7d761afc777eecccb3c27fccbf720fa80a843ede73de068cdc0b00c2e577edf04bb87173cb041942ac857be5d8",
          "sha256": "2b37fa46ba50ebd0452f4eca43e9cdd5258f08158fd35b8748550e5e8cf7bec2",
          "sha1": "4801bbdac5cd013306a9ab961c29177ce6776d29",
          "md5": "0ed87f9033c7d2d79af24d4dccc3696d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.280+c3d8807-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4437137"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "fi.dy.masa",
          "module": "malilib",
          "version": {
            "requires": "0.15.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4440850"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.280+c3d8807-beta.jar",
          "url": "magiclib-1_19_4-0.7.280+c3d8807-beta.jar",
          "size": 360654,
          "sha512": "7e00306b6c8b5a2a0b3079b20c7f76b393e93c7d761afc777eecccb3c27fccbf720fa80a843ede73de068cdc0b00c2e577edf04bb87173cb041942ac857be5d8",
          "sha256": "2b37fa46ba50ebd0452f4eca43e9cdd5258f08158fd35b8748550e5e8cf7bec2",
          "sha1": "4801bbdac5cd013306a9ab961c29177ce6776d29",
          "md5": "0ed87f9033c7d2d79af24d4dccc3696d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.280+c3d8807-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.280+c3d8807-beta-sources.jar",
          "size": 159489,
          "sha512": "072620cdc52adec6a97d9be77fca908f08764ac45fe804f827de1af444ac7fb7e5e9250ae31623606f6aada1a440abe7a16cd7e3206741da7e541998a67e4f83",
          "sha256": "688b781b56021f4a57531001d629af466dbfa84410b2e6410e357baf9adbb2b6",
          "sha1": "6fc3b21de1656eae6bda0cdc172c02e9a3668395",
          "md5": "9a07330f673f917900c6016f888325c5"
        }
      ]
    }
  ]
}
