{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.327+dfd83d3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.1+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.327+dfd83d3-beta.jar",
          "url": "magiclib-1_19_4-0.7.327+dfd83d3-beta.jar",
          "size": 375396,
          "sha512": "a11561da6fb8f5ee5717ab20675cb865172721e27cf28f7231f7e715b80e050bd56c3120a8eecd00d9e838224d28b753864ac9a714a3e23e5684634e4995b2fe",
          "sha256": "c315e041581511f806b1c32c796f17edfcf4cabebb75de5db822ad0dc16f9024",
          "sha1": "24e539f419bf34e9c678c0a4189753532eca372e",
          "md5": "afbf64da90694451b54b310bb5f9692e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.327+dfd83d3-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.1+1.19.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.2-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.327+dfd83d3-beta.jar",
          "url": "magiclib-1_19_4-0.7.327+dfd83d3-beta.jar",
          "size": 375396,
          "sha512": "a11561da6fb8f5ee5717ab20675cb865172721e27cf28f7231f7e715b80e050bd56c3120a8eecd00d9e838224d28b753864ac9a714a3e23e5684634e4995b2fe",
          "sha256": "c315e041581511f806b1c32c796f17edfcf4cabebb75de5db822ad0dc16f9024",
          "sha1": "24e539f419bf34e9c678c0a4189753532eca372e",
          "md5": "afbf64da90694451b54b310bb5f9692e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.327+dfd83d3-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.327+dfd83d3-beta-sources.jar",
          "size": 168979,
          "sha512": "7606f64bafd6a1e150bdb0fa9360fdf3d9c948a4503de0b7cf091dffb965a0af323592025d6e67f5e678d20d09e06135948d4d377d1bbd7b31eb5535d2ea67ec",
          "sha256": "a53934afc7091e41035e4195998150397faba0a86b05fdcc8a704f7626bf6ed3",
          "sha1": "4d13cf5183b30f31ecf6aa6316afaa003b913f7e",
          "md5": "743e9f33507ccff77c18b73da1f1d517"
        }
      ]
    }
  ]
}
