{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.336",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.336.jar",
          "url": "magiclib-1_16_5-0.7.336.jar",
          "size": 379653,
          "sha512": "e49f9696c5c8af89cf1908a33f7e4662cdd281004bb7a18a0a1cbc78f8ec0a71f74f2fc0fa22d49175cb93ec0fcc258cf62cd9f430b1fffa529ad70ea00c03b1",
          "sha256": "ed5ba0ea4accff059200679b92e3ce51801abd33b9e8adc5909c7bb2c9ec0e4f",
          "sha1": "db7aa26d8a7cf7ed03281645681ca33cd807f179",
          "md5": "817369cff39ea9bdeb2744afb2745b13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.336"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.16"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.336.jar",
          "url": "magiclib-1_16_5-0.7.336.jar",
          "size": 379653,
          "sha512": "e49f9696c5c8af89cf1908a33f7e4662cdd281004bb7a18a0a1cbc78f8ec0a71f74f2fc0fa22d49175cb93ec0fcc258cf62cd9f430b1fffa529ad70ea00c03b1",
          "sha256": "ed5ba0ea4accff059200679b92e3ce51801abd33b9e8adc5909c7bb2c9ec0e4f",
          "sha1": "db7aa26d8a7cf7ed03281645681ca33cd807f179",
          "md5": "817369cff39ea9bdeb2744afb2745b13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.336-sources.jar",
          "url": "magiclib-1_16_5-0.7.336-sources.jar",
          "size": 169663,
          "sha512": "11c1929a0b6c56b242cb07198cc01b9f9549c770235c54f20e0bd02fca851cdd5fdcd3ce45e33d08005710aa963cb8a2896447f890ee155ec87f7f43191c8537",
          "sha256": "7b42ecc1af259cdc6031aa0a3bf3ffc2465cfbc349614a92953fe81ffa03f447",
          "sha1": "f39d0b9259af16ccd9c6145520d6c1bffa5f4d92",
          "md5": "27cc3daae0efd2acb21c8a0b03c3da74"
        }
      ]
    }
  ]
}
