{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19",
    "version": "0.5.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3821162"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.55.2+1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19-0.5.31.jar",
          "url": "magiclib-1_19-0.5.31.jar",
          "size": 254216,
          "sha512": "d920ae49c26a3b42b6ca79ede6b8bef7e45343aee6f30c47c7d9cb88e69433c155470ae300916190c16a7e0f9ba94a3f7753754f6ebefae9ccf9c17430568986",
          "sha256": "f75f7dc9bcbdabce9714830741569308ffefe63014090dfebc5ff658a4a64808",
          "sha1": "abfb576b64763c144a16172d4a3fb2a51db51197",
          "md5": "6066ac78568a62c1bbbf2844940cebb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.31"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3821162"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.55.2+1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19-0.5.31.jar",
          "url": "magiclib-1_19-0.5.31.jar",
          "size": 254216,
          "sha512": "d920ae49c26a3b42b6ca79ede6b8bef7e45343aee6f30c47c7d9cb88e69433c155470ae300916190c16a7e0f9ba94a3f7753754f6ebefae9ccf9c17430568986",
          "sha256": "f75f7dc9bcbdabce9714830741569308ffefe63014090dfebc5ff658a4a64808",
          "sha1": "abfb576b64763c144a16172d4a3fb2a51db51197",
          "md5": "6066ac78568a62c1bbbf2844940cebb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19-0.5.31-sources.jar",
          "url": "magiclib-1_19-0.5.31-sources.jar",
          "size": 192555,
          "sha512": "850f2b30549607df3ad84ed21de8133e090e5f6f7bf3ee2bfb4f176b701bffe43a754c1a431ce232192830e3ac7b8a29f4edaa050244a738df787cab02f96463",
          "sha256": "3ce9baca774aff6576c6333537bee1abee492bd6512bc49d5db556df397fea78",
          "sha1": "cc59fe513f2cd6f1a4164034a9ca7fac513a5eb7",
          "md5": "3893d9a43c559eb70ff22b108a9f6fe7"
        }
      ]
    }
  ]
}
