{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.283+320fdb8-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-1_19_3-0.7.283+320fdb8-beta.jar",
          "size": 360748,
          "sha512": "2063352bbc5fbfc277f516c4d19682b92a8783cc88ba4a21c5ba16a5b5f40f4e6a1c4e425e10ab9bf4adead83bc731841c619926c2cdb239a3933c825f52b993",
          "sha256": "4de6cee21a05232f2236884d7a781426f57bba7591b0ca49a1d2c4336e8906bc",
          "sha1": "381f03db7b48593bced1cc58c1542ad99f0cc83b",
          "md5": "3c5ae6e2398ff66af9ba3b17a035299e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4215578"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-1_19_3-0.7.283+320fdb8-beta.jar",
          "size": 360748,
          "sha512": "2063352bbc5fbfc277f516c4d19682b92a8783cc88ba4a21c5ba16a5b5f40f4e6a1c4e425e10ab9bf4adead83bc731841c619926c2cdb239a3933c825f52b993",
          "sha256": "4de6cee21a05232f2236884d7a781426f57bba7591b0ca49a1d2c4336e8906bc",
          "sha1": "381f03db7b48593bced1cc58c1542ad99f0cc83b",
          "md5": "3c5ae6e2398ff66af9ba3b17a035299e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.283+320fdb8-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.283+320fdb8-beta-sources.jar",
          "size": 159607,
          "sha512": "14ab2945132cf245f943d94fee9ef02078eb0babeed3e64cc3c277b0c3f4e65c2126fd9f8f511b3a40b84840cf9c3cd28a5a9acac5df83cc5bd073f51b43e2ed",
          "sha256": "8d84f00977320e07f894980d11e2923e48735a0669ad5e1a959f4fa533b51d4f",
          "sha1": "0d2ed3e828130aec2d7bc2f4eac54c525fb83bdc",
          "md5": "cc9ad584f9ebb96453cf6e0320612359"
        }
      ]
    }
  ]
}
