{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.311+83c833c-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.311+83c833c-beta.jar",
          "url": "magiclib-1_18_2-0.7.311+83c833c-beta.jar",
          "size": 373432,
          "sha512": "bb605da5a209ab7d058346e16e74c636b2bb9dc313cd8301d16bd5f6dbc8b097682c4c7f74e7ac089841b9bad41d7ad8b984ed03fd6c78aec5406827a2df43d8",
          "sha256": "5f22bc94c318ea238d320ead02955dff6a68559115cefe3f228fe8ec6a5abeaf",
          "sha1": "74a2e9ae7369935469910f2c8ca4702cb4100e05",
          "md5": "37570835813be104cd530dd1f019df0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.311+83c833c-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.311+83c833c-beta.jar",
          "url": "magiclib-1_18_2-0.7.311+83c833c-beta.jar",
          "size": 373432,
          "sha512": "bb605da5a209ab7d058346e16e74c636b2bb9dc313cd8301d16bd5f6dbc8b097682c4c7f74e7ac089841b9bad41d7ad8b984ed03fd6c78aec5406827a2df43d8",
          "sha256": "5f22bc94c318ea238d320ead02955dff6a68559115cefe3f228fe8ec6a5abeaf",
          "sha1": "74a2e9ae7369935469910f2c8ca4702cb4100e05",
          "md5": "37570835813be104cd530dd1f019df0c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.311+83c833c-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.311+83c833c-beta-sources.jar",
          "size": 168149,
          "sha512": "7a46263784e864494e222871c6b77de54774e86780ff83262577ece33b8fadc89e537b09726530d8bd31fced2e47abf3e7b06c315153989f3e2ff1e46c05d848",
          "sha256": "7a67f64f45d77942cbae5330c0625fde0ce37fea0bb4a16061aaf5f865b22064",
          "sha1": "5912d881449426b4b8b121d12ff7abc66869422e",
          "md5": "700308767eb864285c1e69540d93820f"
        }
      ]
    }
  ]
}
