{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_19_2",
    "version": "0.5.258+a2512cb-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_19_2-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_19_2-0.5.258+a2512cb-dev.jar",
          "size": 1146828,
          "sha512": "bc73672037cb271af08dc3c5537e4c57fa118e023147f2878abd486ad7085cd0c5f384a396495024c317de0c3f35d8b5f083898972d89602ec07de31ac4836d1",
          "sha256": "4d42fa6e4c94f0de06e1e65a9c9173b4836458315c9d0d638fb887143985147a",
          "sha1": "ea57b474ec7b9887199206168d20246be14bb9f1",
          "md5": "68fe00e5a0bc25fcc7d7629b4a5ad4ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.258+a2512cb-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_19_2",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_19_2-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_19_2-0.5.258+a2512cb-dev.jar",
          "size": 1146828,
          "sha512": "bc73672037cb271af08dc3c5537e4c57fa118e023147f2878abd486ad7085cd0c5f384a396495024c317de0c3f35d8b5f083898972d89602ec07de31ac4836d1",
          "sha256": "4d42fa6e4c94f0de06e1e65a9c9173b4836458315c9d0d638fb887143985147a",
          "sha1": "ea57b474ec7b9887199206168d20246be14bb9f1",
          "md5": "68fe00e5a0bc25fcc7d7629b4a5ad4ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
