{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.318+85c565a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.318+85c565a-beta.jar",
          "url": "magiclib-1_16_5-0.7.318+85c565a-beta.jar",
          "size": 373946,
          "sha512": "5f2a7804cc12ac5292500818a2443a51b8b2a55c065c0a2a132cfaab54a1de63e759847fd21dab651f30211f1ea286f737a891587683715071bdafe7887f9bb3",
          "sha256": "1071ce72f1b8d15a4f7be0d4f8edbf96d00a55d20d8c93d9224769fb2e9c8eca",
          "sha1": "b6889738a64422363ec2dbcd406bf6567245b020",
          "md5": "4999e6c6eda4c2b7834ff1f1a83d6a25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.318+85c565a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.44"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.16"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.318+85c565a-beta.jar",
          "url": "magiclib-1_16_5-0.7.318+85c565a-beta.jar",
          "size": 373946,
          "sha512": "5f2a7804cc12ac5292500818a2443a51b8b2a55c065c0a2a132cfaab54a1de63e759847fd21dab651f30211f1ea286f737a891587683715071bdafe7887f9bb3",
          "sha256": "1071ce72f1b8d15a4f7be0d4f8edbf96d00a55d20d8c93d9224769fb2e9c8eca",
          "sha1": "b6889738a64422363ec2dbcd406bf6567245b020",
          "md5": "4999e6c6eda4c2b7834ff1f1a83d6a25"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.318+85c565a-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.318+85c565a-beta-sources.jar",
          "size": 168030,
          "sha512": "1259c046bb2f174da20321fdbb71efd6a29d51cad76441d7fa03cebdc6698913054375fc4da7b28441d383ba67f8d3c83cc537c2f0684a479e19387e986660f9",
          "sha256": "de299aad318b10cf02dd9455752ef1d8ba2815de1140910e009e68c6ca78a448",
          "sha1": "034e726d246df83a89a7a9f9832a809e8bcaeb48",
          "md5": "a6b4aa4088b2b53cbee05c7ce4284ed8"
        }
      ]
    }
  ]
}
