{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.316+d66e799-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.96"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.316+d66e799-beta.jar",
          "url": "magiclib-1_19_3-0.7.316+d66e799-beta.jar",
          "size": 373820,
          "sha512": "ac9d039131608071ee38362d9b5e001d1ef520f6f86e53bc822846e6764aef1475928705f14a8a73cd7403b5c80542cbd3bf8d8f0778df518139f81df7837f34",
          "sha256": "a8beb4bb07cccc526a17c239c88a47420deea90c7aeff5ac42cbe6fffc293f6c",
          "sha1": "93c1578c31c6094bd75088cf8645d51606c471e3",
          "md5": "c0f1bdb4610c28c0fd7ac737446ca1de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.316+d66e799-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.96"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.316+d66e799-beta.jar",
          "url": "magiclib-1_19_3-0.7.316+d66e799-beta.jar",
          "size": 373820,
          "sha512": "ac9d039131608071ee38362d9b5e001d1ef520f6f86e53bc822846e6764aef1475928705f14a8a73cd7403b5c80542cbd3bf8d8f0778df518139f81df7837f34",
          "sha256": "a8beb4bb07cccc526a17c239c88a47420deea90c7aeff5ac42cbe6fffc293f6c",
          "sha1": "93c1578c31c6094bd75088cf8645d51606c471e3",
          "md5": "c0f1bdb4610c28c0fd7ac737446ca1de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.316+d66e799-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.316+d66e799-beta-sources.jar",
          "size": 168284,
          "sha512": "e6a544beb555ee6b35664d6a81107aa4e1748430c86eccd2ec9facf3ef228f566946a7dcc576d28bf154553b41e16c11fc426f862502b6e90de74e25c5abbcf2",
          "sha256": "aa0eb0725c23eab90e1a976524e0ae9b8d0a09f283f31c7f117436124623d042",
          "sha1": "acc8e4ef9694d5063b02ed11de179c89cc1dceb2",
          "md5": "7bc0714ec06be26a27281408d5f2519a"
        }
      ]
    }
  ]
}
