{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.33.jar",
          "url": "magiclib-1_14_4-0.5.33.jar",
          "size": 258654,
          "sha512": "deb5fa899f8e544674b677ba276f40cb6ea2eaa5a179830f00c8bcd9d2ec81eb4e36bce1b0a51777e51a1ba44d2c9fceda0f31f99d078c8adde1457a7db41416",
          "sha256": "4565a3768c2dae7e60f7cf8dbee50910b694b03f390be0f631babe937ff2fff7",
          "sha1": "99fdf3cde7f88a95db3adb3fd6e57de0d7522b1e",
          "md5": "690e04cd83a051c36254071fcc16ef2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2921052"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761403"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827447"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159393"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.33.jar",
          "url": "magiclib-1_14_4-0.5.33.jar",
          "size": 258654,
          "sha512": "deb5fa899f8e544674b677ba276f40cb6ea2eaa5a179830f00c8bcd9d2ec81eb4e36bce1b0a51777e51a1ba44d2c9fceda0f31f99d078c8adde1457a7db41416",
          "sha256": "4565a3768c2dae7e60f7cf8dbee50910b694b03f390be0f631babe937ff2fff7",
          "sha1": "99fdf3cde7f88a95db3adb3fd6e57de0d7522b1e",
          "md5": "690e04cd83a051c36254071fcc16ef2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.33-sources.jar",
          "url": "magiclib-1_14_4-0.5.33-sources.jar",
          "size": 192203,
          "sha512": "18a99e39a213916eb8afe045597069d8df4413b9d422f4a59b8bdd739ef8f2f3aec6ad2ca1f6fd8c5410878e1160fb83f035949d90d9e6b88a8d6a8e7024790a",
          "sha256": "55014f7c854c36ad8ca2902f81bc0c519ec4baf70ff502322ba18afbd4623d0e",
          "sha1": "f7ae884621a22d88d89233310f90b7c8f10d7819",
          "md5": "23cdd28c6302aca36213013fcb214c04"
        }
      ]
    }
  ]
}
