{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.33.jar",
          "url": "magiclib-1_14_4-0.5.33.jar",
          "size": 258654,
          "sha512": "9bee30e9cd6e6473f720ef2a4c12238c936d72bce49ea944e898380414ad130bb2c9f0e9edaa05575953dba803d1f291a2204bd7bae301d9f6bfe46afeafbcf0",
          "sha256": "115169288b6fb8390a5eb8025788f85d7157e669d6ac0ca989abd9c4f2ec8572",
          "sha1": "ef3ac83a225f187499787d68618f0832b3ee9d3b",
          "md5": "4c7ae8136bc176c2d91dbd49434eae88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2921052"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761403"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827447"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159393"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.33.jar",
          "url": "magiclib-1_14_4-0.5.33.jar",
          "size": 258654,
          "sha512": "9bee30e9cd6e6473f720ef2a4c12238c936d72bce49ea944e898380414ad130bb2c9f0e9edaa05575953dba803d1f291a2204bd7bae301d9f6bfe46afeafbcf0",
          "sha256": "115169288b6fb8390a5eb8025788f85d7157e669d6ac0ca989abd9c4f2ec8572",
          "sha1": "ef3ac83a225f187499787d68618f0832b3ee9d3b",
          "md5": "4c7ae8136bc176c2d91dbd49434eae88"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.33-sources.jar",
          "url": "magiclib-1_14_4-0.5.33-sources.jar",
          "size": 192203,
          "sha512": "5d28aa373dc592d7fde2be3630fc476c700d86f0e7aeee5902a4270e3709c45c0041096c03a26269517d1fef6a921a1e8a627be6a45a8f2292452ba528fa5c04",
          "sha256": "ddc54e28584dd9d8e8ee168a8c3977abea1a206d6770d9679e8f10c2941928e3",
          "sha1": "18167699fd318a5a2e53b704e77089def9e689e9",
          "md5": "0899afcee886f469ea311126c9985645"
        }
      ]
    }
  ]
}
