{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.300+7c8ee92-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_17_1-0.7.300+7c8ee92-beta.jar",
          "size": 358809,
          "sha512": "c7459a272f9b0872041d44b4466ee60f13988dda15df23612e168919954358edf71ea8fd40a87c4c52daed05bed89598725d946a8866b57347e24c1576dad545",
          "sha256": "a1aa380618427e98c539ffdd5ebe50a7e621f50896c146e8a56bdf63d785edd0",
          "sha1": "a32ccdef5923e447550a65b98a865d32adf6924f",
          "md5": "7e511fc5f4e2f87f5997bf42e0676c4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.300+7c8ee92-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_17_1-0.7.300+7c8ee92-beta.jar",
          "size": 358809,
          "sha512": "c7459a272f9b0872041d44b4466ee60f13988dda15df23612e168919954358edf71ea8fd40a87c4c52daed05bed89598725d946a8866b57347e24c1576dad545",
          "sha256": "a1aa380618427e98c539ffdd5ebe50a7e621f50896c146e8a56bdf63d785edd0",
          "sha1": "a32ccdef5923e447550a65b98a865d32adf6924f",
          "md5": "7e511fc5f4e2f87f5997bf42e0676c4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.300+7c8ee92-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.300+7c8ee92-beta-sources.jar",
          "size": 159560,
          "sha512": "d0905ccc228ca24734d0fb6579dafd1ebe2a04d22755f791319dc2563ab014000227352a9e2e1fa93447bb0a84f110335200fc777d9cf64f8d077c693b765df3",
          "sha256": "d154882414dfee535dd57dfe637ce13349b8c796c7540d99f6f04a52cbd6168b",
          "sha1": "85635427609d190337cdebcaa0562a27c73ca468",
          "md5": "69317ba3a9aff8b9d017be52d3c10af0"
        }
      ]
    }
  ]
}
