{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.337+67c250a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_19_2-0.7.337+67c250a-beta.jar",
          "size": 380373,
          "sha512": "c78065b2a47fb0df1d3d0c120db0f465a6420d5a59781afd91c65a6dab8926a909ae540760fd4a404adabd38be5c37bf8be75118fecd47835a5e0becece94500",
          "sha256": "8b551bb05f1a695f75c8edf7d43fdc76daeaf2ede548b56e31db55fe46b95316",
          "sha1": "662501ad1848fb181c2cf648ca1dc3fa1b8f6261",
          "md5": "5c0d507671485fdc65cdd304b64abf1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.337+67c250a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_19_2-0.7.337+67c250a-beta.jar",
          "size": 380373,
          "sha512": "c78065b2a47fb0df1d3d0c120db0f465a6420d5a59781afd91c65a6dab8926a909ae540760fd4a404adabd38be5c37bf8be75118fecd47835a5e0becece94500",
          "sha256": "8b551bb05f1a695f75c8edf7d43fdc76daeaf2ede548b56e31db55fe46b95316",
          "sha1": "662501ad1848fb181c2cf648ca1dc3fa1b8f6261",
          "md5": "5c0d507671485fdc65cdd304b64abf1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.337+67c250a-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.337+67c250a-beta-sources.jar",
          "size": 169759,
          "sha512": "9e80e2275b55a0f93dec4ac63cc41135b632b3c8126ec3eb08ff260748a1c6913b27caaa11c805fb08b08d764c1cbdf3da857848c1a5e1985d953cc1a9926b44",
          "sha256": "a342bcbbed75a89ffd42e3af0485a9be71515a3464477ff8f5cc2b674713b1a6",
          "sha1": "8b1d4d8d2dc1c89239285631064b657a7b480cef",
          "md5": "93a13edf3804cd07f944ecdfe5b8adbb"
        }
      ]
    }
  ]
}
