{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.6.188+e7456b1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.6.188+e7456b1-beta.jar",
          "url": "magiclib-1_17_1-0.6.188+e7456b1-beta.jar",
          "size": 324565,
          "sha512": "9387a212ed988dfc2cc4a4b30ee716558bd4b981a111dc58de239b1b55bb55428177ed2e869a831121c6d0399a31a7b706f26097c008945c990b411b8bef7a3a",
          "sha256": "c6a86e122ce8f4df63fa0ade29365f03574e4c0e3145ca9e24256a2bc5fbbb2e",
          "sha1": "90152a560eb3ab06edbb672cf2dced3d9b3e03db",
          "md5": "2199ad042e751cd68eb596778baa9e7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.188+e7456b1-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827451"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.6.188+e7456b1-beta.jar",
          "url": "magiclib-1_17_1-0.6.188+e7456b1-beta.jar",
          "size": 324565,
          "sha512": "9387a212ed988dfc2cc4a4b30ee716558bd4b981a111dc58de239b1b55bb55428177ed2e869a831121c6d0399a31a7b706f26097c008945c990b411b8bef7a3a",
          "sha256": "c6a86e122ce8f4df63fa0ade29365f03574e4c0e3145ca9e24256a2bc5fbbb2e",
          "sha1": "90152a560eb3ab06edbb672cf2dced3d9b3e03db",
          "md5": "2199ad042e751cd68eb596778baa9e7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.6.188+e7456b1-beta-sources.jar",
          "url": "magiclib-1_17_1-0.6.188+e7456b1-beta-sources.jar",
          "size": 228558,
          "sha512": "c644d69bf1ddf3d57ddd5580c3aaa1d763ea949d28202090858bf31cbf1ba440ffcf2a3d14ed8f51c4640f51d6ebaf196dc63dde9379e526c2cdc0b41ec96168",
          "sha256": "b1c322cd1087a6733e1e8a75893a738ee127e9900f454332ac7128a11594d478",
          "sha1": "1a2a9907a6c52eca795b6170974469e61a322c6a",
          "md5": "1e707893de07036b3503724c721e2738"
        }
      ]
    }
  ]
}
