{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.5.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479748"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.31.jar",
          "url": "magiclib-1_16_5-0.5.31.jar",
          "size": 255196,
          "sha512": "11b7b8110ca998690c29c3359805e834e03a690a17b4525a4017703880d65a72d473270311048c0d56339e18257c15e860836b8a7003111150e33b90655eeea4",
          "sha256": "067509cc1a544d2b6fe05971dc348825180eb93f6e14ba83c5ece61bb08a03e1",
          "sha1": "fda09e1825615be302316bbe3f7a3f1e4bf17aaa",
          "md5": "d672ed61ed3e50dc8799e0e133753f1c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.31"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479748"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493810"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.31.jar",
          "url": "magiclib-1_16_5-0.5.31.jar",
          "size": 255196,
          "sha512": "11b7b8110ca998690c29c3359805e834e03a690a17b4525a4017703880d65a72d473270311048c0d56339e18257c15e860836b8a7003111150e33b90655eeea4",
          "sha256": "067509cc1a544d2b6fe05971dc348825180eb93f6e14ba83c5ece61bb08a03e1",
          "sha1": "fda09e1825615be302316bbe3f7a3f1e4bf17aaa",
          "md5": "d672ed61ed3e50dc8799e0e133753f1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.31-sources.jar",
          "url": "magiclib-1_16_5-0.5.31-sources.jar",
          "size": 192434,
          "sha512": "700a7af26b489ce6f2223c8a1b9910fa43711cc271e4986aae389629f4154d8aa5664161fd044bcdb564cb4142593dec0931b0b670696665975e4fcd5b189487",
          "sha256": "01349d17e2fbb9b4cdd4cc73fa02496d485865fca70abdc5c5f4d0cba82159ba",
          "sha1": "d6a7ae6cbfa0e4de24fb2fd247b894a74eb291f5",
          "md5": "fe77c08a27cdc42798035aa957980615"
        }
      ]
    }
  ]
}
