{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.5.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479748"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.31.jar",
          "url": "magiclib-1_16_5-0.5.31.jar",
          "size": 255196,
          "sha512": "3deaa2af231787b53c4ff23ba4c3fd7d28bd471e22386a9bf4f9bdc51979fcbf6f8ebda41fdd031acb86d6d0723c4b0edb4ececc78229ab66884026b5c5fca8d",
          "sha256": "d32da3c50444b08fc892af59955456c21061b0241e5ddc8f44d55224f8b5b978",
          "sha1": "0fca68db8cdf25a8125c045dad3ad2eea1f6a055",
          "md5": "f78a6a9ed3d8302a7b14e1db106a5a66"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.31"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479748"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493810"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.31.jar",
          "url": "magiclib-1_16_5-0.5.31.jar",
          "size": 255196,
          "sha512": "3deaa2af231787b53c4ff23ba4c3fd7d28bd471e22386a9bf4f9bdc51979fcbf6f8ebda41fdd031acb86d6d0723c4b0edb4ececc78229ab66884026b5c5fca8d",
          "sha256": "d32da3c50444b08fc892af59955456c21061b0241e5ddc8f44d55224f8b5b978",
          "sha1": "0fca68db8cdf25a8125c045dad3ad2eea1f6a055",
          "md5": "f78a6a9ed3d8302a7b14e1db106a5a66"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.31-sources.jar",
          "url": "magiclib-1_16_5-0.5.31-sources.jar",
          "size": 192434,
          "sha512": "f312c67271924cb84e2b789d37b576d6a2cdb4e87bfbe2940b578e94d94844b9e7ae62630a386e166a798af5619772b7bfaab084ba0b2a3aef24c196ed6533fd",
          "sha256": "b8f3ce5a83a1d19a58ef2c0bcb32397f2e8022d198df70253996b20bc368c76f",
          "sha1": "e8fa2aef6ed4d6c60c722c2552fe27e7f6c0eb2a",
          "md5": "c19132f62ca114d2f038884135ad0821"
        }
      ]
    }
  ]
}
