{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.304+4912de4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_19_2-0.7.304+4912de4-beta.jar",
          "size": 361650,
          "sha512": "573041579e46802d8b23de89ad1a981b1725d9a152da61abbcd24f321dc9deb439b1b17b842e09da7d54b2866bf8619f9878798847302afc60fc3d04123f71b1",
          "sha256": "dafcd50798d9222d422c3405cde57b14384b94f30006a09acc95c3eee6c84d0b",
          "sha1": "107bdce096000e3b2f0b0ed1c3b7c7b64ab5dfeb",
          "md5": "6c6c3eabc37ee3ce623e10670e77a5fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.304+4912de4-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_19_2-0.7.304+4912de4-beta.jar",
          "size": 361650,
          "sha512": "573041579e46802d8b23de89ad1a981b1725d9a152da61abbcd24f321dc9deb439b1b17b842e09da7d54b2866bf8619f9878798847302afc60fc3d04123f71b1",
          "sha256": "dafcd50798d9222d422c3405cde57b14384b94f30006a09acc95c3eee6c84d0b",
          "sha1": "107bdce096000e3b2f0b0ed1c3b7c7b64ab5dfeb",
          "md5": "6c6c3eabc37ee3ce623e10670e77a5fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.304+4912de4-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.304+4912de4-beta-sources.jar",
          "size": 159614,
          "sha512": "f980ba79bcf457858d5ed07f9fb1d1eb0bfb6b0af00a33379ba2a1d020f135dbb9dfbfd91f95d001f5187145871b24bc1c6f94081398f4750f5b8f55635ce07f",
          "sha256": "41cd46f41f7ad4d77a08ddfefd90689e7b3084afa2caef0107bb09cf8780a405",
          "sha1": "22a996034ff5bb4f51307a5ac70ea7d7988cf2b4",
          "md5": "ab4d18104126c5e6d0b152e3f0940144"
        }
      ]
    }
  ]
}
