{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.33.jar",
          "url": "magiclib-1_17_1-0.5.33.jar",
          "size": 254467,
          "sha512": "f138fe9b9f0fdb8d5326ab312520d413b3c97544c1333c728347e119e3c23d5db2f39124e10c005c224ed811a680f3341e8607fc9288ec1ff4a1f8a8d25ccb32",
          "sha256": "5df7e9de1dc276c09474251f944a12e252aa8b75352fa178da25fc3f50c6fed4",
          "sha1": "15d68fcafcc14469883209bd4b64966f36f8293d",
          "md5": "0d5a57e76685a4437e97182e00688bca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827451"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.33.jar",
          "url": "magiclib-1_17_1-0.5.33.jar",
          "size": 254467,
          "sha512": "f138fe9b9f0fdb8d5326ab312520d413b3c97544c1333c728347e119e3c23d5db2f39124e10c005c224ed811a680f3341e8607fc9288ec1ff4a1f8a8d25ccb32",
          "sha256": "5df7e9de1dc276c09474251f944a12e252aa8b75352fa178da25fc3f50c6fed4",
          "sha1": "15d68fcafcc14469883209bd4b64966f36f8293d",
          "md5": "0d5a57e76685a4437e97182e00688bca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.33-sources.jar",
          "url": "magiclib-1_17_1-0.5.33-sources.jar",
          "size": 192720,
          "sha512": "b7d241c1cdd15c2f5c6c66e5f2136eb8da333ee3680aee65a373812eededafcfedc469f5cf4c7aecc57300fe9116a3894ac3e049bee0b3f5a1a59f787d5f3e7f",
          "sha256": "21150bd5fcfb0cf201bf9c7b68ebf2dd382ddb672364e0ef60aa6557cb54d3a6",
          "sha1": "5e052f5f3d88da6af0c0a539aac8f2e023017829",
          "md5": "c7f00f266ac53ee660ec1553f4eb48ea"
        }
      ]
    }
  ]
}
