{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.33.jar",
          "url": "magiclib-1_17_1-0.5.33.jar",
          "size": 254467,
          "sha512": "bbe097ee5add531e6a94248f028d2b08fa411eb651e5c818374b7770cbc447dbfcd9c2b1bab32c202d5f4e3dbb894b70cfeacb001ffcbbcd5ae6fa2ffce5e292",
          "sha256": "6a2267ace0859bc9f256c7a0ca54262a607945badad56bb1f34766bd2c60fdb8",
          "sha1": "ee7c09d7db9aaa591e53d0b28d2c38ab1919367e",
          "md5": "52b6259bcda5173629e13b85e121cabf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827451"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.33.jar",
          "url": "magiclib-1_17_1-0.5.33.jar",
          "size": 254467,
          "sha512": "bbe097ee5add531e6a94248f028d2b08fa411eb651e5c818374b7770cbc447dbfcd9c2b1bab32c202d5f4e3dbb894b70cfeacb001ffcbbcd5ae6fa2ffce5e292",
          "sha256": "6a2267ace0859bc9f256c7a0ca54262a607945badad56bb1f34766bd2c60fdb8",
          "sha1": "ee7c09d7db9aaa591e53d0b28d2c38ab1919367e",
          "md5": "52b6259bcda5173629e13b85e121cabf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.33-sources.jar",
          "url": "magiclib-1_17_1-0.5.33-sources.jar",
          "size": 192720,
          "sha512": "657145598b1736de87c302d6fc5c09429d6ba020072fe776ac656ff3588f34f8d41d71d2742cbbfe0d39feede24fdf1ebaa8073a0f87e3f64fca3d351d42a058",
          "sha256": "fa9ab602788931bf629ecd95454adae030cd320909de81f710e50a3faed17189",
          "sha1": "c78634684a859c9d4994bfde187f9abe84a04acd",
          "md5": "bb57fe2e2f296f0aecebdebb61c5f7ab"
        }
      ]
    }
  ]
}
