{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.33.jar",
          "url": "magiclib-1_17_1-0.5.33.jar",
          "size": 254467,
          "sha512": "43dcc4e747cd6b8da1ad4bfcf39f704e08f2e897b16b15633ea014e98b74a43d091a39536ce606b596dd0461f0b0773d1a4d66648ebc917aa29e4ada366b59df",
          "sha256": "9321a19a0d1c1338292cfbb0507b660a854d1a8df6a60ef8dccb6bb32509ea02",
          "sha1": "4f3053e95a3dda5d5dec6fb2ad55fa04da7644d8",
          "md5": "3ba99170033e34a498b987edfe6b9cb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827451"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.33.jar",
          "url": "magiclib-1_17_1-0.5.33.jar",
          "size": 254467,
          "sha512": "43dcc4e747cd6b8da1ad4bfcf39f704e08f2e897b16b15633ea014e98b74a43d091a39536ce606b596dd0461f0b0773d1a4d66648ebc917aa29e4ada366b59df",
          "sha256": "9321a19a0d1c1338292cfbb0507b660a854d1a8df6a60ef8dccb6bb32509ea02",
          "sha1": "4f3053e95a3dda5d5dec6fb2ad55fa04da7644d8",
          "md5": "3ba99170033e34a498b987edfe6b9cb1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.33-sources.jar",
          "url": "magiclib-1_17_1-0.5.33-sources.jar",
          "size": 192720,
          "sha512": "849a8bb1056153d6d30c9115eee2015d26a04740a5416bd733eae3a7a2a7e981974928101b81a801662de4faf98645d6137d328134767dfe0cab246e82cf251b",
          "sha256": "67eee2947846916cdd18b2113d80848d6eae743985233c7fa2721412fea0e703",
          "sha1": "2076cc0c0f9ca154f4f53a1c7975347a815a4221",
          "md5": "162a729018390d983c1b88b362aeb6d3"
        }
      ]
    }
  ]
}
