{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.5.30",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.30.jar",
          "url": "magiclib-1_15_2-0.5.30.jar",
          "size": 254861,
          "sha512": "c83dc36a41a99cac128aa8e5d90625d5271d537c72c02e9b6b9bee97d99413e0c0bf84d1dc55618029af899d3cac319f6263ece2301ac480a7744bf1259a7818",
          "sha256": "fe04b8ecde5e46828c33140693e77813bf5363ee9808a9cfa1d24fd000f847b9",
          "sha1": "f7bded8bc67e89d7e14b1fc0fa7310477cb2b71c",
          "md5": "e084f030038b71677993eed342f47a98"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.30"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493807"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.30.jar",
          "url": "magiclib-1_15_2-0.5.30.jar",
          "size": 254861,
          "sha512": "c83dc36a41a99cac128aa8e5d90625d5271d537c72c02e9b6b9bee97d99413e0c0bf84d1dc55618029af899d3cac319f6263ece2301ac480a7744bf1259a7818",
          "sha256": "fe04b8ecde5e46828c33140693e77813bf5363ee9808a9cfa1d24fd000f847b9",
          "sha1": "f7bded8bc67e89d7e14b1fc0fa7310477cb2b71c",
          "md5": "e084f030038b71677993eed342f47a98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.30-sources.jar",
          "url": "magiclib-1_15_2-0.5.30-sources.jar",
          "size": 192296,
          "sha512": "fa7e3206d4872abf6841b79c2696f54867f4091e88736d7c95734db72c9554ecb6cf4013f4ecc24541e5d1229945b1ed99111393012cebc0f77b49d92d7519d4",
          "sha256": "cb0ecb03da26d5067bad91b2d652da67a4da919cf2da255a23cf43c7a6c7e852",
          "sha1": "c2edf04087b1634a8b1b3cd20adeef51367a2271",
          "md5": "7ba3955be7990b43912244fbb5732c3d"
        }
      ]
    }
  ]
}
