{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_14_4",
    "version": "0.5.258+a2512cb-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_14_4-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_14_4-0.5.258+a2512cb-dev.jar",
          "size": 1150076,
          "sha512": "5c75f80a3533057b6fda5a1b0cae2b265c40ff75507f53cdd0143683f9ffe0ec9b1a8a691803a75a4daaa7bf1ab5e9ac563fdd3bb8a364708331763cee1613bc",
          "sha256": "8da6f1b64670c73b40895573af449bc967484b7861b854ecb3ce63caef3481db",
          "sha1": "82f4d76bc79acd3404f0ac256d397fa085a740a0",
          "md5": "4423a27016dbc9f9d4b70cbac65e0948"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.258+a2512cb-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_14_4",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_14_4-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_14_4-0.5.258+a2512cb-dev.jar",
          "size": 1150076,
          "sha512": "5c75f80a3533057b6fda5a1b0cae2b265c40ff75507f53cdd0143683f9ffe0ec9b1a8a691803a75a4daaa7bf1ab5e9ac563fdd3bb8a364708331763cee1613bc",
          "sha256": "8da6f1b64670c73b40895573af449bc967484b7861b854ecb3ce63caef3481db",
          "sha1": "82f4d76bc79acd3404f0ac256d397fa085a740a0",
          "md5": "4423a27016dbc9f9d4b70cbac65e0948"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
