{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.300+7c8ee92-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_19_3-0.7.300+7c8ee92-beta.jar",
          "size": 360577,
          "sha512": "8d9e2266f85d7753563bc298ec15ab8d1144a9d3295c8383ef824998cdeda88953ff994fbd5fab46b4cd281b5486e720fb3408fea140dd948018f96a1b402790",
          "sha256": "9ae4bfbc9ac0e1ae11d2ef5ba81674296a049c3bce6ea7a3656bf081d7452290",
          "sha1": "7521ce59146e128e79ee1241cefad076263b743c",
          "md5": "540e70c837dfd24002f8bb09849eb35b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.300+7c8ee92-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_19_3-0.7.300+7c8ee92-beta.jar",
          "size": 360577,
          "sha512": "8d9e2266f85d7753563bc298ec15ab8d1144a9d3295c8383ef824998cdeda88953ff994fbd5fab46b4cd281b5486e720fb3408fea140dd948018f96a1b402790",
          "sha256": "9ae4bfbc9ac0e1ae11d2ef5ba81674296a049c3bce6ea7a3656bf081d7452290",
          "sha1": "7521ce59146e128e79ee1241cefad076263b743c",
          "md5": "540e70c837dfd24002f8bb09849eb35b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.300+7c8ee92-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.300+7c8ee92-beta-sources.jar",
          "size": 159638,
          "sha512": "e52ae68495393acd50e988e32d93ef6d3f36d5a979e9271a916b799a2ce565be8577fc4eb5a302c6e66754e295559c232d4dd3ae40f896a045b4a1a4384a6c19",
          "sha256": "f01067bf3f6469b1c3ca32c03f6b8d2b5a0bb24cac5d5686883e7197b76af91d",
          "sha1": "a2f4a23e88ba8e31620937ce3c15e2fe202e1c53",
          "md5": "06ad6941624032be932f240bab806af9"
        }
      ]
    }
  ]
}
