{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-minecraft-compat-1_17_1",
    "version": "0.5.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_17_1-0.5.3+c7ba8f9-beta.jar",
          "url": "magiclib-minecraft-compat-1_17_1-0.5.3+c7ba8f9-beta.jar",
          "size": 142128,
          "sha512": "ae38144c735a595ebd11c2b4481327f3c45e8119369b973b840775767d2379f49f7dea6ae79a9d6b522846f55b1939a1e86e9443d113a28f6f0778587dba9531",
          "sha256": "47c76c085dbc98da42034280458d77587579ce5b9d0c3e92ec79a766a1d82a08",
          "sha1": "5017a485187309fe303274ac70e6a81e902604a5",
          "md5": "88a3c95339958d514b96cc677741cc26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_17_1-0.5.3+c7ba8f9-beta.jar",
          "url": "magiclib-minecraft-compat-1_17_1-0.5.3+c7ba8f9-beta.jar",
          "size": 142128,
          "sha512": "ae38144c735a595ebd11c2b4481327f3c45e8119369b973b840775767d2379f49f7dea6ae79a9d6b522846f55b1939a1e86e9443d113a28f6f0778587dba9531",
          "sha256": "47c76c085dbc98da42034280458d77587579ce5b9d0c3e92ec79a766a1d82a08",
          "sha1": "5017a485187309fe303274ac70e6a81e902604a5",
          "md5": "88a3c95339958d514b96cc677741cc26"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_17_1-0.5.3+c7ba8f9-beta-standalone-dev.jar",
          "url": "magiclib-minecraft-compat-1_17_1-0.5.3+c7ba8f9-beta-standalone-dev.jar",
          "size": 395380,
          "sha512": "fa6c565d9f375eaf9be1655b178055098dece72c94ef545c844d2beebfd990ce08fe76c836c235aaee5bc23cfbbc70f1650a15106ce611feb54da548800ce89f",
          "sha256": "889a11325b9952d470c06592880306cd15518e863eb966ef5517c7f0593f3939",
          "sha1": "dc51c5ffe8fd9007554764d8ac61dfd4bf438eb6",
          "md5": "c12c564c4f4ee3a2b0298d903f1c7328"
        }
      ]
    }
  ]
}
