{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.5.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.13.jar",
          "url": "magiclib-1_14_4-0.5.13.jar",
          "size": 262668,
          "sha512": "c5f04549bc354bef94f6bfab08528aec772177d4706cd01a5cf12ca65a1d701f6d18d8d798a31a974c79ad42e4a0e8d667e92b19262a1aad724821bf9cca94ba",
          "sha256": "2f175573422dc3ee34f698e22ee86498924557a3f3bb77e1a23f98ea0c413f5b",
          "sha1": "3163adee7747733dc7a2bcb07298754716b0c2e2",
          "md5": "2290b384b5db24078ba6b409beddc0c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493805"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.13.jar",
          "url": "magiclib-1_14_4-0.5.13.jar",
          "size": 262668,
          "sha512": "c5f04549bc354bef94f6bfab08528aec772177d4706cd01a5cf12ca65a1d701f6d18d8d798a31a974c79ad42e4a0e8d667e92b19262a1aad724821bf9cca94ba",
          "sha256": "2f175573422dc3ee34f698e22ee86498924557a3f3bb77e1a23f98ea0c413f5b",
          "sha1": "3163adee7747733dc7a2bcb07298754716b0c2e2",
          "md5": "2290b384b5db24078ba6b409beddc0c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.13-sources.jar",
          "url": "magiclib-1_14_4-0.5.13-sources.jar",
          "size": 192230,
          "sha512": "04354f3e48bf4aee060c148432331847d13ec25dea733d729b9110413d4eaf3c98250fb85894b6c3d7c64cac8c77b1337aaf948987bbaedb738a6b4dceba8cd6",
          "sha256": "12e509961112605e2245ac04d59dda7d379a813339e3879c9de2d23dc3aaa612",
          "sha1": "bbd36da55c40519583fabc854ef309605b1c6dd1",
          "md5": "fbb8e200100bc2916928804c0e2aa0dc"
        }
      ]
    }
  ]
}
