{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.280+c3d8807-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.280+c3d8807-beta.jar",
          "url": "magiclib-1_16_5-0.7.280+c3d8807-beta.jar",
          "size": 360742,
          "sha512": "bea9009533eec483c8e1afa9b4bfc5f3097f18ef63cfe4be1879f06381d5fe231b170aceb14e42e1071fabf876be5bbce2cdab7656b3376781445804f193b055",
          "sha256": "fcb5c749fad43902ce5c4412b97b08ca3bc64a4d8b964b3b070170a778669f13",
          "sha1": "01479c2f3829620f03ef685c241ffe05c9be0bcc",
          "md5": "5ac87b0d20b077635d8ce12c5a8738df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.280+c3d8807-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.280+c3d8807-beta.jar",
          "url": "magiclib-1_16_5-0.7.280+c3d8807-beta.jar",
          "size": 360742,
          "sha512": "bea9009533eec483c8e1afa9b4bfc5f3097f18ef63cfe4be1879f06381d5fe231b170aceb14e42e1071fabf876be5bbce2cdab7656b3376781445804f193b055",
          "sha256": "fcb5c749fad43902ce5c4412b97b08ca3bc64a4d8b964b3b070170a778669f13",
          "sha1": "01479c2f3829620f03ef685c241ffe05c9be0bcc",
          "md5": "5ac87b0d20b077635d8ce12c5a8738df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.280+c3d8807-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.280+c3d8807-beta-sources.jar",
          "size": 159281,
          "sha512": "b31c5463aaee79e93de468158f91a1227e85e01d6a4c03498e2e4dc9020146b83d5c047fb9077cfbf1270d8cd2b48c8ffcaa32576f80e2f12c96235c5fe9e9f8",
          "sha256": "5e2a96a1be32fafa624dcd1f0c00a48a3c8254abf416e54a20a973ebcb57eb0c",
          "sha1": "738a08e9b7d19ffd89700608dfa067a4f9111a09",
          "md5": "1da9b3a238f91cd841b85b5832912494"
        }
      ]
    }
  ]
}
