{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.6.187+90f47cd-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.187+90f47cd-beta.jar",
          "url": "magiclib-1_16_5-0.6.187+90f47cd-beta.jar",
          "size": 320151,
          "sha512": "9e81ff94ab0738a7ea9dc0d86761cb8e5895ff0af7782fbca819ece39c98f8bdcb8ce5c6284294b4fdc52e9c8f2ccbc756d4f36662f8950d16b9329c7ef8050f",
          "sha256": "f2bee02b16650028eef53137c6531ec9e2105a1b5e53b678391a465919474b45",
          "sha1": "4a99329a261f43017d07a28b3df742df1cb7a3f4",
          "md5": "2d28954e91f9b53fd89017f545f40f85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.187+90f47cd-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827450"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.187+90f47cd-beta.jar",
          "url": "magiclib-1_16_5-0.6.187+90f47cd-beta.jar",
          "size": 320151,
          "sha512": "9e81ff94ab0738a7ea9dc0d86761cb8e5895ff0af7782fbca819ece39c98f8bdcb8ce5c6284294b4fdc52e9c8f2ccbc756d4f36662f8950d16b9329c7ef8050f",
          "sha256": "f2bee02b16650028eef53137c6531ec9e2105a1b5e53b678391a465919474b45",
          "sha1": "4a99329a261f43017d07a28b3df742df1cb7a3f4",
          "md5": "2d28954e91f9b53fd89017f545f40f85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.187+90f47cd-beta-sources.jar",
          "url": "magiclib-1_16_5-0.6.187+90f47cd-beta-sources.jar",
          "size": 225451,
          "sha512": "90a5d3e0f573d71ece3ee1c66bb74d7fd8b7be3af22a3359fd43cc3a73e07a0140ce18c8028554949cde89857edaa485c9d37e7313c4817f98f9b695d19d81ef",
          "sha256": "6e739152d2d0bd8381ef50788355917d190b510eb8be75d8893acce7d531449f",
          "sha1": "78f46e21765be5f843ff461bd2ef7b99953af93d",
          "md5": "b623bca7a04a3127bfffec2b4c594f36"
        }
      ]
    }
  ]
}
