{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_14_4",
    "version": "0.5.308+9e3633a-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_14_4-0.5.308+9e3633a-dev.jar",
          "url": "ommc-1_14_4-0.5.308+9e3633a-dev.jar",
          "size": 1148820,
          "sha512": "78dcbfbfcf9462a0ce87d196303fd58a69770a4509c8ba933d73c5e43b8616c39cb3f58867a5970660975fc0fdfebdb3e492d004fad7746fb38d2104cef63d79",
          "sha256": "c6e2490592d9b05db06f80c46c61f3d01a8236ea9fa9839f8ead51284bc69f2f",
          "sha1": "5ba7a9e35be0a76dc1deceb3493c78b71b267e5b",
          "md5": "9d16bc0cb1622034b1cdcd2defc7ab89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.308+9e3633a-dev"
          }
        },
        {
          "group": "top.hendrixshen.magiclib",
          "module": "magiclib-1_14_4",
          "version": {
            "requires": "0.7.345"
          },
          "excludes": [
            {
              "group": "carpet",
              "module": "fabric-carpet"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_14_4-0.5.308+9e3633a-dev.jar",
          "url": "ommc-1_14_4-0.5.308+9e3633a-dev.jar",
          "size": 1148820,
          "sha512": "78dcbfbfcf9462a0ce87d196303fd58a69770a4509c8ba933d73c5e43b8616c39cb3f58867a5970660975fc0fdfebdb3e492d004fad7746fb38d2104cef63d79",
          "sha256": "c6e2490592d9b05db06f80c46c61f3d01a8236ea9fa9839f8ead51284bc69f2f",
          "sha1": "5ba7a9e35be0a76dc1deceb3493c78b71b267e5b",
          "md5": "9d16bc0cb1622034b1cdcd2defc7ab89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
