{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.7.329+ed83ba7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.14.4-1.3.7+v200127"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.7.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.7.329+ed83ba7-beta.jar",
          "url": "magiclib-1_14_4-0.7.329+ed83ba7-beta.jar",
          "size": 388318,
          "sha512": "24e168911b4511139a03f7f08724ca43841a1870a1794682d7ae7146b1b118a7a90f90c4cfa36a5acfd2af8daa603519ca182a25efacaf390cf98cb80e8817ec",
          "sha256": "9839ac1620622cfcdbead0e6cc13b5dad00d70c34814170b994cdf74de7b262c",
          "sha1": "f354f2ebc65a2c67f43ed7d4beecd99fc215138f",
          "md5": "3949d88d46452a47d4bc6d39c849162a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.329+ed83ba7-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.14.4-1.3.7+v200127"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.7.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2921052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "cloth-config",
          "version": {
            "requires": "1.8+fabric"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.14"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159393"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.7.329+ed83ba7-beta.jar",
          "url": "magiclib-1_14_4-0.7.329+ed83ba7-beta.jar",
          "size": 388318,
          "sha512": "24e168911b4511139a03f7f08724ca43841a1870a1794682d7ae7146b1b118a7a90f90c4cfa36a5acfd2af8daa603519ca182a25efacaf390cf98cb80e8817ec",
          "sha256": "9839ac1620622cfcdbead0e6cc13b5dad00d70c34814170b994cdf74de7b262c",
          "sha1": "f354f2ebc65a2c67f43ed7d4beecd99fc215138f",
          "md5": "3949d88d46452a47d4bc6d39c849162a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.7.329+ed83ba7-beta-sources.jar",
          "url": "magiclib-1_14_4-0.7.329+ed83ba7-beta-sources.jar",
          "size": 174624,
          "sha512": "bac2dea65bf57f3e65596a0cf50591a75cc95e6b6df4a20bdc691ecb0d8a7892ae21a55f1305a0b7e6d9bfd4e660cd8f35be33b8186f67973752bb88d1a81e6f",
          "sha256": "352d0d2e345e69a3fa51547c7a71bf271479269ca3f16f696b16e050c61abee9",
          "sha1": "684683daef9c33331514d25ba17f6ee2c64ad615",
          "md5": "018385f6096c9c0b19eff317e5be4661"
        }
      ]
    }
  ]
}
