{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.300+7c8ee92-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_19_2-0.7.300+7c8ee92-beta.jar",
          "size": 361488,
          "sha512": "9d4ff71d2d6076913fa7e50ac2ed5c0f71d10cf7da0b2efd221decbd22c5a6d5ed287dac1c2b174b93ccdf5c755a736bb6c0882bba789e39710ae503eb1ef881",
          "sha256": "695f6c901a9668f37ccbfaf44141e300cf2774f5f3320f22175c030bb3da9153",
          "sha1": "e952d8d7951ac34c65da281529a9a0abe671ce4d",
          "md5": "3cb7f7865959435251e060b19712eecf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.300+7c8ee92-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_19_2-0.7.300+7c8ee92-beta.jar",
          "size": 361488,
          "sha512": "9d4ff71d2d6076913fa7e50ac2ed5c0f71d10cf7da0b2efd221decbd22c5a6d5ed287dac1c2b174b93ccdf5c755a736bb6c0882bba789e39710ae503eb1ef881",
          "sha256": "695f6c901a9668f37ccbfaf44141e300cf2774f5f3320f22175c030bb3da9153",
          "sha1": "e952d8d7951ac34c65da281529a9a0abe671ce4d",
          "md5": "3cb7f7865959435251e060b19712eecf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.300+7c8ee92-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.300+7c8ee92-beta-sources.jar",
          "size": 159484,
          "sha512": "99548c404f5856d1e67595508b23b9a0409b5115d916e966628b7fee2c18969fe8cc7700f5207f9b5bd4878e2831d3fa582c80f150a905e7c7fb474aab04ee43",
          "sha256": "380e1c7cd5cc160a70aca5df55887a909e7f8c309cb18cd4de622d923a887da4",
          "sha1": "8ceed56e9b8296e79573ea0d078fdf8d85a8d4c4",
          "md5": "76ddcc3a5a6e205128eade25cb7b25fc"
        }
      ]
    }
  ]
}
