{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-carpet-compat-1_17_1",
    "version": "0.2.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_17_1",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_17_1-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_17_1-0.2.2+32bcf58-beta.jar",
          "size": 144442,
          "sha512": "55ca768d655ead4a4a193f7cf9d6f37982a8a2ddbd5bc3ed195f55bb9f8b500a73beaa760dae7f74bead11ab11b4a4a468ad98c24ef267a79a2590b6b551fb74",
          "sha256": "c4eca7c678ff92ecb73a578b292f45eaf4fd9cd45e26541195336f70e207b1f9",
          "sha1": "b6469507e9dbe13ea53a832434ea0f7d079dcd56",
          "md5": "4fdecebc4d2a87708438082eeeb97e7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_17_1",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_17_1-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_17_1-0.2.2+32bcf58-beta.jar",
          "size": 144442,
          "sha512": "55ca768d655ead4a4a193f7cf9d6f37982a8a2ddbd5bc3ed195f55bb9f8b500a73beaa760dae7f74bead11ab11b4a4a468ad98c24ef267a79a2590b6b551fb74",
          "sha256": "c4eca7c678ff92ecb73a578b292f45eaf4fd9cd45e26541195336f70e207b1f9",
          "sha1": "b6469507e9dbe13ea53a832434ea0f7d079dcd56",
          "md5": "4fdecebc4d2a87708438082eeeb97e7b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_17_1",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_17_1-0.2.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-carpet-compat-1_17_1-0.2.2+32bcf58-beta-standalone-dev.jar",
          "size": 536824,
          "sha512": "7a71e1a5b65fa9238cb4251e6acf5717d66df248a14776132f1a00a7e6790b79aef403d64f103bc9d8411f766e270c98c18f7f0803b8634d984ec66a2ef0aea5",
          "sha256": "f28bea7a3330cbb50be0cce45969430521e19f739a552e579ecc9de2d4eb75cd",
          "sha1": "f2852e4a05b3ce89b3ef09df2fbfef3fb04424a6",
          "md5": "e6fdf623bf54c9deff7e091a2fb32f32"
        }
      ]
    }
  ]
}
