{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.317+92abd79-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.69"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.317+92abd79-beta.jar",
          "url": "magiclib-1_18_2-0.7.317+92abd79-beta.jar",
          "size": 373595,
          "sha512": "8c9f2f1f51e406f7f72b2f70f98fb6ad35804004cba6d2dcdfc4ce5f3615afddae6e014f817bf51a52b91cb4cfd6d653e4b3b6a01b9eab97799ef8f6a3fe96e1",
          "sha256": "1e8c9f0d752139f49343e8a19042eba0209f1a6a82d7a9bff33a2891ca434b1c",
          "sha1": "19dda036009f7707847a8bfab2816a5e3f1a3cf4",
          "md5": "9229440f450dafe1cb4d52b141ccd3de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.317+92abd79-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.69"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.317+92abd79-beta.jar",
          "url": "magiclib-1_18_2-0.7.317+92abd79-beta.jar",
          "size": 373595,
          "sha512": "8c9f2f1f51e406f7f72b2f70f98fb6ad35804004cba6d2dcdfc4ce5f3615afddae6e014f817bf51a52b91cb4cfd6d653e4b3b6a01b9eab97799ef8f6a3fe96e1",
          "sha256": "1e8c9f0d752139f49343e8a19042eba0209f1a6a82d7a9bff33a2891ca434b1c",
          "sha1": "19dda036009f7707847a8bfab2816a5e3f1a3cf4",
          "md5": "9229440f450dafe1cb4d52b141ccd3de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.317+92abd79-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.317+92abd79-beta-sources.jar",
          "size": 168213,
          "sha512": "6804ddc17c8707a0a1ec1a1ae389d89b8c7f1e7687c25597ab179e750738b56107241849828a77e907fec5ae9a18517cbc93c65081807d8b1190d0c0ec06434b",
          "sha256": "38db9a87137c470d2428bf6fd24867d1df3fcdd3a8bca3b27d4f9829e82329eb",
          "sha1": "e74c876da2fc2216f13a94b4303170331aa14e35",
          "md5": "81b8603e7f13ce4190e05dcd2cc58150"
        }
      ]
    }
  ]
}
