{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls",
    "module": "ommc-1_16_5",
    "version": "0.5-alpha+37b832f",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_16_5-0.5-alpha+37b832f.jar",
          "url": "ommc-1_16_5-0.5-alpha+37b832f.jar",
          "size": 145869,
          "sha512": "348e92f80b17c67b028a988ddea5a9e237319f710b1cbcd92f829ecd55483170140db6367b05f0de0d0b4129d54717c87402cea0019f34b254cc098cac090d89",
          "sha256": "1bfa4eeda741a3458181ef3477458156bae2c9b9562ee1118a6e0deda76bff43",
          "sha1": "b9d72435f21c791b1687d01616ce99ab4756694a",
          "md5": "b36ed86913878df968b9a2ef898b02f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls",
          "module": "ommc",
          "version": {
            "requires": "0.5-alpha+37b832f"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_16_5",
          "version": {
            "requires": "0.6.194+3df5798-beta"
          }
        }
      ],
      "files": [
        {
          "name": "ommc-1_16_5-0.5-alpha+37b832f.jar",
          "url": "ommc-1_16_5-0.5-alpha+37b832f.jar",
          "size": 145869,
          "sha512": "348e92f80b17c67b028a988ddea5a9e237319f710b1cbcd92f829ecd55483170140db6367b05f0de0d0b4129d54717c87402cea0019f34b254cc098cac090d89",
          "sha256": "1bfa4eeda741a3458181ef3477458156bae2c9b9562ee1118a6e0deda76bff43",
          "sha1": "b9d72435f21c791b1687d01616ce99ab4756694a",
          "md5": "b36ed86913878df968b9a2ef898b02f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ommc-1_16_5-0.5-alpha+37b832f-sources.jar",
          "url": "ommc-1_16_5-0.5-alpha+37b832f-sources.jar",
          "size": 93983,
          "sha512": "ff1da23010320ed4d81a058a429bc2ccfd9059996fb038a06a0370f09aa1674439663d0744fb2aa226cf2b85993667864fa7a79d657c2eedc61d36de6bf60484",
          "sha256": "77650b43cc951aeff957463a866fbc7568729d213bfbab791e335e9b8b5982cf",
          "sha1": "a4c4f7a85e0deafac1a25f80925db2467dfefe84",
          "md5": "aed9111566c398e7b633729f61b55b6e"
        }
      ]
    }
  ]
}
