{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.321+3d981a5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_19_3-0.7.321+3d981a5-beta.jar",
          "size": 373901,
          "sha512": "173d1b2180acc5a2dc1e585c98cff26ef0e9546a5d541996126e3e50d1bbfc979029df98b0a2e4fbc311cf3c6aa42bd905dc8a69ae7c28878a4a29a85c5d31d6",
          "sha256": "aa188c2cd4cf670f9f441b4d7e18d01f406a6c8f824e2b4eeeb3ab805128cfbf",
          "sha1": "f7834352be3c0062b0b9a077f027e2f4ef07d99e",
          "md5": "b717cd797559531b3a9e8e3b2b480f89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.321+3d981a5-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_19_3-0.7.321+3d981a5-beta.jar",
          "size": 373901,
          "sha512": "173d1b2180acc5a2dc1e585c98cff26ef0e9546a5d541996126e3e50d1bbfc979029df98b0a2e4fbc311cf3c6aa42bd905dc8a69ae7c28878a4a29a85c5d31d6",
          "sha256": "aa188c2cd4cf670f9f441b4d7e18d01f406a6c8f824e2b4eeeb3ab805128cfbf",
          "sha1": "f7834352be3c0062b0b9a077f027e2f4ef07d99e",
          "md5": "b717cd797559531b3a9e8e3b2b480f89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.321+3d981a5-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.321+3d981a5-beta-sources.jar",
          "size": 168536,
          "sha512": "c6b08a6d505a4884f4d215209c21b27b3b90fb429a199f67e633387c5876b5ca85947a2a29bbbe4cba9a6e4b05e9594514b2c559be4b819fb424610d018453d8",
          "sha256": "1ae384554e279a887f9884dc817c3e342d278a548c3c0c1b928f8c98ac60d6e9",
          "sha1": "99dc272c48ff55add5df2d3f5deb4c0d1e2c586f",
          "md5": "4774d8d20b830773004eeb8718218531"
        }
      ]
    }
  ]
}
