{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.308+d9af2fc-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_19_3-0.7.308+d9af2fc-beta.jar",
          "size": 371569,
          "sha512": "f1da6035d19de101c97bba8e90b1c831155621170e0654d58a777c65da9f801276d332281bd07e284948e0fee0affc906892d5915b77f328e1a0c0e2af8a4a69",
          "sha256": "075afd349e5590600b2b019e5611c36a5c87663a7942160169cac13e2a6e8bdc",
          "sha1": "92f646dece82c280da2048db396b7639d1531c06",
          "md5": "32272ca228f366dd38151856384770b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.308+d9af2fc-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_19_3-0.7.308+d9af2fc-beta.jar",
          "size": 371569,
          "sha512": "f1da6035d19de101c97bba8e90b1c831155621170e0654d58a777c65da9f801276d332281bd07e284948e0fee0affc906892d5915b77f328e1a0c0e2af8a4a69",
          "sha256": "075afd349e5590600b2b019e5611c36a5c87663a7942160169cac13e2a6e8bdc",
          "sha1": "92f646dece82c280da2048db396b7639d1531c06",
          "md5": "32272ca228f366dd38151856384770b5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.308+d9af2fc-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.308+d9af2fc-beta-sources.jar",
          "size": 166877,
          "sha512": "736f3b0b2518574f02f869f23b80d765c53063403b096f9e08cdf9b690c919e68dba5029df04a7f5e05474f2946948e034194a5f20c3717b0726dd259248a5ac",
          "sha256": "0b0289a9c123836354cb42499ae00cdbfbf4b03cfc0895bf8264c252637e4ab8",
          "sha1": "f57012acf60dbb743f091a8665e8f61a364a402f",
          "md5": "e6d80337810f4b5eae0a26f4062aa8f3"
        }
      ]
    }
  ]
}
