{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.317+92abd79-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.101"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.317+92abd79-beta.jar",
          "url": "magiclib-1_19_4-0.7.317+92abd79-beta.jar",
          "size": 373917,
          "sha512": "301a24bc1364f17de90597e6dfd3a9d66c4355009e0f8a772e04a5b4ea4e0bd879f1e0d65568b4b645f4e6451ebc550b407517e2d257f49d4fd46e0d8fbec60f",
          "sha256": "d9efb8c059a3c875d0a0c9aa6f41e16e29daff9021aab8acf8873b894add9f52",
          "sha1": "8b3f3ec9a5df23c5aae065e2ee7141d309e91fd6",
          "md5": "c62e2daf4cf2f3f618db35b13cebe3d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.317+92abd79-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.101"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.78.0+1.19.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.2-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.317+92abd79-beta.jar",
          "url": "magiclib-1_19_4-0.7.317+92abd79-beta.jar",
          "size": 373917,
          "sha512": "301a24bc1364f17de90597e6dfd3a9d66c4355009e0f8a772e04a5b4ea4e0bd879f1e0d65568b4b645f4e6451ebc550b407517e2d257f49d4fd46e0d8fbec60f",
          "sha256": "d9efb8c059a3c875d0a0c9aa6f41e16e29daff9021aab8acf8873b894add9f52",
          "sha1": "8b3f3ec9a5df23c5aae065e2ee7141d309e91fd6",
          "md5": "c62e2daf4cf2f3f618db35b13cebe3d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.317+92abd79-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.317+92abd79-beta-sources.jar",
          "size": 168257,
          "sha512": "80070a01360b9c718881e58207b576bd88005925f20805ba2c88bb0591c8d28d1728d7cb71dba165f6d24d1bdf81eb28f5a307045e688d1733710b5547790b15",
          "sha256": "351b1727b3762f15b0d31c7f819834398d1089006e4fb7f9e488982177bb93a0",
          "sha1": "73097711ae24cf50178b22060f09d57c9414d34b",
          "md5": "0dbca110523ddc42f27afb73601f96c4"
        }
      ]
    }
  ]
}
