{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.7.319+530ec3a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.15.2-1.4.8+v200811"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.10.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.319+530ec3a-beta.jar",
          "url": "magiclib-1_15_2-0.7.319+530ec3a-beta.jar",
          "size": 371953,
          "sha512": "3c2c17537cae4bb70c86b81f6081d99db2357411f723e648c44cca9256c3fa93fab91d84daa279fc3ced58609fcf6be8cc367a0f70f3abf8883bb6bad1c632cc",
          "sha256": "3dd102fc7aa18a07a4b4cb6e0adfbcc496842a4bc8c0f497e5433fe1e415167a",
          "sha1": "debc298b14ab379aafeee33e0261331579daad8e",
          "md5": "acb1f96aa67f39a7f8ed464d710cb823"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.319+530ec3a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.15.2-1.4.8+v200811"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.10.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "cloth-config",
          "version": {
            "requires": "2.14.2+fabric"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.319+530ec3a-beta.jar",
          "url": "magiclib-1_15_2-0.7.319+530ec3a-beta.jar",
          "size": 371953,
          "sha512": "3c2c17537cae4bb70c86b81f6081d99db2357411f723e648c44cca9256c3fa93fab91d84daa279fc3ced58609fcf6be8cc367a0f70f3abf8883bb6bad1c632cc",
          "sha256": "3dd102fc7aa18a07a4b4cb6e0adfbcc496842a4bc8c0f497e5433fe1e415167a",
          "sha1": "debc298b14ab379aafeee33e0261331579daad8e",
          "md5": "acb1f96aa67f39a7f8ed464d710cb823"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.319+530ec3a-beta-sources.jar",
          "url": "magiclib-1_15_2-0.7.319+530ec3a-beta-sources.jar",
          "size": 168032,
          "sha512": "455208a9117e9ad926f933c2379f3084c88faafa7cf805f15c43ec27122bc7d6332e368434d40bfd8f4dfc962631b378cc88af052a1e1c2c5ff9012540e6403a",
          "sha256": "e3f6f4f4436f046744c9a31b3b02976f4184e2a5a58acd6e0833d489160c5f70",
          "sha1": "f8fc63d09cc3243a08762b476be81bffaaa26c3f",
          "md5": "3aaa8c321a486a14b8ca3306d8d2cf2f"
        }
      ]
    }
  ]
}
