{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib",
    "version": "0.7.283+320fdb8-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-0.7.283+320fdb8-beta.jar",
          "size": 2580620,
          "sha512": "218d67125df2af48a7659d5eeb43e6f9d4872ded1293fb31eb461d0838adfd5b434124725baeb3afcf10df19bcb85f6f03b5f3f6d1ffd8baba7d2c399ade4373",
          "sha256": "fac06a9a3d3a3eabcd50bb840d0c92abec884a3debe693eda5685ec9f5135fdb",
          "sha1": "fb963dc9202027d978ce8e5a74cc2d23a2132072",
          "md5": "2d310e853846afdf6660a0c312564579"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-0.7.283+320fdb8-beta.jar",
          "size": 2580620,
          "sha512": "218d67125df2af48a7659d5eeb43e6f9d4872ded1293fb31eb461d0838adfd5b434124725baeb3afcf10df19bcb85f6f03b5f3f6d1ffd8baba7d2c399ade4373",
          "sha256": "fac06a9a3d3a3eabcd50bb840d0c92abec884a3debe693eda5685ec9f5135fdb",
          "sha1": "fb963dc9202027d978ce8e5a74cc2d23a2132072",
          "md5": "2d310e853846afdf6660a0c312564579"
        }
      ]
    }
  ]
}
