{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.7.321+3d981a5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.14.4-1.3.7+v200127"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.7.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_14_4-0.7.321+3d981a5-beta.jar",
          "size": 387217,
          "sha512": "6a8eb9ad09c96514d19735409173af91975fcfa695b81e2879e685b8ad2f81666cd29fa095a191ce5abc76e88ae5c4f32838f6767fb84cb64e154c59d32c9dd2",
          "sha256": "8eb1c1f476a1cd2c6aa8b1dd718b0a07b62a2b155c972d8fd7ea22dbd97221cc",
          "sha1": "f8acc76a6d3532286499a76d979333efaf5413c8",
          "md5": "403040f006785090bcb15b70504f844c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.321+3d981a5-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.14.4-1.3.7+v200127"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.7.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2921052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "cloth-config",
          "version": {
            "requires": "1.8+fabric"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.14"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159393"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_14_4-0.7.321+3d981a5-beta.jar",
          "size": 387217,
          "sha512": "6a8eb9ad09c96514d19735409173af91975fcfa695b81e2879e685b8ad2f81666cd29fa095a191ce5abc76e88ae5c4f32838f6767fb84cb64e154c59d32c9dd2",
          "sha256": "8eb1c1f476a1cd2c6aa8b1dd718b0a07b62a2b155c972d8fd7ea22dbd97221cc",
          "sha1": "f8acc76a6d3532286499a76d979333efaf5413c8",
          "md5": "403040f006785090bcb15b70504f844c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.7.321+3d981a5-beta-sources.jar",
          "url": "magiclib-1_14_4-0.7.321+3d981a5-beta-sources.jar",
          "size": 174156,
          "sha512": "4440c1f65b75975dccdbf38114ff51e72efe00382929b62f36aaf91cd401c11004db961a65770bed9a29175bdbf44a204c31c93eaf84f376e7f37f69ea93bf1e",
          "sha256": "584e31b902565eafdc31edff16be53f016ce2ccec28be9f87e12c7eeb2da52bf",
          "sha1": "5e7ff84f1714f5755cf0c3035b7ccc09f5f90f3c",
          "md5": "e858bce708e6ce19d8aa1a1870279370"
        }
      ]
    }
  ]
}
