{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.336+05361cf-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.336+05361cf-beta.jar",
          "url": "magiclib-1_16_5-0.7.336+05361cf-beta.jar",
          "size": 379648,
          "sha512": "38c632082019824f5a628b8222f68025a3e247b15872f2ee0879b80701b30d0879268519dec9d2c86ea39388f8521480b73c34edb823a014a926e08ec0cd211e",
          "sha256": "d09b4f7f72a2063c389f5c9ad109dfd72bf78cf6a3db86e558f6c79c2a427607",
          "sha1": "f6d7ddd1d9904c6d2ea7491d6d99c729b6b6f1ff",
          "md5": "6229923fe8328db7cdc3cc4f4a856b7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.336+05361cf-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.16"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.336+05361cf-beta.jar",
          "url": "magiclib-1_16_5-0.7.336+05361cf-beta.jar",
          "size": 379648,
          "sha512": "38c632082019824f5a628b8222f68025a3e247b15872f2ee0879b80701b30d0879268519dec9d2c86ea39388f8521480b73c34edb823a014a926e08ec0cd211e",
          "sha256": "d09b4f7f72a2063c389f5c9ad109dfd72bf78cf6a3db86e558f6c79c2a427607",
          "sha1": "f6d7ddd1d9904c6d2ea7491d6d99c729b6b6f1ff",
          "md5": "6229923fe8328db7cdc3cc4f4a856b7f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.336+05361cf-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.336+05361cf-beta-sources.jar",
          "size": 169663,
          "sha512": "d99c058b08687d55b3d651fdb3d7be39b3a41902111344ee31713922ea17a1b00084eb2c5f05c9cdc701d4a4068e6345873b5d6889ee977a2808ce38fb54c64c",
          "sha256": "689dad4d07d6fae19b7b416df5f26975b84721b7fce92e3287cfb58f21296274",
          "sha1": "78d1fe2816dd6a53b80cb7553a92ddb976d6c4eb",
          "md5": "5114b94ef5b8b6cd40703979813e4348"
        }
      ]
    }
  ]
}
