{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.309+3356ade-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.309+3356ade-beta.jar",
          "url": "magiclib-1_16_5-0.7.309+3356ade-beta.jar",
          "size": 371842,
          "sha512": "66e6016088bfbbee545cfd2e5e3d1ffffe2f240e48535cd1009955a4dda5ef489c1b2084224c00a4b5a5456f8d92807b97c7ff0256da375a35e729654e7510eb",
          "sha256": "665f053ba416bcbf57b5076efb395ce8326416e7eeeec61f7ed9ad72a7b045a1",
          "sha1": "bdd869c96e607d40cde198309c790f5a5bf667ea",
          "md5": "e7313c456fd7f7b6e2a6e39c2b1b21bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.309+3356ade-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.309+3356ade-beta.jar",
          "url": "magiclib-1_16_5-0.7.309+3356ade-beta.jar",
          "size": 371842,
          "sha512": "66e6016088bfbbee545cfd2e5e3d1ffffe2f240e48535cd1009955a4dda5ef489c1b2084224c00a4b5a5456f8d92807b97c7ff0256da375a35e729654e7510eb",
          "sha256": "665f053ba416bcbf57b5076efb395ce8326416e7eeeec61f7ed9ad72a7b045a1",
          "sha1": "bdd869c96e607d40cde198309c790f5a5bf667ea",
          "md5": "e7313c456fd7f7b6e2a6e39c2b1b21bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.309+3356ade-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.309+3356ade-beta-sources.jar",
          "size": 166677,
          "sha512": "99196ee77c4c95a7a21f7d61f9ddaf78a4962472de9f9d22fc374d83663f774a54a95ca660f4b189affd9cc96b0420a8e2ce88da9c31a10ce912066457b269bc",
          "sha256": "d0d3e7fbc122ef2532874f62e94cf9156819587c46f89a98d275c51f2e4d67ef",
          "sha1": "c082790151f01d01283b92e803fb7b70532b0a2c",
          "md5": "64d768486c396e7251798a0883115a8a"
        }
      ]
    }
  ]
}
