{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_18_2",
    "version": "0.5.308+9e3633a-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_18_2-0.5.308+9e3633a-dev.jar",
          "url": "ommc-1_18_2-0.5.308+9e3633a-dev.jar",
          "size": 1144981,
          "sha512": "c53bee6d88386cf196a72f8dec64e09162742f815d341ef4f6415211a9f829499bd186b62b589d68e2d9b934c60791adf67b123ecd4dc810669c568f78e27570",
          "sha256": "ed43a0636959a6977c227ebdc9c8b06215802fec98577280960528cdf7ae8e68",
          "sha1": "e00ad735afaffd924c254557fa08b394a9dc2373",
          "md5": "ce5f7486f40c353f2ea72b3f4f1fbb44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.308+9e3633a-dev"
          }
        },
        {
          "group": "top.hendrixshen.magiclib",
          "module": "magiclib-1_18_2",
          "version": {
            "requires": "0.7.345"
          },
          "excludes": [
            {
              "group": "carpet",
              "module": "fabric-carpet"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_18_2-0.5.308+9e3633a-dev.jar",
          "url": "ommc-1_18_2-0.5.308+9e3633a-dev.jar",
          "size": 1144981,
          "sha512": "c53bee6d88386cf196a72f8dec64e09162742f815d341ef4f6415211a9f829499bd186b62b589d68e2d9b934c60791adf67b123ecd4dc810669c568f78e27570",
          "sha256": "ed43a0636959a6977c227ebdc9c8b06215802fec98577280960528cdf7ae8e68",
          "sha1": "e00ad735afaffd924c254557fa08b394a9dc2373",
          "md5": "ce5f7486f40c353f2ea72b3f4f1fbb44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
