{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib",
    "version": "0.6.177+c890064-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-0.6.177+c890064-beta.jar",
          "url": "magiclib-0.6.177+c890064-beta.jar",
          "size": 1683477,
          "sha512": "2520eed8cf0d74700f2f77a21ca712fe128ade5e0a8e0d58b870c3c971209496bc28a95ab5e2ca2a02546b7f4b41aafdd82b09a285b76af2379ba5587ec46ae9",
          "sha256": "a6aaebd1da71bf032b760ebb8582f8a89c822ac52a1c52478c95e85ebad56a05",
          "sha1": "2ae2c9b4c9d8c66f212a5a111f80b49df7335d33",
          "md5": "4375acf91bdea8788646ad02d1749bc9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-0.6.177+c890064-beta.jar",
          "url": "magiclib-0.6.177+c890064-beta.jar",
          "size": 1683477,
          "sha512": "2520eed8cf0d74700f2f77a21ca712fe128ade5e0a8e0d58b870c3c971209496bc28a95ab5e2ca2a02546b7f4b41aafdd82b09a285b76af2379ba5587ec46ae9",
          "sha256": "a6aaebd1da71bf032b760ebb8582f8a89c822ac52a1c52478c95e85ebad56a05",
          "sha1": "2ae2c9b4c9d8c66f212a5a111f80b49df7335d33",
          "md5": "4375acf91bdea8788646ad02d1749bc9"
        }
      ]
    }
  ]
}
