{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_20_1",
    "version": "0.5.294+e12a73f-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_20_1-0.5.294+e12a73f-dev.jar",
          "url": "ommc-1_20_1-0.5.294+e12a73f-dev.jar",
          "size": 1139446,
          "sha512": "f5287719c57fd175484b4574e50861be146301fa544892ef44ffd844ca85aade297e7563029c4103a83786ff04084e9ada6b15416b09ba9e1ab15312a84414a8",
          "sha256": "0db8d44eba65b1d08a731504a8ef3d884c073a1b29b42e2c8122b8600b340168",
          "sha1": "b26d9a85748e1d0109ab04e190eddd7abcb97ffd",
          "md5": "041ba343bf96810437a329a846392dca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.294+e12a73f-dev"
          }
        },
        {
          "group": "top.hendrixshen.magiclib",
          "module": "magiclib-1_20_1",
          "version": {
            "requires": "0.7.345"
          },
          "excludes": [
            {
              "group": "carpet",
              "module": "fabric-carpet"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_20_1-0.5.294+e12a73f-dev.jar",
          "url": "ommc-1_20_1-0.5.294+e12a73f-dev.jar",
          "size": 1139446,
          "sha512": "f5287719c57fd175484b4574e50861be146301fa544892ef44ffd844ca85aade297e7563029c4103a83786ff04084e9ada6b15416b09ba9e1ab15312a84414a8",
          "sha256": "0db8d44eba65b1d08a731504a8ef3d884c073a1b29b42e2c8122b8600b340168",
          "sha1": "b26d9a85748e1d0109ab04e190eddd7abcb97ffd",
          "md5": "041ba343bf96810437a329a846392dca"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
