{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.6.217+ca350c3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.12"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "2870184"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.6.217+ca350c3-beta.jar",
          "url": "magiclib-1_14_4-0.6.217+ca350c3-beta.jar",
          "size": 344839,
          "sha512": "a6910431cc265490390628e9252ce36e6cb47d86fe3320133bb52beaea077df6cdb0d67d83549c3f5c1661fc2ff71b46a115b6f367fcbcd4c4c3a90a10d79b3e",
          "sha256": "a504057c71a5650177ea445a807bb6d3cd90593209f56f23957f16d31d5d3e7c",
          "sha1": "c69dd4da3340d2abc778ae53362df1ca386346dd",
          "md5": "f6bf3bc14e960dbdce6ecd994448be4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.217+ca350c3-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.12"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "2870184"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2921052"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761403"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993195"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159393"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.6.217+ca350c3-beta.jar",
          "url": "magiclib-1_14_4-0.6.217+ca350c3-beta.jar",
          "size": 344839,
          "sha512": "a6910431cc265490390628e9252ce36e6cb47d86fe3320133bb52beaea077df6cdb0d67d83549c3f5c1661fc2ff71b46a115b6f367fcbcd4c4c3a90a10d79b3e",
          "sha256": "a504057c71a5650177ea445a807bb6d3cd90593209f56f23957f16d31d5d3e7c",
          "sha1": "c69dd4da3340d2abc778ae53362df1ca386346dd",
          "md5": "f6bf3bc14e960dbdce6ecd994448be4a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.6.217+ca350c3-beta-sources.jar",
          "url": "magiclib-1_14_4-0.6.217+ca350c3-beta-sources.jar",
          "size": 236564,
          "sha512": "c1f97964b3d588438815d0f56744c368d6cf90412c2be8dfa29dda74fb35d87a96ee3d043ae943a0c066d1ac0d6fb66f6e8a7464bd8668144d4e76db189d907b",
          "sha256": "eb811a4c26a0c89e714334684749b30c09b7e16064dfb340e449d066ad23f3c9",
          "sha1": "273d0831d2f70bdce96f6a45bb2cf1d06c06e203",
          "md5": "cb5b8a69f79d1c2fc6319c99e80b8805"
        }
      ]
    }
  ]
}
