{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.318+85c565a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.69"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.318+85c565a-beta.jar",
          "url": "magiclib-1_18_2-0.7.318+85c565a-beta.jar",
          "size": 373594,
          "sha512": "e873988c82ed68ac50b382da8b231f2c54f958a12a1c930e5233824f8e4d6660bfa6a7b71f800491779b84255ac29a25cf4714ff9ebdf5d58c9721ea413f92ef",
          "sha256": "bb219967842fdf95a2417a18dcd515b0a8c39aff6e4a9c4700c64835fc2a525a",
          "sha1": "300669e362be25d743916f6119d6235812770688",
          "md5": "f7d2513f87c197bc034a0d3306af207d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.318+85c565a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.69"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.318+85c565a-beta.jar",
          "url": "magiclib-1_18_2-0.7.318+85c565a-beta.jar",
          "size": 373594,
          "sha512": "e873988c82ed68ac50b382da8b231f2c54f958a12a1c930e5233824f8e4d6660bfa6a7b71f800491779b84255ac29a25cf4714ff9ebdf5d58c9721ea413f92ef",
          "sha256": "bb219967842fdf95a2417a18dcd515b0a8c39aff6e4a9c4700c64835fc2a525a",
          "sha1": "300669e362be25d743916f6119d6235812770688",
          "md5": "f7d2513f87c197bc034a0d3306af207d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.318+85c565a-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.318+85c565a-beta-sources.jar",
          "size": 168212,
          "sha512": "096bb3379cde2093d5afb0d1779a85c3f79417f6a27783f96f2bb5378c0a86dc04020011fd3165a8eea1d0d6c8e9f2bd94d86358a4cd5a5aa0dc6d4a4251a7f0",
          "sha256": "dbf1d1cf83fdd5fb0726ca8ba45ca12e1753e8d43b9cf70177f847dae38e05ec",
          "sha1": "0be8b1c2d70562bfab957854921ff0723bbf1bc3",
          "md5": "21d0f83aa50d33a0642d3c0706210356"
        }
      ]
    }
  ]
}
