{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base",
    "version": "0.7.12+b31abea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-base-0.7.12+b31abea-beta.jar",
          "url": "magiclib-base-0.7.12+b31abea-beta.jar",
          "size": 779900,
          "sha512": "a4d76eb585a0515c85d11be7c4c5ad4a24e94e4db619f7ba35c7150eceff8ffd838d6db0c41ad4e2c953405ced83eb62d8bab822b987685ca1023f71a7d537bc",
          "sha256": "219a0cac71cf5e6798d302a91be6c88363307ed58466386e729d63dfc0440ce4",
          "sha1": "06971c5bcf78addc463deb0fb71463e9f46495aa",
          "md5": "4b336798b61d3bd9f9e4289529868652"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-base-0.7.12+b31abea-beta.jar",
          "url": "magiclib-base-0.7.12+b31abea-beta.jar",
          "size": 779900,
          "sha512": "a4d76eb585a0515c85d11be7c4c5ad4a24e94e4db619f7ba35c7150eceff8ffd838d6db0c41ad4e2c953405ced83eb62d8bab822b987685ca1023f71a7d537bc",
          "sha256": "219a0cac71cf5e6798d302a91be6c88363307ed58466386e729d63dfc0440ce4",
          "sha1": "06971c5bcf78addc463deb0fb71463e9f46495aa",
          "md5": "4b336798b61d3bd9f9e4289529868652"
        }
      ]
    }
  ]
}
