{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base",
    "version": "0.7.12+b31abea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-base-0.7.12+b31abea-beta.jar",
          "url": "magiclib-base-0.7.12+b31abea-beta.jar",
          "size": 779898,
          "sha512": "a79f90ff4c2ba4923d49c52e63ae9cc67919c4120b769c9d60a19333d3db0fcdbdaef75583f7de7d62b053961cdec2deb6f1075ec7a8bdcca3dc0073fecf1f83",
          "sha256": "0cd66a7508ce49d7e4b6ed0f98ee7c0d91a8be1a477feb645492c98a6230d7fd",
          "sha1": "486cdc112332e399224d53a24dae6208f81f8179",
          "md5": "7b45137a6419829ddc7623a309a0cad7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-base-0.7.12+b31abea-beta.jar",
          "url": "magiclib-base-0.7.12+b31abea-beta.jar",
          "size": 779898,
          "sha512": "a79f90ff4c2ba4923d49c52e63ae9cc67919c4120b769c9d60a19333d3db0fcdbdaef75583f7de7d62b053961cdec2deb6f1075ec7a8bdcca3dc0073fecf1f83",
          "sha256": "0cd66a7508ce49d7e4b6ed0f98ee7c0d91a8be1a477feb645492c98a6230d7fd",
          "sha1": "486cdc112332e399224d53a24dae6208f81f8179",
          "md5": "7b45137a6419829ddc7623a309a0cad7"
        }
      ]
    }
  ]
}
