{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.33.jar",
          "url": "magiclib-1_15_2-0.5.33.jar",
          "size": 255022,
          "sha512": "a920356ea2e3f90f7146d64b9352752fea484fea4c87dcd250f3982a46f99037b59d96250c56d0aee5167406fcf4357c27df37f2c199baaabe0da27c8b6df3c0",
          "sha256": "b45d4618922aaa21e3b3725da4d3490d77c81dfdfe249143e50032f3bde7e3bd",
          "sha1": "a021c48241f72fd1189b62a25ee9b574986f9a2e",
          "md5": "078ee674bba5440a244494bdd5280a6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761404"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827449"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.33.jar",
          "url": "magiclib-1_15_2-0.5.33.jar",
          "size": 255022,
          "sha512": "a920356ea2e3f90f7146d64b9352752fea484fea4c87dcd250f3982a46f99037b59d96250c56d0aee5167406fcf4357c27df37f2c199baaabe0da27c8b6df3c0",
          "sha256": "b45d4618922aaa21e3b3725da4d3490d77c81dfdfe249143e50032f3bde7e3bd",
          "sha1": "a021c48241f72fd1189b62a25ee9b574986f9a2e",
          "md5": "078ee674bba5440a244494bdd5280a6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.33-sources.jar",
          "url": "magiclib-1_15_2-0.5.33-sources.jar",
          "size": 192475,
          "sha512": "f7880ee70e9c66ee61f87853910565d731addae2ded48e265786326bf8871b5a4e9a1890a70066ef3188f95b630641ae0089bbd6cdd89090135ed38f3d244f78",
          "sha256": "bd06bce273f8cd97d672975b757462992979614ecef26e89b17b7d9e82afb99b",
          "sha1": "2c20cebdfbc1aa2b2fd4ae107454254243fd7a4b",
          "md5": "adc40f9b9ceb60a73987c2aaaf62ea5e"
        }
      ]
    }
  ]
}
