{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.33.jar",
          "url": "magiclib-1_15_2-0.5.33.jar",
          "size": 255022,
          "sha512": "068a0ac586f6b76bdcfaa7ac89017438970b1c086ac5b73bbd6b7144ae2c05217065b2ff4e110f827c762f9d8c11f9b4d87acfd5f1a7075c5d2fdacd732eec29",
          "sha256": "7400bb77782f573500f3adb396a88aa4949c774839e66862496e1a550ef38720",
          "sha1": "cdc7d1521aa4e0a23ba5614f0d174c5af0223b41",
          "md5": "58460aecbaab7756a62aeaeff2c4f6f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761404"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827449"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.33.jar",
          "url": "magiclib-1_15_2-0.5.33.jar",
          "size": 255022,
          "sha512": "068a0ac586f6b76bdcfaa7ac89017438970b1c086ac5b73bbd6b7144ae2c05217065b2ff4e110f827c762f9d8c11f9b4d87acfd5f1a7075c5d2fdacd732eec29",
          "sha256": "7400bb77782f573500f3adb396a88aa4949c774839e66862496e1a550ef38720",
          "sha1": "cdc7d1521aa4e0a23ba5614f0d174c5af0223b41",
          "md5": "58460aecbaab7756a62aeaeff2c4f6f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.33-sources.jar",
          "url": "magiclib-1_15_2-0.5.33-sources.jar",
          "size": 192475,
          "sha512": "ef99d8fb7c194fc8f10cc69f659ac9101b9ea7f675ec35457644b0d6e828e4b1408b87c7d53b222ca02ab773c5a30b403aad8b91134a33d7b058b9ce6d56be76",
          "sha256": "0a12c13c6c3a27b83d9f78cd70cb2ce3ed0bffb1100924832ea562b9c6c11ca2",
          "sha1": "726bd7fa625015e77f8842a0d275f2f4524c5c4b",
          "md5": "a11043171ba6415f5b5e7c0706486ff0"
        }
      ]
    }
  ]
}
