{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra-1_17_1",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_17_1-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_17_1-0.7.2+32bcf58-beta.jar",
          "size": 157470,
          "sha512": "1d4ab02cb47388313a003df14b6200c4aa2d772b0ef557726b46e4ce4964dd9370136046631f1b5adc9f1b99337138cb5ebb56073c3115da0b013e924ee2b527",
          "sha256": "75ff4468475d15bdc8fabb0a40863fbf52315324b9f9e9530a11cf0beab09a1f",
          "sha1": "58249c3d0ce0ca2e8fe1803d8773dba59c1ba1f2",
          "md5": "062d49d9e07d345b2286ed29a99589ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_17_1-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_17_1-0.7.2+32bcf58-beta.jar",
          "size": 157470,
          "sha512": "1d4ab02cb47388313a003df14b6200c4aa2d772b0ef557726b46e4ce4964dd9370136046631f1b5adc9f1b99337138cb5ebb56073c3115da0b013e924ee2b527",
          "sha256": "75ff4468475d15bdc8fabb0a40863fbf52315324b9f9e9530a11cf0beab09a1f",
          "sha1": "58249c3d0ce0ca2e8fe1803d8773dba59c1ba1f2",
          "md5": "062d49d9e07d345b2286ed29a99589ca"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_17_1-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-malilib-extra-1_17_1-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 413008,
          "sha512": "c811d1eddace53334e25e3a37ec3d62faa591c6e914263c02334c4d7fdeaa36bdf3a82a69d215c895bcf833d3d8de7ce17dda2b4460e5c62d668df3aeb699bf5",
          "sha256": "51067b76d8af99197f2cc06d567b4decdbd764c3e73962ef461d83bcde1caf1d",
          "sha1": "bea0c81fbcafe37546793a4081491caea5fd1ded",
          "md5": "6eaf0700ca20798d8419f303f0fe13e8"
        }
      ]
    }
  ]
}
