{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.330+0499b91-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.1+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.330+0499b91-beta.jar",
          "url": "magiclib-1_19_4-0.7.330+0499b91-beta.jar",
          "size": 375396,
          "sha512": "293e0a4789500955617e5d91d693d94fd865745caeacc8c40d365622d1207106fc1d052523095cde4a4062cab7c9a6ba396342c73079b0afbd9427d8ef74aec9",
          "sha256": "97a19de92e39bb1f476c94178850c5ea6cb4dffd876c525251e8aef2337267f5",
          "sha1": "1d0a00171ca0ce771f1b9d487dafd5887a3d7723",
          "md5": "d7e7a5a13ed3f47710db06a5908e75c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.330+0499b91-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.1+1.19.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.2-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.330+0499b91-beta.jar",
          "url": "magiclib-1_19_4-0.7.330+0499b91-beta.jar",
          "size": 375396,
          "sha512": "293e0a4789500955617e5d91d693d94fd865745caeacc8c40d365622d1207106fc1d052523095cde4a4062cab7c9a6ba396342c73079b0afbd9427d8ef74aec9",
          "sha256": "97a19de92e39bb1f476c94178850c5ea6cb4dffd876c525251e8aef2337267f5",
          "sha1": "1d0a00171ca0ce771f1b9d487dafd5887a3d7723",
          "md5": "d7e7a5a13ed3f47710db06a5908e75c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.330+0499b91-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.330+0499b91-beta-sources.jar",
          "size": 168979,
          "sha512": "2b5d8f2dc181ed566448fe1d4d450054a53a203346c928a48c6c95247b744d4f549b543f78afc2293faca49c8705323b3ae466652cd12d080db07f41534a16ae",
          "sha256": "56b1f5e1bea215d40208d0f676549d093b37eb762687b0d87064900cf871b2ad",
          "sha1": "4f8cf947adba645e23dee8624eca707ce496ab30",
          "md5": "32f418db7f9fa97709afe4cd10a916ec"
        }
      ]
    }
  ]
}
