{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.302+8d1be4b-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.302+8d1be4b-beta.jar",
          "url": "magiclib-1_16_5-0.7.302+8d1be4b-beta.jar",
          "size": 360870,
          "sha512": "dfdce894cf31a926ceca424142abcb6ce46fb5876bc82223108f757f8fb7ce357a4f6334ea0cd8349d199976dc27fcf647954d0c2ebf9cac1bfe2d07262cdaf8",
          "sha256": "ed11b9b7e5c23dca1ff21ae7ec684ff4f3fe0363e3b3e7d16a038d999d78ecd1",
          "sha1": "ea625bfea375e37d5caf90c54fcb023fc9c3161b",
          "md5": "a75346e931290024d8e7f24e13e74956"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.302+8d1be4b-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.302+8d1be4b-beta.jar",
          "url": "magiclib-1_16_5-0.7.302+8d1be4b-beta.jar",
          "size": 360870,
          "sha512": "dfdce894cf31a926ceca424142abcb6ce46fb5876bc82223108f757f8fb7ce357a4f6334ea0cd8349d199976dc27fcf647954d0c2ebf9cac1bfe2d07262cdaf8",
          "sha256": "ed11b9b7e5c23dca1ff21ae7ec684ff4f3fe0363e3b3e7d16a038d999d78ecd1",
          "sha1": "ea625bfea375e37d5caf90c54fcb023fc9c3161b",
          "md5": "a75346e931290024d8e7f24e13e74956"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.302+8d1be4b-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.302+8d1be4b-beta-sources.jar",
          "size": 159565,
          "sha512": "5624c050d89b0e6f89cd27ba2f29a9ba036d1b383ca090adc3dbbf6c4e35cb0dbdb41bdf20a4b63b7ba27739f2bb0be63624c26f221930acd3e60a44340d2e4f",
          "sha256": "dca02e4c491f4b243b0d808a4c824d836d28609ef9a868366a52ef56bf924323",
          "sha1": "1c96e0312af64dff189eef3f232d71090a68b76f",
          "md5": "f73d83238e8c6f7357821061972c0715"
        }
      ]
    }
  ]
}
