{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_16_5",
    "version": "0.5.260+86e6882-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_16_5-0.5.260+86e6882-dev.jar",
          "url": "ommc-1_16_5-0.5.260+86e6882-dev.jar",
          "size": 1153649,
          "sha512": "b63d8cc9b7a81d8b5ffd5544a646483a695559437147aa67386b3cb77e8465e692a52a2b5984dff28bca110a9cb0c89786089a06b223b974326e452d4c05d0f2",
          "sha256": "84d0dd539bd938d802e6ae02975fb9b086dd5bb51e2fcf669756a9a40a38ad03",
          "sha1": "5e648a48ba58c19deebfde79577fef33d51b939f",
          "md5": "2a706b7d128f5d81c13e28b209c67ff2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.260+86e6882-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_16_5",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_16_5-0.5.260+86e6882-dev.jar",
          "url": "ommc-1_16_5-0.5.260+86e6882-dev.jar",
          "size": 1153649,
          "sha512": "b63d8cc9b7a81d8b5ffd5544a646483a695559437147aa67386b3cb77e8465e692a52a2b5984dff28bca110a9cb0c89786089a06b223b974326e452d4c05d0f2",
          "sha256": "84d0dd539bd938d802e6ae02975fb9b086dd5bb51e2fcf669756a9a40a38ad03",
          "sha1": "5e648a48ba58c19deebfde79577fef33d51b939f",
          "md5": "2a706b7d128f5d81c13e28b209c67ff2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
