{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.304+4912de4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_18_2-0.7.304+4912de4-beta.jar",
          "size": 360570,
          "sha512": "76414ba0bf0608913c158d41801295b27194db1c3b67f26d924e6a3697c95717070f904f5049a324e2f1a015231a6bcf3137647290de8a1a63eff10d9fab50f6",
          "sha256": "2ddf832359a550b22787a0276195eeb6f0d3aecb7410c015a0064822e5898fde",
          "sha1": "4a2b583709c08736a7d7921ec77acf97655a4ad2",
          "md5": "9c0311059980a825ad04c56dda581a72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.304+4912de4-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_18_2-0.7.304+4912de4-beta.jar",
          "size": 360570,
          "sha512": "76414ba0bf0608913c158d41801295b27194db1c3b67f26d924e6a3697c95717070f904f5049a324e2f1a015231a6bcf3137647290de8a1a63eff10d9fab50f6",
          "sha256": "2ddf832359a550b22787a0276195eeb6f0d3aecb7410c015a0064822e5898fde",
          "sha1": "4a2b583709c08736a7d7921ec77acf97655a4ad2",
          "md5": "9c0311059980a825ad04c56dda581a72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.304+4912de4-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.304+4912de4-beta-sources.jar",
          "size": 159698,
          "sha512": "e4f73c16279177a35dbe2ced018bdfdfa31943d1a9c3289d54db12ea2fdb6e1498f24a5f9e09e4b38dd883d3b30faecba28c19b1dda741b3484278d0776c2e5b",
          "sha256": "400d67ceb92b30ff116225b7533b333218cce23aff7827337912943c933ad6ea",
          "sha1": "14cdc0fda4d2a752a860596185d3343bec37113c",
          "md5": "0fced4546e522db8a8996e2d59a9452f"
        }
      ]
    }
  ]
}
