{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.313+71378a6-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.313+71378a6-beta.jar",
          "url": "magiclib-1_17_1-0.7.313+71378a6-beta.jar",
          "size": 371829,
          "sha512": "2f3ee4a0485f615935f4308ad0fbcced230a0e5b008d437740d842929fc5ad6eb3d01e0efbe9001846d90165c60d66e75cc904f4be72e2b1b9f556b150726ad8",
          "sha256": "b7b5eb483b3f28c7202e90f57800e54ddedb8d300142fe3e2f365de94230beea",
          "sha1": "8ad7e6d68ad39fdb7b10b86025aa0fe89e0d6bfe",
          "md5": "7084ca9e1d3f7e6a6c8737f0d48aa167"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.313+71378a6-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.313+71378a6-beta.jar",
          "url": "magiclib-1_17_1-0.7.313+71378a6-beta.jar",
          "size": 371829,
          "sha512": "2f3ee4a0485f615935f4308ad0fbcced230a0e5b008d437740d842929fc5ad6eb3d01e0efbe9001846d90165c60d66e75cc904f4be72e2b1b9f556b150726ad8",
          "sha256": "b7b5eb483b3f28c7202e90f57800e54ddedb8d300142fe3e2f365de94230beea",
          "sha1": "8ad7e6d68ad39fdb7b10b86025aa0fe89e0d6bfe",
          "md5": "7084ca9e1d3f7e6a6c8737f0d48aa167"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.313+71378a6-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.313+71378a6-beta-sources.jar",
          "size": 168140,
          "sha512": "6aca23444736804892e9390469e75a674153b34ab2f835300daf2eec09818fdfc34eacb0d1f8b2c656d20463d6c2b0455facfa1ce7ebc8732b42e86c7f1a48a6",
          "sha256": "979eeaa0174821c57a96386e396fc071f62bd48d88c5f621d74f53e1fa4ba40b",
          "sha1": "7b0d10a1e523f7cdcb6cd9a1f1255348ae222f8f",
          "md5": "f3f6375c22ea5ea4da3e832ae4dfa3c5"
        }
      ]
    }
  ]
}
