{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.311+83c833c-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.311+83c833c-beta.jar",
          "url": "magiclib-1_16_5-0.7.311+83c833c-beta.jar",
          "size": 373783,
          "sha512": "3d997165a2883d9ae2223c743e967989faae5b8f47dadf915a026b39c22aa383ff82ce27075a4296c0a3b122eb0bf81f9299718a6e555871cc3f00947346329a",
          "sha256": "0c348f26c85eb520781f9dd27146888fc18a3c2e9eba79340021663bc81321ab",
          "sha1": "2487ed1de2c39c9b7e98ef13a0de74576fa12dcc",
          "md5": "0c118e43ad7470b488a8cc9f1a604237"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.311+83c833c-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.311+83c833c-beta.jar",
          "url": "magiclib-1_16_5-0.7.311+83c833c-beta.jar",
          "size": 373783,
          "sha512": "3d997165a2883d9ae2223c743e967989faae5b8f47dadf915a026b39c22aa383ff82ce27075a4296c0a3b122eb0bf81f9299718a6e555871cc3f00947346329a",
          "sha256": "0c348f26c85eb520781f9dd27146888fc18a3c2e9eba79340021663bc81321ab",
          "sha1": "2487ed1de2c39c9b7e98ef13a0de74576fa12dcc",
          "md5": "0c118e43ad7470b488a8cc9f1a604237"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.311+83c833c-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.311+83c833c-beta-sources.jar",
          "size": 167967,
          "sha512": "500cceff40db1044ed14cb3159e223fa4b4c6c24fa084ae12f6240203998b183b64932ce66f0f1b0fb10597ff24a1e437740cca82135ae2c49cd81e770a9a75c",
          "sha256": "dc04654c150d305b1a539f62eacd8e52fb2bc249f706966f19ffed3b38a11e4b",
          "sha1": "b3569a1c781218c9b97349a8bbd4b78adb917516",
          "md5": "62c034e16f7a5f15ca363cec0efe2dc1"
        }
      ]
    }
  ]
}
