{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base-1_19_3",
    "version": "0.7.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.72.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_19_3-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-base-1_19_3-0.7.3+c7ba8f9-beta.jar",
          "size": 119930,
          "sha512": "096ab530103bc46290470120533b6e935b4341fa7eb1f4bf40f837b8bc687ed87bdb4de1f83b13c1aefe633f909cadaefa4587b9f2f299d3c2bc5916795114e8",
          "sha256": "9e5c6781d665077aa2dc18e8d12852bc0db122984fc099546330c61ef63fa6a3",
          "sha1": "2cccd59cc08b4dd6e9d93a5182f415fb92d6af41",
          "md5": "bc53fa0afb78e60695d6fbcb94d6785e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.72.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4215578"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_19_3-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-base-1_19_3-0.7.3+c7ba8f9-beta.jar",
          "size": 119930,
          "sha512": "096ab530103bc46290470120533b6e935b4341fa7eb1f4bf40f837b8bc687ed87bdb4de1f83b13c1aefe633f909cadaefa4587b9f2f299d3c2bc5916795114e8",
          "sha256": "9e5c6781d665077aa2dc18e8d12852bc0db122984fc099546330c61ef63fa6a3",
          "sha1": "2cccd59cc08b4dd6e9d93a5182f415fb92d6af41",
          "md5": "bc53fa0afb78e60695d6fbcb94d6785e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_19_3-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "url": "magiclib-base-1_19_3-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "size": 260414,
          "sha512": "90ae3b9c6f8d8c48cd32e7e3a8854357eb85501e5571390fdd49d4a11b56387e2508a0cd01dad30342a82423cf63ef795a2ca215a11d83751ac9cc6cceb921f2",
          "sha256": "fb3a55ac9eeafa8f12d67e1a7821187a8678e1f045a936f2ebe75a682a82856f",
          "sha1": "211c9e14633020ed694a2e5a5f6f22684017c578",
          "md5": "3954cedea147542fa4834f24af288b4f"
        }
      ]
    }
  ]
}
