{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-carpet-compat-1_16_5",
    "version": "0.2.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_16_5",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_16_5-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_16_5-0.2.2+32bcf58-beta.jar",
          "size": 144688,
          "sha512": "7f87337c05a280684933dcfad7484ee5f39a0d05fa0b34149ceb8c96ddf3f8d1f5efcde81baf6375f5472aeb8e7cc137de75d4d3eebc5c2e7429e18e5a94ba76",
          "sha256": "ca552f5860fd77ff2b8c38ca76b36c5a6c8a3d44d48e4e66fb200cfadf9a6349",
          "sha1": "b962279bb5949a8804299fb35f7a21e99f430c06",
          "md5": "fb0bdffd1b5826fd7460cbcb5aab61c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_16_5",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_16_5-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_16_5-0.2.2+32bcf58-beta.jar",
          "size": 144688,
          "sha512": "7f87337c05a280684933dcfad7484ee5f39a0d05fa0b34149ceb8c96ddf3f8d1f5efcde81baf6375f5472aeb8e7cc137de75d4d3eebc5c2e7429e18e5a94ba76",
          "sha256": "ca552f5860fd77ff2b8c38ca76b36c5a6c8a3d44d48e4e66fb200cfadf9a6349",
          "sha1": "b962279bb5949a8804299fb35f7a21e99f430c06",
          "md5": "fb0bdffd1b5826fd7460cbcb5aab61c2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_16_5",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_16_5-0.2.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-carpet-compat-1_16_5-0.2.2+32bcf58-beta-standalone-dev.jar",
          "size": 538850,
          "sha512": "fec351dee786604fd967389e8a75ef88a4ed610d5e33ed250535abf7d871fd3960fbe17e0a7890e32e79a99d68c41fa4076414f4f2ef6914b1fc24b4074b74a1",
          "sha256": "66001f417d654e211a3689f901132fde1945710e3c6575e0e34e1c081a3aec68",
          "sha1": "772c84c1634a820c0b5963b4047ea3b7db13a3cd",
          "md5": "326dbccd76c54150b74f5f4e2833a6ff"
        }
      ]
    }
  ]
}
