{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib",
    "version": "0.7.331+c783ba0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-0.7.331+c783ba0-beta.jar",
          "size": 2998667,
          "sha512": "31ac9c40f349fe408deb94099686dbb510266ee96016eb5f450265a370e0c330b957257ecb5bdbdd49809fe949b715217b47f409f326ecc70091e9fa55681354",
          "sha256": "9eb162d82ade0be421bf3a88a3a454a1dac9ea28e38f4331fc05f67a5fe2ee95",
          "sha1": "653fe1a066fa9c46d9f76880c34f02389b5d9079",
          "md5": "3e9be5c4eece80ee9b9c4be76921f94a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-0.7.331+c783ba0-beta.jar",
          "size": 2998667,
          "sha512": "31ac9c40f349fe408deb94099686dbb510266ee96016eb5f450265a370e0c330b957257ecb5bdbdd49809fe949b715217b47f409f326ecc70091e9fa55681354",
          "sha256": "9eb162d82ade0be421bf3a88a3a454a1dac9ea28e38f4331fc05f67a5fe2ee95",
          "sha1": "653fe1a066fa9c46d9f76880c34f02389b5d9079",
          "md5": "3e9be5c4eece80ee9b9c4be76921f94a"
        }
      ]
    }
  ]
}
