{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.331+c783ba0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_16_5-0.7.331+c783ba0-beta.jar",
          "size": 375225,
          "sha512": "d64f4fa31d5abea793adaf2f1c136a3a2d886a275b8452d979e5925793d6d3d7f028280944215c3f35ef9c5cbfd241948046bafbd310b24a8b8d77b6192ab98e",
          "sha256": "5d591e5e17c5b61074d26a2f003337939ad3331ae5f58f1bd764c56cd8a7991d",
          "sha1": "5c4a0b36b56a02100c1b1e4fa9fa43c14c79edca",
          "md5": "99c854eed7b1eebe82527fa172796a3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.331+c783ba0-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.16"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_16_5-0.7.331+c783ba0-beta.jar",
          "size": 375225,
          "sha512": "d64f4fa31d5abea793adaf2f1c136a3a2d886a275b8452d979e5925793d6d3d7f028280944215c3f35ef9c5cbfd241948046bafbd310b24a8b8d77b6192ab98e",
          "sha256": "5d591e5e17c5b61074d26a2f003337939ad3331ae5f58f1bd764c56cd8a7991d",
          "sha1": "5c4a0b36b56a02100c1b1e4fa9fa43c14c79edca",
          "md5": "99c854eed7b1eebe82527fa172796a3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.331+c783ba0-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.331+c783ba0-beta-sources.jar",
          "size": 168752,
          "sha512": "e87bf2b11e168dbe5573eacd2da9006bb7ef87c7d175f891c864eebb87bdffd41c8f08c82e7318b34dd13d6543dc6a1615aa085924324e554c19188fab2617b6",
          "sha256": "8f8a9d7565402030d2c5ebab335d391ddfd070f207d675af6a4931e611266d9d",
          "sha1": "9a3fdb90ecabfd6095030fcd1b52e7c51375e11c",
          "md5": "169968a1e798dd81d93bef705f98e487"
        }
      ]
    }
  ]
}
