{
  "formatVersion": "1.1",
  "component": {
    "group": "fi.dy.masa",
    "module": "malilib",
    "version": "23w14a-0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "malilib-23w14a-0.16.0.jar",
          "url": "malilib-23w14a-0.16.0.jar",
          "size": 540171,
          "sha512": "51478cde5d31afb7b80ce35668c7203a19553da6b8bd184496a93c13cb9452d9943efc10d195f04ce9d9aac68abef60e83a83cb917047835dd5b7ea6b243b81b",
          "sha256": "70e6ba2fafc5fd0719b5eb8e61ea7c804c3b52b174254646f877633510840833",
          "sha1": "1a1e6e91a68096ac29d9020134838c9f4a8c86a6",
          "md5": "2fd1b32837d62b501b67313b4521b0eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.11.0+938a1d56ff"
          }
        }
      ],
      "files": [
        {
          "name": "malilib-23w14a-0.16.0.jar",
          "url": "malilib-23w14a-0.16.0.jar",
          "size": 540171,
          "sha512": "51478cde5d31afb7b80ce35668c7203a19553da6b8bd184496a93c13cb9452d9943efc10d195f04ce9d9aac68abef60e83a83cb917047835dd5b7ea6b243b81b",
          "sha256": "70e6ba2fafc5fd0719b5eb8e61ea7c804c3b52b174254646f877633510840833",
          "sha1": "1a1e6e91a68096ac29d9020134838c9f4a8c86a6",
          "md5": "2fd1b32837d62b501b67313b4521b0eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "malilib-23w14a-0.16.0-sources.jar",
          "url": "malilib-23w14a-0.16.0-sources.jar",
          "size": 266576,
          "sha512": "77da5acc8d341662623f0cf25f6cf460bfa8daaaa77e26906bde6e9d595e423f63ab517e5ecf7722c2d34f6953e40e9e5caaa2b452947d245f5d88f1718e8730",
          "sha256": "1e97ea63470143b6103d665b6a84175e2a2de0a6c1e9e652d456f370436e470f",
          "sha1": "93f1cc6747a12ce2a4d377fd18ef994c1cc06209",
          "md5": "04346a81c087a7a9d470f877e1268f86"
        }
      ]
    }
  ]
}
