{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.337+67c250a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_16_5-0.7.337+67c250a-beta.jar",
          "size": 379648,
          "sha512": "f0cea03471fbf87726a7abf14edde7365d62ce2d32d44fc866e0acb454c3c10deff04cce5d639ecfe64d92e736cad1c0d2cb3f9007ab573e78ed6ec32ce4b331",
          "sha256": "a2c88a463ea0b8bc63b934f522d8cc665cebcdcd4f3fc9229a7ceeb84a1de3e5",
          "sha1": "8c7bc3f8247bd2ff7a68342e05a33f2e2b01343e",
          "md5": "6592fb0f86f775bae708d2f0f4abf22f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.337+67c250a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.16"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_16_5-0.7.337+67c250a-beta.jar",
          "size": 379648,
          "sha512": "f0cea03471fbf87726a7abf14edde7365d62ce2d32d44fc866e0acb454c3c10deff04cce5d639ecfe64d92e736cad1c0d2cb3f9007ab573e78ed6ec32ce4b331",
          "sha256": "a2c88a463ea0b8bc63b934f522d8cc665cebcdcd4f3fc9229a7ceeb84a1de3e5",
          "sha1": "8c7bc3f8247bd2ff7a68342e05a33f2e2b01343e",
          "md5": "6592fb0f86f775bae708d2f0f4abf22f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.337+67c250a-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.337+67c250a-beta-sources.jar",
          "size": 169663,
          "sha512": "c34da4c349c75681838d012289b2566a15db81a8cadaff01e39a1e739fe6270982c9ac466ac60cce99ff2e66a3677a7b84d8febae0b15edc904590cca8e237be",
          "sha256": "f8b6c284dc0e60ea136022c8fd5e7c0dea1e8373c95f16cc32003dae4c097383",
          "sha1": "64084e2bbeb751b14ea705bcd59f07aa898991e6",
          "md5": "b1cd0aa40e6b326c620fe5453bfcc195"
        }
      ]
    }
  ]
}
