{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base-1_16_5",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_16_5-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_16_5-0.7.2+32bcf58-beta.jar",
          "size": 119659,
          "sha512": "df975e1bb3602834bcbb51e855e98d45326b2066ff7b91bec2795965dedc2f5434b7d3a43eb14cb80f4a0171bf87af60436d0351c512629be7411f71d0fb6a31",
          "sha256": "a88d5f1f488cdf0bc22ae414dfc239259362446173d6249bf110298f3b0196b6",
          "sha1": "0e7cd562c0ea9727b646ccbb8ae755785783f355",
          "md5": "8cf16084cf74f4f88b5aa96b73a5f2a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_16_5-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_16_5-0.7.2+32bcf58-beta.jar",
          "size": 119659,
          "sha512": "df975e1bb3602834bcbb51e855e98d45326b2066ff7b91bec2795965dedc2f5434b7d3a43eb14cb80f4a0171bf87af60436d0351c512629be7411f71d0fb6a31",
          "sha256": "a88d5f1f488cdf0bc22ae414dfc239259362446173d6249bf110298f3b0196b6",
          "sha1": "0e7cd562c0ea9727b646ccbb8ae755785783f355",
          "md5": "8cf16084cf74f4f88b5aa96b73a5f2a2"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_16_5-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-base-1_16_5-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 260112,
          "sha512": "bb366c2f38b8545cea26571cecd0307cb361ffa28b7d1c46bb476864d5b4cd5aafa55d454b3ad14107c3b511a6b9c57f50af2eae8bfe2a3dbde75c8b24c11529",
          "sha256": "2786246c9947fa34427c25fd84951652f82b24840d6c613fb4c6b6d919553b69",
          "sha1": "ac8adec2af59ea6257ace64764b60077b5ae05dd",
          "md5": "3926259bcb3d804397a65ff8042cf96c"
        }
      ]
    }
  ]
}
