{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.337+67c250a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_18_2-0.7.337+67c250a-beta.jar",
          "size": 379300,
          "sha512": "beea7b93e170e5953be07d1957a7157f104ea13c2a1c5a4c4b410b86e52a2b373cbe00d35595fbc21b87aaea6014f3021249d0daff93e8ed5fa9306db4c8d291",
          "sha256": "ae0950876c69018da3bf62792ef10a0736d41793a0a22ec25ad35156de07dcb8",
          "sha1": "8c770f555b9fcaf4d91b5d4149c13c0d6be3f0b9",
          "md5": "270cc68b98659cfdff847a1571338fa6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.337+67c250a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.2-fabric1.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_18_2-0.7.337+67c250a-beta.jar",
          "size": 379300,
          "sha512": "beea7b93e170e5953be07d1957a7157f104ea13c2a1c5a4c4b410b86e52a2b373cbe00d35595fbc21b87aaea6014f3021249d0daff93e8ed5fa9306db4c8d291",
          "sha256": "ae0950876c69018da3bf62792ef10a0736d41793a0a22ec25ad35156de07dcb8",
          "sha1": "8c770f555b9fcaf4d91b5d4149c13c0d6be3f0b9",
          "md5": "270cc68b98659cfdff847a1571338fa6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.337+67c250a-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.337+67c250a-beta-sources.jar",
          "size": 169844,
          "sha512": "1dd722cc09efa0639c2fde100e70026d5f7a079c1278c8e2eae7d85fa2175d6b6ab7f58411600e96bec671c1a3bafc4e81c5df3a035fcc85fd506d32d93e19db",
          "sha256": "99ee4e5fb198f40796b3dad0a9d1d18e24259702fe423e7eb8f51c5f889e5710",
          "sha1": "dacfbb9484270b399e617aedbd8b261604928e4c",
          "md5": "949b1c3ead1593a5ada760c2bc0389b2"
        }
      ]
    }
  ]
}
