{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.305+183e2ea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_16_5-0.7.305+183e2ea-beta.jar",
          "size": 360870,
          "sha512": "e7c951240b7c0bb1d94fc08ba9549f0df7e9dd11942f01774b1d7e0bd1a908490d9d6a1ab98f1355107c79c9a38e3db6408badfe3fb8c7ee5f283cb30ed01f89",
          "sha256": "79ab041a8cf363846e4f79c1f323fc6ffab656ce43de50171d20d47852619cfb",
          "sha1": "b2b5accd861780f401d07616bff4afa786fdcaaf",
          "md5": "68a75c0459bdbe45953fc72d4cb19acb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.305+183e2ea-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_16_5-0.7.305+183e2ea-beta.jar",
          "size": 360870,
          "sha512": "e7c951240b7c0bb1d94fc08ba9549f0df7e9dd11942f01774b1d7e0bd1a908490d9d6a1ab98f1355107c79c9a38e3db6408badfe3fb8c7ee5f283cb30ed01f89",
          "sha256": "79ab041a8cf363846e4f79c1f323fc6ffab656ce43de50171d20d47852619cfb",
          "sha1": "b2b5accd861780f401d07616bff4afa786fdcaaf",
          "md5": "68a75c0459bdbe45953fc72d4cb19acb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.305+183e2ea-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.305+183e2ea-beta-sources.jar",
          "size": 159565,
          "sha512": "0273b0d12a69ceb49fe524c5bf4f10145064b9bd5d2a7c3f719fbc205bc7ac3b3c5a8f39c0b3f2f769dd1d5d85817aa5c8a9743a91af7b427dc9a577ae3a131a",
          "sha256": "bdb13d1fee09c31fb2bcca70b579eaac6c6628e6726873ecb9ae95e85c01ec60",
          "sha1": "ad3c2b1ed3db17830f0581f49f65304c00bb0b8f",
          "md5": "b0ac08476afabf387bbb33a7a8f71e91"
        }
      ]
    }
  ]
}
