{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.329+ed83ba7-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.329+ed83ba7-beta.jar",
          "url": "magiclib-1_19_2-0.7.329+ed83ba7-beta.jar",
          "size": 375965,
          "sha512": "d7230467abe46baef4df73ce0e0c47bd48818f27e9c7ea4bc02775f5b75bbc13f740fcd49dbfd046a1113c0524afbe92652297c69d84d78acbf7aefbf4bcb97e",
          "sha256": "710b1fcb58465b200e47a4252cf0cc85adf0093eb1dc00037fd46c1655335cd5",
          "sha1": "984c4166141e65dbf50f778132e0ab117ab3ec70",
          "md5": "8cf290612eefcf0bd70999189cd6b95f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.329+ed83ba7-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.2-1.4.84+v221018"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "4.2.0-beta.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.329+ed83ba7-beta.jar",
          "url": "magiclib-1_19_2-0.7.329+ed83ba7-beta.jar",
          "size": 375965,
          "sha512": "d7230467abe46baef4df73ce0e0c47bd48818f27e9c7ea4bc02775f5b75bbc13f740fcd49dbfd046a1113c0524afbe92652297c69d84d78acbf7aefbf4bcb97e",
          "sha256": "710b1fcb58465b200e47a4252cf0cc85adf0093eb1dc00037fd46c1655335cd5",
          "sha1": "984c4166141e65dbf50f778132e0ab117ab3ec70",
          "md5": "8cf290612eefcf0bd70999189cd6b95f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.329+ed83ba7-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.329+ed83ba7-beta-sources.jar",
          "size": 168858,
          "sha512": "6c6159f16950d913ea18602a101ac7c71d2af8d799cb2c11a75ffc8977cdfcdc347db2f4d4a09f2bd3e36f742c602159b4604eabe609cb3f7b900ba53bb6fdc5",
          "sha256": "9d896ffcf7fa879c10884145fc2bde9771b6a0df5cce56d3acfbba5cd7824629",
          "sha1": "08147a9db876faf1a482c04e2c19019f40281a4b",
          "md5": "5d98a66f71cc2d4af0497dbbca749399"
        }
      ]
    }
  ]
}
