{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.322+57464f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.80.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.322+57464f9-beta.jar",
          "url": "magiclib-1_19_4-0.7.322+57464f9-beta.jar",
          "size": 374114,
          "sha512": "ed6c91a8d8f9a1c64ab065b64d0ef9d7efc3ceecd861aaba81d29d5f3ea7227b187be81716510a25d121945acdf362cf5149a05fa08515a907e48e006538e24b",
          "sha256": "90d411dcf0889d3984f1bbdf98eca7c71e839ef8a1bff0ba64318b3b8a2d5cc9",
          "sha1": "03c3d80e8643e3fe92be15bbd327d4c4fb72355a",
          "md5": "a83fe8c21ce835c11663380e8d971120"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.322+57464f9-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.80.0+1.19.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.2-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.322+57464f9-beta.jar",
          "url": "magiclib-1_19_4-0.7.322+57464f9-beta.jar",
          "size": 374114,
          "sha512": "ed6c91a8d8f9a1c64ab065b64d0ef9d7efc3ceecd861aaba81d29d5f3ea7227b187be81716510a25d121945acdf362cf5149a05fa08515a907e48e006538e24b",
          "sha256": "90d411dcf0889d3984f1bbdf98eca7c71e839ef8a1bff0ba64318b3b8a2d5cc9",
          "sha1": "03c3d80e8643e3fe92be15bbd327d4c4fb72355a",
          "md5": "a83fe8c21ce835c11663380e8d971120"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.322+57464f9-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.322+57464f9-beta-sources.jar",
          "size": 168472,
          "sha512": "152effc19fc2aa264f792c5c4e714738c8b533ff8fb988ebaabebbe004a448ff815242dd84b53e7909e33a9a714c70d3b71735afddb04fbc6199a1f63228ca1c",
          "sha256": "f20d082baa431bb9e1ed190351ab9075307fe5d6e1b5561b4d7bc42f12df84ca",
          "sha1": "2db4cad0ac97ba84544f2334772afc8c8dc85cce",
          "md5": "fa0f2ec59bb59841b9af395287337156"
        }
      ]
    }
  ]
}
