{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.305+183e2ea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_18_2-0.7.305+183e2ea-beta.jar",
          "size": 360570,
          "sha512": "f84d75e999863a18e7c8bedba6e159dce9c874edeee7f4a1e6b9d262a05b131e44a943930b2b471e2cde4eb0b52f8c201e49565cbf41094644705a66b373ede4",
          "sha256": "311eb33b28389474e11d1683e4b337869bb7dae7b0fb8adec69b56823cc38b2c",
          "sha1": "c83649111fc419de44e700b379466d87c2ec8f80",
          "md5": "2e122dae205f9de32b0c165379420636"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.305+183e2ea-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_18_2-0.7.305+183e2ea-beta.jar",
          "size": 360570,
          "sha512": "f84d75e999863a18e7c8bedba6e159dce9c874edeee7f4a1e6b9d262a05b131e44a943930b2b471e2cde4eb0b52f8c201e49565cbf41094644705a66b373ede4",
          "sha256": "311eb33b28389474e11d1683e4b337869bb7dae7b0fb8adec69b56823cc38b2c",
          "sha1": "c83649111fc419de44e700b379466d87c2ec8f80",
          "md5": "2e122dae205f9de32b0c165379420636"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.305+183e2ea-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.305+183e2ea-beta-sources.jar",
          "size": 159697,
          "sha512": "5378b3bb7e6ea9cdcc34277676e791c71e0563c4f2f01411d65a12ef4f7686a24e6a442b455e30fdc447a1d483f6a176be143fc011480f16c025a44f15b94b59",
          "sha256": "1d16fad8cfee483fdc564ca56c4f881d737ce17d580a2e67f44e4f8e60dd7bfa",
          "sha1": "f534702a901facb5491c190bb89ab8c51be8b901",
          "md5": "93198bc0a6a11059a612e9626d3ee70f"
        }
      ]
    }
  ]
}
