{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.283+320fdb8-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-1_19_2-0.7.283+320fdb8-beta.jar",
          "size": 361670,
          "sha512": "13b8a5ffbef5bb602840f49b1065989a691366f091af272ecf09f59a6f4ef7ee0bf5be1d765d471f718a63479dcb4e5ff4a0d33b72df1a74a0684ce42b5a351a",
          "sha256": "27bd7bc9c6fd0b0c211c58ee5a3d0a43e9f537cbdb06d6835b21fd1a846d453f",
          "sha1": "880cf91a6ed2eb2ad2dc435f4981705d69aa6271",
          "md5": "7e2ae8ce49a8b05a2dfeabf248c90cbe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-1_19_2-0.7.283+320fdb8-beta.jar",
          "size": 361670,
          "sha512": "13b8a5ffbef5bb602840f49b1065989a691366f091af272ecf09f59a6f4ef7ee0bf5be1d765d471f718a63479dcb4e5ff4a0d33b72df1a74a0684ce42b5a351a",
          "sha256": "27bd7bc9c6fd0b0c211c58ee5a3d0a43e9f537cbdb06d6835b21fd1a846d453f",
          "sha1": "880cf91a6ed2eb2ad2dc435f4981705d69aa6271",
          "md5": "7e2ae8ce49a8b05a2dfeabf248c90cbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.283+320fdb8-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.283+320fdb8-beta-sources.jar",
          "size": 159456,
          "sha512": "dfe0dcbb24589c450363b8b8e9d7a48390cad326ccd850fe86a3f62205ce14b7ccae490ec9c767d20e436c0b9d60a52bf9e4431eb9a1630988c17ac6e96ee44f",
          "sha256": "6ad9f7a34d673158ea6a632840742999020a9229485feaaaab7a4902fef281c1",
          "sha1": "01f7792a8b506374ed8a86b30cbdd148876fa4ef",
          "md5": "d8782e08cfaa5bac76f519d490dc983f"
        }
      ]
    }
  ]
}
