{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-core",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.12"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-core-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-core-0.7.2+32bcf58-beta.jar",
          "size": 146237,
          "sha512": "5fa16f6cd33695a2386a5b8a2655840f65ff735ed8c06a7310d4c7ebbeaced9fcd0549509b0d13a8ab5fffdb5abac9472810de4e9747c71d425951fe8740ae80",
          "sha256": "a1b6cd7615dc64da379fb6650fb68d9545dda440341216ee28dbee69afae8871",
          "sha1": "e83b1b9c2f4142d12c73245912e12c0b40f67e22",
          "md5": "77a70c31121c99b90ce86d4d033926dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.12"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-core-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-core-0.7.2+32bcf58-beta.jar",
          "size": 146237,
          "sha512": "5fa16f6cd33695a2386a5b8a2655840f65ff735ed8c06a7310d4c7ebbeaced9fcd0549509b0d13a8ab5fffdb5abac9472810de4e9747c71d425951fe8740ae80",
          "sha256": "a1b6cd7615dc64da379fb6650fb68d9545dda440341216ee28dbee69afae8871",
          "sha1": "e83b1b9c2f4142d12c73245912e12c0b40f67e22",
          "md5": "77a70c31121c99b90ce86d4d033926dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-core-0.7.2+32bcf58-beta-sources.jar",
          "url": "magiclib-core-0.7.2+32bcf58-beta-sources.jar",
          "size": 28467,
          "sha512": "1286a3cad690d3264ce4a2de4d157d0c4633d46148ffa5b911fecc63cd6f185424b2bed210ded40f70756ed3e610cfb81855b5d9dc0d434bccab97090b3d05c6",
          "sha256": "2d277d92f9ac8b8cdc498244e626c8abc8d8632fc8e4342d42704fe029d1d8f1",
          "sha1": "5acd1acb131249d16f7eaab68efedee3888f4e09",
          "md5": "952e53883bb6a0de801fea842914aaee"
        }
      ]
    }
  ]
}
