{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra-1_18_2",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_18_2",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_18_2-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_18_2-0.7.2+32bcf58-beta.jar",
          "size": 159602,
          "sha512": "29f124232828beeab7b281f54b11acf60fbaa85dd5347e4b23bbe268eef2d9e7556145e73540b08f459c751ae1187ba326612a9d7faa25a06fb8b9da20d0a499",
          "sha256": "890980faf000b96f0b84254c26be361450ccbb60c2c45c04bc935f674f78c409",
          "sha1": "5c7b797ddebdf452db7c9dcd04cc533abfaf3273",
          "md5": "6165ee232ba3b0ce9cce68ad53929484"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_18_2",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_18_2-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_18_2-0.7.2+32bcf58-beta.jar",
          "size": 159602,
          "sha512": "29f124232828beeab7b281f54b11acf60fbaa85dd5347e4b23bbe268eef2d9e7556145e73540b08f459c751ae1187ba326612a9d7faa25a06fb8b9da20d0a499",
          "sha256": "890980faf000b96f0b84254c26be361450ccbb60c2c45c04bc935f674f78c409",
          "sha1": "5c7b797ddebdf452db7c9dcd04cc533abfaf3273",
          "md5": "6165ee232ba3b0ce9cce68ad53929484"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_18_2",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_18_2-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-malilib-extra-1_18_2-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 415079,
          "sha512": "fe3631c6f671f44d23b462f2fc27271b3d486f2b8fb6401c4cda601931047f80c70218ceb955463880f5c1b6575a03c2d352f531d7f65359af1150e6f4fa7a3b",
          "sha256": "95ff07c04b81c7e157cd7a952496f4c600660ec77becc948a3bc2f0dcd7d944c",
          "sha1": "78b36151e090587fe8390aa5eb6778999f878b1f",
          "md5": "c2aa461f0456c975e78e8f6696ef5582"
        }
      ]
    }
  ]
}
