{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.331+c783ba0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.1+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_19_4-0.7.331+c783ba0-beta.jar",
          "size": 375395,
          "sha512": "be3634d3d6946554d1ca0c6ca552ecf590e412b9177a064c5eadc50d5de2ef997738a386d4263cd42e060d4f523d1de4d7ea2485d6954d9712dae74d087066a2",
          "sha256": "08170e93cfb811b28351142c5b521855f5c5b5fdfb4f4f574fc2ff154bec4b2b",
          "sha1": "284e828ca396c0bc656c6e8e3b6924fa42ea6a62",
          "md5": "4c6a179b8b66e41cbfd10b256fb44ac9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.331+c783ba0-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.1+1.19.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.2-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_19_4-0.7.331+c783ba0-beta.jar",
          "size": 375395,
          "sha512": "be3634d3d6946554d1ca0c6ca552ecf590e412b9177a064c5eadc50d5de2ef997738a386d4263cd42e060d4f523d1de4d7ea2485d6954d9712dae74d087066a2",
          "sha256": "08170e93cfb811b28351142c5b521855f5c5b5fdfb4f4f574fc2ff154bec4b2b",
          "sha1": "284e828ca396c0bc656c6e8e3b6924fa42ea6a62",
          "md5": "4c6a179b8b66e41cbfd10b256fb44ac9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.331+c783ba0-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.331+c783ba0-beta-sources.jar",
          "size": 168979,
          "sha512": "aa8b670cb01be10b10f9fe0d49ede609e3a8186f2be842676d8560faa1cabe267f9b1f0c66a254f5479b5a69dc5f2c46c1ea4f0b40a154bfbf12f961d6df24a1",
          "sha256": "d63b85aa10d408e4df5629afa44af61d5f77c88eeb1ed7d01814d0a89481b968",
          "sha1": "67eebc1ba0513d8c16ef7e5c05e8771d81a847ea",
          "md5": "16973e2ccf545cbbfd21f781c2b4512f"
        }
      ]
    }
  ]
}
