{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.5.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.12.jar",
          "url": "magiclib-1_14_4-0.5.12.jar",
          "size": 260373,
          "sha512": "0600ffecb8078dced924625977fe000efdbdba869efad6dd3d97c0293d37ef60c7c339cca8da6642dc88d5cc64f636164983a9a16afe6b7e50a532639de6cf17",
          "sha256": "6cfdbfe5c547a96a6a43cd8ac6ca4285ebcb9b2b5d057a58b2a29f39df7c691d",
          "sha1": "eae354ee5fb79bf3eb01057d4435e6de7c01bca0",
          "md5": "d0cafb9da3bcf56b637cfea3c79633f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.12"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493805"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.12.jar",
          "url": "magiclib-1_14_4-0.5.12.jar",
          "size": 260373,
          "sha512": "0600ffecb8078dced924625977fe000efdbdba869efad6dd3d97c0293d37ef60c7c339cca8da6642dc88d5cc64f636164983a9a16afe6b7e50a532639de6cf17",
          "sha256": "6cfdbfe5c547a96a6a43cd8ac6ca4285ebcb9b2b5d057a58b2a29f39df7c691d",
          "sha1": "eae354ee5fb79bf3eb01057d4435e6de7c01bca0",
          "md5": "d0cafb9da3bcf56b637cfea3c79633f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.12-sources.jar",
          "url": "magiclib-1_14_4-0.5.12-sources.jar",
          "size": 190977,
          "sha512": "a48b95642b698a474fab8fc2f82339905409fb7addef8319eb70264a1f1b9850c397e34b47c5f43464f23302ba11b355ff8005869af280eb81d3ec3b624ef4a8",
          "sha256": "e3fa5306f6e489f5810359cfad1b0aeb2f5d63fcd03c1bf3e53880fd9d3a8e33",
          "sha1": "fb67c218047221a309919d01caba0578d78fcd09",
          "md5": "a5a470d38ee98eb04dcaeb4dbd788263"
        }
      ]
    }
  ]
}
