{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.7.318+85c565a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.10.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.318+85c565a-beta.jar",
          "url": "magiclib-1_15_2-0.7.318+85c565a-beta.jar",
          "size": 371956,
          "sha512": "6e3c12abbac68290c9f2f663d2a627f3ee14ffd334c8f5a910689dcd970eef249c49ea2ad741203abd9a602985e7c013ab6624b4e42bb6c01db694d7fd935820",
          "sha256": "b7200be8d317d2ae34d8dddb2dcecef13e44112ee9b5546f96582209663440b4",
          "sha1": "0188e855a7d6d3acaa0b73dce7e330d0d171b9b9",
          "md5": "5bad9f33fc4095882c5deae77da4ea6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.318+85c565a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.8"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.10.7"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "cloth-config",
          "version": {
            "requires": "2.14.2+fabric"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.15"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.318+85c565a-beta.jar",
          "url": "magiclib-1_15_2-0.7.318+85c565a-beta.jar",
          "size": 371956,
          "sha512": "6e3c12abbac68290c9f2f663d2a627f3ee14ffd334c8f5a910689dcd970eef249c49ea2ad741203abd9a602985e7c013ab6624b4e42bb6c01db694d7fd935820",
          "sha256": "b7200be8d317d2ae34d8dddb2dcecef13e44112ee9b5546f96582209663440b4",
          "sha1": "0188e855a7d6d3acaa0b73dce7e330d0d171b9b9",
          "md5": "5bad9f33fc4095882c5deae77da4ea6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.7.318+85c565a-beta-sources.jar",
          "url": "magiclib-1_15_2-0.7.318+85c565a-beta-sources.jar",
          "size": 167856,
          "sha512": "18f7fba40b5d856d035b0ac61c67da35cee223c7ab0a0210ca99967521d1307d03d6ca06ca54bfb0e8c57accf7a4e592cf797f1ddf271ecb91495ab7c0c8990b",
          "sha256": "9c6b3f79360bfae32280bfc1ac9f988cf87334e797faedc58ee2a2c0be6b5650",
          "sha1": "557c0458edf704a3255a4845c594550c1a5d7091",
          "md5": "893124996481a55030da4f39b9c7b415"
        }
      ]
    }
  ]
}
