{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra-1_14_4",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_14_4",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_14_4-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_14_4-0.7.2+32bcf58-beta.jar",
          "size": 157464,
          "sha512": "8170ddde4ef5822d445270402ca6743478f56a5de1b30804ae3e581c55aa3fe1a15bd8ae656b6769e9264c8f5d73b1ceefb589ea81c868f3f3e60476a2960221",
          "sha256": "d737546e6f2f6e7b57ca35e708f47493ae029553723abb2f56ab9e6968eec913",
          "sha1": "7c7cb57da9992dc7cca7b724dd52b33d9542a3b6",
          "md5": "efec17c3a8c4b4b96685ddee946e6ead"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_14_4",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_14_4-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_14_4-0.7.2+32bcf58-beta.jar",
          "size": 157464,
          "sha512": "8170ddde4ef5822d445270402ca6743478f56a5de1b30804ae3e581c55aa3fe1a15bd8ae656b6769e9264c8f5d73b1ceefb589ea81c868f3f3e60476a2960221",
          "sha256": "d737546e6f2f6e7b57ca35e708f47493ae029553723abb2f56ab9e6968eec913",
          "sha1": "7c7cb57da9992dc7cca7b724dd52b33d9542a3b6",
          "md5": "efec17c3a8c4b4b96685ddee946e6ead"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_14_4",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_14_4-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-malilib-extra-1_14_4-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 412590,
          "sha512": "3f159a5ac7c164b6d9dd308104d3b4f78b3c6a73d3f48592c397741eecaf511f323263065cad3619fb42da0fe569addf866de4b8971ae35241787559a19f55a7",
          "sha256": "092639d01f9ffb0a828b1db77c00ae6c48aebfb9d8e132c928ab760560ec7912",
          "sha1": "d0b1be3ca5058ed7a5092c269d3ca6dd822c0215",
          "md5": "8c068289fba39372cdaa69b603ca6781"
        }
      ]
    }
  ]
}
