{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.5.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.55.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.31.jar",
          "url": "magiclib-1_18_2-0.5.31.jar",
          "size": 254294,
          "sha512": "bde3a3aae321f1656eabefd47d8f6a4e99be3d02b5e19b23d04bae8611584103a840758d218f29a74067b44560a587f07414149067bedefab27522bea3952e75",
          "sha256": "1fda068f3b340d581af84387c1f00c320c9572e290552ef2794a8f935c0a7682",
          "sha1": "7704c71662696f79cbfc7f75d99b34803ece9302",
          "md5": "8720d6e04b776bfa4fdd4ba7c2a0a6fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.31"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.55.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3545107"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.31.jar",
          "url": "magiclib-1_18_2-0.5.31.jar",
          "size": 254294,
          "sha512": "bde3a3aae321f1656eabefd47d8f6a4e99be3d02b5e19b23d04bae8611584103a840758d218f29a74067b44560a587f07414149067bedefab27522bea3952e75",
          "sha256": "1fda068f3b340d581af84387c1f00c320c9572e290552ef2794a8f935c0a7682",
          "sha1": "7704c71662696f79cbfc7f75d99b34803ece9302",
          "md5": "8720d6e04b776bfa4fdd4ba7c2a0a6fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.31-sources.jar",
          "url": "magiclib-1_18_2-0.5.31-sources.jar",
          "size": 192538,
          "sha512": "fb9502f19752e7adbe8ad85d85ad8a516b8b6e9b53b50d353952047d7deb176db52b9aeab2c3798e89e80b7e102ed98a189a36e230dd4f5ad55319f677910102",
          "sha256": "62fe9496e6f883327c8f13362d3371d889fae9b6c57a8b0b41366189a16d7c9d",
          "sha1": "24013fe314701c607a54b6293f154ff08d930111",
          "md5": "04aa360bf9a212393157a52a4a200f4b"
        }
      ]
    }
  ]
}
