{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.6.187+90f47cd-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3030941"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.6.187+90f47cd-beta.jar",
          "url": "magiclib-1_15_2-0.6.187+90f47cd-beta.jar",
          "size": 319168,
          "sha512": "4d7a2b92fc25955c1a996c7430a44aaac056bd2afe0057bc1d3c71793db97c3b156d555bc52dc8be3a2c369a4c61b4116e0d2f0926b5932899f4f3ebf08715f0",
          "sha256": "12364df676c5f990c6570807310b53240ffa68057b0ea2c03f8c8d2185bc54e6",
          "sha1": "7cea6f42b57c7922b7353537b23014089c94bdb3",
          "md5": "7a5efd22db472e90aae0079998f8a1ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.187+90f47cd-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3030941"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761404"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827449"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.6.187+90f47cd-beta.jar",
          "url": "magiclib-1_15_2-0.6.187+90f47cd-beta.jar",
          "size": 319168,
          "sha512": "4d7a2b92fc25955c1a996c7430a44aaac056bd2afe0057bc1d3c71793db97c3b156d555bc52dc8be3a2c369a4c61b4116e0d2f0926b5932899f4f3ebf08715f0",
          "sha256": "12364df676c5f990c6570807310b53240ffa68057b0ea2c03f8c8d2185bc54e6",
          "sha1": "7cea6f42b57c7922b7353537b23014089c94bdb3",
          "md5": "7a5efd22db472e90aae0079998f8a1ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.6.187+90f47cd-beta-sources.jar",
          "url": "magiclib-1_15_2-0.6.187+90f47cd-beta-sources.jar",
          "size": 225216,
          "sha512": "1d1f9dffd42893759b0ceb614a5f7735d1e19a88ccf5fe19b90e9569b03ae82d3c342931ff672cdb03d8adcf1affc21c33bbc8526d8eb58ff63ed9fef89fb7f4",
          "sha256": "8fabcf75d045586a0bb4841cd563252c1e1b7eb58f57c8ea615f77351a5fadcf",
          "sha1": "55394fa189f8e7b5be2413d52a6d1c88807dd6d8",
          "md5": "8d9ea8234cce7aa7d26e2f4c07338f0a"
        }
      ]
    }
  ]
}
