{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.308+d9af2fc-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_17_1-0.7.308+d9af2fc-beta.jar",
          "size": 369743,
          "sha512": "ac8be6697ce82569c68d4ea1397acd0519691c4ec8f414b1bbe7b6971b4879487a6224cf34db0f92b321914a21d8a5e89e1266ff62e97872ad07000535319df9",
          "sha256": "7aba8d006df91c6e1a0b795c2b1d1874bc69cb84af38ec6f5fd88c7a3fa68724",
          "sha1": "c90c0781cd5623da5df078dce6a93ec6f9edbaad",
          "md5": "86b9cde531e3d8080bea68d3ef027689"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.308+d9af2fc-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_17_1-0.7.308+d9af2fc-beta.jar",
          "size": 369743,
          "sha512": "ac8be6697ce82569c68d4ea1397acd0519691c4ec8f414b1bbe7b6971b4879487a6224cf34db0f92b321914a21d8a5e89e1266ff62e97872ad07000535319df9",
          "sha256": "7aba8d006df91c6e1a0b795c2b1d1874bc69cb84af38ec6f5fd88c7a3fa68724",
          "sha1": "c90c0781cd5623da5df078dce6a93ec6f9edbaad",
          "md5": "86b9cde531e3d8080bea68d3ef027689"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.308+d9af2fc-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.308+d9af2fc-beta-sources.jar",
          "size": 166797,
          "sha512": "7f05173b56838c52219e8e37b1749e8c825ee7291a18b9dcdb82c6ca19b47dbb4e2f9c6f5074538328963d8709218caf6b5be5e224000b3bddaaef885d71cbf8",
          "sha256": "181384be7b19be3c2b0a0b5cfd03c4ae76be878dd5145cb0519c74e45cb6b116",
          "sha1": "8fcc4927b639ce54e9ecc67335aa5a8920dc5fb2",
          "md5": "824cd1db5c93ad191e3dc1d5b3f4cef6"
        }
      ]
    }
  ]
}
