{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.321+3d981a5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_17_1-0.7.321+3d981a5-beta.jar",
          "size": 372071,
          "sha512": "c0ddade9e0f8703a81f639b25bd20416c4b1695328c4a0731d79ac9c60fe1eda762870792bd7801b34ca7e1c5c87360441c4a14be037d1e1bd7ef71a01f7c599",
          "sha256": "66acdef359d4a755bbb795fcbf6610e707aaa8f2a92e70badd4d586aa9371d6d",
          "sha1": "4d362a33b313a089def001b8bcb4d94dbca81777",
          "md5": "87e22b9ead9eb78aca28f9496a7da664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.321+3d981a5-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_17_1-0.7.321+3d981a5-beta.jar",
          "size": 372071,
          "sha512": "c0ddade9e0f8703a81f639b25bd20416c4b1695328c4a0731d79ac9c60fe1eda762870792bd7801b34ca7e1c5c87360441c4a14be037d1e1bd7ef71a01f7c599",
          "sha256": "66acdef359d4a755bbb795fcbf6610e707aaa8f2a92e70badd4d586aa9371d6d",
          "sha1": "4d362a33b313a089def001b8bcb4d94dbca81777",
          "md5": "87e22b9ead9eb78aca28f9496a7da664"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.321+3d981a5-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.321+3d981a5-beta-sources.jar",
          "size": 168456,
          "sha512": "0f943ccf60f5c0ba10ab6030a6ae1814003fd04eec2e0e25c0672891a0acc079ae4826bf2b21a5d34ed62a10ada8c1ca352a3e7d28f7933fb9b705b8b33783fd",
          "sha256": "f55ab951fdef69a66f2e0f2bde9d745607be60fe5268cdf1c9eaa74ff667fe11",
          "sha1": "dbb6e99f10be7cd15c432010987c4642dae9530f",
          "md5": "63fe3edfc71fe92a8e8373de00af4d8c"
        }
      ]
    }
  ]
}
