{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.322+57464f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.322+57464f9-beta.jar",
          "url": "magiclib-1_17_1-0.7.322+57464f9-beta.jar",
          "size": 372040,
          "sha512": "070d7e6f5ddc394594e16a6b6d57c719bc44c428c36427c6dcd53b435395dbccbb2b8399a078d040a1b255a518488cca504fc9fa66d2ebdfffeec5601a21a9c0",
          "sha256": "3273c2d1a2b9c40b9ba576af1c76631e45807a7adcc17a0c67ae3fe92aac78fb",
          "sha1": "4d8f7452d9882569ed7ddb9bdf9485ca6debf71f",
          "md5": "77b8a312acdc2e412fa88198728b324f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.322+57464f9-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.322+57464f9-beta.jar",
          "url": "magiclib-1_17_1-0.7.322+57464f9-beta.jar",
          "size": 372040,
          "sha512": "070d7e6f5ddc394594e16a6b6d57c719bc44c428c36427c6dcd53b435395dbccbb2b8399a078d040a1b255a518488cca504fc9fa66d2ebdfffeec5601a21a9c0",
          "sha256": "3273c2d1a2b9c40b9ba576af1c76631e45807a7adcc17a0c67ae3fe92aac78fb",
          "sha1": "4d8f7452d9882569ed7ddb9bdf9485ca6debf71f",
          "md5": "77b8a312acdc2e412fa88198728b324f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.322+57464f9-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.322+57464f9-beta-sources.jar",
          "size": 168420,
          "sha512": "024984767fae4b9950612bd43bd445a4d16c17bb81cfa4cf3a8349ed6a527f26ea42cfe13451cfadb5d9348808631aaf1c8985353420a7524c0c3fec6d82ac3a",
          "sha256": "334f7dbb95ffaa5c478f292bd741c5f21a3657e9ccc011ac22012225fd4da477",
          "sha1": "c9b8cd9ed65d2cb60158a503d8ecb6f832df316b",
          "md5": "ad1fe45b22ef2153d5bd1cd4332272c4"
        }
      ]
    }
  ]
}
