{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.305+183e2ea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_19_4-0.7.305+183e2ea-beta.jar",
          "size": 360782,
          "sha512": "48018a522b27bfb3594bab9d93bcfb0317a9f0a9c88468da5659056be94fe6e46ba480bce4705c2484e30a74eacc97f8cce842517d5ef960471b53d6feaa7dba",
          "sha256": "9498a0f9874a346040e0fb69afe050c20daa6ce5932d1b7d1c8b88edff04c4b7",
          "sha1": "c0190acffbd0332d212ea624c1f7af670f45abf1",
          "md5": "d326412b1265cbb989ec56c707b1a921"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.305+183e2ea-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.305+183e2ea-beta.jar",
          "url": "magiclib-1_19_4-0.7.305+183e2ea-beta.jar",
          "size": 360782,
          "sha512": "48018a522b27bfb3594bab9d93bcfb0317a9f0a9c88468da5659056be94fe6e46ba480bce4705c2484e30a74eacc97f8cce842517d5ef960471b53d6feaa7dba",
          "sha256": "9498a0f9874a346040e0fb69afe050c20daa6ce5932d1b7d1c8b88edff04c4b7",
          "sha1": "c0190acffbd0332d212ea624c1f7af670f45abf1",
          "md5": "d326412b1265cbb989ec56c707b1a921"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.305+183e2ea-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.305+183e2ea-beta-sources.jar",
          "size": 159774,
          "sha512": "32fdb0ef6ab579ad35c2462426e3e4fedf043bc1d8284798554f04a37c46183d3efd02f8717934f7af4e51d30581e765c357552a9bbe39ee1b004cc462ecff12",
          "sha256": "998f736c685acd5b0d63989e21c06fc14c9fee76301999ad386362e7d114c53d",
          "sha1": "e6919d1e3f10a2a67da32a75f672370129059a1c",
          "md5": "7ce2777987acbbb87646c6d339cb0563"
        }
      ]
    }
  ]
}
