{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.327+dfd83d3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.327+dfd83d3-beta.jar",
          "url": "magiclib-1_18_2-0.7.327+dfd83d3-beta.jar",
          "size": 374882,
          "sha512": "e1e3f2a0501a77613ca0a389707ed89a5387b345715b077c5332b428c9dde59fca1f3bc5d6cf40b727cdc6fb1c02356c2ab0e1e13f28bc6ade4a94ad8bd4f26e",
          "sha256": "ecb02a24344fd33dd6009a27bbe1f7000483b0c241ef2162e4ab08f773c53e87",
          "sha1": "847c3485de8cb2f4c4ba7b0183a34abafe190815",
          "md5": "6e717cf09873e75b6d48880e88505862"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.327+dfd83d3-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.327+dfd83d3-beta.jar",
          "url": "magiclib-1_18_2-0.7.327+dfd83d3-beta.jar",
          "size": 374882,
          "sha512": "e1e3f2a0501a77613ca0a389707ed89a5387b345715b077c5332b428c9dde59fca1f3bc5d6cf40b727cdc6fb1c02356c2ab0e1e13f28bc6ade4a94ad8bd4f26e",
          "sha256": "ecb02a24344fd33dd6009a27bbe1f7000483b0c241ef2162e4ab08f773c53e87",
          "sha1": "847c3485de8cb2f4c4ba7b0183a34abafe190815",
          "md5": "6e717cf09873e75b6d48880e88505862"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.327+dfd83d3-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.327+dfd83d3-beta-sources.jar",
          "size": 168941,
          "sha512": "a2d781479e94697dba45ffbe0777b2dc75d95d3b09c529368aad81be03ebb73f5db5e7f0d6484c33afe047e97607835834d5c5c12b49d29981ec9a7edbad02e2",
          "sha256": "78bd96cb2bc74666fb08899cfb3e7478eb4a86030c390f465971494985ddaee1",
          "sha1": "3c0a028e7873c5a319cb33d696aa7ab6f6f9fac0",
          "md5": "2dafaba797f2224cfe316f9b4ee27e70"
        }
      ]
    }
  ]
}
