{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.5.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.31.jar",
          "url": "magiclib-1_15_2-0.5.31.jar",
          "size": 254861,
          "sha512": "3e10261a5b3f77f9a943d2c75cf199100f356c9a6c15f5b56eab86b9e70cead529b308cdff1ba104b3bff6dc1f01345beaef1c8f2141a48fd46e194cb062307e",
          "sha256": "73ca6845b8f1aec8009b60da54dcb53e01d5b1f6b7bba1a80cd47faf4cb8e644",
          "sha1": "acd00d6c5d4baade8175f28b82cdf469ce84ec20",
          "md5": "363c6936a383b73a046c3a5b1d1b890e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.31"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493807"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.31.jar",
          "url": "magiclib-1_15_2-0.5.31.jar",
          "size": 254861,
          "sha512": "3e10261a5b3f77f9a943d2c75cf199100f356c9a6c15f5b56eab86b9e70cead529b308cdff1ba104b3bff6dc1f01345beaef1c8f2141a48fd46e194cb062307e",
          "sha256": "73ca6845b8f1aec8009b60da54dcb53e01d5b1f6b7bba1a80cd47faf4cb8e644",
          "sha1": "acd00d6c5d4baade8175f28b82cdf469ce84ec20",
          "md5": "363c6936a383b73a046c3a5b1d1b890e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.31-sources.jar",
          "url": "magiclib-1_15_2-0.5.31-sources.jar",
          "size": 192296,
          "sha512": "2d53b1dcf8e892109244084d178308511d718c90f6860347e2ef3280c67db2b72956a900ec8cf1c0f2ce4d0b4de4695f4632ad6833e8d4900ce3ded42da6c2ba",
          "sha256": "f59b0cd59b9887c66b64378d781975ee3937a9c35e1b3361d27632f265137381",
          "sha1": "7115cffe5eb7c100866c98f106293c2d563a016a",
          "md5": "ba0f03dcfc85ea4abf7f25eec06bfe0e"
        }
      ]
    }
  ]
}
