{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_15_2",
    "version": "0.5.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.31.jar",
          "url": "magiclib-1_15_2-0.5.31.jar",
          "size": 254861,
          "sha512": "3184d0c3a96cc3e2a6738edb525059fce45fe5567400d334d1fb81fd22de3c4e0a827fb8610c8853f5443bbb519658e29dede3f3d7885360808aa595ca3a8140",
          "sha256": "f4ad47b2d526a59b149cc10a7a0737f5222689d289fba295fe1fda25650e33e8",
          "sha1": "0f65ad11fb4fd7faada799b7457b343bf5dd64b7",
          "md5": "23afea38b9569361249973bb68d7b5ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.31"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2942271"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3271693"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493807"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.31.jar",
          "url": "magiclib-1_15_2-0.5.31.jar",
          "size": 254861,
          "sha512": "3184d0c3a96cc3e2a6738edb525059fce45fe5567400d334d1fb81fd22de3c4e0a827fb8610c8853f5443bbb519658e29dede3f3d7885360808aa595ca3a8140",
          "sha256": "f4ad47b2d526a59b149cc10a7a0737f5222689d289fba295fe1fda25650e33e8",
          "sha1": "0f65ad11fb4fd7faada799b7457b343bf5dd64b7",
          "md5": "23afea38b9569361249973bb68d7b5ed"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_15_2-0.5.31-sources.jar",
          "url": "magiclib-1_15_2-0.5.31-sources.jar",
          "size": 192296,
          "sha512": "5af88410d0afe4758825cca9371af0ed767dfc8634b6ba8ca75c34e326d3ce4bcb15c6fd7f1994ddc63aa25ad3790f7708ff83603b860a023567a17cb8b3c791",
          "sha256": "506a941b0cac97c6d43c4e8a7aad82900d257f888a8493d137b588a780b28d48",
          "sha1": "57de216f6fcfa265a3b5b67916f0648252f8e9bf",
          "md5": "55230217ed68b33a235aa1e86b01fd39"
        }
      ]
    }
  ]
}
