{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.6.191+b8dbc1a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.191+b8dbc1a-beta.jar",
          "url": "magiclib-1_16_5-0.6.191+b8dbc1a-beta.jar",
          "size": 328339,
          "sha512": "60b10916c8dbeac2daa2c77528fcb1382dac9e745a2b81c14845d3e9fbcc4ad6ac68465d5cc40d18ac5d78aefcf84fe75ae34f722507f09c01a571e2029319f7",
          "sha256": "c0ae15eb667a778158c4cef6067d5814a3b4d97156ae5ec5193d68423059ecdf",
          "sha1": "ad82f8a30788e62a660910a3bb2cb97e87ad077e",
          "md5": "14605878ccb91996eb9e7e10c1b1637d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.191+b8dbc1a-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827450"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.191+b8dbc1a-beta.jar",
          "url": "magiclib-1_16_5-0.6.191+b8dbc1a-beta.jar",
          "size": 328339,
          "sha512": "60b10916c8dbeac2daa2c77528fcb1382dac9e745a2b81c14845d3e9fbcc4ad6ac68465d5cc40d18ac5d78aefcf84fe75ae34f722507f09c01a571e2029319f7",
          "sha256": "c0ae15eb667a778158c4cef6067d5814a3b4d97156ae5ec5193d68423059ecdf",
          "sha1": "ad82f8a30788e62a660910a3bb2cb97e87ad077e",
          "md5": "14605878ccb91996eb9e7e10c1b1637d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.191+b8dbc1a-beta-sources.jar",
          "url": "magiclib-1_16_5-0.6.191+b8dbc1a-beta-sources.jar",
          "size": 229527,
          "sha512": "f7b98209fa19820d203e203a73825515b048f788acd31afbed40ec0d152f648e70b30c90be23a0c071c3176f17b3f44d0d2ce54f10bea0342c766fbbd3a73f9d",
          "sha256": "89d66fa51bb03c080af280e78997c383d30a979f8cae4e6d09d0369a39dd2cd1",
          "sha1": "b0f0133f01c444e89a3ea6bd2ac84e28aa2f0e43",
          "md5": "31f188733980c9b2488f4dcab219263a"
        }
      ]
    }
  ]
}
