{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-minecraft-compat-1_17_1",
    "version": "0.5.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_17_1-0.5.2+32bcf58-beta.jar",
          "url": "magiclib-minecraft-compat-1_17_1-0.5.2+32bcf58-beta.jar",
          "size": 142140,
          "sha512": "33b2ec565463459b13d0cabffd516c0c84916f751e19c67598c441ca6234c30e8f856763520f960365bc05be5e9e80dbbfac208b9cc538496e1886e2d20321ff",
          "sha256": "a5f6f063bf5ea80fd8b3ac62b4e41b1c3c6545fc2bcab8ddf0176776a1ab7cb2",
          "sha1": "b7417b4a73d2f8df31c7dc6cb772680bd1cd4b90",
          "md5": "4c9e845baa55bfc4aac2e85a3129eff3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_17_1-0.5.2+32bcf58-beta.jar",
          "url": "magiclib-minecraft-compat-1_17_1-0.5.2+32bcf58-beta.jar",
          "size": 142140,
          "sha512": "33b2ec565463459b13d0cabffd516c0c84916f751e19c67598c441ca6234c30e8f856763520f960365bc05be5e9e80dbbfac208b9cc538496e1886e2d20321ff",
          "sha256": "a5f6f063bf5ea80fd8b3ac62b4e41b1c3c6545fc2bcab8ddf0176776a1ab7cb2",
          "sha1": "b7417b4a73d2f8df31c7dc6cb772680bd1cd4b90",
          "md5": "4c9e845baa55bfc4aac2e85a3129eff3"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_17_1-0.5.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-minecraft-compat-1_17_1-0.5.2+32bcf58-beta-standalone-dev.jar",
          "size": 395383,
          "sha512": "f2190b310fffd7c591c094e67e54671e329e7db55fb526634f2ee1e10ccf71d1e963fbf8b346a783c2f5f90dead8ed4687f02f7a3ef09ed3c71832d7db921f2d",
          "sha256": "d88038b77b30543b12aa9325373e793933db9718d528cd667e7bfbfd13e1c8b3",
          "sha1": "1cf5e05a6c01020152efb5a7601c715084017ee0",
          "md5": "d7c64265dc9fdc5604099eb9ba5be777"
        }
      ]
    }
  ]
}
