{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.304+4912de4-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_19_3-0.7.304+4912de4-beta.jar",
          "size": 360738,
          "sha512": "fe6dfc9c5d775ea1d615890a29179994d2e1386fadccf7f32ec7fcb1515fa3ba9a9dc08979a069ea2cbf8dbe7336fa8b04923741d624cc4267e0a6749f04d2d3",
          "sha256": "f71988db920fa1a055df723969025a21bc5fc09f2b9d048f4a16166a7d768903",
          "sha1": "e67761d978117c9ceee57c9f48d5746ef6f985af",
          "md5": "acede2671377fcafdc7030672ee22387"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.304+4912de4-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.304+4912de4-beta.jar",
          "url": "magiclib-1_19_3-0.7.304+4912de4-beta.jar",
          "size": 360738,
          "sha512": "fe6dfc9c5d775ea1d615890a29179994d2e1386fadccf7f32ec7fcb1515fa3ba9a9dc08979a069ea2cbf8dbe7336fa8b04923741d624cc4267e0a6749f04d2d3",
          "sha256": "f71988db920fa1a055df723969025a21bc5fc09f2b9d048f4a16166a7d768903",
          "sha1": "e67761d978117c9ceee57c9f48d5746ef6f985af",
          "md5": "acede2671377fcafdc7030672ee22387"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.304+4912de4-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.304+4912de4-beta-sources.jar",
          "size": 159767,
          "sha512": "413ee3f59cd54175c95f75ba4628b5cd68749e7a7ccdfcc7d5724e2331fa4f3a935c12d4d053faa18612cf7c6a39f5ceaaa37660ef660d899a680514848c029d",
          "sha256": "9946b2e34130470655b6036d352a72a66b32016170e23ae3bd3824b5cf6332dc",
          "sha1": "9dc2f3b043d51214f11816347cd893e30e18db3f",
          "md5": "81c5cdc633b12622594bbba092b75c49"
        }
      ]
    }
  ]
}
