{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.326+2b20e19-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.326+2b20e19-beta.jar",
          "url": "magiclib-1_17_1-0.7.326+2b20e19-beta.jar",
          "size": 373278,
          "sha512": "6bf599ce6f66a9ff5e6e8b0e8039760ed0fedf6f83a6eeeeea6404bf90a4ab945deb417eb93ab51aab9d63438043fb53fe71b5622d33ed4060cae76e006b884b",
          "sha256": "81ed3823c610d11d8edeb0578f8a9be51c98f4f45a6a72ebb787ee905930fa0d",
          "sha1": "2f373b6750f2978dd59a08ae37da97816f842be0",
          "md5": "f8aa724bb92a2c29cfafb24953e292f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.326+2b20e19-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.326+2b20e19-beta.jar",
          "url": "magiclib-1_17_1-0.7.326+2b20e19-beta.jar",
          "size": 373278,
          "sha512": "6bf599ce6f66a9ff5e6e8b0e8039760ed0fedf6f83a6eeeeea6404bf90a4ab945deb417eb93ab51aab9d63438043fb53fe71b5622d33ed4060cae76e006b884b",
          "sha256": "81ed3823c610d11d8edeb0578f8a9be51c98f4f45a6a72ebb787ee905930fa0d",
          "sha1": "2f373b6750f2978dd59a08ae37da97816f842be0",
          "md5": "f8aa724bb92a2c29cfafb24953e292f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.326+2b20e19-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.326+2b20e19-beta-sources.jar",
          "size": 168932,
          "sha512": "0fd77d126f7f0f55c9efd08cd6656b359c31e5812d721f8614fc689059bf5928e29b9f2df153ec8a09407e9f7dd27cafe8af6f36d1ea13e74a5d76a98bccc6e3",
          "sha256": "33fefbcae65422e68ad556830fb2619d41d9f9d351dec70df0af9105f91ec05b",
          "sha1": "4a742204876a0646ba52fee59a53a24b3da990c8",
          "md5": "c18226fef2a918db6210874e31b889ba"
        }
      ]
    }
  ]
}
