{
  "formatVersion": "1.1",
  "component": {
    "group": "fi.dy.masa",
    "module": "minihud",
    "version": "1.20-pre5-0.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "minihud-1.20-pre5-0.27.0.jar",
          "url": "minihud-1.20-pre5-0.27.0.jar",
          "size": 336590,
          "sha512": "8fd0f23e7af432eeacdb570194237478ffbbf01f6882c173c35cf30c50eb9ceff40b98d61b16b9de179e23abfe375d5382e4de672e40feedccc881eae7dfa9ec",
          "sha256": "42e2534009798f03ceea06bfce82b701fe521d4ac750a0509cb8e93b9822cbca",
          "sha1": "ba27d123a6c2b9d5361ee92ad4e1d6b18589b6e0",
          "md5": "62f130fd463188c21601154430e0df2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "fi.dy.masa.malilib",
          "module": "malilib-fabric-1.20-pre5",
          "version": {
            "requires": "0.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "minihud-1.20-pre5-0.27.0.jar",
          "url": "minihud-1.20-pre5-0.27.0.jar",
          "size": 336590,
          "sha512": "8fd0f23e7af432eeacdb570194237478ffbbf01f6882c173c35cf30c50eb9ceff40b98d61b16b9de179e23abfe375d5382e4de672e40feedccc881eae7dfa9ec",
          "sha256": "42e2534009798f03ceea06bfce82b701fe521d4ac750a0509cb8e93b9822cbca",
          "sha1": "ba27d123a6c2b9d5361ee92ad4e1d6b18589b6e0",
          "md5": "62f130fd463188c21601154430e0df2e"
        }
      ]
    }
  ]
}
