{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.308+d9af2fc-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_18_2-0.7.308+d9af2fc-beta.jar",
          "size": 371344,
          "sha512": "bfd0125444c6f4022315a085f7b35f91c0a89d4bee6cfce536b068e908a847976ce0fd6a1240970a9b2da0dcc6b39bb81a7e4531e3af6b7e5d9e5dc1caad1738",
          "sha256": "cfe46be0fa8d3f0dce9b75f246c47e1e834cf2d767f26c67fc40926c1bfb0637",
          "sha1": "24b4fd3a9cecc126f816ac4a3d651c177eb9c41b",
          "md5": "55a3d9bfc3a61d34b1b1c2f8d9246e82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.308+d9af2fc-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.308+d9af2fc-beta.jar",
          "url": "magiclib-1_18_2-0.7.308+d9af2fc-beta.jar",
          "size": 371344,
          "sha512": "bfd0125444c6f4022315a085f7b35f91c0a89d4bee6cfce536b068e908a847976ce0fd6a1240970a9b2da0dcc6b39bb81a7e4531e3af6b7e5d9e5dc1caad1738",
          "sha256": "cfe46be0fa8d3f0dce9b75f246c47e1e834cf2d767f26c67fc40926c1bfb0637",
          "sha1": "24b4fd3a9cecc126f816ac4a3d651c177eb9c41b",
          "md5": "55a3d9bfc3a61d34b1b1c2f8d9246e82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.308+d9af2fc-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.308+d9af2fc-beta-sources.jar",
          "size": 166807,
          "sha512": "c993ea93469662dc77bbb3311324eb75b33a9ab7345f4b1135116626e753d458bd56ea4384455df6ad753a7330057d50b33d563abf6a4fcfe56c8f1cf040287b",
          "sha256": "2ff34ad128296cd5d3f4ab492e41a7af4f27b43c4f76de1b16e2e4fb14a509e5",
          "sha1": "5ac5dcfa50624ea028771ab62d62f43fea357378",
          "md5": "b552f19b839dd01302e60335ee3d08fe"
        }
      ]
    }
  ]
}
