{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.321+3d981a5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_18_2-0.7.321+3d981a5-beta.jar",
          "size": 373676,
          "sha512": "77f6aefc9f85dbb1a8d464d00e4bd7b81bb8f11ad8fe6eabb5459e0fb50ba200fa9d3405c2a14ad079ddcae5317a1087617aaf0e3dbd1fd9e295740aa2431e2a",
          "sha256": "b2f0c50f4284dac16d78d29d2c20c2b4e4c69c6c43e29fb6b02705e403894368",
          "sha1": "9d8e8a690985748f36a3fac6192f01ceb030da0e",
          "md5": "de873731e609c15786a697859c5fc433"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.321+3d981a5-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.321+3d981a5-beta.jar",
          "url": "magiclib-1_18_2-0.7.321+3d981a5-beta.jar",
          "size": 373676,
          "sha512": "77f6aefc9f85dbb1a8d464d00e4bd7b81bb8f11ad8fe6eabb5459e0fb50ba200fa9d3405c2a14ad079ddcae5317a1087617aaf0e3dbd1fd9e295740aa2431e2a",
          "sha256": "b2f0c50f4284dac16d78d29d2c20c2b4e4c69c6c43e29fb6b02705e403894368",
          "sha1": "9d8e8a690985748f36a3fac6192f01ceb030da0e",
          "md5": "de873731e609c15786a697859c5fc433"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.321+3d981a5-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.321+3d981a5-beta-sources.jar",
          "size": 168466,
          "sha512": "7edb14946e36d6fdde5dd68f2389f04a34e81e67263c22e886f335073ea78dbf5bc2e43e561e33a2b4260114772179ec6232480cd75c072afe86d66a1ab27f5a",
          "sha256": "dd7792d80b0a02af66935d48508153da27d4cccac3597acce2eefa87287725e6",
          "sha1": "9b6b33907290bdff3b53bd07ca4d79c203ca648b",
          "md5": "677f4aea0cc00dfb1a4653756149473f"
        }
      ]
    }
  ]
}
