{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.5.40",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.66.0+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4065495"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.40.jar",
          "url": "magiclib-1_18_2-0.5.40.jar",
          "size": 254453,
          "sha512": "98815b835389c3cd9da236a4e00006083d77895cdf7eeaf74498dce8a459cacf361987e226c17e3022e2412b36bfa754a635f39cb89bdbddd2916dc7dc64c49a",
          "sha256": "18f212b036defca60bf0df97e740936c08081d73366668ee5ae82ddd66a38920",
          "sha1": "3ce9713c2977e8404ad74542f36cb9ade840c9d3",
          "md5": "2bbf0bbf1131e9dc0b953170a0f8447b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.40"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.66.0+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4065495"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.40.jar",
          "url": "magiclib-1_18_2-0.5.40.jar",
          "size": 254453,
          "sha512": "98815b835389c3cd9da236a4e00006083d77895cdf7eeaf74498dce8a459cacf361987e226c17e3022e2412b36bfa754a635f39cb89bdbddd2916dc7dc64c49a",
          "sha256": "18f212b036defca60bf0df97e740936c08081d73366668ee5ae82ddd66a38920",
          "sha1": "3ce9713c2977e8404ad74542f36cb9ade840c9d3",
          "md5": "2bbf0bbf1131e9dc0b953170a0f8447b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.40-sources.jar",
          "url": "magiclib-1_18_2-0.5.40-sources.jar",
          "size": 192713,
          "sha512": "732f18e9245617590ead9bc111cca89fb88b526b830cfef825bf4ea051e9838f2189a7fc865f3ad1ea5b8a51f38b712d46484dab05ea8703b86369a380ead0a9",
          "sha256": "53f52be2e251d6cf87a711884da88dd7bcd826079fee3ae790ab64e7db279235",
          "sha1": "2431c9b38982a9982d9a2bc1eac36e1d63168461",
          "md5": "ce83dc94963ad9a7037e45979345570b"
        }
      ]
    }
  ]
}
