{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_14_4",
    "version": "0.5.36",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.36.jar",
          "url": "magiclib-1_14_4-0.5.36.jar",
          "size": 270405,
          "sha512": "00f119262be4bffeaf64b4439dcd02ac70e2abc3c5acec61981e8ad90cdacb172b19e58db6d27da5978500bcbf7a5b212fa8eb8088f84ae9bc19442571abd22f",
          "sha256": "f1750bde64c50b9388496f059505934b394a2dfbd6c3284cef58df6b9dab6d30",
          "sha1": "6b93a1dc26b41f62ec88800965d97bd1e6bfabe7",
          "md5": "e022dd2ed2f8abf5edcf7b5ac65170ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.36"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.14"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "2876325"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3121565"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2921052"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761403"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827447"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159393"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.36.jar",
          "url": "magiclib-1_14_4-0.5.36.jar",
          "size": 270405,
          "sha512": "00f119262be4bffeaf64b4439dcd02ac70e2abc3c5acec61981e8ad90cdacb172b19e58db6d27da5978500bcbf7a5b212fa8eb8088f84ae9bc19442571abd22f",
          "sha256": "f1750bde64c50b9388496f059505934b394a2dfbd6c3284cef58df6b9dab6d30",
          "sha1": "6b93a1dc26b41f62ec88800965d97bd1e6bfabe7",
          "md5": "e022dd2ed2f8abf5edcf7b5ac65170ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_14_4-0.5.36-sources.jar",
          "url": "magiclib-1_14_4-0.5.36-sources.jar",
          "size": 198259,
          "sha512": "33f7bc51cb9a902b1091228fe2ec675d23d490cc41a5de4fc5833c11cddd17925f838e6658bd76451b14c08b234d86ee5b41a36f55429879d544b7df94e0d0c0",
          "sha256": "2f0acad5287d4de26bd176093ec69d9cb8c8b972e1ae0cc036fbe41527bd8b33",
          "sha1": "6c62e39dc6c300a870c1a2622813805defb6bf36",
          "md5": "1d5bc2f94ad5e0d4e1dc841c9187a475"
        }
      ]
    }
  ]
}
