{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.5.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.14.jar",
          "url": "magiclib-1_18_2-0.5.14.jar",
          "size": 246575,
          "sha512": "da197628bdd83e7f592f08bcfa9037199d63f060fca035d293794bcd0343852f43e844b07dff35ffbfca5fd0b1b08adc74c0b75592dcfe413611578ab9ff07fe",
          "sha256": "5f4fa5a40fc2224e9256976cbbac6c2fd52af71345feabfbbd9e0853d1ebf9e8",
          "sha1": "adca6a344f1614169499d8a56671ddff5c294254",
          "md5": "18ae4dc9d7d7e39ca5669a8694bedd32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3545107"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.14.jar",
          "url": "magiclib-1_18_2-0.5.14.jar",
          "size": 246575,
          "sha512": "da197628bdd83e7f592f08bcfa9037199d63f060fca035d293794bcd0343852f43e844b07dff35ffbfca5fd0b1b08adc74c0b75592dcfe413611578ab9ff07fe",
          "sha256": "5f4fa5a40fc2224e9256976cbbac6c2fd52af71345feabfbbd9e0853d1ebf9e8",
          "sha1": "adca6a344f1614169499d8a56671ddff5c294254",
          "md5": "18ae4dc9d7d7e39ca5669a8694bedd32"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.14-sources.jar",
          "url": "magiclib-1_18_2-0.5.14-sources.jar",
          "size": 186602,
          "sha512": "cde0383113a0dab1ce92065babd3048eada9a28041848e279793e6d278400e18ab812ffc27a7fb78cfb0650a68f8070a39026b6deb9b37d37b743ae3d955a350",
          "sha256": "011b660a1c70fccbe8d4c1567b80b8a79ceb581a7c395792318f9ebe518750a8",
          "sha1": "8359a55de70ac6b2017cd57bb6908f3bd474e209",
          "md5": "d0667abade906c5fee5e38789163a54d"
        }
      ]
    }
  ]
}
