{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-0.5.33.jar",
          "url": "magiclib-0.5.33.jar",
          "size": 1421977,
          "sha512": "26862f16285e770ceeb888205237d5a7b75e8995d1f843de6bb42f27981ba963ae0f07c49ede5a0879f5da227b19e95b8c9e6b553666fd1d70f54ead0ecdd321",
          "sha256": "c774a297302e3bd4e36c0350a7b6c2bdfdb870fe01b23d91629fa8e590dbcf42",
          "sha1": "e52ad01e1c228e11d155edbefac5169223497db0",
          "md5": "3e89f7c4bc886edf80408c4f314ca36b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-0.5.33.jar",
          "url": "magiclib-0.5.33.jar",
          "size": 1421977,
          "sha512": "26862f16285e770ceeb888205237d5a7b75e8995d1f843de6bb42f27981ba963ae0f07c49ede5a0879f5da227b19e95b8c9e6b553666fd1d70f54ead0ecdd321",
          "sha256": "c774a297302e3bd4e36c0350a7b6c2bdfdb870fe01b23d91629fa8e590dbcf42",
          "sha1": "e52ad01e1c228e11d155edbefac5169223497db0",
          "md5": "3e89f7c4bc886edf80408c4f314ca36b"
        }
      ]
    }
  ]
}
