{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-0.5.33.jar",
          "url": "magiclib-0.5.33.jar",
          "size": 1422397,
          "sha512": "3a26f351c1326a21e3685a3d53d9b8ed5a776c4557e59e545842a2b815054ffdaaeeb45b3fd04365ef0b9b8c68c19ba1df18829240bfe01b201d9666b18089d5",
          "sha256": "36817448c3d6101d9aa3111c3bcb410ef0cd8417e1b592c91e81f6c233e51e25",
          "sha1": "68968117f6b3ea8b423eac29e7cbd0b72a7e0f1e",
          "md5": "91f2b51f8473cc8fc4499481d822d638"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-0.5.33.jar",
          "url": "magiclib-0.5.33.jar",
          "size": 1422397,
          "sha512": "3a26f351c1326a21e3685a3d53d9b8ed5a776c4557e59e545842a2b815054ffdaaeeb45b3fd04365ef0b9b8c68c19ba1df18829240bfe01b201d9666b18089d5",
          "sha256": "36817448c3d6101d9aa3111c3bcb410ef0cd8417e1b592c91e81f6c233e51e25",
          "sha1": "68968117f6b3ea8b423eac29e7cbd0b72a7e0f1e",
          "md5": "91f2b51f8473cc8fc4499481d822d638"
        }
      ]
    }
  ]
}
