{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.33.jar",
          "url": "magiclib-1_16_5-0.5.33.jar",
          "size": 255404,
          "sha512": "a563967e48303d8dd8f7eb60facdebeca80fae4572ece77d81abc24b7f48ddf23cbbb6f499b90059da59e76ffc04e61c421a7cfef8ce23f8c821ab9d7121dea7",
          "sha256": "c226c7afbd1f70951550590ca3d6e3fea11c2a5eccd98a95eb0378f349ea3567",
          "sha1": "7dec9eab92d537be4d32cf3cd5a580bf2929b744",
          "md5": "26cd8b2e76f1dd5ad8899d7864fb1b3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827450"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.33.jar",
          "url": "magiclib-1_16_5-0.5.33.jar",
          "size": 255404,
          "sha512": "a563967e48303d8dd8f7eb60facdebeca80fae4572ece77d81abc24b7f48ddf23cbbb6f499b90059da59e76ffc04e61c421a7cfef8ce23f8c821ab9d7121dea7",
          "sha256": "c226c7afbd1f70951550590ca3d6e3fea11c2a5eccd98a95eb0378f349ea3567",
          "sha1": "7dec9eab92d537be4d32cf3cd5a580bf2929b744",
          "md5": "26cd8b2e76f1dd5ad8899d7864fb1b3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.33-sources.jar",
          "url": "magiclib-1_16_5-0.5.33-sources.jar",
          "size": 192633,
          "sha512": "7a032128d35f5a142ba7fd22ef69ef728a60f286d8076f81ae61e5afa82034057db43aaf709da1aa5b435c6053a1eed4f2273f8b9405451ab1de183467b0c68b",
          "sha256": "907cdf3fbc0fb5af31c27703de5e3178f929f3e702570992ca3ca36136dfe762",
          "sha1": "377aa18c2807655beb68cc939a0f2cab65e7687d",
          "md5": "ece6de216cd4830494a361af362ba022"
        }
      ]
    }
  ]
}
