{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.33.jar",
          "url": "magiclib-1_16_5-0.5.33.jar",
          "size": 255404,
          "sha512": "9badd3e147343d1278b191361de6b25723ab31ff87f2c297f50667224c851fc3dd5785beecbb088d6fdff08e18c5f118e84f3af619724db727b15820825f3d4a",
          "sha256": "0fabc9501f03f60e5daf9f52c2daa42ce990d0324ddabba5c6248d1c91c5412b",
          "sha1": "9ac05c1d7134006dccb12bd783d6c1e144a7c8bd",
          "md5": "b79eb46a5e3280b8f2d44789527f9657"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827450"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.33.jar",
          "url": "magiclib-1_16_5-0.5.33.jar",
          "size": 255404,
          "sha512": "9badd3e147343d1278b191361de6b25723ab31ff87f2c297f50667224c851fc3dd5785beecbb088d6fdff08e18c5f118e84f3af619724db727b15820825f3d4a",
          "sha256": "0fabc9501f03f60e5daf9f52c2daa42ce990d0324ddabba5c6248d1c91c5412b",
          "sha1": "9ac05c1d7134006dccb12bd783d6c1e144a7c8bd",
          "md5": "b79eb46a5e3280b8f2d44789527f9657"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.5.33-sources.jar",
          "url": "magiclib-1_16_5-0.5.33-sources.jar",
          "size": 192633,
          "sha512": "bc19330a98d466642a2ffa8722a2b83eaa2153677ebdeaf0e1b5e04b537904ed2f8cd0355460428264cf13ae1a04be026f04fcd664ded2448a1b8744acad50a4",
          "sha256": "05f527723bd7becc0c13393c09e7df0577ee34070d7b8304c794d4b8ff2424bf",
          "sha1": "878a7a9281844c6c882ee1813c9533660c348a74",
          "md5": "ae0b5aa97d2808b8950f6ccebf3d01f5"
        }
      ]
    }
  ]
}
