{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.336+05361cf-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.1+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.336+05361cf-beta.jar",
          "url": "magiclib-1_19_4-0.7.336+05361cf-beta.jar",
          "size": 379798,
          "sha512": "72193b613c459179e215fbcc41a400bf8ad40cd3f9e4e55a92c7d0083b9ad96e9f7426277a374ccbeb4d56294fc353cf79f80523cc78d8d8e41df693d0aa24d6",
          "sha256": "8a7fc52282952c48402a5f6a5b9ed398566e149d3cff8f16097335abb4519d2a",
          "sha1": "8f6d8c74b2af7eefc0c1f48db6338884ab8b6d93",
          "md5": "234b2fc6087c71f9f072fb3d0b517a2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.336+05361cf-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.81.1+1.19.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.2-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.336+05361cf-beta.jar",
          "url": "magiclib-1_19_4-0.7.336+05361cf-beta.jar",
          "size": 379798,
          "sha512": "72193b613c459179e215fbcc41a400bf8ad40cd3f9e4e55a92c7d0083b9ad96e9f7426277a374ccbeb4d56294fc353cf79f80523cc78d8d8e41df693d0aa24d6",
          "sha256": "8a7fc52282952c48402a5f6a5b9ed398566e149d3cff8f16097335abb4519d2a",
          "sha1": "8f6d8c74b2af7eefc0c1f48db6338884ab8b6d93",
          "md5": "234b2fc6087c71f9f072fb3d0b517a2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.336+05361cf-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.336+05361cf-beta-sources.jar",
          "size": 169911,
          "sha512": "a0496164885c9e12601c7677fd82f9a3b91dce41f5f451862b95113fd3f4982d8ec2248b578560f9939110c589029cb079d9c594bbd868dee97b2cef8ffc6541",
          "sha256": "41cee660ffd3e18ca40c52039a409964abcb22f8f2cc2643cc8ff1f881318c78",
          "sha1": "386545b4b1ae7dc4082e1dd063c3f4c9b11ff921",
          "md5": "3cc7afd00f601aeaa50ba06edcd08ef9"
        }
      ]
    }
  ]
}
