{
  "formatVersion": "1.1",
  "component": {
    "group": "fi.dy.masa",
    "module": "malilib",
    "version": "23w16a-0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "malilib-23w16a-0.16.0.jar",
          "url": "malilib-23w16a-0.16.0.jar",
          "size": 540543,
          "sha512": "9a0d5f357ed62dfcdc5d4e56b6952b67183c544b35d3814c60e99a749fd12a6250882802a6a37f2dda923f28cb108f13db5d7f4a50f57f4b6a95f3b2a2412e2b",
          "sha256": "62ed243ef667625661260f4d7e34118529dd5d55c7ba87fe72afd17dd8d25bac",
          "sha1": "8ce4afe52015f2df008ba5ada461bd7cdcd47eb0",
          "md5": "0b979ada4167d58e6a82b0447d691b81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.11.1+03ffe37867"
          }
        }
      ],
      "files": [
        {
          "name": "malilib-23w16a-0.16.0.jar",
          "url": "malilib-23w16a-0.16.0.jar",
          "size": 540543,
          "sha512": "9a0d5f357ed62dfcdc5d4e56b6952b67183c544b35d3814c60e99a749fd12a6250882802a6a37f2dda923f28cb108f13db5d7f4a50f57f4b6a95f3b2a2412e2b",
          "sha256": "62ed243ef667625661260f4d7e34118529dd5d55c7ba87fe72afd17dd8d25bac",
          "sha1": "8ce4afe52015f2df008ba5ada461bd7cdcd47eb0",
          "md5": "0b979ada4167d58e6a82b0447d691b81"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "malilib-23w16a-0.16.0-sources.jar",
          "url": "malilib-23w16a-0.16.0-sources.jar",
          "size": 266680,
          "sha512": "010836c77f250e938ecf0db03d041c9983393a490b4531bf9996ca8e0f526387a9249058e9fd1defa30d082494d776cf7ee3f503434f8998d50742907710ba07",
          "sha256": "3253a1e2ccf2315da70650f0ef9438a4d1354259c6ceeee82bab3fa9c179ca94",
          "sha1": "2f1449f4be61c0b841504de496cd219513262915",
          "md5": "4ad83898fae3d54013e6d4c6261ea6a7"
        }
      ]
    }
  ]
}
