{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.6.193+84fd02e-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.193+84fd02e-beta.jar",
          "url": "magiclib-1_16_5-0.6.193+84fd02e-beta.jar",
          "size": 328340,
          "sha512": "89ff3f3f03917076bf03fbd290da91db1f1f07ef234e125f50683e45940ad5c4202a1a074a4229f3fb7c9698b33ce506a3ac4b794caa895a440cf0a60a3e757e",
          "sha256": "322ed1ba860e3728ef0ebe555dd59ff0df236d2b79921b02da3abe107b913547",
          "sha1": "fa1241c1f8b94b108835ffe0cacaffdd3bb4b8ad",
          "md5": "e72c8e7e816516a92fe46703151d5f23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.193+84fd02e-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.10"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.193+84fd02e-beta.jar",
          "url": "magiclib-1_16_5-0.6.193+84fd02e-beta.jar",
          "size": 328340,
          "sha512": "89ff3f3f03917076bf03fbd290da91db1f1f07ef234e125f50683e45940ad5c4202a1a074a4229f3fb7c9698b33ce506a3ac4b794caa895a440cf0a60a3e757e",
          "sha256": "322ed1ba860e3728ef0ebe555dd59ff0df236d2b79921b02da3abe107b913547",
          "sha1": "fa1241c1f8b94b108835ffe0cacaffdd3bb4b8ad",
          "md5": "e72c8e7e816516a92fe46703151d5f23"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.193+84fd02e-beta-sources.jar",
          "url": "magiclib-1_16_5-0.6.193+84fd02e-beta-sources.jar",
          "size": 229527,
          "sha512": "da68d62027982623843d087427ad05a04ffce55a95047e2b04177e95c1c107492266cf42cd223ef4273b738523214ff3a5b5d9ffa0dd70d293f746ec051744dd",
          "sha256": "a6b528bb92f73ee8989419a11605c92c093d371170b3791ec2b870d7ccc18c2b",
          "sha1": "6f61a0fd2857b115d9089f202496bcc56cfc4273",
          "md5": "39535815054d8d3d7c6f2ac95da0beda"
        }
      ]
    }
  ]
}
