{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-carpet-compat",
    "version": "0.7.12+b31abea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-carpet-compat-0.7.12+b31abea-beta.jar",
          "url": "magiclib-carpet-compat-0.7.12+b31abea-beta.jar",
          "size": 930009,
          "sha512": "39655f04f59d26bcbb5f108ab0710c84071f24269e2efc7d172326d83052304517f76afe97784fad3909c49d6d20e1b33ddd030196f148af8bf356502cdc433c",
          "sha256": "ac4f22091d40690a3ebe456acc144333812237d3e81b6237ea4c2528b65be3c3",
          "sha1": "d5a6018297f3f35f0683dea0a19cfbb553c04ece",
          "md5": "a1555c4d03f5341f8ee2a73affda9b53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-carpet-compat-0.7.12+b31abea-beta.jar",
          "url": "magiclib-carpet-compat-0.7.12+b31abea-beta.jar",
          "size": 930009,
          "sha512": "39655f04f59d26bcbb5f108ab0710c84071f24269e2efc7d172326d83052304517f76afe97784fad3909c49d6d20e1b33ddd030196f148af8bf356502cdc433c",
          "sha256": "ac4f22091d40690a3ebe456acc144333812237d3e81b6237ea4c2528b65be3c3",
          "sha1": "d5a6018297f3f35f0683dea0a19cfbb553c04ece",
          "md5": "a1555c4d03f5341f8ee2a73affda9b53"
        }
      ]
    }
  ]
}
