{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-carpet-compat",
    "version": "0.7.12+b31abea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-carpet-compat-0.7.12+b31abea-beta.jar",
          "url": "magiclib-carpet-compat-0.7.12+b31abea-beta.jar",
          "size": 911552,
          "sha512": "7457a0c56fc9f928adc5d152a84c3d3a473db7016769a7da7dc74f9268ef3887bc9f7c6d55aff50ccb0d840dc761eab1a3ad8500eb0bc756bb7c12e6100463b1",
          "sha256": "119ea3a9f6a37e0de858db287d4c0d67cf50c4413ae5972cf1f0e7319d1bd863",
          "sha1": "e4b6bbf6198db59c7fb29763350cfb7cc8db8ba4",
          "md5": "e0928e71cc61161e2c9024a87b5ff650"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-carpet-compat-0.7.12+b31abea-beta.jar",
          "url": "magiclib-carpet-compat-0.7.12+b31abea-beta.jar",
          "size": 911552,
          "sha512": "7457a0c56fc9f928adc5d152a84c3d3a473db7016769a7da7dc74f9268ef3887bc9f7c6d55aff50ccb0d840dc761eab1a3ad8500eb0bc756bb7c12e6100463b1",
          "sha256": "119ea3a9f6a37e0de858db287d4c0d67cf50c4413ae5972cf1f0e7319d1bd863",
          "sha1": "e4b6bbf6198db59c7fb29763350cfb7cc8db8ba4",
          "md5": "e0928e71cc61161e2c9024a87b5ff650"
        }
      ]
    }
  ]
}
