{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.5.31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479750"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.31.jar",
          "url": "magiclib-1_17_1-0.5.31.jar",
          "size": 254308,
          "sha512": "7041366b4ea7c830976f764b276a8537cea8e58163a59f2be63be1d13baea9289c883827c03ac08e5ab3cac66346c5a622b7fc30b7188cecb76ca09e77678b3e",
          "sha256": "194c6a62e4c0389c7d1c14035f6af7f153bc33a8a99e7ebfde1fbbe061c08e61",
          "sha1": "184e30493e710736fd8c03edd798c182ca657112",
          "md5": "7c7e398e77c489e672baf3ac93e9e146"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.31"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479750"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493811"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.31.jar",
          "url": "magiclib-1_17_1-0.5.31.jar",
          "size": 254308,
          "sha512": "7041366b4ea7c830976f764b276a8537cea8e58163a59f2be63be1d13baea9289c883827c03ac08e5ab3cac66346c5a622b7fc30b7188cecb76ca09e77678b3e",
          "sha256": "194c6a62e4c0389c7d1c14035f6af7f153bc33a8a99e7ebfde1fbbe061c08e61",
          "sha1": "184e30493e710736fd8c03edd798c182ca657112",
          "md5": "7c7e398e77c489e672baf3ac93e9e146"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.31-sources.jar",
          "url": "magiclib-1_17_1-0.5.31-sources.jar",
          "size": 192545,
          "sha512": "2c5c6c875c8d4222e2f23aa7e36ffb52ecce75b96a74ce9497a07bdc46adce7074cfe5680e20dd348f8e4433c1047589fbfa38a666e93a53e2c53aada77118d9",
          "sha256": "1c0ddc6eeb9b1d84ab42522dade76055f5dd7e4f1e1dd89ecfce3ecde619a4ff",
          "sha1": "61078bf4c0b6798be53515983cddfa4ae7556bf4",
          "md5": "f8ae1cfeb37426a86ac8e01decbc885f"
        }
      ]
    }
  ]
}
