{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.300+7c8ee92-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_19_4-0.7.300+7c8ee92-beta.jar",
          "size": 360621,
          "sha512": "0a2922738c40d417f3aa3e14e5af5336120977b8a6e7727e210efb33a59a11d316a9639ab8f794d7c1cf009dae0c5c173be6c979ba9ce31f2c00f83886ec6c67",
          "sha256": "c5d57749f9a41885dd4e8ffb545ee552150bcda3e239561cfe4f32e4dc6aed65",
          "sha1": "df14fc1b7cc0e3f66fe4b4b2ee5798d1dd8ba9f3",
          "md5": "8bc028ac5b0ce65f50e01a506878f693"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.300+7c8ee92-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4446319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4444338"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4441645"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.77.0+1.19.4"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4453670"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.300+7c8ee92-beta.jar",
          "url": "magiclib-1_19_4-0.7.300+7c8ee92-beta.jar",
          "size": 360621,
          "sha512": "0a2922738c40d417f3aa3e14e5af5336120977b8a6e7727e210efb33a59a11d316a9639ab8f794d7c1cf009dae0c5c173be6c979ba9ce31f2c00f83886ec6c67",
          "sha256": "c5d57749f9a41885dd4e8ffb545ee552150bcda3e239561cfe4f32e4dc6aed65",
          "sha1": "df14fc1b7cc0e3f66fe4b4b2ee5798d1dd8ba9f3",
          "md5": "8bc028ac5b0ce65f50e01a506878f693"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.300+7c8ee92-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.300+7c8ee92-beta-sources.jar",
          "size": 159645,
          "sha512": "2aa3b76423cf99a84b6c58cc7b4f31542bc1b214d130054683263d068da6fc868d641bf32d0af5086d6354ffb0611bea39463476e89fd4b9203eeb3d46121bf1",
          "sha256": "7b156e9f39e380db69702d6e6077619b966fe8a476ebe6d6e10c340acb541abd",
          "sha1": "d18058b7ba77fa41b8abf31bbc2c281759dc95f3",
          "md5": "2e4ddd9ab1d300664188603df0da310c"
        }
      ]
    }
  ]
}
