{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra-1_19_3",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_19_3",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_19_3-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_19_3-0.7.2+32bcf58-beta.jar",
          "size": 159603,
          "sha512": "e247182f0af417478afe73e15ca66ca9f9f0054e2d6a1f4b44efe82aa96cbec4ff4810c93ffdc9241ed3753d79423c05900141df3a3bea6be6793caa890638f5",
          "sha256": "1fe18df6aaf8370789c526ee6b1211c63a81f031dddbdef5ac09c67a9950f997",
          "sha1": "024187a33626798b3bd70ad8119fefab16d5e80e",
          "md5": "073ea75307aab1cdc93e45e0db08d544"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_19_3",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_19_3-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-malilib-extra-1_19_3-0.7.2+32bcf58-beta.jar",
          "size": 159603,
          "sha512": "e247182f0af417478afe73e15ca66ca9f9f0054e2d6a1f4b44efe82aa96cbec4ff4810c93ffdc9241ed3753d79423c05900141df3a3bea6be6793caa890638f5",
          "sha256": "1fe18df6aaf8370789c526ee6b1211c63a81f031dddbdef5ac09c67a9950f997",
          "sha1": "024187a33626798b3bd70ad8119fefab16d5e80e",
          "md5": "073ea75307aab1cdc93e45e0db08d544"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_19_3",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_19_3-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-malilib-extra-1_19_3-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 415341,
          "sha512": "19799f4a69f5758953fec09585acb3cf881de1b9db07f0a7b4116aeebb7a53bf03fd23e2d1e17c047f89cf75523067b5a9619872ad78d169434b30dddc4eef26",
          "sha256": "8b43fb325872ab17f5f6ba4b82b13c9606a33ff1863325a3152d8a65537b407f",
          "sha1": "7da182443ec0337805d0aa4df71b681e09dd89fa",
          "md5": "444f1409a1b6583475894992ec9508c4"
        }
      ]
    }
  ]
}
