{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.284+fd02f73-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.284+fd02f73-beta.jar",
          "url": "magiclib-1_18_2-0.7.284+fd02f73-beta.jar",
          "size": 360543,
          "sha512": "aba13e474b6c7a5c4abd88cbf209072836af58f341035c9c045eb31826fc0b961db88db61871658a2cd39e8accf5a924a0097d985c49b4737ed7b67068275f14",
          "sha256": "8a34ebbdcc8e0b0bbc243f53d9226f82946df44400b03b92f087f8bc1ccfd5cc",
          "sha1": "e0cc087fad0b526b7a8fcf55c0a04eba5ae60920",
          "md5": "51ca5a28ab2084afb480131e69122f80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.284+fd02f73-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.284+fd02f73-beta.jar",
          "url": "magiclib-1_18_2-0.7.284+fd02f73-beta.jar",
          "size": 360543,
          "sha512": "aba13e474b6c7a5c4abd88cbf209072836af58f341035c9c045eb31826fc0b961db88db61871658a2cd39e8accf5a924a0097d985c49b4737ed7b67068275f14",
          "sha256": "8a34ebbdcc8e0b0bbc243f53d9226f82946df44400b03b92f087f8bc1ccfd5cc",
          "sha1": "e0cc087fad0b526b7a8fcf55c0a04eba5ae60920",
          "md5": "51ca5a28ab2084afb480131e69122f80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.284+fd02f73-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.284+fd02f73-beta-sources.jar",
          "size": 159526,
          "sha512": "483a05e35f86796245ea7622315088526eda399dd7df21049f303dad086a79ef95765d72982d9b21bd0bb87de0fa3bff76c321a69d9768bd50326faf6487219a",
          "sha256": "6ec6a04de5eb0c504820fabe7eb95172b017df132baaa36cc6b939d718490a47",
          "sha1": "bada26570a0fd19d75b9890254158b830cb37a82",
          "md5": "ad601c75746f50c4420d2bce0a7ff4b2"
        }
      ]
    }
  ]
}
