{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.331+c783ba0-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_17_1-0.7.331+c783ba0-beta.jar",
          "size": 373277,
          "sha512": "42e3f2e2377b3d1b5323c01a513b3d135fa557c1f6f2644c09433f0e9b01e5207cd0cb4e85c23fe4d830d6384e8c8def94c4d5ee8d2be2fc1e18bbb77a1fef92",
          "sha256": "9125a556ef273e67e0ae191bc5959be1160ba4b6310cedc36a76a1ca203cd906",
          "sha1": "d0e33560be3fbfb8d4b80a82576145502b522029",
          "md5": "b483148419609100c3295189f4ffed7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.331+c783ba0-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.17.1-1.4.57+v220119"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.331+c783ba0-beta.jar",
          "url": "magiclib-1_17_1-0.7.331+c783ba0-beta.jar",
          "size": 373277,
          "sha512": "42e3f2e2377b3d1b5323c01a513b3d135fa557c1f6f2644c09433f0e9b01e5207cd0cb4e85c23fe4d830d6384e8c8def94c4d5ee8d2be2fc1e18bbb77a1fef92",
          "sha256": "9125a556ef273e67e0ae191bc5959be1160ba4b6310cedc36a76a1ca203cd906",
          "sha1": "d0e33560be3fbfb8d4b80a82576145502b522029",
          "md5": "b483148419609100c3295189f4ffed7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.331+c783ba0-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.331+c783ba0-beta-sources.jar",
          "size": 168931,
          "sha512": "9a2597f40ab2383547419cf6a2e2cad5b2bd7c8b9a7d9d0e435330fa6a9ec31a6bb6cfbe1b4efbad5dfccb492670fa0dba9854d22fee390e241b7d8d9acb2ef6",
          "sha256": "c8df9f8cc4e8d94e4f8af435e157a9e1f6898992cfa52496cc2e7743a2b2d1bb",
          "sha1": "b78ba6c9ce40b6190051f1e677ef51c7aa25f6ef",
          "md5": "2fc2a7dbc58393fa57f38290f42e7e37"
        }
      ]
    }
  ]
}
