{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-unspecified.jar",
          "url": "magiclib-1_19_2-unspecified.jar",
          "size": 361476,
          "sha512": "5e0b0a0de16c6703ecf514ce53cf5499ba5b000e3ecb8958907ec55bd56cafe9ff62bfc6c37c34992b3680e5762cfe5f37f0bda4a3825eda89739a9586f859e0",
          "sha256": "4d0838ccc7e6a13fd772f93dc1be533f313a8fe3ffcc9b8d6654359af89ea7b7",
          "sha1": "ee44a7e5adae3d2d986401f675b422b0ab2ed30b",
          "md5": "0d8761bc0b104a6623101b9cccaf96b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-unspecified.jar",
          "url": "magiclib-1_19_2-unspecified.jar",
          "size": 361476,
          "sha512": "5e0b0a0de16c6703ecf514ce53cf5499ba5b000e3ecb8958907ec55bd56cafe9ff62bfc6c37c34992b3680e5762cfe5f37f0bda4a3825eda89739a9586f859e0",
          "sha256": "4d0838ccc7e6a13fd772f93dc1be533f313a8fe3ffcc9b8d6654359af89ea7b7",
          "sha1": "ee44a7e5adae3d2d986401f675b422b0ab2ed30b",
          "md5": "0d8761bc0b104a6623101b9cccaf96b4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-unspecified-sources.jar",
          "url": "magiclib-1_19_2-unspecified-sources.jar",
          "size": 159332,
          "sha512": "79cb8c53de26b3fd3fab4745399e8bba5f0aa1b2bae7ae82ee85877b5dec14f66016a9e9e46eae5b9f6c039618f84f69591df3267fd78c123ad8edeecdf54a5b",
          "sha256": "a6fea516562ba0bc363722430f3bd11e1faf6c83daf69a1f3c452c03019622c5",
          "sha1": "36d4dda8e531df3311faed9d4213cbc97cf6d013",
          "md5": "f6418683ff2bc8a28464e58435091b90"
        }
      ]
    }
  ]
}
