{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.317+92abd79-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.57"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.317+92abd79-beta.jar",
          "url": "magiclib-1_17_1-0.7.317+92abd79-beta.jar",
          "size": 371991,
          "sha512": "6cdba1ac3766656dafb857b856a73f00610e1bb283521bec475cf42270951528ecd001526fa8811cc2c0ad4fa957a1dbd14ce1c438e20b827c95db7adc9cd527",
          "sha256": "7c44b381340f5ea49c789520a7884e92fe8235c23efc35fdd51f8d67f885db27",
          "sha1": "66c7321d407b04106e1c3f91948df99174be0153",
          "md5": "87e8a5353cb29890c46915b4c20b4966"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.317+92abd79-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "carpet",
          "version": {
            "requires": "1.4.57"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "2.0.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.17"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.317+92abd79-beta.jar",
          "url": "magiclib-1_17_1-0.7.317+92abd79-beta.jar",
          "size": 371991,
          "sha512": "6cdba1ac3766656dafb857b856a73f00610e1bb283521bec475cf42270951528ecd001526fa8811cc2c0ad4fa957a1dbd14ce1c438e20b827c95db7adc9cd527",
          "sha256": "7c44b381340f5ea49c789520a7884e92fe8235c23efc35fdd51f8d67f885db27",
          "sha1": "66c7321d407b04106e1c3f91948df99174be0153",
          "md5": "87e8a5353cb29890c46915b4c20b4966"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.317+92abd79-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.317+92abd79-beta-sources.jar",
          "size": 168203,
          "sha512": "feb6af2d0dbfb6470da00a5e8d0a60de247f12c444ed5f5cf22508d5b72b0ca3a3ef4c686ba7074907330c19e867a70f6202be7c0ed5da6052bd33945bcfcb02",
          "sha256": "4a9d20edc63fa992a873faf4717dba0546a4e44d6bbac1034ede64eab1bf1fbd",
          "sha1": "12d67fd686cd9abc59c41746d6b45458fa0a8487",
          "md5": "a7051d1a7e9b93ee5eed6694964fac5f"
        }
      ]
    }
  ]
}
