{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_4",
    "version": "0.7.337+67c250a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.84.0+1.19.4"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_19_4-0.7.337+67c250a-beta.jar",
          "size": 379798,
          "sha512": "1426b980fa788f85c06786d9c35f92c25b20245738f5b7292fd57cbc6afcbe3b9c2804d990be75695be4768f240d74693b71fde8a5eb34145d2fa82a1cafc22e",
          "sha256": "aed53195fde8a666f456efdde1e15743f280b50f7122f0f6d6ad624e912a6421",
          "sha1": "5d62c1c1e8b720d7b8560661204a74b7c4776fc0",
          "md5": "39f8b02637c0001e684d63beb329a4b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.337+67c250a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.21"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.4-1.4.101+v230319"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4519977"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.84.0+1.19.4"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.2-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "4441240"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.337+67c250a-beta.jar",
          "url": "magiclib-1_19_4-0.7.337+67c250a-beta.jar",
          "size": 379798,
          "sha512": "1426b980fa788f85c06786d9c35f92c25b20245738f5b7292fd57cbc6afcbe3b9c2804d990be75695be4768f240d74693b71fde8a5eb34145d2fa82a1cafc22e",
          "sha256": "aed53195fde8a666f456efdde1e15743f280b50f7122f0f6d6ad624e912a6421",
          "sha1": "5d62c1c1e8b720d7b8560661204a74b7c4776fc0",
          "md5": "39f8b02637c0001e684d63beb329a4b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_4-0.7.337+67c250a-beta-sources.jar",
          "url": "magiclib-1_19_4-0.7.337+67c250a-beta-sources.jar",
          "size": 169911,
          "sha512": "018e83453e83d34efbdfa56de9d6f4433214676929a83b04f50a2ebff3a2cf2564f350492de45a33801ae30716335d438798cedfe6f266f69422261be2cf0415",
          "sha256": "273ed9603541fab0fe00861ed94e8bf11724d0c7f9bd20d86f88558355a79abc",
          "sha1": "a4895fa94e0ed3db885a3a1e733ba1b3ac5217e4",
          "md5": "df42905351f26af9b18090cb51460b98"
        }
      ]
    }
  ]
}
