{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib",
    "version": "0.5.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-0.5.16.jar",
          "url": "magiclib-0.5.16.jar",
          "size": 1402301,
          "sha512": "119a87aeaf58654537377a25ef77b2168b81e2a0ab0b0f5bc6ea8c486568901615b6f3d85b636921f187d5d62b80899daad9c1239e1b30d6c7efbe249b53fc72",
          "sha256": "7d50186991af28fb24f92c92280938fda276915325e7d084c3c8ee466ee005e2",
          "sha1": "989f7927f69b551bdd008f75dec88a0d615b5576",
          "md5": "0d2003a28d50e63608c84b0917865fa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-0.5.16.jar",
          "url": "magiclib-0.5.16.jar",
          "size": 1402301,
          "sha512": "119a87aeaf58654537377a25ef77b2168b81e2a0ab0b0f5bc6ea8c486568901615b6f3d85b636921f187d5d62b80899daad9c1239e1b30d6c7efbe249b53fc72",
          "sha256": "7d50186991af28fb24f92c92280938fda276915325e7d084c3c8ee466ee005e2",
          "sha1": "989f7927f69b551bdd008f75dec88a0d615b5576",
          "md5": "0d2003a28d50e63608c84b0917865fa5"
        }
      ]
    }
  ]
}
