{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base-1_15_2",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4031627"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_15_2-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_15_2-0.7.2+32bcf58-beta.jar",
          "size": 119159,
          "sha512": "d62a8945f173ddddc1ee0590414716dd2724989ed7bd2ddbafe6f6183df6aca361968dc390cd767b231702d955e1ac6e441c8aa0b8219374e31e08f3209d62b6",
          "sha256": "48dc7b54f793a1d79ba4d815d1463513f790086b6bb66fd316cbaf5ed6301555",
          "sha1": "ee0aac1f4abb48bf878597da34dd442c1500ec95",
          "md5": "14b33e7b49eee5d170e82b6624191fee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4031627"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761404"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993196"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_15_2-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_15_2-0.7.2+32bcf58-beta.jar",
          "size": 119159,
          "sha512": "d62a8945f173ddddc1ee0590414716dd2724989ed7bd2ddbafe6f6183df6aca361968dc390cd767b231702d955e1ac6e441c8aa0b8219374e31e08f3209d62b6",
          "sha256": "48dc7b54f793a1d79ba4d815d1463513f790086b6bb66fd316cbaf5ed6301555",
          "sha1": "ee0aac1f4abb48bf878597da34dd442c1500ec95",
          "md5": "14b33e7b49eee5d170e82b6624191fee"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_15_2-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-base-1_15_2-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 259591,
          "sha512": "4e9ba5b0cd807ca23bf94b37726e5ec168d2089acb29f2266036e42be8a9e7d23d4ec17d6f642a6e8b082d6a8597818303e8a8beec7f0212aaa83f6c95a827b9",
          "sha256": "ba437d1cd872eab20881879fe1cef4511175f9f4fc49c6e491f153da383efd80",
          "sha1": "7019f4c4092fefeee812fe9ae3dc94712524da94",
          "md5": "cd7e7e71af212f756af5695683ac898e"
        }
      ]
    }
  ]
}
