{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base-1_15_2",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4031627"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_15_2-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_15_2-0.7.2+32bcf58-beta.jar",
          "size": 119159,
          "sha512": "41de92fa6077605ce5de2948ec937a63d70cd0294495c1ad21cee863d108f1e7ec317419f5d9129f2bf82782ef95a3853dc2b66b4686799d8d353a6584342c47",
          "sha256": "1de40dba45cc2b3aa46f5a8109268e4562e21b7de85000de638467a694e9a485",
          "sha1": "a9837876c425b2364a1e5dd50534fb2b6a563a39",
          "md5": "cfa55b0efd97247b0ce54a4fa8ab39dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.28.5+1.15"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4031627"
          }
        },
        {
          "group": "curse.maven",
          "module": "auto-config-updated-api-373261",
          "version": {
            "requires": "2959868"
          }
        },
        {
          "group": "curse.maven",
          "module": "cloth-config-348521",
          "version": {
            "requires": "3761404"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993196"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3159390"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_15_2-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_15_2-0.7.2+32bcf58-beta.jar",
          "size": 119159,
          "sha512": "41de92fa6077605ce5de2948ec937a63d70cd0294495c1ad21cee863d108f1e7ec317419f5d9129f2bf82782ef95a3853dc2b66b4686799d8d353a6584342c47",
          "sha256": "1de40dba45cc2b3aa46f5a8109268e4562e21b7de85000de638467a694e9a485",
          "sha1": "a9837876c425b2364a1e5dd50534fb2b6a563a39",
          "md5": "cfa55b0efd97247b0ce54a4fa8ab39dc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_15_2-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-base-1_15_2-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 259591,
          "sha512": "d44ad0915c837ce727a574b01fc0901accd77ce782268fffd3d4bd7674bbacc082d03ae915b9678f99e28451aee6791a03dadd21f1ede5cb2674dcb41a38b789",
          "sha256": "fdce4df3996437b807fa13d90c4bb39744b96129f07bd9a39e74153211e03dc0",
          "sha1": "69691d819293ec47eea0983f9731cbe885eefa55",
          "md5": "5a168e3d7c7be6d3df198f472efbc34c"
        }
      ]
    }
  ]
}
