{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-unspecified.jar",
          "url": "magiclib-1_17_1-unspecified.jar",
          "size": 358811,
          "sha512": "6eef6007415f270f5bf0a5bf5e7d37f04ca1a4b45cd0fc5fc8cc4078cf346bc89496318224ec7c07e2575b22fa4d1038d6868d205656e32cda449e8992a55468",
          "sha256": "7f5b429870bf33d5672644b2f107b493901b336c74e6e36e45c79a76efbc7b67",
          "sha1": "e7d622a7fe2d9ec99082568142ccfc164727bdcb",
          "md5": "ac810a7bdc2439e6e1d48af7e38ee7b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-unspecified.jar",
          "url": "magiclib-1_17_1-unspecified.jar",
          "size": 358811,
          "sha512": "6eef6007415f270f5bf0a5bf5e7d37f04ca1a4b45cd0fc5fc8cc4078cf346bc89496318224ec7c07e2575b22fa4d1038d6868d205656e32cda449e8992a55468",
          "sha256": "7f5b429870bf33d5672644b2f107b493901b336c74e6e36e45c79a76efbc7b67",
          "sha1": "e7d622a7fe2d9ec99082568142ccfc164727bdcb",
          "md5": "ac810a7bdc2439e6e1d48af7e38ee7b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-unspecified-sources.jar",
          "url": "magiclib-1_17_1-unspecified-sources.jar",
          "size": 159405,
          "sha512": "50a1470f60cdbc2dd4249fd05c9a343e49b83c64c5e4fb3a1fe22ca6276f7d81bed8d5e37a4ed10f08f8bb6f4bf3f4a1e02085305592dfbfab857e82bd16ec1f",
          "sha256": "3263a720b0c1b3f1888c0ff542dba403c1437e07e7a29d1851ba1cc1defb5786",
          "sha1": "933170529a314812757b9fa3c63d28fc38bc4940",
          "md5": "85967cea7a55e4379700b0cef9be6a12"
        }
      ]
    }
  ]
}
