{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc",
    "version": "0.5.260+86e6882-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-0.5.260+86e6882-dev.jar",
          "url": "ommc-0.5.260+86e6882-dev.jar",
          "size": 9975764,
          "sha512": "64f148fd7161dc0e83bf9c2695e1a3ba048d6f26001737c47db680c54e3899e257a3d60c58e7d69a464deb3108a19afdc7d329263533b143803cdb50fb0bdb33",
          "sha256": "5297291ed15ad1c6d787729add5e4c43cabd4874c25802039c620d1e4effae4e",
          "sha1": "5397cc79353c25e80baa4ab34d2091944979b867",
          "md5": "2b634555d95f2aa762b749ea065e1a88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ommc-0.5.260+86e6882-dev.jar",
          "url": "ommc-0.5.260+86e6882-dev.jar",
          "size": 9975764,
          "sha512": "64f148fd7161dc0e83bf9c2695e1a3ba048d6f26001737c47db680c54e3899e257a3d60c58e7d69a464deb3108a19afdc7d329263533b143803cdb50fb0bdb33",
          "sha256": "5297291ed15ad1c6d787729add5e4c43cabd4874c25802039c620d1e4effae4e",
          "sha1": "5397cc79353c25e80baa4ab34d2091944979b867",
          "md5": "2b634555d95f2aa762b749ea065e1a88"
        }
      ]
    }
  ]
}
