{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.5.25",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479750"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.5"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.25.jar",
          "url": "magiclib-1_17_1-0.5.25.jar",
          "size": 254088,
          "sha512": "5fb880b095c870ecd0c09b70fb7292a0eeac9fc7c5842d6ddbcc6c872338e68bb40adb5c29856ec2942e985a346baa0fd3cc6f619d24df70139ef160a8431e30",
          "sha256": "69cb50aeb4ef3707f6a78b7443ef9f7285320b732e8f0ef0f75eaa7c88d3f228",
          "sha1": "5d143b4484e82df9c6992c6a22ffd463c15292a4",
          "md5": "7b522e635a23763b231205d088928ded"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.25"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3479750"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.5"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3493811"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.25.jar",
          "url": "magiclib-1_17_1-0.5.25.jar",
          "size": 254088,
          "sha512": "5fb880b095c870ecd0c09b70fb7292a0eeac9fc7c5842d6ddbcc6c872338e68bb40adb5c29856ec2942e985a346baa0fd3cc6f619d24df70139ef160a8431e30",
          "sha256": "69cb50aeb4ef3707f6a78b7443ef9f7285320b732e8f0ef0f75eaa7c88d3f228",
          "sha1": "5d143b4484e82df9c6992c6a22ffd463c15292a4",
          "md5": "7b522e635a23763b231205d088928ded"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.5.25-sources.jar",
          "url": "magiclib-1_17_1-0.5.25-sources.jar",
          "size": 192401,
          "sha512": "6c67f15a4e395fcda55933bbade91001dca58becb376b478a82ffce38d233a08fc69e594894d4b680c9db54429000831dc912061e8f0b4e65516dd1ffe46edb8",
          "sha256": "7aab4cbbbc92a07fdc97a767eb943799c9397fc213f16d3e996b2f6b4eb06340",
          "sha1": "a803b6de2831a0cec86081b71b78720993b7bd18",
          "md5": "b4e59b65ebb216083d978345f7532841"
        }
      ]
    }
  ]
}
