{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.7.330+0499b91-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.330+0499b91-beta.jar",
          "url": "magiclib-1_16_5-0.7.330+0499b91-beta.jar",
          "size": 375226,
          "sha512": "53dca3ba03f5dc73b2fc98f56dd34795364240cdc40e8de0bd65038ff5dac361f882315da4fe312d2d46505df2a63c0ded3f9f54c57cc6b80c23598ea5083099",
          "sha256": "2d1241e2e2fca2661527b1c0ff167fcdcd03c5e8263aa12bdf3d4ea44fa7474f",
          "sha1": "acd6cc5238c47e29d618afa414845dfdde868b86",
          "md5": "9b81a6105c7125e1faef86c1ed9d1bf0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.330+0499b91-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.28"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.16.5-1.4.44+v210714"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "1.16.23"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.16"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.330+0499b91-beta.jar",
          "url": "magiclib-1_16_5-0.7.330+0499b91-beta.jar",
          "size": 375226,
          "sha512": "53dca3ba03f5dc73b2fc98f56dd34795364240cdc40e8de0bd65038ff5dac361f882315da4fe312d2d46505df2a63c0ded3f9f54c57cc6b80c23598ea5083099",
          "sha256": "2d1241e2e2fca2661527b1c0ff167fcdcd03c5e8263aa12bdf3d4ea44fa7474f",
          "sha1": "acd6cc5238c47e29d618afa414845dfdde868b86",
          "md5": "9b81a6105c7125e1faef86c1ed9d1bf0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.7.330+0499b91-beta-sources.jar",
          "url": "magiclib-1_16_5-0.7.330+0499b91-beta-sources.jar",
          "size": 168752,
          "sha512": "aaf819ff69b5006eca178d4137acaeb6ef80ae4bbf16f34d7758c83071915205bc3b8c72d255357508e5977ed46d133b61a3c942fb107a1f1c9fd7abec6569d9",
          "sha256": "f7006c6bc1b0760e6822d4c7efacf84c3c7cf3f6334bf02c1cd816f0737e87bd",
          "sha1": "8e97b41ad09b1901115b6b9b7a370879486bf295",
          "md5": "079136a5f3a345383bff84737eeb8640"
        }
      ]
    }
  ]
}
