{
  "formatVersion": "1.1",
  "component": {
    "group": "curse.maven",
    "module": "ommc-454900-1_18_2",
    "version": "0.5-alpha+4d91bac",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-454900-1_18_2-0.5-alpha+4d91bac.jar",
          "url": "ommc-454900-1_18_2-0.5-alpha+4d91bac.jar",
          "size": 146192,
          "sha512": "47414679df9258c54dfe58d42edaada7e98eb2b408f78176e7f6a004c46d45734e9ddcab919790fc8ff6c33b99b0aa251f7e0e6899daa927e2ebf73f7b7da000",
          "sha256": "fda0f675b618df5c209f0375041089742780013b4e890e5d2ded784d8b971127",
          "sha1": "f6db1fa05b6da4905457ca2975e29de5dc7e4019",
          "md5": "97c11533fb0fde1b10e2d131e15eaba7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "ommc-454900",
          "version": {
            "requires": "0.5-alpha+4d91bac"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_18_2",
          "version": {
            "requires": "0.5.37"
          }
        }
      ],
      "files": [
        {
          "name": "ommc-454900-1_18_2-0.5-alpha+4d91bac.jar",
          "url": "ommc-454900-1_18_2-0.5-alpha+4d91bac.jar",
          "size": 146192,
          "sha512": "47414679df9258c54dfe58d42edaada7e98eb2b408f78176e7f6a004c46d45734e9ddcab919790fc8ff6c33b99b0aa251f7e0e6899daa927e2ebf73f7b7da000",
          "sha256": "fda0f675b618df5c209f0375041089742780013b4e890e5d2ded784d8b971127",
          "sha1": "f6db1fa05b6da4905457ca2975e29de5dc7e4019",
          "md5": "97c11533fb0fde1b10e2d131e15eaba7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ommc-454900-1_18_2-0.5-alpha+4d91bac-sources.jar",
          "url": "ommc-454900-1_18_2-0.5-alpha+4d91bac-sources.jar",
          "size": 93497,
          "sha512": "a6e4659285a338a4191f6da478f0c1597ee107980a52241d3f352576ab349d8829a9dc624256040fcfe04a8736f1f3b55b63d6647694bc27a1bd42444fae976a",
          "sha256": "5f8f20670c471c39231cdc333eb76ba2df7df99271eedc0d4cf385008e125eba",
          "sha1": "6db4ba34dde14a0f14285428707e3b9b39a08df6",
          "md5": "4271d24a59a3b952d8b80f586632e136"
        }
      ]
    }
  ]
}
