{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_19_2",
    "version": "0.5.292+eec667c-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_19_2-0.5.292+eec667c-dev.jar",
          "url": "ommc-1_19_2-0.5.292+eec667c-dev.jar",
          "size": 1146855,
          "sha512": "037fe9ffa4440b4dca2b017bb01eaa00e20a1ca245f98869abb40e9830a5378086d15e62641d4985d15259d1b9833b37671755a7baaa15ddd9e22eb0deb40cab",
          "sha256": "08c46bb7accdf1e9943032710c3f9a1215aec7f1473c11a82ce527f4098e366b",
          "sha1": "f84d17b4429e62e1b01ffa688d8c2bff9a74c524",
          "md5": "05a9a92a5d8a0ca039c60b68c568f07d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.292+eec667c-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_19_2",
          "version": {
            "requires": "0.7.336"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_19_2-0.5.292+eec667c-dev.jar",
          "url": "ommc-1_19_2-0.5.292+eec667c-dev.jar",
          "size": 1146855,
          "sha512": "037fe9ffa4440b4dca2b017bb01eaa00e20a1ca245f98869abb40e9830a5378086d15e62641d4985d15259d1b9833b37671755a7baaa15ddd9e22eb0deb40cab",
          "sha256": "08c46bb7accdf1e9943032710c3f9a1215aec7f1473c11a82ce527f4098e366b",
          "sha1": "f84d17b4429e62e1b01ffa688d8c2bff9a74c524",
          "md5": "05a9a92a5d8a0ca039c60b68c568f07d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
