{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra",
    "version": "0.7.12+b31abea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "url": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "size": 976918,
          "sha512": "d624f347d1a3b070d98565c4644f02fac46102dae6e37ea8faaa7ef8e9275a067421ed2390b2464d283400dc0de7884911b0a243645c6007e0cac22ff40ed071",
          "sha256": "ea7fca0a4ae14adf639cf690ae294dbdf58ad2189406012e9312c900aebbc158",
          "sha1": "63e0ebc2771bba46e04f8298e8d5bc9faae2ecb8",
          "md5": "dfd79b5fafbeaac38a757ec28a273c85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "url": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "size": 976918,
          "sha512": "d624f347d1a3b070d98565c4644f02fac46102dae6e37ea8faaa7ef8e9275a067421ed2390b2464d283400dc0de7884911b0a243645c6007e0cac22ff40ed071",
          "sha256": "ea7fca0a4ae14adf639cf690ae294dbdf58ad2189406012e9312c900aebbc158",
          "sha1": "63e0ebc2771bba46e04f8298e8d5bc9faae2ecb8",
          "md5": "dfd79b5fafbeaac38a757ec28a273c85"
        }
      ]
    }
  ]
}
