{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra",
    "version": "0.7.12+b31abea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "url": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "size": 976865,
          "sha512": "1a0e15f0423a1ea6043bd42a2f501b6609b87086c534437900372e120caf941b896c7e40bb3d53f9c796a2a3644119fec2a0857fb25fd48984ebd5548fb3259c",
          "sha256": "a9cb5ebb7c86e5da4c323896e2032b5b35c419ff2a20cdeae23d1605ff9ae9f6",
          "sha1": "8e23ba24dce189a439d0cc3eb9a1aeffcd41d7ce",
          "md5": "68e47585e4f7d698a38e9df7fd3ff9c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "url": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "size": 976865,
          "sha512": "1a0e15f0423a1ea6043bd42a2f501b6609b87086c534437900372e120caf941b896c7e40bb3d53f9c796a2a3644119fec2a0857fb25fd48984ebd5548fb3259c",
          "sha256": "a9cb5ebb7c86e5da4c323896e2032b5b35c419ff2a20cdeae23d1605ff9ae9f6",
          "sha1": "8e23ba24dce189a439d0cc3eb9a1aeffcd41d7ce",
          "md5": "68e47585e4f7d698a38e9df7fd3ff9c1"
        }
      ]
    }
  ]
}
