{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra",
    "version": "0.7.12+b31abea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "url": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "size": 977275,
          "sha512": "b83a73b0e44ab08c11428a9341a6adf2f2804599e23fc6d11cfccb584ae7033a0d7ec00489e6c8531bbcb7e8bc5f44e7cacbd160b3dbe522b784ce5b791cac0a",
          "sha256": "0f61c3df7bb7fd89d961c8bb9e134bcb16760740d32c51912c2f9f67cb38da7d",
          "sha1": "9f57a5d6a4a960456d659a8f5b582ae1a8522dbf",
          "md5": "d3ebeabbb1a8172f9d026009900f37c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "url": "magiclib-malilib-extra-0.7.12+b31abea-beta.jar",
          "size": 977275,
          "sha512": "b83a73b0e44ab08c11428a9341a6adf2f2804599e23fc6d11cfccb584ae7033a0d7ec00489e6c8531bbcb7e8bc5f44e7cacbd160b3dbe522b784ce5b791cac0a",
          "sha256": "0f61c3df7bb7fd89d961c8bb9e134bcb16760740d32c51912c2f9f67cb38da7d",
          "sha1": "9f57a5d6a4a960456d659a8f5b582ae1a8522dbf",
          "md5": "d3ebeabbb1a8172f9d026009900f37c9"
        }
      ]
    }
  ]
}
