{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.302+8d1be4b-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.302+8d1be4b-beta.jar",
          "url": "magiclib-1_18_2-0.7.302+8d1be4b-beta.jar",
          "size": 360570,
          "sha512": "aacdc1078bd8dedd328f85f9bee7342703e49a20746c6f2a0e903260ca4550099aa8987de17a24a9e28c08252027f511a352406fa55ae5f9ec0d7d80f84857d0",
          "sha256": "92a8f308b9d142a0fef8af59a6e7cb3fd75c4bf9de426436dfa16da1bbdc938a",
          "sha1": "b896801c638cc876571770d049e298b69fb7dd7c",
          "md5": "d4ea088427c88c10784a043fb8f8dcdb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.302+8d1be4b-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3725895"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145213"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993199"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.302+8d1be4b-beta.jar",
          "url": "magiclib-1_18_2-0.7.302+8d1be4b-beta.jar",
          "size": 360570,
          "sha512": "aacdc1078bd8dedd328f85f9bee7342703e49a20746c6f2a0e903260ca4550099aa8987de17a24a9e28c08252027f511a352406fa55ae5f9ec0d7d80f84857d0",
          "sha256": "92a8f308b9d142a0fef8af59a6e7cb3fd75c4bf9de426436dfa16da1bbdc938a",
          "sha1": "b896801c638cc876571770d049e298b69fb7dd7c",
          "md5": "d4ea088427c88c10784a043fb8f8dcdb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.302+8d1be4b-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.302+8d1be4b-beta-sources.jar",
          "size": 159696,
          "sha512": "2660f6ab7dcf49651a3a965b80ce03b3224eda7858fb228a1daf139a11ae114c0313fff2b4d0baa31abfd9a49e464cfd9e7a9fe44dacc3a60f5691f0267869ff",
          "sha256": "e5c9800189edbcec94b387b833da23c6ef8baa6dca3c30bf4357b3702ed0e1ed",
          "sha1": "5a2bf1252fbedae5e52a754b5d328aeeb6a8cd77",
          "md5": "408a14a42957b7dda851aa0877e2d00f"
        }
      ]
    }
  ]
}
