{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-minecraft-compat-1_14_4",
    "version": "0.5.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_14_4",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_14_4-0.5.2+32bcf58-beta.jar",
          "url": "magiclib-minecraft-compat-1_14_4-0.5.2+32bcf58-beta.jar",
          "size": 158597,
          "sha512": "837d1159e0ba68eedea49c48cb23e03aad65e3d53b7bbe5fe6171bbd90c22fc8bfbe1b62c1d49b939226d44fffb421d65d2767242f8d048414d8a24903494398",
          "sha256": "284a2fd3bfbc70791f51ff4df055749fd278f954d9f70d78986d83922cd97f10",
          "sha1": "884d65b55ebb5e9fdb302c01206bc67d605d8ec6",
          "md5": "2c386caabc750ca73065cb052a8aaec6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_14_4",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_14_4-0.5.2+32bcf58-beta.jar",
          "url": "magiclib-minecraft-compat-1_14_4-0.5.2+32bcf58-beta.jar",
          "size": 158597,
          "sha512": "837d1159e0ba68eedea49c48cb23e03aad65e3d53b7bbe5fe6171bbd90c22fc8bfbe1b62c1d49b939226d44fffb421d65d2767242f8d048414d8a24903494398",
          "sha256": "284a2fd3bfbc70791f51ff4df055749fd278f954d9f70d78986d83922cd97f10",
          "sha1": "884d65b55ebb5e9fdb302c01206bc67d605d8ec6",
          "md5": "2c386caabc750ca73065cb052a8aaec6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_14_4",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_14_4-0.5.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-minecraft-compat-1_14_4-0.5.2+32bcf58-beta-standalone-dev.jar",
          "size": 411115,
          "sha512": "e6b60c3749cab04be2b4c16e136f9f618a445ebfc41789176052640d387967bd8c8bf94b57c7bd71c6633a4dc7631c379ce2763801ba47bae98a5717418d9a7a",
          "sha256": "ee8c4d096ffeed971162592fc73d168ed96616e1b2099fc05c95a7c06faeb73c",
          "sha1": "00b1d33a1b9d716e92d5219a7322330897e68b78",
          "md5": "b5446659f9860f797b7a6942fcedf925"
        }
      ]
    }
  ]
}
