{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.327+dfd83d3-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.327+dfd83d3-beta.jar",
          "url": "magiclib-1_19_3-0.7.327+dfd83d3-beta.jar",
          "size": 375153,
          "sha512": "3dbea127317775c1c09fe0906d190cfc88752d98436eac80b04c2bdca442716c5c41839b94a839c080a894888cfe22d7a49ec4c6700e8d57fccd6f6fde535ae7",
          "sha256": "2f14f5373359c65b2836b4f7236cb6a918cd6c0b505bf8ad157b8d703bf81731",
          "sha1": "a7fcfb9c858b118eeb08db22a709c0fae19604d3",
          "md5": "61713b64863a0c532468b77b476cd3c8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.327+dfd83d3-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.20"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.327+dfd83d3-beta.jar",
          "url": "magiclib-1_19_3-0.7.327+dfd83d3-beta.jar",
          "size": 375153,
          "sha512": "3dbea127317775c1c09fe0906d190cfc88752d98436eac80b04c2bdca442716c5c41839b94a839c080a894888cfe22d7a49ec4c6700e8d57fccd6f6fde535ae7",
          "sha256": "2f14f5373359c65b2836b4f7236cb6a918cd6c0b505bf8ad157b8d703bf81731",
          "sha1": "a7fcfb9c858b118eeb08db22a709c0fae19604d3",
          "md5": "61713b64863a0c532468b77b476cd3c8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.327+dfd83d3-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.327+dfd83d3-beta-sources.jar",
          "size": 169006,
          "sha512": "c718bf9b54a3f5b3d66f84b36e74964ac461b84692582f8e94eb9f27139a5154c23ae9a9bf3822ab6366f01d1b2d7d5e91a2355867e631b02e96b543a0de2771",
          "sha256": "29226b468d7eed4577e81973de092d08637ec3d890b5b55e51daf3fc88012b95",
          "sha1": "c95690dbe4ef4fc0f6897da208cfa3b2db5705a8",
          "md5": "e86b98d882689322b3934c62f3c93dbc"
        }
      ]
    }
  ]
}
