{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib",
    "version": "0.7.336",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-0.7.336.jar",
          "url": "magiclib-0.7.336.jar",
          "size": 3033815,
          "sha512": "1cbc33aacb3168a867fb895bcb5f9e27d1a7898ab856b880c97592905fdc154a35b5e7ada7db8f7d2e32289a1c230dddc9f9715cb1ec277f4fb25a36344512e1",
          "sha256": "dc9200f2433fc6ef6c011403fc9edf3cfa565281d76f05b4e7e8c8cece1a7e56",
          "sha1": "33b22da11516a23e8e0852a53ddae42ea249a4a0",
          "md5": "15552bf387144425772d5bd934e014c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-0.7.336.jar",
          "url": "magiclib-0.7.336.jar",
          "size": 3033815,
          "sha512": "1cbc33aacb3168a867fb895bcb5f9e27d1a7898ab856b880c97592905fdc154a35b5e7ada7db8f7d2e32289a1c230dddc9f9715cb1ec277f4fb25a36344512e1",
          "sha256": "dc9200f2433fc6ef6c011403fc9edf3cfa565281d76f05b4e7e8c8cece1a7e56",
          "sha1": "33b22da11516a23e8e0852a53ddae42ea249a4a0",
          "md5": "15552bf387144425772d5bd934e014c3"
        }
      ]
    }
  ]
}
