{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.319+530ec3a-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.319+530ec3a-beta.jar",
          "url": "magiclib-1_19_3-0.7.319+530ec3a-beta.jar",
          "size": 373821,
          "sha512": "c0a5d8f33716cfcb21bad7f6b2dc747da18688707f9cb39d8c7b09e67a11178f9df8e6d6db318339fc8356e4b6409e59b762cc6d08d8bd630503c7bfc024b5b6",
          "sha256": "3cdfd75322f95a6e44249ebdfdb54740c9e0763c7a1b6e57bfb18056be988f05",
          "sha1": "e6c1f1a8599fc8d397684315c9a4a9dd25136f95",
          "md5": "80e92f89ba72a6beaad0988e4f1d8b9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.319+530ec3a-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.19.3-1.4.96+v230201"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "5.1.0-beta.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.1+1.19.3"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1.1-fabric1.19"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.3"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.319+530ec3a-beta.jar",
          "url": "magiclib-1_19_3-0.7.319+530ec3a-beta.jar",
          "size": 373821,
          "sha512": "c0a5d8f33716cfcb21bad7f6b2dc747da18688707f9cb39d8c7b09e67a11178f9df8e6d6db318339fc8356e4b6409e59b762cc6d08d8bd630503c7bfc024b5b6",
          "sha256": "3cdfd75322f95a6e44249ebdfdb54740c9e0763c7a1b6e57bfb18056be988f05",
          "sha1": "e6c1f1a8599fc8d397684315c9a4a9dd25136f95",
          "md5": "80e92f89ba72a6beaad0988e4f1d8b9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.319+530ec3a-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.319+530ec3a-beta-sources.jar",
          "size": 168459,
          "sha512": "9ec091536b293634c5903713551e9472367292982af5c826f36a93cf3034a753fcda1193b4bc8a907d8c6b46f28a5703b95d97ac9c729a76fbd076f25e27f848",
          "sha256": "40657543eebc0389571456ce4c96ca105d8b7c2347364030e3e7deb2bbf6385f",
          "sha1": "41f8eb40304b193b975dc5669579db7a4d44aa29",
          "md5": "496aa404c45edd9dc4840844b7ab644e"
        }
      ]
    }
  ]
}
