{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-carpet-compat-1_19_3",
    "version": "0.2.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_19_3",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4279344"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_19_3-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_19_3-0.2.2+32bcf58-beta.jar",
          "size": 144157,
          "sha512": "a40748843cc18752a89480d6ad0fd50c0a38fde7197e29460a8ea9bace6c6b00d7708280adbf41abbbbb7ded33057a29a9450b002552b97b76be1ec2798297bf",
          "sha256": "e1ddd63363adfb2ce609b72fa96d103810098bfc7ca6c19b7ebf61ac3587c65e",
          "sha1": "29d89c289d806baf908a917a6e221d3b60ec8112",
          "md5": "0c67d1a7aa7f3068b5fd20932255dcc1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_19_3",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4279344"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_19_3-0.2.2+32bcf58-beta.jar",
          "url": "magiclib-carpet-compat-1_19_3-0.2.2+32bcf58-beta.jar",
          "size": 144157,
          "sha512": "a40748843cc18752a89480d6ad0fd50c0a38fde7197e29460a8ea9bace6c6b00d7708280adbf41abbbbb7ded33057a29a9450b002552b97b76be1ec2798297bf",
          "sha256": "e1ddd63363adfb2ce609b72fa96d103810098bfc7ca6c19b7ebf61ac3587c65e",
          "sha1": "29d89c289d806baf908a917a6e221d3b60ec8112",
          "md5": "0c67d1a7aa7f3068b5fd20932255dcc1"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-minecraft-compat-1_19_3",
          "version": {
            "requires": "0.5.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-carpet-compat-1_19_3-0.2.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-carpet-compat-1_19_3-0.2.2+32bcf58-beta-standalone-dev.jar",
          "size": 536883,
          "sha512": "5dd2c1d298d67c91117b1796b2b3be59609d9f12c5d519e0751c8d29cdaaa1a13b1be21d76607763e9210622be0b19f4be7b856af3eab28721a188337cc7442c",
          "sha256": "519186641a72fb042c02c226159b6e51ec5580c21849e0897dd1dc23a4889e7a",
          "sha1": "f127ca841fc63ed8f40e0b1f2814a5623c0fe7af",
          "md5": "8593612cc194d077f57ef594e32e672a"
        }
      ]
    }
  ]
}
