{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.6.175+62c773e-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.175+62c773e-beta.jar",
          "url": "magiclib-1_16_5-0.6.175+62c773e-beta.jar",
          "size": 299705,
          "sha512": "ec20f5e7e73378ec07294133b7f015b2dbe82eea630a0e6451c8e10f24a8dcbe0fd36defb3ebe554b74de63b6bdea83ddbafc360d38e3aabe84676a3c0668bf5",
          "sha256": "6502fedd8f9123ac3a6216c823fec217872dce623ceab06a415b9ccea2b9693d",
          "sha1": "d793725bbafb41d6f4c310cc54976a5058a2e7b8",
          "md5": "c1f1ca5b456c5aa9d596fbe2f2d34664"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.175+62c773e-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827450"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.175+62c773e-beta.jar",
          "url": "magiclib-1_16_5-0.6.175+62c773e-beta.jar",
          "size": 299705,
          "sha512": "ec20f5e7e73378ec07294133b7f015b2dbe82eea630a0e6451c8e10f24a8dcbe0fd36defb3ebe554b74de63b6bdea83ddbafc360d38e3aabe84676a3c0668bf5",
          "sha256": "6502fedd8f9123ac3a6216c823fec217872dce623ceab06a415b9ccea2b9693d",
          "sha1": "d793725bbafb41d6f4c310cc54976a5058a2e7b8",
          "md5": "c1f1ca5b456c5aa9d596fbe2f2d34664"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.175+62c773e-beta-sources.jar",
          "url": "magiclib-1_16_5-0.6.175+62c773e-beta-sources.jar",
          "size": 214731,
          "sha512": "6d1532c6bf26b4c73ba2b4b355b4bbae9e042ace3f94a7f9562c2b09f2c2d32eb5862501eb032ea139e5ddaf70b4c924e76c1c1f37266ad6820e8d9eddcd14f9",
          "sha256": "aa8179c285c6ddac9c476537e4b5351e11ab52c1a3775028123cee428aced0b4",
          "sha1": "af7cc3b7ee2a2e4046acd8b26d32c3761bddcac0",
          "md5": "eb7a62e3493fcf4d1cbaa582fedf8e30"
        }
      ]
    }
  ]
}
