{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.6.221+5077f40-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.73.2+1.19.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.6.221+5077f40-beta.jar",
          "url": "magiclib-1_19_2-0.6.221+5077f40-beta.jar",
          "size": 332072,
          "sha512": "1c61613212dd94f459b60688794d1e136d3310db81668e07201ca6ff828272cd1f4010c42912b4f46376e1e47342e5016381a83a4ef877e3422784fe7267d30c",
          "sha256": "6cc48ca084a8d44fa0f4ec4f4fc7346298d88670e7825568ae24f54c49377bb8",
          "sha1": "bcd35a3a36723b365d1445169e98dc58fb83c468",
          "md5": "fc92f885692e8d9555d1d6cdb0ddb0ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.221+5077f40-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.73.2+1.19.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.14"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.6.221+5077f40-beta.jar",
          "url": "magiclib-1_19_2-0.6.221+5077f40-beta.jar",
          "size": 332072,
          "sha512": "1c61613212dd94f459b60688794d1e136d3310db81668e07201ca6ff828272cd1f4010c42912b4f46376e1e47342e5016381a83a4ef877e3422784fe7267d30c",
          "sha256": "6cc48ca084a8d44fa0f4ec4f4fc7346298d88670e7825568ae24f54c49377bb8",
          "sha1": "bcd35a3a36723b365d1445169e98dc58fb83c468",
          "md5": "fc92f885692e8d9555d1d6cdb0ddb0ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.6.221+5077f40-beta-sources.jar",
          "url": "magiclib-1_19_2-0.6.221+5077f40-beta-sources.jar",
          "size": 232304,
          "sha512": "d533c8b02981a0fd125a2b7d3742a9c75c5b34a2cf6cf51d81a7d3100a3e6e3939d5c2476a5cbd6e15b0917fec2878370782e621d96ec778360f23842f0f1b44",
          "sha256": "dd2814c173de6b9041f8ea9548dc9a6b1c10d44c41fc91342b9e2a428f44167d",
          "sha1": "f4dcd780128ecb4eaea77394c571dd9acdad7218",
          "md5": "fdea10006301fe34e0b39eb9ba7ba065"
        }
      ]
    }
  ]
}
