{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.311+83c833c-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.311+83c833c-beta.jar",
          "url": "magiclib-1_17_1-0.7.311+83c833c-beta.jar",
          "size": 371828,
          "sha512": "32aa0a23fc112af177e187a858dac1f2d3dafad2232ddd65b8c0bdae49b74a917e360b6e305e8b4702e9306714d41d7c077b5c9da388ab0acdab5e469463b472",
          "sha256": "ec73c1a9d6db23b3bb1d38aecd6c30bf7332cd2f1566dd3cfd7279cacd6fd72a",
          "sha1": "cf836ee9ee4bb0871998d7eda42bc7237713c420",
          "md5": "4b862b86aa10c4930c0c0c586465a05d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.311+83c833c-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.311+83c833c-beta.jar",
          "url": "magiclib-1_17_1-0.7.311+83c833c-beta.jar",
          "size": 371828,
          "sha512": "32aa0a23fc112af177e187a858dac1f2d3dafad2232ddd65b8c0bdae49b74a917e360b6e305e8b4702e9306714d41d7c077b5c9da388ab0acdab5e469463b472",
          "sha256": "ec73c1a9d6db23b3bb1d38aecd6c30bf7332cd2f1566dd3cfd7279cacd6fd72a",
          "sha1": "cf836ee9ee4bb0871998d7eda42bc7237713c420",
          "md5": "4b862b86aa10c4930c0c0c586465a05d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.311+83c833c-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.311+83c833c-beta-sources.jar",
          "size": 168139,
          "sha512": "86fe31e7d0e9e91ed0d7c435e870914b584ccc4eb9b82cf4ee13eac2e43aad87e28ad75f92bc34e893bc4adbd265989812b4205120b9f181da7aaed40a613864",
          "sha256": "e9e1aba44a5516a6c0df2e58bff75f48f0fed4a37b7e2b338177ca09db752452",
          "sha1": "6ac43969b249c51db2eea5efcaf947f18fbddba6",
          "md5": "f03e15d5fb8d3fa3a596324f43c4ee20"
        }
      ]
    }
  ]
}
