{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_2",
    "version": "0.7.302+8d1be4b-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.302+8d1be4b-beta.jar",
          "url": "magiclib-1_19_2-0.7.302+8d1be4b-beta.jar",
          "size": 361650,
          "sha512": "9e042475091ea7258238e2ab33c0ba6914a0b04f80081e0312286eb84382e3c12917d801aa4484e916fec45b51536ad19d35d6eaf7b2fe543b63fc1671411f3a",
          "sha256": "0ac1d17d413ffef31db408ec06f145d3300da317345e01b5d40d12acc93593b4",
          "sha1": "ee3cbd6035b37c9f1359623210fad56d1b9a5493",
          "md5": "b1c10b5e0f852a445da70e88a19dff90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.302+8d1be4b-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4033215"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3923052"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145207"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.2"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993200"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.302+8d1be4b-beta.jar",
          "url": "magiclib-1_19_2-0.7.302+8d1be4b-beta.jar",
          "size": 361650,
          "sha512": "9e042475091ea7258238e2ab33c0ba6914a0b04f80081e0312286eb84382e3c12917d801aa4484e916fec45b51536ad19d35d6eaf7b2fe543b63fc1671411f3a",
          "sha256": "0ac1d17d413ffef31db408ec06f145d3300da317345e01b5d40d12acc93593b4",
          "sha1": "ee3cbd6035b37c9f1359623210fad56d1b9a5493",
          "md5": "b1c10b5e0f852a445da70e88a19dff90"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_2-0.7.302+8d1be4b-beta-sources.jar",
          "url": "magiclib-1_19_2-0.7.302+8d1be4b-beta-sources.jar",
          "size": 159613,
          "sha512": "85215b41d890b86d4ac49b4a136ce27c29707d0e338b1b66065c6b187c16a880070f0590b0df6c386ab2c87546343989f9ded4060367b9091c09c7aa42dffb00",
          "sha256": "32383ecea0db02fadd0fabf7d6ea1cc49a13949c98a772759519d8a10386b248",
          "sha1": "efad874f9a47510f42273b99dc2e24ec16104b01",
          "md5": "34048d6cff04eaa8740b7804e7f248e7"
        }
      ]
    }
  ]
}
