{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.7.326+2b20e19-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.326+2b20e19-beta.jar",
          "url": "magiclib-1_18_2-0.7.326+2b20e19-beta.jar",
          "size": 374883,
          "sha512": "8886fa41d2e6f4c4698bd85919f3947d677571771175914042bce3bc902c28f54ac47955a850f958d00879e9f2781a7590c0289ea830b59da4095b31dc83eac5",
          "sha256": "243c45fb1c1330fffdee28407231d0b7e962658e0f99de70fa634717e9518bb0",
          "sha1": "0e0713a53db3a5757681dd3b85ab1e0d895535ec",
          "md5": "b16deda979b513efc12bd190fb473740"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.326+2b20e19-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "carpet",
          "module": "fabric-carpet",
          "version": {
            "requires": "1.18.2-1.4.69+v220331"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "modmenu",
          "version": {
            "requires": "3.2.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.18.2"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "in-game-account-switcher",
          "version": {
            "requires": "8.0.1-fabric1.18"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "lazydfu",
          "version": {
            "requires": "0.1.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "maven.modrinth",
          "module": "imblocker",
          "version": {
            "requires": "1.0.20_pre5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3692365"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.326+2b20e19-beta.jar",
          "url": "magiclib-1_18_2-0.7.326+2b20e19-beta.jar",
          "size": 374883,
          "sha512": "8886fa41d2e6f4c4698bd85919f3947d677571771175914042bce3bc902c28f54ac47955a850f958d00879e9f2781a7590c0289ea830b59da4095b31dc83eac5",
          "sha256": "243c45fb1c1330fffdee28407231d0b7e962658e0f99de70fa634717e9518bb0",
          "sha1": "0e0713a53db3a5757681dd3b85ab1e0d895535ec",
          "md5": "b16deda979b513efc12bd190fb473740"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.7.326+2b20e19-beta-sources.jar",
          "url": "magiclib-1_18_2-0.7.326+2b20e19-beta-sources.jar",
          "size": 168942,
          "sha512": "6a2226485efb12efa9e2c217917e8e57213755553ba89f8ea4f8a0b94455c5558b105c9c5db9dad4c2cebf5411b178c88aee520c6631ebaadc488cd1e7f163e7",
          "sha256": "b1e0309ea2a30831a5f80c22dbabf281025d4e273f81c41c531de1d3129420d9",
          "sha1": "fc3fb3200a9d35f65ab833c5d147c04eca0d3509",
          "md5": "e8dfa1c94c13d9258c1d2a77c7c593f8"
        }
      ]
    }
  ]
}
