{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_16_5",
    "version": "0.6.196+2fd0900-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.12"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.196+2fd0900-beta.jar",
          "url": "magiclib-1_16_5-0.6.196+2fd0900-beta.jar",
          "size": 328448,
          "sha512": "f7e1cc4191f03a11ffd3b0af1d73b978902bbfaecf69afe47168220b6e18bcb85711f35c96da291786dd74132e3721089b42907b51264bce861c2b74ae935b0e",
          "sha256": "76840ab0801e0c4d99112d412215ae8caa3d8eee9553b93c8fee9f68380e62ea",
          "sha1": "ed1baf3fc91e7f879b80cdf30fd0c2280bb8480d",
          "md5": "ee827b1d5fcdf4eedb0df9bd729c6dac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.196+2fd0900-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.42.0+1.16"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.12"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3388185"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3542536"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850092"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993197"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.196+2fd0900-beta.jar",
          "url": "magiclib-1_16_5-0.6.196+2fd0900-beta.jar",
          "size": 328448,
          "sha512": "f7e1cc4191f03a11ffd3b0af1d73b978902bbfaecf69afe47168220b6e18bcb85711f35c96da291786dd74132e3721089b42907b51264bce861c2b74ae935b0e",
          "sha256": "76840ab0801e0c4d99112d412215ae8caa3d8eee9553b93c8fee9f68380e62ea",
          "sha1": "ed1baf3fc91e7f879b80cdf30fd0c2280bb8480d",
          "md5": "ee827b1d5fcdf4eedb0df9bd729c6dac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_16_5-0.6.196+2fd0900-beta-sources.jar",
          "url": "magiclib-1_16_5-0.6.196+2fd0900-beta-sources.jar",
          "size": 230364,
          "sha512": "edf8b2c870fbe777f6ff08a8ff00941d9ae5b05b907402174e0dcae56e30b88f69e60abc4b6c620fade9066e7eec0f9069dd4efc969846622601577f7decf978",
          "sha256": "26f8da2c2bc1271390c76d583b2852f155aad28ae5fb43bfad3bf4ab7ea9c55d",
          "sha1": "6bb4aefc1f34193d3b45e012e968669f9b3ee9ed",
          "md5": "94e09f254807d8c5df979a33d973bb9c"
        }
      ]
    }
  ]
}
