{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_15_2",
    "version": "0.5.258+a2512cb-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_15_2-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_15_2-0.5.258+a2512cb-dev.jar",
          "size": 1152626,
          "sha512": "5f079c489e59f03f014c750f84990e81abafb21a1a1214a7d2f74153defb9871ed9693dcd8beaf16ea69772ba771505302660b37b18e85bdfc0de481272ee948",
          "sha256": "e834350efd2683992750cdd705781b75750d037615687f7de88a176b0c896bec",
          "sha1": "8e6058da21f2570a2958514b795729eb2516fc8e",
          "md5": "b93e34b34a979d306bd1745ec17170b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.258+a2512cb-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_15_2",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_15_2-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_15_2-0.5.258+a2512cb-dev.jar",
          "size": 1152626,
          "sha512": "5f079c489e59f03f014c750f84990e81abafb21a1a1214a7d2f74153defb9871ed9693dcd8beaf16ea69772ba771505302660b37b18e85bdfc0de481272ee948",
          "sha256": "e834350efd2683992750cdd705781b75750d037615687f7de88a176b0c896bec",
          "sha1": "8e6058da21f2570a2958514b795729eb2516fc8e",
          "md5": "b93e34b34a979d306bd1745ec17170b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
