{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.6.178+1c236b1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.6.178+1c236b1-beta.jar",
          "url": "magiclib-1_17_1-0.6.178+1c236b1-beta.jar",
          "size": 302076,
          "sha512": "13b0c6d7043b9b0939eec214a494e2b8f76674742eb873c12ba1751c6aed934756d6026f3311403fb8b6d9e4754d978150a7298d2c4a66e7062d558b20c40547",
          "sha256": "a82ba0821d0cd2483c01acba8a006778b2baf4bd382f77d55905f125b73d4a71",
          "sha1": "48f68d030b0db05a28d52c9156869d293ae52ea3",
          "md5": "98d9835dcae88a20f398e8786f91062a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.6.178+1c236b1-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.9"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3850095"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827451"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.6.178+1c236b1-beta.jar",
          "url": "magiclib-1_17_1-0.6.178+1c236b1-beta.jar",
          "size": 302076,
          "sha512": "13b0c6d7043b9b0939eec214a494e2b8f76674742eb873c12ba1751c6aed934756d6026f3311403fb8b6d9e4754d978150a7298d2c4a66e7062d558b20c40547",
          "sha256": "a82ba0821d0cd2483c01acba8a006778b2baf4bd382f77d55905f125b73d4a71",
          "sha1": "48f68d030b0db05a28d52c9156869d293ae52ea3",
          "md5": "98d9835dcae88a20f398e8786f91062a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.6.178+1c236b1-beta-sources.jar",
          "url": "magiclib-1_17_1-0.6.178+1c236b1-beta-sources.jar",
          "size": 215979,
          "sha512": "b04b6fa7523327890ad077839f945be2cda4a580a9957096496faafbfd827f7bf91ac372b02e8c85c14f15b4fdc34a937f750932ba466bb207b580bb3c817289",
          "sha256": "2af733629e92e31519e75cf6a19dacc8969554781d0048c43130b65a61044ad4",
          "sha1": "da142a11f50ec93def94d956e1bd9fba929431a0",
          "md5": "499f6b0b513956e5b85a586b6340cb37"
        }
      ]
    }
  ]
}
