{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_15_2",
    "version": "0.5.260+86e6882-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_15_2-0.5.260+86e6882-dev.jar",
          "url": "ommc-1_15_2-0.5.260+86e6882-dev.jar",
          "size": 1152636,
          "sha512": "2448839d63807e875c55ebdaf93c8a6524263cae278993525804c5c20f46fb6aa4134691053d0d666766aa2ccaa67bc9119c78710f473c7fa9ced5d08312fe4b",
          "sha256": "bfdac5ff116e4f9936bed8817d7fb4851a4f17be722022d4e3f6fd5ca92ae482",
          "sha1": "335fd632b35d7031bf07b4e67fc20f9f3dd6646e",
          "md5": "e040386e00ec89af5b331a91833095b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.260+86e6882-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_15_2",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_15_2-0.5.260+86e6882-dev.jar",
          "url": "ommc-1_15_2-0.5.260+86e6882-dev.jar",
          "size": 1152636,
          "sha512": "2448839d63807e875c55ebdaf93c8a6524263cae278993525804c5c20f46fb6aa4134691053d0d666766aa2ccaa67bc9119c78710f473c7fa9ced5d08312fe4b",
          "sha256": "bfdac5ff116e4f9936bed8817d7fb4851a4f17be722022d4e3f6fd5ca92ae482",
          "sha1": "335fd632b35d7031bf07b4e67fc20f9f3dd6646e",
          "md5": "e040386e00ec89af5b331a91833095b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
