{
  "formatVersion": "1.1",
  "component": {
    "group": "fi.dy.masa",
    "module": "malilib",
    "version": "1.20-pre5-0.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "malilib-1.20-pre5-0.16.0.jar",
          "url": "malilib-1.20-pre5-0.16.0.jar",
          "size": 540369,
          "sha512": "408efbfdd558e5170f4109596bea441584c49fb1ecd85acf17f109ea839495fbd737b65377c33c5638241098798f92f4d3d926346cb3fc70c7f92ca9256f9e2e",
          "sha256": "d31372fc49b82c6253c071aa11f9fdd4cf9ff86029afaa99ecceee03d22a09a8",
          "sha1": "d06770b4ea0e2c6a5db78b218c15b4225b9de080",
          "md5": "68f465395b0cb0a1f90209b1eea60a83"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.19"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "0.11.6+f7923f6db3"
          }
        }
      ],
      "files": [
        {
          "name": "malilib-1.20-pre5-0.16.0.jar",
          "url": "malilib-1.20-pre5-0.16.0.jar",
          "size": 540369,
          "sha512": "408efbfdd558e5170f4109596bea441584c49fb1ecd85acf17f109ea839495fbd737b65377c33c5638241098798f92f4d3d926346cb3fc70c7f92ca9256f9e2e",
          "sha256": "d31372fc49b82c6253c071aa11f9fdd4cf9ff86029afaa99ecceee03d22a09a8",
          "sha1": "d06770b4ea0e2c6a5db78b218c15b4225b9de080",
          "md5": "68f465395b0cb0a1f90209b1eea60a83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "malilib-1.20-pre5-0.16.0-sources.jar",
          "url": "malilib-1.20-pre5-0.16.0-sources.jar",
          "size": 266587,
          "sha512": "904bd78ffc84c732df71a2d82b454fee8a8cd60c1ebdb5a795ca6a8f988a65a30c4a3b4a26e08b5bcedad328f015a5d31eca033673e2d891a3bd584932ab9dff",
          "sha256": "3a532053d020025fb767945e19f0fb79ea8fa735e21ee642f61c34da03d5b73e",
          "sha1": "c3c2372e3261ff76a84a904c77a0798c4b02a743",
          "md5": "64a4e313b2c65fb4ee33ec8b5ff4235f"
        }
      ]
    }
  ]
}
