{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-malilib-extra-1_17_1",
    "version": "0.7.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_17_1-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-malilib-extra-1_17_1-0.7.3+c7ba8f9-beta.jar",
          "size": 157456,
          "sha512": "59761ffb16c625d2545cde9d8745ec6521660ddb8b0465e41fcdc56fca85fa0e22f3b60949ae32c77ce634e426020a306c20b4d7fa76f7925ffb1da0fd02380e",
          "sha256": "b707486dce35af41f17a0ea8de09fa636f25a856bcff933462588639bb637447",
          "sha1": "98b68d2d4ec940395586bca1523bf135ed8871c6",
          "md5": "979896005da2ce5600aa7a6822eb7c16"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_17_1-0.7.3+c7ba8f9-beta.jar",
          "url": "magiclib-malilib-extra-1_17_1-0.7.3+c7ba8f9-beta.jar",
          "size": 157456,
          "sha512": "59761ffb16c625d2545cde9d8745ec6521660ddb8b0465e41fcdc56fca85fa0e22f3b60949ae32c77ce634e426020a306c20b4d7fa76f7925ffb1da0fd02380e",
          "sha256": "b707486dce35af41f17a0ea8de09fa636f25a856bcff933462588639bb637447",
          "sha1": "98b68d2d4ec940395586bca1523bf135ed8871c6",
          "md5": "979896005da2ce5600aa7a6822eb7c16"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_17_1",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-malilib-extra-1_17_1-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "url": "magiclib-malilib-extra-1_17_1-0.7.3+c7ba8f9-beta-standalone-dev.jar",
          "size": 413005,
          "sha512": "0f1876eb34e69898ec60486a0610614bbc9cdb7594223df203dd85b6dec7cc1121dbb0f5f2b6085d1ee4df954328f8eb77cf87f4b6b14a52cfe81a47d2b47add",
          "sha256": "2d4c6061fb31fec37ec6caae618eb5b7e5b1b4ef1448fe9627f69d47cf9f8ea2",
          "sha1": "0d1c03ac75727463052ea9ed9f38c3d74a9811e9",
          "md5": "96122f48bcc7b6091bde76bec1070393"
        }
      ]
    }
  ]
}
