{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_18_2",
    "version": "0.5.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.55.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.32.jar",
          "url": "magiclib-1_18_2-0.5.32.jar",
          "size": 254453,
          "sha512": "1a61fffcf35f91e8e4b0a505c153cd40105c471485b635f62939b1d903c9a60725ea5392356c85812984c570ece16732552a94c68d374b51513dd4a3aca8b30c",
          "sha256": "02c92707e344160ff048a9003f38f524c55870839accb438d0216e1a6bb5e3ec",
          "sha1": "cf6b088f7e49c2e6063f5e37335bdff01d5a6bd7",
          "md5": "fa7912d55bd0be43d7b2f2ad8edeb9ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3745497"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.55.1+1.18.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.7"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3545107"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.32.jar",
          "url": "magiclib-1_18_2-0.5.32.jar",
          "size": 254453,
          "sha512": "1a61fffcf35f91e8e4b0a505c153cd40105c471485b635f62939b1d903c9a60725ea5392356c85812984c570ece16732552a94c68d374b51513dd4a3aca8b30c",
          "sha256": "02c92707e344160ff048a9003f38f524c55870839accb438d0216e1a6bb5e3ec",
          "sha1": "cf6b088f7e49c2e6063f5e37335bdff01d5a6bd7",
          "md5": "fa7912d55bd0be43d7b2f2ad8edeb9ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_18_2-0.5.32-sources.jar",
          "url": "magiclib-1_18_2-0.5.32-sources.jar",
          "size": 192682,
          "sha512": "cb251578c9084decc96a284dd45a06dd1314b89282178ca28edd46a572e098e6b39d88686b7efa1505db26a1064488b6196c6a696654d3649aeacf5422683959",
          "sha256": "72e46aae5428bb4c75f1ad5c1274c76f741fafa9e1c4bfef210f523e7cffb439",
          "sha1": "94fb18fa3e46ebaf1f7ef1191d50d6e91ee9270a",
          "md5": "e162e1e27449e298cfc1a99b52908499"
        }
      ]
    }
  ]
}
