{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_18_2",
    "version": "0.5.258+a2512cb-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_18_2-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_18_2-0.5.258+a2512cb-dev.jar",
          "size": 1146684,
          "sha512": "897c18da8c24e1256a472a3d23595ef90c3d854d800683f3d42b2a212c042eac481d648a945190b7af26f207f970569facb5c29dafe823b3b3fae82813eb6016",
          "sha256": "e27be9d3448bb0fe738f095a82f52e4cd744e55cf4b7d2f2a19c072e4c2a89e0",
          "sha1": "e0dff24e112825aa2326a2e9003d1fc3cf92a802",
          "md5": "119d2105249400d602075e7254646f79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.258+a2512cb-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_18_2",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_18_2-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_18_2-0.5.258+a2512cb-dev.jar",
          "size": 1146684,
          "sha512": "897c18da8c24e1256a472a3d23595ef90c3d854d800683f3d42b2a212c042eac481d648a945190b7af26f207f970569facb5c29dafe823b3b3fae82813eb6016",
          "sha256": "e27be9d3448bb0fe738f095a82f52e4cd744e55cf4b7d2f2a19c072e4c2a89e0",
          "sha1": "e0dff24e112825aa2326a2e9003d1fc3cf92a802",
          "md5": "119d2105249400d602075e7254646f79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
