{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-22w17a",
    "version": "0.5.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3761830"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.3+1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-22w17a-0.5.16.jar",
          "url": "magiclib-22w17a-0.5.16.jar",
          "size": 246827,
          "sha512": "41c54f95e9c9baf8beb9174c844ff4a2532610dbdebea160afbb0ce58bac850d8150b3ee6633d79b86350e908bc76c2e8856ebcc8431f9cc8d9cac6e91728b28",
          "sha256": "f3110458b12f650e2f2718dd86f12ab6199f029783f92e7dceeff4b516544727",
          "sha1": "ed4fb2e02fa03b743f5696e2106cf4e58f77916f",
          "md5": "c739a379ddf228345ca550c702e1909a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.16"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3692220"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3761830"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.51.3+1.19"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3545107"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3761225"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-22w17a-0.5.16.jar",
          "url": "magiclib-22w17a-0.5.16.jar",
          "size": 246827,
          "sha512": "41c54f95e9c9baf8beb9174c844ff4a2532610dbdebea160afbb0ce58bac850d8150b3ee6633d79b86350e908bc76c2e8856ebcc8431f9cc8d9cac6e91728b28",
          "sha256": "f3110458b12f650e2f2718dd86f12ab6199f029783f92e7dceeff4b516544727",
          "sha1": "ed4fb2e02fa03b743f5696e2106cf4e58f77916f",
          "md5": "c739a379ddf228345ca550c702e1909a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-22w17a-0.5.16-sources.jar",
          "url": "magiclib-22w17a-0.5.16-sources.jar",
          "size": 186765,
          "sha512": "c93ff3bfb3e339b2e83f1f94e2d75affb2a0dfd330609bbc7089b6ae23c953b63c2370fe13d9834a3d0bbea7f6ea330d429f42b70e75f0c232cb13cb8290af8b",
          "sha256": "788d4c3db549038cdd8d6a9798c8206e2fab1d2069942fd77563af34f0f892e7",
          "sha1": "351bd992571bd99e1e8ac5443a2c5f25a9b6ea85",
          "md5": "5ece2a1e59ab58aae0fd40c51fa50368"
        }
      ]
    }
  ]
}
