{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-base-1_19_3",
    "version": "0.7.2+32bcf58-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.72.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_19_3-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_19_3-0.7.2+32bcf58-beta.jar",
          "size": 119945,
          "sha512": "b13764f42025cedd4b0e07f48342cb64efb5ac8088c1790e3392cc638a9af42f00c77ae96a7c898cf09ae6fd0e6ecefe18d7c4003d3ded4f6c0c21d8c5704795",
          "sha256": "4c7f2c4beeb28772feffcb261db8f8feed8699855f2c05f6b3c1eafaafbadc23",
          "sha1": "f55f1dc1fb4e27ca60657576196a2e5a24927055",
          "md5": "0b18d0c0d4f4313adfbd48982f26efa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.72.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4215578"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_19_3-0.7.2+32bcf58-beta.jar",
          "url": "magiclib-base-1_19_3-0.7.2+32bcf58-beta.jar",
          "size": 119945,
          "sha512": "b13764f42025cedd4b0e07f48342cb64efb5ac8088c1790e3392cc638a9af42f00c77ae96a7c898cf09ae6fd0e6ecefe18d7c4003d3ded4f6c0c21d8c5704795",
          "sha256": "4c7f2c4beeb28772feffcb261db8f8feed8699855f2c05f6b3c1eafaafbadc23",
          "sha1": "f55f1dc1fb4e27ca60657576196a2e5a24927055",
          "md5": "0b18d0c0d4f4313adfbd48982f26efa5"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-core",
          "version": {
            "requires": "0.7.2+32bcf58-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-base-1_19_3-0.7.2+32bcf58-beta-standalone-dev.jar",
          "url": "magiclib-base-1_19_3-0.7.2+32bcf58-beta-standalone-dev.jar",
          "size": 260416,
          "sha512": "32ede7851729719ced9f4872f6e3c9217211bd1ed4f0b1e44e2ed44a4bea9532a30a117d560015f58eeee62648911dff42a9355ab2fe927c1c6551899d6a6969",
          "sha256": "9c12ee42119f65ffd5bcb3a74a29b6b71a1f1ef3618b088c40b6182a46295c06",
          "sha1": "2014f4d8d2413421d2105aa57cef9cd3f3bc82b7",
          "md5": "f21ef858e1ccd99d0fcf5add633788b3"
        }
      ]
    }
  ]
}
