{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.283+320fdb8-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-1_17_1-0.7.283+320fdb8-beta.jar",
          "size": 358985,
          "sha512": "48b0f307e620b9d2eab8c7c1dc98ef2ac3b73c7cc661bb43db703c4ad281ad13d2337c0244cedf8aa45f1b1c6b2de9a6e6d0322a5d65320235d48ad751b761a8",
          "sha256": "59710b02f9aaf58ac1d9cd68135fd4d623c752f8ad32a6e3417dcefc62c05918",
          "sha1": "25c0b4cc72e50882f0f3ee154a6c949c81c784a7",
          "md5": "74a5467265718fb8e4a689fab695016d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.283+320fdb8-beta.jar",
          "url": "magiclib-1_17_1-0.7.283+320fdb8-beta.jar",
          "size": 358985,
          "sha512": "48b0f307e620b9d2eab8c7c1dc98ef2ac3b73c7cc661bb43db703c4ad281ad13d2337c0244cedf8aa45f1b1c6b2de9a6e6d0322a5d65320235d48ad751b761a8",
          "sha256": "59710b02f9aaf58ac1d9cd68135fd4d623c752f8ad32a6e3417dcefc62c05918",
          "sha1": "25c0b4cc72e50882f0f3ee154a6c949c81c784a7",
          "md5": "74a5467265718fb8e4a689fab695016d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.283+320fdb8-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.283+320fdb8-beta-sources.jar",
          "size": 159531,
          "sha512": "b84debd4127d9b48f6969c332b9760d0f65c90d3106c7c26208e2095ccd47b544acfb93997053be59cd5494657dfc74d8978e92948f2379abe40bfb7755f92ce",
          "sha256": "c4d9607f6b1e3493f7d45fd07599d5b40669f758b283001998c8d3420c26ea69",
          "sha1": "1beafebc65420b24b7f1faf760fff5c71b58e336",
          "md5": "78ea057b8732aa66ed5b908811c54d9f"
        }
      ]
    }
  ]
}
