{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_3",
    "version": "0.7.280+c3d8807-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.280+c3d8807-beta.jar",
          "url": "magiclib-1_19_3-0.7.280+c3d8807-beta.jar",
          "size": 360556,
          "sha512": "58d6eb19e21153e2bc63b044364ee0de9791a471b358dec146b631094dfb8e35e7f1d3439c6b561601de228df9eaaea03b90cd600e182ea4620c918a818ba410",
          "sha256": "1845514f0e3b7a412292ba6e50da0adfa1027f9bc84452388abcb5f780a5cbb8",
          "sha1": "9ce9f29144bdfc279012b4db8e2c5fdba7cb5dfd",
          "md5": "570803cfc34495a630b315350c7afb89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.280+c3d8807-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.76.0+1.19.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "4375849"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "4147598"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4159524"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "4215578"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4441838"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.280+c3d8807-beta.jar",
          "url": "magiclib-1_19_3-0.7.280+c3d8807-beta.jar",
          "size": 360556,
          "sha512": "58d6eb19e21153e2bc63b044364ee0de9791a471b358dec146b631094dfb8e35e7f1d3439c6b561601de228df9eaaea03b90cd600e182ea4620c918a818ba410",
          "sha256": "1845514f0e3b7a412292ba6e50da0adfa1027f9bc84452388abcb5f780a5cbb8",
          "sha1": "9ce9f29144bdfc279012b4db8e2c5fdba7cb5dfd",
          "md5": "570803cfc34495a630b315350c7afb89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_3-0.7.280+c3d8807-beta-sources.jar",
          "url": "magiclib-1_19_3-0.7.280+c3d8807-beta-sources.jar",
          "size": 159483,
          "sha512": "3e4d2825a6570375f2b28a28468c44e0a0333a986a4d9ea9e709fd17883711d6eff86b47dfb74263ffff43e22ba3fc701db926f3cda794f16f487e86efa50462",
          "sha256": "09c54ad670666f601d4e0c2aeea49c6484bf08401b687603b2f34ea25400eba1",
          "sha1": "7e64f31b8f19b9bc6096e51bcb1decb91ec5eb0b",
          "md5": "d7530520036121928c841dab79a792b9"
        }
      ]
    }
  ]
}
