{
  "formatVersion": "1.1",
  "component": {
    "group": "com.plusls.oh-my-minecraft-client",
    "module": "ommc-1_19_4",
    "version": "0.5.258+a2512cb-dev",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-1_19_4-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_19_4-0.5.258+a2512cb-dev.jar",
          "size": 1145176,
          "sha512": "1a964ab2f5795ed5ca825cf7fb089b2141fe3f899530c46fff2c9b8b1e4854879401a5e0073a6fa5defd846c0394cb01950dc9837c4f2271c5f2a77c34d1fb30",
          "sha256": "848e44075fd7cde0ec594ad5ce876e20be4e176b8917c0acb21a132f45b66246",
          "sha1": "d06a843172585265b6f94ebe540594460899d808",
          "md5": "c537e5d8406a13307d425c9e563d9178"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.plusls.oh-my-minecraft-client",
          "module": "ommc",
          "version": {
            "requires": "0.5.258+a2512cb-dev"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_19_4",
          "version": {
            "requires": "0.7.283+320fdb8-beta"
          },
          "excludes": [
            {
              "group": "curse.maven",
              "module": "carpet-349239"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ommc-1_19_4-0.5.258+a2512cb-dev.jar",
          "url": "ommc-1_19_4-0.5.258+a2512cb-dev.jar",
          "size": 1145176,
          "sha512": "1a964ab2f5795ed5ca825cf7fb089b2141fe3f899530c46fff2c9b8b1e4854879401a5e0073a6fa5defd846c0394cb01950dc9837c4f2271c5f2a77c34d1fb30",
          "sha256": "848e44075fd7cde0ec594ad5ce876e20be4e176b8917c0acb21a132f45b66246",
          "sha1": "d06a843172585265b6f94ebe540594460899d808",
          "md5": "c537e5d8406a13307d425c9e563d9178"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
