{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-minecraft-compat-1_19_3",
    "version": "0.5.3+c7ba8f9-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_19_3",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_19_3-0.5.3+c7ba8f9-beta.jar",
          "url": "magiclib-minecraft-compat-1_19_3-0.5.3+c7ba8f9-beta.jar",
          "size": 142196,
          "sha512": "1e7e8f261edef6aafa39e6e0e8f797389cef95866ebb03ebe6db38b880832756d859ea4770e10e16bc64d82e3516e0f7c6fc1e613d9cda230671e7eeb2945ed0",
          "sha256": "8577fb35a8be7ed544b380e7e819a3096a9ea31a01f7921f70f910ac53828ebd",
          "sha1": "3141b479a68c8480a1c1774555de9db26f856a32",
          "md5": "a4750baf8480c9dfaf61bf5b14623308"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_19_3",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_19_3-0.5.3+c7ba8f9-beta.jar",
          "url": "magiclib-minecraft-compat-1_19_3-0.5.3+c7ba8f9-beta.jar",
          "size": 142196,
          "sha512": "1e7e8f261edef6aafa39e6e0e8f797389cef95866ebb03ebe6db38b880832756d859ea4770e10e16bc64d82e3516e0f7c6fc1e613d9cda230671e7eeb2945ed0",
          "sha256": "8577fb35a8be7ed544b380e7e819a3096a9ea31a01f7921f70f910ac53828ebd",
          "sha1": "3141b479a68c8480a1c1774555de9db26f856a32",
          "md5": "a4750baf8480c9dfaf61bf5b14623308"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen.magic-project",
          "module": "magiclib-base-1_19_3",
          "version": {
            "requires": "0.7.3+c7ba8f9-beta"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            },
            {
              "group": "net.fabricmc",
              "module": "*"
            },
            {
              "group": "curse.maven",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "magiclib-minecraft-compat-1_19_3-0.5.3+c7ba8f9-beta-standalone-dev.jar",
          "url": "magiclib-minecraft-compat-1_19_3-0.5.3+c7ba8f9-beta-standalone-dev.jar",
          "size": 395721,
          "sha512": "dd43527c3e205586351b66ad0272328c4e70b5cceee0f9ee0fb1f5143b54f43b42051aba95e529f69229a6ab69f2937ec9ac47b67a8c5418280e421826a1c1f2",
          "sha256": "56f76efa69fcbe0414c23ab698affd42c94de2cc7085cba880dd53049ec36cf3",
          "sha1": "a76071ba081e1bccd29289540d009478d3e90183",
          "md5": "f04cc7f32332474ec738c001c9aa6909"
        }
      ]
    }
  ]
}
