{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-minecraft-compat",
    "version": "0.7.12+b31abea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-minecraft-compat-0.7.12+b31abea-beta.jar",
          "url": "magiclib-minecraft-compat-0.7.12+b31abea-beta.jar",
          "size": 842709,
          "sha512": "684cc449cda7b28818fc8cf0d4477dc8e8ec5da49160a6b7f11a24f0b3c05f112245142209823b206c3f75e05830c7de900c340ec19f7123960e7862e5aded9b",
          "sha256": "f160c9177edb42e093f8f3d72c05aec96f6297986d33ad5864a868fd38703f40",
          "sha1": "a508b5c2476713ea7b1165154212d040e89f5ba5",
          "md5": "81077bacece97d78019b3af678255901"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-minecraft-compat-0.7.12+b31abea-beta.jar",
          "url": "magiclib-minecraft-compat-0.7.12+b31abea-beta.jar",
          "size": 842709,
          "sha512": "684cc449cda7b28818fc8cf0d4477dc8e8ec5da49160a6b7f11a24f0b3c05f112245142209823b206c3f75e05830c7de900c340ec19f7123960e7862e5aded9b",
          "sha256": "f160c9177edb42e093f8f3d72c05aec96f6297986d33ad5864a868fd38703f40",
          "sha1": "a508b5c2476713ea7b1165154212d040e89f5ba5",
          "md5": "81077bacece97d78019b3af678255901"
        }
      ]
    }
  ]
}
