{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen.magic-project",
    "module": "magiclib-minecraft-compat",
    "version": "0.7.12+b31abea-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "magiclib-minecraft-compat-0.7.12+b31abea-beta.jar",
          "url": "magiclib-minecraft-compat-0.7.12+b31abea-beta.jar",
          "size": 842556,
          "sha512": "19115f75b09c777af778a274c72c72f4b5aa57ad102a580474532df2eafd905b419d3b6e132723fa44702774c3f19303345f85fab9cd858b0ffb438c7dc4f355",
          "sha256": "550e2a32d801fc87524290637ee49eb4e231cd8d400b056454cb89cc1a7ef8a7",
          "sha1": "5ec6940912fe1c52dae5a62b5b60150a018acd8f",
          "md5": "ae101a5737eddfd539e1ae70e56e6ad4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-minecraft-compat-0.7.12+b31abea-beta.jar",
          "url": "magiclib-minecraft-compat-0.7.12+b31abea-beta.jar",
          "size": 842556,
          "sha512": "19115f75b09c777af778a274c72c72f4b5aa57ad102a580474532df2eafd905b419d3b6e132723fa44702774c3f19303345f85fab9cd858b0ffb438c7dc4f355",
          "sha256": "550e2a32d801fc87524290637ee49eb4e231cd8d400b056454cb89cc1a7ef8a7",
          "sha1": "5ec6940912fe1c52dae5a62b5b60150a018acd8f",
          "md5": "ae101a5737eddfd539e1ae70e56e6ad4"
        }
      ]
    }
  ]
}
