{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_17_1",
    "version": "0.7.275+e9e31a5-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.275+e9e31a5-beta.jar",
          "url": "magiclib-1_17_1-0.7.275+e9e31a5-beta.jar",
          "size": 358819,
          "sha512": "a666b9f671e38cd5d338689395252f77b0c99c238b1db1d718d76cc5bd9d353207e12e5f5b78f77768d5423e616df13e0040e8d6180bcba66ae187fc12b63c69",
          "sha256": "e392c339b5144f6908311097028315e8df38db3c8f0e45e97cc84d41d2d852f9",
          "sha1": "bec5bf291693563e028f6f86700f88e5fd82dee0",
          "md5": "cbe1b36e56fb8cee7778ce77fcfedbf8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.7.275+e9e31a5-beta"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.17"
          }
        },
        {
          "group": "org.projectlombok",
          "module": "lombok",
          "version": {
            "requires": "1.18.26"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.46.1+1.17"
          }
        },
        {
          "group": "curse.maven",
          "module": "carpet-349239",
          "version": {
            "requires": "3613865"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "3498871"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "4145216"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3993198"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3209972"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "4271884"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3248104"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.275+e9e31a5-beta.jar",
          "url": "magiclib-1_17_1-0.7.275+e9e31a5-beta.jar",
          "size": 358819,
          "sha512": "a666b9f671e38cd5d338689395252f77b0c99c238b1db1d718d76cc5bd9d353207e12e5f5b78f77768d5423e616df13e0040e8d6180bcba66ae187fc12b63c69",
          "sha256": "e392c339b5144f6908311097028315e8df38db3c8f0e45e97cc84d41d2d852f9",
          "sha1": "bec5bf291693563e028f6f86700f88e5fd82dee0",
          "md5": "cbe1b36e56fb8cee7778ce77fcfedbf8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_17_1-0.7.275+e9e31a5-beta-sources.jar",
          "url": "magiclib-1_17_1-0.7.275+e9e31a5-beta-sources.jar",
          "size": 159410,
          "sha512": "443b15f3d2c7ba2a9cef2a76d81e4d31500d4eb5c25f53ad71925983357c89c5400eb25c34187d995c85e0c8cb8203502aaa82e149c6b99e7d02122a5282065b",
          "sha256": "557656829d2ededd3f5e3ce5cf0bf6647093fc3c9902db52d9e81bef66d7e366",
          "sha1": "ac09d3693988decec04343133024f3c8507b7a5f",
          "md5": "7fe84c9279f6bc03205bea1f5a5abe6f"
        }
      ]
    }
  ]
}
