{
  "formatVersion": "1.1",
  "component": {
    "group": "curse.maven",
    "module": "ommc-454900-1_14_4",
    "version": "0.5-alpha+4d91bac",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ommc-454900-1_14_4-0.5-alpha+4d91bac.jar",
          "url": "ommc-454900-1_14_4-0.5-alpha+4d91bac.jar",
          "size": 142493,
          "sha512": "a790a0caabcc03842dd2c92beb9e26c4a5533e0a8cafb08ea80abbd9fa237e724d6273f0b9b9fe8665f4e049fba0c907d49d7ee4e5b80b54dbcc1981e73cd3c5",
          "sha256": "43c26489c9b6e48f0ce8942a2c421f171fde47f737d022b485c7a2b48305e7bd",
          "sha1": "660b2afc87958dfb18b63683034a7969c654ac8c",
          "md5": "a99806a21c5b6611c9f4c43e80bd59ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "ommc-454900",
          "version": {
            "requires": "0.5-alpha+4d91bac"
          }
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib-1_14_4",
          "version": {
            "requires": "0.5.37"
          }
        }
      ],
      "files": [
        {
          "name": "ommc-454900-1_14_4-0.5-alpha+4d91bac.jar",
          "url": "ommc-454900-1_14_4-0.5-alpha+4d91bac.jar",
          "size": 142493,
          "sha512": "a790a0caabcc03842dd2c92beb9e26c4a5533e0a8cafb08ea80abbd9fa237e724d6273f0b9b9fe8665f4e049fba0c907d49d7ee4e5b80b54dbcc1981e73cd3c5",
          "sha256": "43c26489c9b6e48f0ce8942a2c421f171fde47f737d022b485c7a2b48305e7bd",
          "sha1": "660b2afc87958dfb18b63683034a7969c654ac8c",
          "md5": "a99806a21c5b6611c9f4c43e80bd59ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ommc-454900-1_14_4-0.5-alpha+4d91bac-sources.jar",
          "url": "ommc-454900-1_14_4-0.5-alpha+4d91bac-sources.jar",
          "size": 93839,
          "sha512": "d775109ad8214830b70639e0a4523a745954a9ad6cb338bd1423639bf0af85fb2b1850a2a9552dc3b0a549da5801c1909b31ec738e6fae9ccc0b495036e79443",
          "sha256": "237ecc0aa003473def1ab2467b267be5b2d071db19de64bcad86b11fab51de3c",
          "sha1": "90cf8ac337bdca61bfd09d1f381cc35dfcd8f419",
          "md5": "077e1b7071c947aa452673d6019bc699"
        }
      ]
    }
  ]
}
