{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_1",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.5+1.19.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3902967"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_1-0.5.33.jar",
          "url": "magiclib-1_19_1-0.5.33.jar",
          "size": 254388,
          "sha512": "1fc0e59f7639aa892cfad60cedbfde6ca423937eecac3c6ea9254e590ef6a3ef853666c8075da27b803ae414022e1d066a419e70841fd87b055a88ae0af3cf54",
          "sha256": "f2b944db3afcf78aa929bce32e3d31dbfb3e47d59121922b0dca6920bc5724b6",
          "sha1": "2d82fc6cfb951a55961a7da8033bf950b9dec4cd",
          "md5": "f9ed0238e7dadad976310276d8a076ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.5+1.19.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3902967"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827454"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_1-0.5.33.jar",
          "url": "magiclib-1_19_1-0.5.33.jar",
          "size": 254388,
          "sha512": "1fc0e59f7639aa892cfad60cedbfde6ca423937eecac3c6ea9254e590ef6a3ef853666c8075da27b803ae414022e1d066a419e70841fd87b055a88ae0af3cf54",
          "sha256": "f2b944db3afcf78aa929bce32e3d31dbfb3e47d59121922b0dca6920bc5724b6",
          "sha1": "2d82fc6cfb951a55961a7da8033bf950b9dec4cd",
          "md5": "f9ed0238e7dadad976310276d8a076ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_1-0.5.33-sources.jar",
          "url": "magiclib-1_19_1-0.5.33-sources.jar",
          "size": 192728,
          "sha512": "731bcfe654fee26ac901801d71268d07baa693efe392a9f8ff1634f3f44847427b8434bb819839c1582624841a96eb3350d2df0c8c049b19c83ae3280cc6c8aa",
          "sha256": "fea3f1d2d21be80f47b3783ef415c1b0b9f0a1d0180bd740a91a2ffb3e4c4ae3",
          "sha1": "e4cc612b386d60afbf5c60c2a5887d32a1fb3eff",
          "md5": "1b1a610551abfb767468b0b993e0a26c"
        }
      ]
    }
  ]
}
