{
  "formatVersion": "1.1",
  "component": {
    "group": "top.hendrixshen",
    "module": "magiclib-1_19_1",
    "version": "0.5.33",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.5+1.19.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3902967"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_1-0.5.33.jar",
          "url": "magiclib-1_19_1-0.5.33.jar",
          "size": 254388,
          "sha512": "be6ee19ab1fc693aaf0b42673ae1e8be7f3ff35dae510feb3738706e611e1818906a65ecae90ff77e2c65f379af2a2a9685f4b1f31dce40c4ed3c0afa0ac75bd",
          "sha256": "6a95c8980f14399286e79242f234ef9a9e74d88403a811834df817b800c87af2",
          "sha1": "6545abf488b96bc3549fdd407e6c44266564cd8e",
          "md5": "f3b1f1ccbd2ec03efac69bcd51ddb6df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "top.hendrixshen",
          "module": "magiclib",
          "version": {
            "requires": "0.5.33"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.58.5+1.19.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.14.8"
          }
        },
        {
          "group": "curse.maven",
          "module": "malilib-303119",
          "version": {
            "requires": "1.19"
          }
        },
        {
          "group": "curse.maven",
          "module": "modmenu-308702",
          "version": {
            "requires": "3902967"
          }
        },
        {
          "group": "curse.maven",
          "module": "in-game-account-switcher-232676",
          "version": {
            "requires": "3827454"
          }
        },
        {
          "group": "curse.maven",
          "module": "lazydfu-433518",
          "version": {
            "requires": "3821870"
          }
        },
        {
          "group": "curse.maven",
          "module": "imblockerfabric-399225",
          "version": {
            "requires": "3845251"
          }
        },
        {
          "group": "curse.maven",
          "module": "smooth-boot-415758",
          "version": {
            "requires": "3821513"
          }
        }
      ],
      "files": [
        {
          "name": "magiclib-1_19_1-0.5.33.jar",
          "url": "magiclib-1_19_1-0.5.33.jar",
          "size": 254388,
          "sha512": "be6ee19ab1fc693aaf0b42673ae1e8be7f3ff35dae510feb3738706e611e1818906a65ecae90ff77e2c65f379af2a2a9685f4b1f31dce40c4ed3c0afa0ac75bd",
          "sha256": "6a95c8980f14399286e79242f234ef9a9e74d88403a811834df817b800c87af2",
          "sha1": "6545abf488b96bc3549fdd407e6c44266564cd8e",
          "md5": "f3b1f1ccbd2ec03efac69bcd51ddb6df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "magiclib-1_19_1-0.5.33-sources.jar",
          "url": "magiclib-1_19_1-0.5.33-sources.jar",
          "size": 192728,
          "sha512": "2a91182b5632cbd86d431d533af42ebcff44bbf1ae8001bd800cf6e01e4a18e006240c8cbe3695304ee66be0fa5e00d924188ebfce69a22ca85039770ee432f9",
          "sha256": "3d6f87380ccaf783e00ef5c2008dcbab7f1c706f06045c8a62a2d3e984a819fc",
          "sha1": "e46f96c39cbb0f3ca3d3a8ebfe2764489e5efe97",
          "md5": "9c528a1c144243c6e78f31a5151e5c8f"
        }
      ]
    }
  ]
}
